### ISSUE TITLE
"Literals" seen as variables

### ISSUE THREAD

**Issue by SystemsModelling** [rubberduck-vba/Rubberduck#2617] opened 2017-02-03 11:32 UTC
Local variable 'a5' is not declared 
It's part of a string .Range("A5:B5")

 Local variable 'D1' is not declared 
Application.GoTo [D1], True

**Comment by comintern** [comment] 2017-02-03 14:56
I can't replicate an inspection result with the first code snippet.  Can you either post the complete procedure, or if you can't, a minimal example that causes the inspection result?  Also, the inspection result should have the referenced variable in the same case that it appears in the code.  Is the inspection reporting `a5` or `A5`?  Does it select the string literal when you double-click on the inspection result in the code?

In the second snippet, `[D1]` is actually not a literal - it is a foreign member call that VBA internally resolves to `Application.[_Evaluate]("D1")`.  That specific inspection result is a duplicate of #2548 and #2565.  Note that the code `Application.GoTo [D1], True` should eventually trigger it's _own_ inspection result, as it is being evaluating at runtime as call to `ActiveSheet`.  `Application.[_Evaluate]` = `Application.ActiveSheet.Evaluate`.

**Comment by SystemsModelling** [comment] 2017-02-03 15:52
I'm sorry, I read the wrong line. The code is

Sub testWhyIs2ndRowIncreasing1R1C1()
844      ActiveSheet.Range("A5:B5").FormulaR1C1 = Array("=RC8", "=RC7")
846      Debug.Print [a5].Formula, [a5].FormulaR1C1   ' =$H5          =RC8

So it was the lowercase [a5] it was picking up.

I also get
 Member 'testWhyIs2ndRowIncreasing1R1C1' is implicitly public 
fair enough

and
 Consider renaming procedure 'testWhyIs2ndRowIncreasing1R1C1' 
because it ends in a 1.
Now that I know about those '@ flags I can use them if necessary to reduce noise from false positives.


By the way, how do I know from the list of issues whether they are open or closed?
I can see Open or Closed in the heading of the issue itself but nothing obvious in the list

**Comment by comintern** [comment] 2017-02-03 16:01
@SystemsModelling - The easiest way to determine if an issue is open or closed from the list is to use the filter dropdown to the left of the search - just select "Open issues and pull requests".  It should add the search meta `is:issue is:open` to the dialog.  If you're looking at the complete list results, the exclamation point icon to the left of the issue will be green if it's open, red if it's closed.

If the bracketed identifier is the only result trigger, I'll go ahead an close this as a duplicate of the issues I referenced above.

**Closed by comintern** 2017-02-03 16:01 UTC

**Comment by SystemsModelling** [comment] 2017-02-03 16:05
Ah yes, I've just seen is:open is:issue 
which explains why I saw grey circles rather than green or red.
Thanks, comintern.
As you may guess I've only just started here.

Patrick

**Comment by retailcoder** [comment] 2017-02-03 16:09
@comintern in the current build bracketed expressions resolve as `BracketedExpression` "declarations", which fixes the problem of having the resolver treating them as undeclared identifiers.

**Comment by retailcoder** [comment] 2017-02-03 16:11
@SystemsModeling you can also track what issues have been merged into the current build and what's going to be released next, in the [Maintenance](https://github.com/rubberduck-vba/Rubberduck/projects/4) "project", which we try to maintain and keep up-to-date :-)
