### ISSUE TITLE
"unknown" exception

### ISSUE THREAD

**Issue by BaronBodissey** [rubberduck-vba/Rubberduck#3088] opened 2017-06-28 16:08 UTC
Just following rd advice to create an issue with the log file.

Also, I suggest you instantiate rolling log file as there's so much log that one log file isn't enough.

Best regards.

```
2017-06-28 18:02:59.0860;INFO-2.0.13.32288;Rubberduck.App;Rubberduck version 2.0.13.32288 loading:
	Operating System: Microsoft Windows NT 10.0.15063.0 x64
	Host Product: Microsoft Office 2016 x86
	Host Version: 16.0.8201.2102
	Host Executable: WINWORD.EXE;
2017-06-28 18:03:15.5350;WARN-2.0.13.32288;Rubberduck.Parsing.Symbols.TypeAnnotationPass;Failed to resolve type VBProject;
2017-06-28 18:03:15.6510;WARN-2.0.13.32288;Rubberduck.Parsing.Symbols.TypeAnnotationPass;Failed to resolve type VBE;
2017-06-28 18:03:15.6660;WARN-2.0.13.32288;Rubberduck.Parsing.Symbols.TypeAnnotationPass;Failed to resolve type VBE;
2017-06-28 18:03:15.7100;WARN-2.0.13.32288;Rubberduck.Parsing.Symbols.TypeAnnotationPass;Failed to resolve type VBE;
2017-06-28 18:03:15.7300;WARN-2.0.13.32288;Rubberduck.Parsing.Symbols.TypeAnnotationPass;Failed to resolve type System.__ComObject;
2017-06-28 18:03:15.7780;WARN-2.0.13.32288;Rubberduck.Parsing.Symbols.TypeAnnotationPass;Failed to resolve type VBProject;
2017-06-28 18:03:15.7780;WARN-2.0.13.32288;Rubberduck.Parsing.Symbols.TypeAnnotationPass;Failed to resolve type System.__ComObject;
[...]
2017-06-28 18:03:47.0819;ERROR-2.0.13.32288;Rubberduck.UI.SourceControl.SourceControlViewViewModel;System.Runtime.InteropServices.COMException (0x800AC372): Exception de HRESULT : 0x800AC372
   à Microsoft.Vbe.Interop._VBComponent.Export(String FileName)
   à Rubberduck.VBEditor.SafeComWrappers.VBA.VBComponent.ExportAsSourceFile(String folder, Boolean tempFile) dans C:\Users\Mathieu\Documents\GitHub\Rubberduck (main)\Rubberduck\Rubberduck.VBEEditor\SafeComWrappers\VBA\VBComponent.cs:ligne 142
   à Rubberduck.VBEditor.SafeComWrappers.VBA.VBProject.ExportSourceFiles(String folder) dans C:\Users\Mathieu\Documents\GitHub\Rubberduck (main)\Rubberduck\Rubberduck.VBEEditor\SafeComWrappers\VBA\VBProject.cs:ligne 178
   à Rubberduck.SourceControl.SourceControlProviderBase.Status() dans C:\Users\Mathieu\Documents\GitHub\Rubberduck (main)\Rubberduck\Rubberduck.SourceControl\SourceControlProviderBase.cs:ligne 140
   à Rubberduck.SourceControl.GitProvider.Status() dans C:\Users\Mathieu\Documents\GitHub\Rubberduck (main)\Rubberduck\Rubberduck.SourceControl\GitProvider.cs:ligne 497
   à Rubberduck.UI.SourceControl.ChangesViewViewModel.RefreshView() dans C:\Users\Mathieu\Documents\GitHub\Rubberduck (main)\Rubberduck\RetailCoder.VBE\UI\SourceControl\ChangesViewViewModel.cs:ligne 59
   à Rubberduck.UI.SourceControl.ChangesViewViewModel.set_Provider(ISourceControlProvider value) dans C:\Users\Mathieu\Documents\GitHub\Rubberduck (main)\Rubberduck\RetailCoder.VBE\UI\SourceControl\ChangesViewViewModel.cs:ligne 49
   à Rubberduck.UI.SourceControl.SourceControlViewViewModel.SetChildPresenterSourceControlProviders(ISourceControlProvider provider) dans C:\Users\Mathieu\Documents\GitHub\Rubberduck (main)\Rubberduck\RetailCoder.VBE\UI\SourceControl\SourceControlViewViewModel.cs:ligne 684
   à Rubberduck.UI.SourceControl.SourceControlViewViewModel.set_Provider(ISourceControlProvider value) dans C:\Users\Mathieu\Documents\GitHub\Rubberduck (main)\Rubberduck\RetailCoder.VBE\UI\SourceControl\SourceControlViewViewModel.cs:ligne 247
   à Rubberduck.UI.SourceControl.SourceControlViewViewModel.OpenRepoAssignedToProject() dans C:\Users\Mathieu\Documents\GitHub\Rubberduck (main)\Rubberduck\RetailCoder.VBE\UI\SourceControl\SourceControlViewViewModel.cs:ligne 897
   à Rubberduck.UI.SourceControl.SourceControlViewViewModel.Refresh() dans C:\Users\Mathieu\Documents\GitHub\Rubberduck (main)\Rubberduck\RetailCoder.VBE\UI\SourceControl\SourceControlViewViewModel.cs:ligne 910
   à Rubberduck.UI.SourceControl.SourceControlViewViewModel.<.ctor>b__11_8(Object _) dans C:\Users\Mathieu\Documents\GitHub\Rubberduck (main)\Rubberduck\RetailCoder.VBE\UI\SourceControl\SourceControlViewViewModel.cs:ligne 74
   à Rubberduck.UI.Command.DelegateCommand.ExecuteImpl(Object parameter) dans C:\Users\Mathieu\Documents\GitHub\Rubberduck (main)\Rubberduck\RetailCoder.VBE\UI\Command\DelegateCommand.cs:ligne 26
   à Rubberduck.UI.Command.CommandBase.Execute(Object parameter) dans C:\Users\Mathieu\Documents\GitHub\Rubberduck (main)\Rubberduck\RetailCoder.VBE\UI\Command\CommandBase.cs:ligne 54;
```

**Comment by retailcoder** [comment] 2017-06-28 16:14
The `COMException` is thrown here:

> **Microsoft.Vbe.Interop._VBComponent.Export(String FileName)**
à Rubberduck.VBEditor.SafeComWrappers.VBA.VBComponent.ExportAsSourceFile(String folder, Boolean tempFile) dans C:\Users\Mathieu\Documents\GitHub\Rubberduck (main)\Rubberduck\Rubberduck.VBEEditor\SafeComWrappers\VBA\VBComponent.cs:ligne 142

Does the path include spaces? Is it a UNC path?

**Comment by BaronBodissey** [comment] 2017-06-28 16:18
nop:
C:\Users\memyself\Desktop\DotNet\Office\repogittestrubberduck

**Comment by retailcoder** [comment] 2017-06-28 16:21
hmm, would the `ProjectId` happen to contain funky characters? Verify the `%appdata%\Rubberduck\SourceControl.rubberduck` configuration file.

**Comment by BaronBodissey** [comment] 2017-06-28 16:24
nop...for what I see:

<?xml version="1.0" encoding="utf-8"?>
<Configuration>
  <SourceControlSettings>
    <UserName />
    <EmailAddress />
    <DefaultRepositoryLocation />
    <Repositories>
      <Repository>
        <Id>97244304</Id>
        <LocalLocation>C:\Users\memyself\Desktop\DotNet\Office\repogittestrubberduck\Project</LocalLocation>
        <RemoteLocation>C:\Users\memyself\Desktop\DotNet\Office\repogittestrubberduck\Project</RemoteLocation>
      </Repository>
    </Repositories>
    <CommandPromptLocation>cmd.exe</CommandPromptLocation>
  </SourceControlSettings>
</Configuration>

**Comment by retailcoder** [comment] 2017-06-28 16:32
Is it the only open project? Source Control was designed to work with the active project, wheels come off if there's project-switching involved... TBH source control wheels come off for too many reasons to my taste though.

**Comment by BaronBodissey** [comment] 2017-06-29 06:44
Yes it was the only open project. I only have one.

**Comment by rubberduck203** [comment] 2018-03-09 10:43
@retailcoder looks like an export issue as far as #3758 is concerned. 
Leave this one open?

**Comment by Vogel612** [comment] 2018-03-24 01:42
Removed the source-control label and edited the OP for brevity

**Comment by pgeerkens** [comment] 2018-10-20 02:56
Hi Guys - remember me from last year?

I just encountered this when I in my own source-code dump into a directory and that directory is open in a File Explorer window. Perhaps that helps someone on Rubber Duck track down this error.

**Comment by bclothier** [comment] 2019-10-05 03:19
I just had a look at this issue and I'm unfortunately unable to reproduce this issue. 

This is what I did:

Using battleship spreadsheet, I exported the contents of the project to a folder. 
I open a Windows explorer to the same path.
I then export. No error.
I then create a new folder within it.
I then export, targeting the new folder but do not select it just yet.
I delete the folder via windows explorer.
I then select the folder and it still exports, re-creating the folder in the process.

Am I missing something?

**Comment by kwcolson** [comment] 2020-11-13 19:23
I got this exact error, which is how I landed on this page. When I changed the export from:

component.Export("c:\temp\test.cls");
to
component.Export("c:\\temp\\test.cls");
The problem resolved.

Posting in case this might help someone.

**Comment by rubberduck203** [comment] 2020-11-13 20:14
@kwcolson whats the difference between those two lines?
They look the same.

**Comment by kwcolson** [comment] 2020-11-13 20:44
@rubberduck203 updated

**Closed** 2021-04-01 05:33 UTC
Labels: bug, feature-export
