### ISSUE TITLE
Warn about ambiguous but legal module variable name

### ISSUE THREAD

**Issue by retailcoder** [rubberduck-vba/Rubberduck#3176] opened 2017-07-28 15:28 UTC
Per the VBA language specifications:

> A variable defined by a <module-variable-declaration> may have a variable name that is the same as the enum name of a <enum-declaration> defined in the same module but such a variable cannot be referenced using its variable name even if the variable name is module qualified.

So we need an inspection that warns about fields that are named the same as an enum name declared in the same module (same as enum *member name* would be ok?)

**Comment by BZngr** [comment] 2017-07-31 14:14
Trying to understand what the the inspection would be looking for.  Is the code below an example of what should be caught by the inspection?  Executing 'DoSomething()' generates an error.

```
Enum FruitType
    Apple = 1
    Orange = 2
    Plum = 3
End Enum

Public FruitType As String

Sub DoSomething()
    FruitType = "I'm a fruit"
    MsgBox FruitType
End Sub
```

The below 'works' in so far as executing 'DoSomething()' does not generate an error:

```
Enum FruitType
    Apple = 1
    Orange = 2
    Plum = 3
End Enum

Sub DoSomething()
    Dim FruitType As String
    FruitType = "I'm a fruit"
    MsgBox FruitType
End Sub
```

**Comment by retailcoder** [comment] 2017-07-31 14:36
It's the first case we're interested in warning about - there's a run-time error waiting to happen, but the VBE will happily compile that code regardless. In the 2nd snippet `FruitType` being declared in local scope makes it unambiguous (per VBA scoping rules) that local refs to `FruitType` are referring to the local variable. In the 1st snippet the name legally exists for two different things, in the same scope.

The inspection would turn a run-time notification into a design-time one, which is always a net gain.

**Comment by BZngr** [comment] 2017-08-08 16:14
In addition to variable/enum  name collisions, the VBE allows a name conflict to be created (and saved) between an Enum type name and a ClassModule name.  The good news is that the Enum/Class name conflict is identified by the VBE when closing the editor/Excel.  That said, the user can still click 'OK' when closing the editor, and the conflict is allowed to persist.

I'm looking for some input on this issue. I have code that adds the inspection to detect an existing name conflict between an Enum and other declaration types.  My question has to do with how to resolve the conflict.  I had thought it would be appropriate to associated the Rename QuickFix with this inspection result. So, in order to allow the user to efficiently select the declaration to rename, the inspection (as currently written) creates results for both the Enum and the other conflicting declaration(s) (variable or classmodule).  The thought was that the user could select the conflicting declaration he wants to rename and click the 'Fix' button to initiate the rename.  

However, what I've found is that the Rename process/logic quickly becomes very difficult since it must correctly resolve/interpret flawed parser results - the flaws caused by the name conflict(s) e.g., Enum reference identified/parsed as a Variable reference.  As I dreamed up conflict scenarios and attempted to resolve them with the RenameRefactor logic, the RenameRefactor code quickly became specific to my scenario(s)...with no general solution in sight.  It looks to me like using the rename quickfix is an unsolvable path.  Basically, the code needs to know when to believe and when to disbelieve the parse results.   As a result, I'm now thinking the best/simplest approach is to identify and locate the conflict(s)...and stop there.  Rather than associate the inspection result with the rename quickfix, prompt the user (by some mechanism) to fix the name conflict(s) manually.  After trying the rename-by-code approach, it seems to me that only the user can reliably interpret and rename the various conflicting references.

**Comment by BZngr** [comment] 2017-08-09 16:38
Probably need a sanity check at this point.  It would seem that the name conflict identified for this issue is wider than just enums.  If the purpose of the inspection is to find name conflicts that will cause an error at runtime, then any name conflict qualifies to be found by the inspection.  For example:


```
Option Explicit

Private Enum DoSomething
    Eat = 1
    Sleep = 2
    Code = 3
End Enum

Sub DoSomething()
    MsgBox "Just Do It"
End Sub

Public Function DoSomething() As Long
    DoSomething
    DoSomething = DoSomething.Code
End Function


```
The above module can be coded and saved in the VBE without any warnings.  Of course, any attempt to execute this code will result in an error.  In the above case, the Enum is just one case of the `DoSomething` name conflict.  There is still a latent name conflict error even if the Enum Type name is changed.

So, it seems appropriate to me that this inspection should be detecting _**all**_ name conflicts.  As indicated in my previous comment, my current approach is to 'Observe and Report' - there is no QuickFix offered to the user.  The inspection result will recommend that the user manually resolve them.  This would also have implications for RenameRefactoring.  Current plan: If the declaration to be renamed is part of an existing name conflict, the user will be informed, and the refactor operation cancelled.  

Have I wandered beyond the intent of this issue?

**Comment by retailcoder** [comment] 2017-08-09 18:14
Yeah that would be well beyond the scope of the inspection; we only need to warn about code that VBA happily compiles (Debug > Compile Project), but blows up at run-time.

**Comment by BZngr** [comment] 2017-08-09 19:14
OK - so...reeling the scope back 'in'.  I want to make sure I'm solving the right problem.  If the goal of this inspection is to find code (specifically same-module, enumeration type/Variable name conflicts) that compile but blow up during runtime, then my 'starting point' example (repeated below) does not appear to meet the criteria.  The `FruitType ` string assignment in `DoSomething()` is picked up by _Debug > Compile_ with an error that says 'Expected variable or procedure not enum type' - which is the same error one gets at runtime.

```
Enum FruitType
    Apple = 1
    Orange = 2
    Plum = 3
End Enum

Public FruitType As String

Sub DoSomething()
    FruitType = "I'm a fruit"
    MsgBox FruitType
End Sub
```

TBH I'm no longer seeing an issue to warn the user about that isn't handled by the VBE.

**Comment by retailcoder** [comment] 2017-08-09 19:23
hmm, might be that the inspection is moot? TBH I put it up from freaking out over how the spec defined it, without verifying how the VBE implemented it.

**Closed** 2017-08-09 19:33 UTC
Labels: difficulty-02-ducky, feature-inspections, status-declined
