### ISSUE TITLE
Remapping of CTRL-C

### ISSUE THREAD

**Issue by SteveLaycock** [rubberduck-vba/Rubberduck#3686] opened 2018-01-09 20:40 UTC
Following installation of the recent updated I'm finding that ctrl-C is opening the code window rather than copying the highlighted text.

It could be me having done something I don't remember.  If it is rubber duck then please be advised this remapping is very very naughty.

**Comment by Hosch250** [comment] 2018-01-09 20:41
It is RD, and it is unintentional. The team is working on a fix.

**Comment by Vogel612** [comment] 2018-01-09 20:41
*~blushes* We're totally not aware of this and it's behaving as designed

**Comment by rkapka** [comment] 2018-01-10 09:02
This is my mistake... While redesigning hotkeys I changed this shortcut for testing purposes and never changed it back (I should have at least chosen a less invasive one 😞 ). @retailcoder already checked in a fix, but he only updated the `app.settings` file and this won't suffice. The `.settings` file also needs to be updated.

**Comment by bolcholesterol** [comment] 2018-01-10 14:20
Sorry, but could you tell me what version doesn't have this bug?

**Comment by retailcoder** [comment] 2018-01-10 14:53
@bolcholesterol it's just the *default* - you can change the hotkey mappings in the Settings dialog:

![image](https://user-images.githubusercontent.com/5751684/34778679-06f619dc-f5ec-11e7-9ae5-28e5b69d024c.png)

The *intended* hotkey for the Code Explorer toolwindow is Ctrl+R, which overrides the VBE's shortcut for the *Project Explorer*.

**Closed** 2018-01-11 05:39 UTC
Labels: bug, difficulty-02-ducky, feature-hotkeys
