### ISSUE TITLE
Failure to Load

### ISSUE THREAD

**Issue by susnick** [rubberduck-vba/Rubberduck#4232] opened 2018-07-25 20:35 UTC
After I reopen my access database, RD fails to load. I have to sign out of my desktop and back in for it to work correctly. What should I be checking?

**Comment by retailcoder** [comment] 2018-07-25 20:52
Which version/build did you download/are you <s>running</s> trying to run?

If the message is coming from the VBE, then the installer correctly registered the add-in as such, but somehow failed to register the COM components. Are you local admin? IIRC the v2.2.0 "green release" has issues with local admin accounts.

If the message is coming from Rubberduck, then COM registration is probably ok, but logging being disabled by default, it's hard to tell exactly what happened.

Assuming the file didn't get to be created, I think you can enable logging without loading Rubberduck, by creating a `rubberduck.config` file under `%appdata%\Rubberduck`, with this content:

```xml
<?xml version="1.0" encoding="utf-8"?>
<Configuration>
  <GeneralSettings>
    <MinimumLogLevel>0</MinimumLogLevel>
  </GeneralSettings>
</Configuration>
```

**Comment by MDoerner** [comment] 2018-07-25 21:33
Since you state that RD does not load when you __reopen__ your Access database,and it loads again after a restart, this is probably due to issue  #3905. This again isa long standing problem with the cleanup of COM objects from the C# side.

Could you have a look in the task manager whether there remains a process for your Access database after you closed it? If there is one, could you terminate it via the task manager and see whether RD loads afterwards?

Are you running the latest release version or a prerelease version?

**Comment by bclothier** [comment] 2018-07-29 13:53
I'm going to close this as a dupe of #3905 -- further comments should go there.

**Closed by bclothier** 2018-07-29 13:53 UTC
Labels: bug, duplicate, support

**Comment by susnick** [comment] 2018-07-30 17:37
FYI Access was still running in Task Manager. So killing it fixed the issue. Thanks
