### ISSUE TITLE
Sorting in the Code Explorer doesn't work properly on initial sort.

### ISSUE THREAD

**Issue by daFreeMan** [rubberduck-vba/Rubberduck#2069] opened 2016-07-15 16:34 UTC
The initial sort order shown in the CodeExplorer doesn't seem to make much sense:
![rd](https://cloud.githubusercontent.com/assets/11889733/16879924/bc15b91c-4a80-11e6-8dcb-71514ee030c5.PNG)

It's not sorted by name (`Get` should come after all the `Gathers`) nor by code order (`GatherData` is defined first, yet listed third).

However, if there are different item types in the module, they are sorted by type, then name:
![rd2](https://cloud.githubusercontent.com/assets/11889733/16880025/36d6de6a-4a81-11e6-9012-2b43c21c1b4a.PNG)
Almost:
![rd3](https://cloud.githubusercontent.com/assets/11889733/16880636/36b7ecdc-4a84-11e6-87bf-5f27d64259e3.PNG)
Unless it's a matter of case sensitivity in the sort, except:
![rd4](https://cloud.githubusercontent.com/assets/11889733/16880698/729d318a-4a84-11e6-8d27-07b5debbb159.PNG)
_cut me some slack, have you tried drawing a question mark using a trackball lately???_

And it's not a matter of `Public` vs `Private` or `Sub` vs `Function`:
~~~
Private Sub PrintSbMTotalRow
Public Sub BuildReportDriver
Public Sub ReportClinicChange
Public Sub TestBuildReport
Public Sub UpdatePivotDates
Private Sub PrintSbMValue
~~~

**However**, once sort settings have been manually changed, everything seems to be just fine:
![rd6](https://cloud.githubusercontent.com/assets/11889733/16880982/e2eab1a0-4a85-11e6-8a46-1fb5bafd102b.PNG)
![rd7](https://cloud.githubusercontent.com/assets/11889733/16881069/488c946a-4a86-11e6-9550-484947e7e2e8.PNG)

Though sorting does seem to be case sensitive, can that be changed, or at least an option given?
![rd8](https://cloud.githubusercontent.com/assets/11889733/16881461/4d33d922-4a88-11e6-949f-bb7001950cd0.PNG)

**But**, reselecting group sorting is still a bit wonky:
![rd9](https://cloud.githubusercontent.com/assets/11889733/16881295/8d70a408-4a87-11e6-9e1e-aec703d8f63f.PNG)
~~~
Private Sub PrintNPSDataRows
Public Sub BuildReportDriver
Public Sub ReportClinicChange
Public Sub TestBuildReport
Private Sub PrintNPSFooterRows
~~~
_Note: `Public Sub UpdatePivotDates`, which was sorted into this group in the initial sort, is no longer here, I've confirmed that it's sorted in its proper location._
![rd8](https://cloud.githubusercontent.com/assets/11889733/16881447/3e199eb8-4a88-11e6-8ddc-41761a175cca.PNG)

Also, sort settings are not preserved. I usually uncheck `By Type`, yet each time I start an IDE, it's selected.

**Comment by retailcoder** [comment] 2016-07-15 16:43
@Hosch250 I thought this was as designed, but it doesn't appear to be. Can you take a look?

**Comment by daFreeMan** [comment] 2016-07-15 17:35
At @Hosch250's request:

for the first image:
![rd](https://cloud.githubusercontent.com/assets/11889733/16883088/48b368d8-4a90-11e6-81d0-d38484b4f2dc.PNG)
~~~
Private Function GatherScoreByMonthData
Private Function GetCount
Public Function GatherData
Private Sub GatherCareExperienceData
Private Sub GatherSatSurveyData
~~~
hmmm... maybe it is grouping those by type, then by visibility, then alpha. _However_, the 4th image (the one with the _awesome_ question mark), shows all `Sub`s but the visibility changes from `Private` to `Public`, then back to `Private`

**Comment by Hosch250** [comment] 2016-07-15 18:27
![](https://cloud.githubusercontent.com/assets/11889733/16879924/bc15b91c-4a80-11e6-8dcb-71514ee030c5.PNG)

Notice that item 3 doesn't have the same image as the ones above and below it.  How did that get put in the middle of a group?

**Comment by Hosch250** [comment] 2016-07-15 18:29
OK, those are different images for public/private functions.

**Comment by Hosch250** [comment] 2016-07-15 18:30
Turning By Type off, then on again, fixes this.

**Comment by daFreeMan** [comment] 2016-07-15 18:40
Except that it doesn't, @Hosch250.

The 2nd to last image in my OP shows 3 `Public Sub` between several `Private Sub` _after_ I reselected ByType (you'll see that I disabled `by Type` in the image 2 above that with the big exclamation point). There are a long list of `Private Sub` above and below that small snapshot. I can get a broader view if you'd like.

**Comment by Hosch250** [comment] 2016-07-15 18:43
Could you share the project with me?  I found that changing this:

    _projects = new ObservableCollection<CodeExplorerItemViewModel>(value.OrderBy(o => o.NameWithSignature));
    ReorderChildNodes(_projects);

to this:

    ReorderChildNodes(value);
    _projects = new ObservableCollection<CodeExplorerItemViewModel>(value.OrderBy(o => o.NameWithSignature));

fixes the initial sort problem (don't ask me why...)

**Comment by PeterMTaylor** [comment] 2016-07-15 23:10
Are there any hidden Unicode or unusual characters classified as unidefined being sorted within hex or strings that RD collected in the initial run? Just thinking...

**Comment by Hosch250** [comment] 2016-07-16 02:24
I guess this was closed because of the commit message.  If it isn't fixed in the next release, just reopen it.

**Comment by daFreeMan** [comment] 2016-07-18 19:13
Sadly, this doesn't seem to have been fixed in 2.0.6.

![rd](https://cloud.githubusercontent.com/assets/11889733/16927093/d9139e82-4cf9-11e6-8295-02c5bb15537e.PNG)

Same code, same module declarations, same example shot as originally posted (well, it's a new screen grab with 2.0.6 running, but it's the same place in the tree. You knew what I meant...

I'm don't see anywhere that I can reopen it, so one of y'alls gonna have to.

**Comment by Hosch250** [comment] 2016-07-19 00:58
Could you make a minimal reproducable example and share the project so I can see this first hand?

**Comment by daFreeMan** [comment] 2016-07-19 16:55
Rename this from `.txt` to `.xlsm` to get around Git restrictions 
[RD Default Sort Issue.txt](https://github.com/rubberduck-vba/Rubberduck/files/371987/RD.Default.Sort.Issue.txt)
![rd](https://cloud.githubusercontent.com/assets/11889733/16958778/00576f30-4db0-11e6-8c6b-2bcd13cc945d.PNG)

**Comment by Hosch250** [comment] 2016-07-19 17:03
![](http://imgur.com/XnvlkxO)

**Comment by Hosch250** [comment] 2016-07-19 17:04
Hmm, as soon as I change it, it messes everything up.

**Comment by daFreeMan** [comment] 2016-07-19 17:06
Yeah, it does sort properly once you change any of the sort order settings, but not until then.

Also, the sort settings are not retained from one launch to the next, but that may need to be a different issue

**Comment by Hosch250** [comment] 2016-07-19 17:11
Opposite here.  Worked right the first time, but not afterward...

**Comment by daFreeMan** [comment] 2016-07-19 17:16
that's.... weird...

**Comment by Hosch250** [comment] 2016-07-19 17:18
Got it.  I essentially wrote a random sort generator :P

    // keep types with different icons and the same declaration type (document/class module) separate
    // documents come first
    if (x.ExpandedIcon != y.ExpandedIcon)
    {
        // ReSharper disable once PossibleInvalidOperationException - this will have a component
        return x.QualifiedSelection.Value.QualifiedName.Component.Type ==
               Microsoft.Vbe.Interop.vbext_ComponentType.vbext_ct_Document
            ? -1
            : 1;
    }

**Comment by Hosch250** [comment] 2016-07-19 17:19
Notice that it correctly puts documents, first, both otherwise, it always returns `1`, regardless of what `x` is and what `y` is.

**Closed** 2016-07-19 18:08 UTC
Labels: bug, code-explorer, user-interface
