### ISSUE TITLE
Status bar shows function and get accessor return types as Object, rather than the actual object type

### ISSUE THREAD

**Issue by ThunderFrame** [rubberduck-vba/Rubberduck#4096] opened 2018-06-16 07:50 UTC
For library functions/classes, the return type is always shown as `Object` in the RD statusbar.

```vb
Sub foo()
    
    Dim x As Variant
        
    Set x = stdole.LoadPicture() 'Function returning stdole.IPictureDisp
    Set x = Excel.Application() 'Property Get Accessor returning Excel.Application
    
End Sub
```

![status](https://user-images.githubusercontent.com/16574009/41496906-b48fb5d6-718d-11e8-9211-e72b5b0c2f59.png)

**Comment by MDoerner** [comment] 2018-06-16 08:35
Just to make sure, can you verify that the VBA library got loaded successfully?

**Comment by ThunderFrame** [comment] 2018-06-16 11:46
As per 4091, there appear to be problems with the `VBA` library.

Looking closer at `Application` in `Set x = Excel.Application()`, the status bar shows it as being a member of `IHiHoLines`:

![status2](https://user-images.githubusercontent.com/16574009/41498350-b73b0a44-71ae-11e8-9ec1-32ab744d2218.png)

**Comment by ThunderFrame** [comment] 2018-06-16 11:53
i.e. I think 4091 is the most critical resolver bug right now.

**Comment by bclothier** [comment] 2018-06-16 18:36
Note that any COM object that has [`appobject` attribute](https://msdn.microsoft.com/en-us/library/windows/desktop/aa366726(v=vs.85).aspx) will also have a global scope. What this means is that for a VBA project that references an `Excel` library and `Access` library, there will be two implicit instances of `Excel.Application` and `Access.Application` loaded into the memory and thus can be accessed without the `Application` prefixing. The reference priority governs which `Application` object will take priority in cases where there are collisions in the member names for the respective `Application` objects. 

Therefore, the resolver need to know about any `appobject`-decorated COM objects in addition to the VBA project itself and resolve any implicit references accordingly.

**Comment by MDoerner** [comment] 2018-06-16 18:42
We already take the reference priority and the referenced library into consideration. That is not the problem here.  The problem is that there are tons of members with the same name in the same library.

**Comment by comintern** [comment] 2018-07-15 18:03
The 2 lines of code assigning to `x` are manifesting 2 different issues. The `stdole.LoadPicture()` issue is in the `ReferencedDeclarationsCollector` - currently the `ComParameter` for its `ReturnType` is failing, so it defaults the declaration to `Object`.

The `Excel.Application()` is declaration looks like it's being generated correctly, but all of the interface and coclass implementations are getting scoped to Global. I don't remember that being an issue for the resolver before, but apparently it is now.

Note: The COM collector is already processing the appobject attribute, and it's available from `ComType.IsAppObject`, it just never got added as a member on `ClassModuleDeclaration`.

**Comment by comintern** [comment] 2018-07-15 22:56
Not a regression. This appears to have always been broken.

**Closed** 2018-11-15 15:04 UTC
Labels: bug, resolver
