### ISSUE TITLE
Arg Out of Range Exception getting out of range exception

### ISSUE THREAD

**Issue by daFreeMan** [rubberduck-vba/Rubberduck#3918] opened 2018-04-10 12:49 UTC
Win10 x64, Access2016 x64, RD 2.2.0

Getting
```
WARN-2.2.6672.28001;Rubberduck.Inspections.Rubberduck.Inspections.Inspector;System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection.
```
On the initial parse of a project.

Full log:
[RubberduckLog.txt](https://github.com/rubberduck-vba/Rubberduck/files/1894596/RubberduckLog.txt)

**Comment by Vogel612** [comment] 2018-04-10 13:52
Duplicate of #3906

**Closed by Vogel612** 2018-04-10 13:52 UTC
