### ISSUE TITLE
Code Inspector - Cancelation of "Fix" is triggering reparsing

### ISSUE THREAD

**Issue by Pitterling** [rubberduck-vba/Rubberduck#1231] opened 2016-03-22 10:02 UTC
"Cancel" button like on "Ecapsulate Field" Windows is triggering reparsing of project. Also text frames are to small hiding text.

![rd-ci-reparsing](https://cloud.githubusercontent.com/assets/4181164/13947894/597ee976-f01d-11e5-86da-26d53a38f380.PNG)

**Comment by Hosch250** [comment] 2016-03-22 15:45
These really need WPF windows.  WPF windows are scheduled for 2.1, but the UI problems will be fixed by release, even if it is just a manual resize.  I don't know why Cancel triggers a parse, but this will be fixed too.

**Comment by retailcoder** [comment] 2016-03-22 17:03
The quick-fixes weren't designed to be cancellable.

They're executed from a command in the `InspectionResultsViewModel`, and by design, refresh the inspection results after executing:

        private void ExecuteQuickFixes(IEnumerable<CodeInspectionQuickFix> quickFixes)
        {
            foreach (var quickFix in quickFixes)
            {
                quickFix.Fix();
            }

            Task.Run(() => ExecuteRefreshCommandAsync(null));
        }

(code [here](https://github.com/rubberduck-vba/Rubberduck/blob/next/RetailCoder.VBE/UI/CodeInspections/InspectionResultsViewModel.cs#L182-L190))

Making quick-fixes cancellable would require modifying the [CodeInspectionQuickFix](https://github.com/rubberduck-vba/Rubberduck/blob/next/RetailCoder.VBE/Inspections/CodeInspectionQuickFix.cs#L23) abstract method `public void Fix();`, to turn it into `public bool Fix();` or something - that would ripple to all implementations and be a pain in the neck.

There's another way. We could add these members to the base class:

    private bool _isCancelled;
    public bool IsCancelled { get { return _isCancelled; } }

    public void Cancel()
    {
        _isCancelled = true;
    }

And then we could change `ExecuteQuickFixes` to this:

        private void ExecuteQuickFixes(IReadOnlyList<CodeInspectionQuickFix> quickFixes)
        {
            var completed = 0;
            foreach (var quickFix in quickFixes)
            {
                // if we have more than 1 fix to run, one cancelled should cancel all remaining fixes:
                if (!quickFixes.Any(fix => fix.IsCancelled)
                {
                    quickFix.Fix();
                    if (quickFix.IsCancelled) { completed++; }
                }
                else
                {
                    break; // no need to keep iterating
                }
            }

            // refresh if any quickfix has completed without cancelling:
            if (completed != 0)
            {
                Task.Run(() => ExecuteRefreshCommandAsync(null));
            }
        }

Now, for this to work, the quick-fix itself needs to set its `IsCancelled` state.

The [EncapsulateFieldQuickFix](https://github.com/rubberduck-vba/Rubberduck/blob/next/RetailCoder.VBE/Inspections/EncapsulatePublicFieldInspectionResult.cs#L50-L60) calls into a refactoring:

        public override void Fix()
        {
            var vbe = Selection.QualifiedName.Project.VBE;

            using (var view = new EncapsulateFieldDialog())
            {
                var factory = new EncapsulateFieldPresenterFactory(_parseResult, new ActiveCodePaneEditor(vbe, _wrapperFactory), view);
                var refactoring = new EncapsulateFieldRefactoring(factory, new ActiveCodePaneEditor(vbe, _wrapperFactory));
                refactoring.Refactor(_target);
            }
        }

Since the quickfix owns the `EncapsulateFieldDialog` instance, it should be able to access the `DialogResult` value directly, assuming clicking the `Cancel` button sets the dialog's result accordingly. If that's the case, then adding this line just before the closing brace of the `using` scope should give us the flag value we're after:

    IsCancelled = view.DialogResult == DialogResult.Cancel;

---

About this comment:

    // if we have more than 1 fix to run, one cancelled should cancel all remaining fixes:

Typically, fixes that need a UI can't be "fixed in module" nor "fixed in project", so this check is only a sanity check really - non-UI fixes wouldn't cancel anyway, and UI fixes would be a collection of 1. But let's just not assume that's always going to be the case, and cancel the batch after the user cancels one.

Despite all the attention given to `IsCancelled`, it's important that the refresh still happens when *any* quick-fix actually did modify anything anywhere - hence we need to track `completed` fixes, and run the refresh if `completed` is greater than 0 after we're done running/cancelling quick-fixes.

**Closed** 2016-03-26 07:52 UTC
Labels: bug, user-interface
