### ISSUE TITLE
False positive "Object variable {x} is assigned without the 'Set' keyword"

### ISSUE THREAD

**Issue by daFreeMan** [rubberduck-vba/Rubberduck#4318] opened 2018-08-29 15:54 UTC
Win10, Excel2016 (desktop), RD .3723

The following code generates a false positive on both the `.Values = ` and the `.XValues = ` lines

```VBA
  Dim TheChart As ChartObject
  Set TheChart = report.ChartObjects.Add(20, 20, 736, 211)
  Dim Ser As Series
  With TheChart
    Set Ser = .Chart.SeriesCollection.NewSeries
    With Ser
      Set .Values = "='" & DataRange.Parent.Name & "'!" & DataRange.Rows(mtdRow).Address(external:=False)
      .AxisGroup = xlPrimary
      .Name = "MTD"
      .ChartType = xlColumnClustered
      .XValues = "'" & DataRange.Parent.Name & "'!" & DataRange.Rows(xAxisRow).Address(external:=False)
      .ApplyDataLabels
```

Adding the `Set` keyword (as I've done based on the recommendation) generates RTE `424 - Object Required`.

My reading of the [MS docs](https://docs.microsoft.com/en-us/office/vba/api/excel.series.values) indicates that there are no objects here.

**Comment by daFreeMan** [comment] 2018-08-29 16:27
Gobs of this:

> 2018-08-29 11:24:32.1852;WARN-2.2.0.3723;Rubberduck.Parsing.Symbols.TypeAnnotationPass;Failed to resolve type _Recordset_Deprecated;
> 2018-08-29 11:24:32.2272;WARN-2.2.0.3723;Rubberduck.Parsing.Symbols.TypeAnnotationPass;Failed to resolve type _Recordset_Deprecated;
> 2018-08-29 11:24:32.2652;WARN-2.2.0.3723;Rubberduck.Parsing.Symbols.TypeAnnotationPass;Failed to resolve type _Recordset_Deprecated;
> 2018-08-29 11:24:32.2652;WARN-2.2.0.3723;Rubberduck.Parsing.Symbols.TypeAnnotationPass;Failed to resolve type _Recordset_Deprecated;
> 2018-08-29 11:24:32.2802;WARN-2.2.0.3723;Rubberduck.Parsing.Symbols.TypeAnnotationPass;Failed to resolve type _Recordset_Deprecated;
> 2018-08-29 11:24:32.2802;WARN-2.2.0.3723;Rubberduck.Parsing.Symbols.TypeAnnotationPass;Failed to resolve type _Recordset_Deprecated;
> 2018-08-29 11:24:32.2952;WARN-2.2.0.3723;Rubberduck.Parsing.Symbols.TypeAnnotationPass;Failed to resolve type _Recordset_Deprecated;
> 2018-08-29 11:24:32.2952;WARN-2.2.0.3723;Rubberduck.Parsing.Symbols.TypeAnnotationPass;Failed to resolve type _Recordset_Deprecated;
> 2018-08-29 11:24:32.3112;WARN-2.2.0.3723;Rubberduck.Parsing.Symbols.TypeAnnotationPass;Failed to resolve type _Recordset_Deprecated;
> 2018-08-29 11:24:32.3112;WARN-2.2.0.3723;Rubberduck.Parsing.Symbols.TypeAnnotationPass;Failed to resolve type _Recordset_Deprecated;
> 2018-08-29 11:24:32.3262;WARN-2.2.0.3723;Rubberduck.Parsing.Symbols.TypeAnnotationPass;Failed to resolve type _Recordset_Deprecated;
> 2018-08-29 11:24:32.3262;WARN-2.2.0.3723;Rubberduck.Parsing.Symbols.TypeAnnotationPass;Failed to resolve type _Recordset_Deprecated;
> 2018-08-29 11:24:32.3412;WARN-2.2.0.3723;Rubberduck.Parsing.Symbols.TypeAnnotationPass;Failed to resolve type _Recordset_Deprecated;
> 2018-08-29 11:24:32.4072;WARN-2.2.0.3723;Rubberduck.Parsing.Symbols.TypeAnnotationPass;Failed to resolve type VBE;
> 

Full log attached.
[RubberduckLog.txt](https://github.com/rubberduck-vba/Rubberduck/files/2332941/RubberduckLog.txt)

**Comment by daFreeMan** [comment] 2018-08-29 17:51
A couple of additional examples, in case it helps:

    Application.StatusBar = "Printing Cust Exp: " & CI.Name
    InRange.ColumnWidth = Width
    WorkRange.Font.Size = 10

**Comment by comintern** [comment] 2018-08-29 22:56
Oddly, I can't duplicate this in next, which makes me think it's a resolver issue. What references do you have in that project?

**Comment by daFreeMan** [comment] 2018-08-30 12:34
@comintern I've got:
* Visual Basic for Applications
* Microsoft Excel 16.0 Object Library
* OLE Automation
* Microsoft Office 16.0 Object Library
* Microsoft ActiveX Data Objects (multi-dimensional) 6.0 Library
* Microsoft ActiveX Data Objects 6.1 Library
* Microsoft ActiveX Data Objects Reordset 6.0 Library
* Microsoft Scripting Runtime

**Comment by daFreeMan** [comment] 2018-08-30 12:41
here's another example:

```VBA
  Dim RS As ADODB.Recordset
  Set RS = New ADODB.Recordset
  RS.ActiveConnection = dbConfig.SetupConnection(dbConfig.SQLConString)
```

(ignore the poor naming - I'm getting to that...)

**Comment by MDoerner** [comment] 2018-08-30 12:47
The last one is a bit nasty. The `ActiveConnection` property has a `Property Let` accepting both a string and a connection object.

The inspections probably assumes that a `Property Let` can only accept value types. However, as unintuitive as it is, that is not true.

**Comment by daFreeMan** [comment] 2018-08-31 12:39
Just updated from .3723 to .3739 and things seem to have gotten worse... 😞 

At the end of the day yesterday, my Excel project was down to 199 `Use meaningful names` inspection results and **no** other inspections (Posted a pic in chat for proof!). This morning, I've got _1, 2, 3... LOTS_ of new `ObjectAssignedWithoutSet` inspection results. 

<s>Almost</s> all of them <s>appear to be</s> are this:

```VBA
  Dim CI As ClinicItem
  For Each CI In clinicList.ClinicItems
```

The `CI` in the `For Each...` is being flagged as not being assigned without `Set`. They're not all specifically that particular list, either, though the majority are. There's also this one:

```VBA
  Dim cht As Chart
  Set cht = ActiveSheet.ChartObjects(1).Chart
  Dim srs As Series
  Set srs = cht.SeriesCollection(1)
  Dim pt As Point
  For Each pt In srs.Points
```

Just something funky in my class that's breaking things.

_Yes, I know, `ActiveSheet`. It's time to pay back some tech debt on this project, I'm getting there..._

**Comment by MDoerner** [comment] 2018-08-31 13:28
The inspection should really ignore these assignments.

**Comment by daFreeMan** [comment] 2018-08-31 13:30
Agreed, @MDoerner, however, these inspection results were _not_ present yesterday under .3723 but they're showing up now under .3739, so there's some sort of regression that's made things worse.

**Comment by MDoerner** [comment] 2018-08-31 13:36
This is a regression caused by PR #4314 trying to speed up the inspection. It removed the check that the assignment is an assignment in a Let statement.

**Comment by comintern** [comment] 2018-08-31 13:42
My fault. PR #4314 was apparently missing a commit that explicitly checks for `For Each` contexts. That was restructured because the prior code wasn't handling them correctly in all cases (see #4294). I can hot fix it in a couple hours.

**Comment by Vogel612** [comment] 2018-09-09 17:51
@carlossierra311 as I understand it, the root cause for these issues should be similar, which is why I closed as duplicate. Assuming that the fix for this issue doesn't resolve your issue as well, that'd definitely need a more thorough look into.

**Comment by carlossierra311** [comment] 2018-09-09 18:00
@Vogel612, Ok. I understand!  
Anyway, just as a clarification, I didn't mean to question you closing the other issue. I really think it's me who should have looked more carefully before posting :)

**Comment by daFreeMan** [comment] 2018-09-09 18:14
@carlossierra311  - Don't take it personally! Much better to have an issue reported twice than not at all. In fact, I'm usually the one posting the dupe report. In this case, it just happened that I had posted this issue, so I was well aware that it was already here.

**Comment by carlossierra311** [comment] 2018-09-09 18:29
Not at all!  ;)

**Comment by daFreeMan** [comment] 2018-11-12 14:57
Found a few more examples:

      Application.StatusBar = "Printing for: " & customerName

With "Object variable 'StatusBar'" being flagged. According to [MS Docs](https://docs.microsoft.com/en-us/office/vba/api/excel.application.statusbar), `Application` is an object, while the property `StatusBar` is a string. 

Is the issue that the inspection is seeing the Application object and throwing, instead of digging deeper to note that the property in question is _not_ an object?

**Comment by daFreeMan** [comment] 2018-11-12 15:47
As a followup to one of my earlier examples, I started with:

```VBA
  Dim RS As ADODB.Recordset
  Set RS = New ADODB.Recordset
  
  RS.ActiveConnection = dbConfig.SetupConnection(dbConfig.SQLConString)
```

This time I used the `Use 'Set' Keyword` quick fix, and this is what I got:

```VBA
  Dim RS As ADODB.Recordset
  Set RS = New ADODB.Recordset
  
  RS.Set ActiveConnection = dbConfig.SetupConnection(dbConfig.SQLConString)
```

After applying the fix, the code was parsed, but was _not_ compiled, as I got no warning about attempting to parse uncompilable code. Obviously, that won't compile, as an attempt to do so failed. Also, based on the parse of that code, I got 2 warnings and 2 errors:

> Warning | Member 'Set' was not found on the compile-time interface for type 'Recordset'.
Error | Variable 'ActiveConnection' is used but not assigned.
Error | Local variable 'ActiveConnection' is not declared.
Warning | Variable 'ActiveConnection' is not assigned.

I guess, based on the broken code, those are appropriate, however weird they may look...

I'm not sure if the misplacement of the `Set` keyword is going to be an issue once this is fixed, as I don't recall having had this when applying that quick fix in past, however, I thought I'd note it for the record.

**Comment by daFreeMan** [comment] 2018-12-03 15:08
Hate to be the bearer of bad news... I'm still having this issue in build .4244:

![2018-12-03 10_07_32-code inspections](https://user-images.githubusercontent.com/11889733/49382053-635f5000-f6e3-11e8-913c-a130de657c15.png)

**Comment by daFreeMan** [comment] 2018-12-03 18:30
Also getting this for a `Function as Variant` that I've written. I do _not_ know if this one was generating an error previously or if this is a new one.

![2018-12-03 13_29_12-microsoft visual basic for applications - satisfaction summary master v3 29 - de](https://user-images.githubusercontent.com/11889733/49393560-97486e80-f6ff-11e8-846a-7f93d0572842.png)

**Comment by daFreeMan** [comment] 2018-12-03 18:49
A nice clean log showing the generation of the most recently noted issue:
[RubberduckLog.txt](https://github.com/rubberduck-vba/Rubberduck/files/2640810/RubberduckLog.txt)

**Comment by daFreeMan** [comment] 2018-12-04 17:58
As of build .4261, this seems to be resolved!! 
I pulled the `'@Ignore` annotations from this code and got no inspection warnings.

.4261 does say "Fixes a variety of bugs", so maybe this was one inadvertently taken care of (and/or someone forgot to close this one).

**Comment by daFreeMan** [comment] 2018-12-04 19:32
Correction to above report:

_Every_ occurrence of `Application.StatusBar = "Text " & {something}` is triggering the inspection.

_Every_ occurrence of `Application.StatusBar = "Text"` passes cleanly.

**Comment by retailcoder** [comment] 2018-12-04 19:41
That's consistent with how the inspection/evaluation is currently implemented: given a non-object literal, we know there's no `Set` keyword needed. Given an expression, ....LHS should run the show (and `Variant` *should* be ignored... unless RHS is known to be an object type), because we currently can't evaluate the type of the RHS expression.

**Comment by MDoerner** [comment] 2018-12-04 20:06
The problem here is the following case in the inspection:
```csharp
var simpleName = expression.GetDescendent<VBAParser.SimpleNameExprContext>();
if (simpleName != null)
{
    return declarationFinderProvider.DeclarationFinder.MatchName(simpleName.identifier().GetText())
        .Any(d => AccessibilityCheck.IsAccessible(project, module, reference.ParentScoping, d) && d.IsObject);
}
```
This is supposed to cover the case wherer the RHS is a reference to a single varable or function. However, it is also triggered __every time_ the expression contains a `simpleNameExpression` and it will always return the first one it finds, which is also alwys wrong fro member accesses. 

In the last example it finds 'clinic`, which is of an object type.

**Closed** 2018-12-06 19:57 UTC
Labels: bug, feature-inspections, regression

**Comment by daFreeMan** [comment] 2019-04-18 17:50
This has, once again, reared its ugly head.

Version 2.4.1.4666
OS: Microsoft Windows NT 10.0.15063.0, x64
Host Product: Microsoft Office 2016 x64
Host Version: 16.0.4822.1000
Host Executable: EXCEL.EXE

```VBA
  Dim theChart As ChartObject
  Set theChart = report.ChartObjects.Add(20, 20, 736, 211)
  Dim Ser As Series
  With theChart
    Set Ser = .Chart.SeriesCollection.NewSeries
    With Ser
      .Values = "='" & DataRange.Parent.Name & "'!" & DataRange.Rows(mtdRow).Address(external:=False)
      .AxisGroup = xlPrimary
      .Name = "MTD"
      .ChartType = xlColumnClustered
      .XValues = "'" & DataRange.Parent.Name & "'!" & DataRange.Rows(xAxisRow).Address(external:=False)
      .ApplyDataLabels
      .DataLabels.Format.TextFrame2.TextRange.Font.Size = 9
      .Format.Fill.ForeColor.RGB = 11957550
    End With
```

The 2nd instance refers to a nearly identical line a few lines down in the code

![2019-04-18 13_48_22-Code Inspections](https://user-images.githubusercontent.com/11889733/56380633-b512fd80-61e0-11e9-9ccd-948c15f5849e.png)
