### ISSUE TITLE
Antlr grammar problem with line continuation after member access operator (.)

### ISSUE THREAD

**Issue by transistor1** [rubberduck-vba/Rubberduck#1650] opened 2016-06-01 13:47 UTC
Getting a parse error on the below:

```
Sub Valid_Expression_With_Parse_Error()
    Set app = Access. _
        Application
End Sub

```
Error: "no viable alternative at input '._\r\n'"

This is a contrived example, but it should illustrate the error.

**Comment by Vogel612** [comment] 2016-06-01 16:43
Wow that's evil.... like really evil...

the root cause for this will be in [L560-571](https://github.com/rubberduck-vba/Rubberduck/blob/next/Rubberduck.Parsing/Grammar/VBAParser.g4#L560-L571)

```
lExpression :
    lExpression whiteSpace? LPAREN whiteSpace? argumentList? whiteSpace? RPAREN                         # indexExpr
    | lExpression DOT unrestrictedIdentifier                                                            # memberAccessExpr
    | lExpression LINE_CONTINUATION whiteSpace? DOT unrestrictedIdentifier                              # memberAccessExpr
    | lExpression EXCLAMATIONPOINT unrestrictedIdentifier                                               # dictionaryAccessExpr
    | lExpression LINE_CONTINUATION EXCLAMATIONPOINT unrestrictedIdentifier                             # dictionaryAccessExpr
    | lExpression LINE_CONTINUATION EXCLAMATIONPOINT LINE_CONTINUATION unrestrictedIdentifier           # dictionaryAccessExpr
    | ME                                                                                                # instanceExpr
    | identifier                                                                                        # simpleNameExpr
    | DOT unrestrictedIdentifier                                                                        # withMemberAccessExpr
    | EXCLAMATIONPOINT unrestrictedIdentifier                                                           # withDictionaryAccessExpr
;
```

This just doesn't expect line continuations (see `DOT unrestrictedIdentifer`). Fixing this seems like a pain in the backside

**Comment by retailcoder** [comment] 2016-06-01 16:46
Work-around:

    Sub Valid_Expression_With_Parse_Error()
        Set app = Access _
            .Application
    End Sub

This is also a "more standard" way of line-continuing member expressions. It's supposed to be handled, @transistor1 can you confirm whether it parses fine?

**Comment by transistor1** [comment] 2016-06-01 16:54
@retailcodwr, your snippert *does* parse correctly, but I have a slew of legacy code I inherited that most likely does it the "wrong way".  VBA programmers aren't known for doing stuff the standard way. :)

**Closed** 2016-06-01 19:47 UTC
Labels: bug, critical, vba-grammar
