### ISSUE TITLE
Code Inspect Activeproject only

### ISSUE THREAD

**Issue by CharlesRHall** [rubberduck-vba/Rubberduck#4636] opened 2018-12-13 22:51 UTC
Was this ever implemented - it was discussed back in 2016 - it seems essential to my use - I hate wading through messages for a project I am not working on

**Comment by bclothier** [comment] 2018-12-13 22:59
I'm going to close this as a duplicate of #3041 which incidentally also will be addressed in some form by upcoming PR #4535. This isn't the exact thing because the PR deals with treating the user libraries as "external" in the sense that we will only parse for the resolution of the references. We can't simply just skip a project since that would cause the analysis to come up with false positives about undeclared declarations among other things. However, it will skip those projects for inspections, which should satisfy the request here.

**Closed by bclothier** 2018-12-13 22:59 UTC
