### ISSUE TITLE
RD had an error

### ISSUE THREAD

**Issue by daFreeMan** [rubberduck-vba/Rubberduck#2098] opened 2016-07-20 12:57 UTC
Renaming a class module.

![rd](https://cloud.githubusercontent.com/assets/11889733/16987003/c1aad120-4e57-11e6-9d43-808a840fdb5d.PNG)
[rubberduck.log.txt](https://github.com/rubberduck-vba/Rubberduck/files/373707/rubberduck.log.txt)

Is it me, or is it odd that @Hosch250 user directory structure is identified in the log file error messages?

**Comment by Vogel612** [comment] 2016-07-20 14:51
It's just as expected that Hosch's user directory structure is identifier in the log file error messages, because the release was built by him. Accordingly that user-structure is in the logs

Relevant stacktrace from within the log:

```
2016-07-20 08:54:38.2085;ERROR;DynamicInjectorfb844f590a714f0bb022fcabecb0d199;System.ArgumentOutOfRangeException: Index and count must refer to a location within the string.
Parameter name: count
   at System.String.Remove(Int32 startIndex, Int32 count)
   at Rubberduck.Refactorings.Rename.RenameRefactoring.GetReplacementLine(String content, String newName, Selection selection) in C:\Users\hosch\Documents\Visual Studio 2015\Projects\Rubberduck\RetailCoder.VBE\Refactorings\Rename\RenameRefactoring.cs:line 433
   at Rubberduck.Refactorings.Rename.RenameRefactoring.RenameUsages(Declaration target, String interfaceName) in C:\Users\hosch\Documents\Visual Studio 2015\Projects\Rubberduck\RetailCoder.VBE\Refactorings\Rename\RenameRefactoring.cs:line 395
   at Rubberduck.Refactorings.Rename.RenameRefactoring.Rename() in C:\Users\hosch\Documents\Visual Studio 2015\Projects\Rubberduck\RetailCoder.VBE\Refactorings\Rename\RenameRefactoring.cs:line 199
   at Rubberduck.Refactorings.Rename.RenameRefactoring.Refactor(Declaration target) in C:\Users\hosch\Documents\Visual Studio 2015\Projects\Rubberduck\RetailCoder.VBE\Refactorings\Rename\RenameRefactoring.cs:line 62
   at Rubberduck.UI.Command.CommandBase.Execute(Object parameter) in C:\Users\hosch\Documents\Visual Studio 2015\Projects\Rubberduck\RetailCoder.VBE\UI\Command\CommandBase.cs:line 60;
```

**Comment by Hosch250** [comment] 2016-07-20 15:33
Selection is off.  Are there any preprocessor directives in this file?

**Comment by daFreeMan** [comment] 2016-07-20 18:10
Nope

**Comment by Vogel612** [comment] 2016-09-15 14:50
Is this still relevant for 2.0.8?

**Comment by retailcoder** [comment] 2016-09-15 14:52
Probably. `RenameRefactoring` has a number of problems, this could be one.

**Comment by Vogel612** [comment] 2016-12-22 13:56
Has been recently reproduced in the linked issue, accordingly is still relevant

**Comment by retailcoder** [comment] 2017-03-02 16:26
can't repro on current build. closing for now, let's see how 2.0.12 goes.

**Closed by retailcoder** 2017-03-02 16:26 UTC
Labels: bug, critical, feature-refactorings, refactoring-rename
