### ISSUE TITLE
Adding "Next/Loop" following "For each" doesn't ignore comments.

### ISSUE THREAD

**Issue by Zak-Michael-Armstrong** [rubberduck-vba/Rubberduck#4289] opened 2018-08-20 13:02 UTC
Reproduction:

Create new Module.

Create test Sub.

Write the following comment:

`'For Each [Add whatever you want here]`

Hit enter.

A next/loop statement will be automatically added, even though the "for each" is contained within a comment.

**Comment by bclothier** [comment] 2018-08-20 13:07
Thanks for reporting! This is already known, described in #4266, so I'll close this as a duplicate.

**Comment by comintern** [comment] 2018-08-20 13:07
Duplicate of #4168 and #4266.  Block completion will be disabled until it becomes more stable.

**Closed by bclothier** 2018-08-20 13:07 UTC

**Comment by Zak-Michael-Armstrong** [comment] 2018-08-20 13:08
Cool, thanks. I figured it'd probably been found, but a quick bug search didn't throw anything up.
