### ISSUE TITLE
 Local variable 'Mid$' is not declared 

### ISSUE THREAD

**Issue by SystemsModelling** [rubberduck-vba/Rubberduck#2618] opened 2017-02-03 11:59 UTC
Local variable 'Mid$' is not declared 
It's a VBA function. Elsewhere it reports  Replace function `Mid` with existing typed function

**Comment by comintern** [comment] 2017-02-03 14:41
This only seems to effect the strongly typed declarations:

```
Sub test()
    Debug.Print Mid$("foo", 2, 1)   '<--resolves to local variable
    Debug.Print Mid("foo", 2, 1)    '<--resolves to VBA.Strings.Mid
End Sub
```

**Comment by retailcoder** [comment] 2017-02-03 14:57
regression bug :disappointed:

**Comment by comintern** [comment] 2017-03-04 19:10
Reopening.  86e2660 fixed everything _except_ for Mid\Mid$. Those functions are still an issue because the grammar isn't making a distinction between the Mid _statement_ ...

`Mid(foo, 2, 1) = bar`

...and the Mid _function_:

`bar = Mid(foo, 2, 1)`

**Comment by Vogel612** [comment] 2017-03-04 19:16
why do we not have a regression test for this yet? it's bitten us in the back twice now ...

**Comment by MDoerner** [comment] 2017-07-03 20:19
I cannot reproduce the original issue anymore; closing.

**Closed by MDoerner** 2017-07-03 20:19 UTC
Labels: bug, parse-tree-processing
