### ISSUE TITLE
RD misbehaving with VBIDE on opening VBIDE

### ISSUE THREAD

**Issue by SmileyFtW** [rubberduck-vba/Rubberduck#4858] opened 2019-03-15 16:04 UTC
Version 2.4.0.4586
OS: Microsoft Windows NT 10.0.17134.0, x64
Host Product: Microsoft Office x86
Host Version: 16.0.11328.20146
Host Executable: EXCEL.EXE

When I open the VBE either using Alt-F11 or from the developer tab I get the RD loading logo then this is how the VBE looks: 
![image](https://user-images.githubusercontent.com/42221335/54445047-ff9ce800-4711-11e9-8b9f-dc0afb95db68.png)

Attempting to resize the window causes Excel to lock up.

**Comment by bclothier** [comment] 2019-03-15 16:10
Linking #4722 and #4607

**Comment by comintern** [comment] 2019-03-15 16:12
By "lock up", do you mean go into a non-responsive state?  Also, to be clear - Excel is locking up, not just the VBE, right?

I also notice that you have MZ-Tools installed.  Can you reproduce this with MZ-Tools disabled? How about with RD disabled and MZ-Tools enabled?  If you have any other add-ins installed, I'd test them independently also.

If you could get a trace level log of this and post it here, that would be awesome.

**Comment by retailcoder** [comment] 2019-03-15 16:14
Interesting. I've had this weirdly-sized VBE occur to me (Excel 2016 x64), without MZ-Tools. I've mentally blamed in on Excel 2016, since RD doesn't do anything about the IDE window size.

Maximizing the IDE mainwindow worked fine though (didn't try resizing manually).

**Comment by djrivers** [comment] 2019-03-16 02:25
That always almost happens to me. Though there will also be times that RD will open maximized. I don't think it has anything to do with MZ-Tools. I've always had that tool installed. RD still opens, sometimes maximized and sometimes with that small window. Never tried manually resizing it though.

**Comment by SmileyFtW** [comment] 2019-03-17 19:06
I *think* it may be some window docking that is the root cause. I disabled MZT, Disabled all add-ins. Installed the latest pre-release. No joy; still the same - a complete lockup of Excel. I also did a Repair on MS Office which didn't help either.
I attempted to drag the VBE to resize and once I got a little resizing everything locked up and I had to restart Excel. Same thing when clicking the maximize button on the VBE window. Sometimes the window text would get really big and pixellated like resizing with a constant resolution.
I also opened with a new workbook so there wouldn't be anything for RD to work through; still locked up Excel.

I have gotten back to normal by setting RD to not open any windows (I normally had it to open Code Explorer and ToDo panes) and VBE options to not dock anything. So the VBE opened with only a code pane in the VBE window. Then opening CE with Project Explorer not docked/shown I was able to get back to work. It may indeed be a vagary within Excel itself and the docking of the PE, CE, and Properties panes upon startup.

**Comment by SmileyFtW** [comment] 2019-03-19 16:48
Update: problem persists. Opened it again today and the pint-size VBE window presented itself; growing it locked everything up. After restarting Excel, opened the VBE maximized it and closed all panes except the code pane and then was able to open the CE and other panes. Interestingly, when I tried to open the Immediate and Locals panes they didn't seem to respond. The separation/sizing bar was all the way to the bottom of the screen; dragged up to see them.

**Comment by Vogel612** [comment] 2019-03-19 16:53
This makes me wonder whether the WM_SIZE messages we intercept for dockable windows somehow interferes here... We shouldn't be able to mess with anything, but still...

**Comment by bclothier** [comment] 2019-04-24 14:37
I'm now of opinion that this isn't a RD issue. I've been seeing reports of this issues even on installs without RD.

**Comment by SmileyFtW** [comment] 2019-04-24 15:14
It sure is annoying and apparently unpredictable. Sure would like to know how others have encountered it (i.e. not using RD) and their setup: other add-ins installed, etc.

**Comment by daFreeMan** [comment] 2019-04-24 15:15
I've had that happen a couple of times with _Firefox_, but not (in my recollection) to the VBE.

**Comment by MDoerner** [comment] 2019-04-24 16:03
Currently, I observe the resize, but not the locking up, regularly at work, where no RD is installed. This only started to happen after we switched from Office 2010 to 365. My guess is that there is some strange problem between the hosts window manager and the VBE.

It might be that RD tries to react to the resize from the strange window size in a way the window manager really does not like. However, to really see what is going on, we will probably have to find a way to reproduce it with a debugger attached.

**Comment by SmileyFtW** [comment] 2019-04-24 16:20
I’ll help anyway I can…

**Comment by SonGokussj4** [comment] 2019-04-24 17:05
Hey, this is happening lately too. Often after I Clean/Build the RD project again, start Excel and press ALT+F11. On my second monitor, it appears on the top left. No stuck, I just make it bigger and it's fine. I'm on Office 2019. (which, I assume, should be somewhere in the neighbor of Office 365)

**Comment by bclothier** [comment] 2019-08-31 17:39
Because this issue covers two things - the weird tiny window behavior which as above already has been established as beyond RD's control (it will occurs even on a vanilla IDE. This seems more to do with Windows or Office365. The other issue about Excel locking, however, hasn't been observed. Thus, I'll close this. If there's any observation of Excel locking, open a new issue for that specifically.

**Closed by bclothier** 2019-08-31 17:39 UTC
Labels: bug, heisenbug
