### ISSUE TITLE
bugs in grammar

### ISSUE THREAD

**Issue by u-riaz** [rubberduck-vba/Rubberduck#1267] opened 2016-03-28 13:10 UTC
This ticket will be used to report some grammar bugs, as I'll continue to find them.
Here are some, I'd found yet.
1. modified `forNextStmt` & `forEachStmt` and add `typeHint?` in the last lines of both statements which were `NEXT (WS ambiguousIdentifier )?` . This is to support statements like `Next n%` etc. 
2. modified `deleteSettingStmt`, and made second parameter optional, initially only 3rd was optional. According to MSDN 2nd and 3rd both can be optional.
3. modified `lineLabel` from "ambiguousIdentifier ':';" to "(ambiguousIdentifier | SHORTLITERAL) ':';". I'd found some macros making line labels as `10:` etc. So, first version was not working.

These things were necessary for me, so, I'd changed grammar, RD may be handling these someway other. 

Now, I'm facing another issue.  Here is the code
```
Public Function A(var As Integer)
' some_code
 Do
 Loop Until var > 10
End Function
```
and here is the problematic rule
```
doLoopStmt :
	DO endOfStatement 
	block?
	LOOP
	|
	DO WS (WHILE | UNTIL) WS valueStmt endOfStatement
	block?
	LOOP
	| 
	DO endOfStatement
	block
	LOOP WS (WHILE | UNTIL) WS valueStmt
;
``` 

The question is, why `block` is not optional in last case? Either it is strict rule or mistake. Making `block` optional here can lead any problems?

**Comment by autoboosh** [comment] 2016-03-28 14:01
Do you want to send a PR with your changes once you're done?

The steps to update the grammar are:

1. Change grammar
2. Regenerate parser
3. Add tests
4. Send PR

If you're using Visual Studio 2013 you can use this addin https://github.com/tunnelvisionlabs/antlr4cs to regenerate the parser.

Tests can be added to the Grammar.VBAParserTests class. If you have some production code you can share you could also add them under the Testfiles folder so we can be sure we won't have any regressions.

Also it looks like you're still using the now outdated combined parser. If you update to the latest version of the next branch you'll see that there are no hardcoded strings in the parser anymore.

The issue you mentioned in point 3 might be replaced by the numberLiteral parser rule instead of SHORTLITERAL.

**Comment by autoboosh** [comment] 2016-04-01 16:27
Do you have an example for the "for each type hint" case?

**Comment by u-riaz** [comment] 2016-04-04 11:29
Every "For" loop with iterating variable having a `type hint` can be an example, i.e.
``` 
For n% = 1 To 5
 ' loop body statements
Next n%
```

Sorry, I don't have a setup for PR. I'm just using VBA.g with ANTLR's jar file to generate parser and then import these generated files into a Java project and generate tokens. 
You can guide me to send you the required things (test cases etc.) and you may go for a PR.
Yes, I'm using the older version, because I'd few changes (to support our particular scenarios) in VBA.g, and moving to next one would require some time to sync my changes with new version.

**Comment by u-riaz** [comment] 2016-04-04 11:42
Here is another problem :smile:
Following code snippet is failing to parse, and the reason is at line# 5.
```
If n3 = 1 Then
	If n2 = 1 Then S3 = "t" Else S3 = " m"
ElseIf n3 = 5 Then
	S3 = "m"
ElseIf n3 = 4 Then S3 = " t"
Else
	S3 = s09(n3)
End If
```

If we split line#5 to
```
ElseIf n3 = 4 Then 
      S3 = " t"
```
then all go OK.
This is because grammar requires `endOfStatement` after `Then`. I'd tried to making this `endOfStatement` optional but then ANTLR reports an error of possibly empty string matching (as `block?` is also optional.
Please help me to resolve this.
Thanks

**Comment by ThunderFrame** [comment] 2016-04-04 13:27
I'm AFK, but is this potentially an issue with #ElseIf Compiler Directive as well? Can Compliler Directives use the single line syntax like regular `If True Then DoFoo`?

**Comment by retailcoder** [comment] 2016-04-04 14:49
@ThunderFrame this won't compile:

    #If Win64 Then Dim Foo As Integer

So I wouldn't worry about inline `Then` for precompiler directives - they're not allowed.

**Comment by ThunderFrame** [comment] 2016-04-04 20:31
I was thinking more about Compiler continuations:

```vb
  #If VBA7 Then #Const x = 7
```
But that doesn't compile either.

**Comment by autoboosh** [comment] 2016-04-09 16:42
@u-riaz. The For-Loop example should work now.

The thing about compiling the parser yourself was just a suggestion. Your examples are more than enough to reproduce/fix these issues.

Also nice catch with that ElseIf bug, according to spec the "end of line" is optional (it shouldn't even be an end of statement). I'll have a look.

**Comment by autoboosh** [comment] 2016-05-11 21:27
Everything mentioned in this issue should be fixed. Please open a new issue if you find anything else.

**Closed by autoboosh** 2016-05-11 21:27 UTC
Labels: bug, code-parsing, vba-grammar
