### ISSUE TITLE
Code Inspecttions with no selected item displays empty context menu

### ISSUE THREAD

**Issue by IvenBach** [rubberduck-vba/Rubberduck#4803] opened 2019-02-15 00:19 UTC
Version 2.4.0.4533
OS: Microsoft Windows NT 6.1.7601 Service Pack 1, x64
Host Product: Microsoft Office 2013 x86
Host Version: 15.0.5093.1000
Host Executable: EXCEL.EXE

**Description**
Context menu attempts to be displayed when right click is used on grouping header before any item is selected.

**To Reproduce**
1. Have code that will show for as an inspection.
2. Right click on a grouping header. Tiny context menu attempts to show but nothing is available.

**Expected behavior**
Edge case. I'm not sure any menu should display if a context menu is shown without a selection.

**Screenshots**
![code inspections no selection context menu](https://user-images.githubusercontent.com/26076874/52825868-5069e400-3073-11e9-9e3e-d5363e25135b.png)

**Related**

1. Select an inspection
![inspection selected](https://user-images.githubusercontent.com/26076874/52825987-d554fd80-3073-11e9-98e6-a649f7d9a925.png)

2. Collapse header containing selected inspection.
3. Right click on another header. Same context menu shows for last selected item.
![context menu shown on header for collapsed inspection](https://user-images.githubusercontent.com/26076874/52826006-e7cf3700-3073-11e9-8e34-864e6320f673.png)

**Comment by comintern** [comment] 2019-02-15 00:33
Duplicate of #4791.

**Closed by comintern** 2019-02-15 00:33 UTC
Labels: bug, duplicate
