### ISSUE TITLE
Inappropriate "can be written as a function" opportunity

### ISSUE THREAD

**Issue by BStrauss3** [rubberduck-vba/Rubberduck#5932] opened 2022-01-16 15:11 UTC
Sub Increment(ByRef l as Long)
  l = l + 1
End Sub

Usage:

Increment account

Is flagged as "can be written as a function". Not sure this is really any better:

Function Increment(ByVal l as Long) as Long
   Increment = l + 1
End Function

Usage:

account = Increment(account)

**Comment by Vogel612** [comment] 2022-01-17 09:18
Considering that this doesn't actually exhibit any unintended behavior, I don't think this issue is actionable. As such I am closing it :)

**Closed by Vogel612** 2022-01-17 09:18 UTC
Labels: feature-refactorings, support, feature-inspection-quickfixes

**Comment by BStrauss3** [comment] 2022-01-17 14:10
I think that's fair.

I dumped  RD into a large existing project. And 40 hours in I'm still finding it overwhelming.  You might consider offering a "minimal existing project" set to enable at first. But that's a different request.

⁣
-----Burton


On Jan 17, 2022, 3:18 AM, at 3:18 AM, Clemens Lieb ***@***.***> wrote:
>Considering that this doesn't actually exhibit any unintended behavior,
>I don't think this issue is actionable. As such I am closing it :)
>
>-- 
>Reply to this email directly or view it on GitHub:
>https://github.com/rubberduck-vba/Rubberduck/issues/5932#issuecomment-1014301621
>You are receiving this because you authored the thread.
>
>Message ID:
***@***.***>
