### ISSUE TITLE
Great new version runs fine in Access now, too!

### ISSUE THREAD

**Issue by TorstenBStrauch** [rubberduck-vba/Rubberduck#3366] opened 2017-09-09 13:25 UTC
Hi guys,

Big cheers to all of you - I finally managed to use the Unit Test Framework in Access successfully, even with multiple Test Classes! Very well done! 👍 

However, there is still one small glitch: if you use multiple test modules

![attachment1](https://user-images.githubusercontent.com/26816385/30240579-4fdb3c60-9573-11e7-8cbc-b705aaf671b7.JPG)

the test runner obviously confuses the "Assert" and "Fake" objects of the different modules and throws runtime error 91 "Object or With block variable not set".

However, there is a workaround for that - see here:

![attachment2](https://user-images.githubusercontent.com/26816385/30240581-5d2a6cec-9573-11e7-91a8-ea62e331f7cc.JPG)

With this workaround in place, things work excellent.

Looking forward to the next version!

Cheers,
Torsten

**Comment by retailcoder** [comment] 2017-10-05 02:03
I think the problem is that the runner is actually confusing the `ModuleInitialize` methods between modules, and always calling the same one, which leaves the `Assert` object of the *would-be current module* not set.

A better solution would be to give these methods unique names, since Access doesn't understand module-qualified invocations like Excel does. The name isn't important, only the annotation is.

We need to get these methods to be named uniquely across test modules.. and perhaps even introduce an inspection to warn about same-name members in different modules.

**Comment by bclothier** [comment] 2018-10-25 10:56
Closing this because this has been long ago fixed in build 2.2 where we changed the way we run tests so this is no longer an issue.

**Closed by bclothier** 2018-10-25 10:56 UTC
Labels: bug, feature-unit-testing
