### ISSUE TITLE
Incorrect Inspection Result: 	The annotation 'TestMethod' was expected to have less arguments.

### ISSUE THREAD

**Issue by SteveLaycock** [rubberduck-vba/Rubberduck#5484] opened 2020-05-01 09:58 UTC
**Rubberduck version information**
Version 2.5.0.5422
OS: Microsoft Windows NT 10.0.18363.0, x64
Host Product: Microsoft Office x64
Host Version: 16.0.12730.20236
Host Executable: WINWORD.EXE

**Description**
I have 73 of these incorrect inspection reports.  My recollection is that I didn't used to get these error reports.

Here is an example that reproduces the incorrect inspection
```vba
'@TestMethod("StrO")
Private Sub T01_Count3()                        'TODO Rename test
    On Error GoTo TestFail
    
    'Arrange:
    Dim myTest As StrO
    Set myTest = StrO.Make("Hello,There,World")
    
    Dim myExpected As Long
    myExpected = 3
    
    'Act
    Dim myResult As Long
    myResult = myTest.CountSubStr
    
    'Assert:
    Assert.AreEqual myExpected, myResult

TestExit:
    Exit Sub
TestFail:
    Assert.Fail "Test raised an error: #" & Err.Number & " - " & Err.Description
End Sub
```

**Additional context**

**Comment by daFreeMan** [comment] 2020-05-01 10:41
Posting a log (you can drag 'n drop, not embed the text) may help determine the cause.

**Comment by SteveLaycock** [comment] 2020-05-01 11:00
As requested.

[RubberduckLog.txt](https://github.com/rubberduck-vba/Rubberduck/files/4563722/RubberduckLog.txt)


The resource I am working on at the moment is here

[https://github.com/SteveLaycock/StrO](url)

and is a bit of a mess because I'm new to github and haven't properly got my head around things yet.

**Comment by MDoerner** [comment] 2020-05-01 11:28
This is a duplicate of #5460.

**Closed by MDoerner** 2020-05-01 11:28 UTC
Labels: duplicate
