### ISSUE TITLE
Excel crashes on close.

### ISSUE THREAD

**Issue by casterle** [rubberduck-vba/Rubberduck#2524] opened 2017-01-12 20:57 UTC
2017-01-12 13:00:23.0003;INFO-2.0.11.2453;Rubberduck.App;Rubberduck version 2.0.11.2453 loading:
	Operating System: Microsoft Windows NT 6.1.7601 Service Pack 1 x64
	Host Product: Microsoft Office 2013 x86
	Host Version: 15.0.4885.1000
	Host Executable: EXCEL.EXE;

Steps to reproduce:
1) Open a new excel workbook
2) Click Developer tab
3) Click "Visual Basic" button
4) When the editor opens, click the "Refresh" button
5) Close the editor
6) Close Excel

It doesn't matter if you save the file on exit or not, nor does it matter if the worksheet contains one or more macros.

**Comment by retailcoder** [comment] 2017-01-12 21:35
Assuming you waited for a "Ready" state before closing, recent PR #2513 (unreleased yet) somewhat addresses this very much known issue that's been annoying the heck out of me for quite a while now.

Off the current [next] build, I haven't had a hard crash yet (e.g. "Excel is trying to recover your information"), but I've seen the EXCEL.EXE process linger in Task Manager after closing, *and also* quite frequent "clean" exits too (2.0.11 *does* cleanly exit quite often as well).

It *seems* to be related to the teardown of dockable toolwindows and/or commandbars, and/or a stray parser thread still accessing COM objects that the VBE has already destroyed.

**Comment by retailcoder** [comment] 2017-01-12 21:43
Please clarify.. is there a step 4.5, "wait for 'ready' state"?

**Comment by casterle** [comment] 2017-01-12 22:02
Yes, I was waiting for ‘ready’ state.

**Comment by retailcoder** [comment] 2017-01-27 04:00
Event log:

````
Application: EXCEL.EXE
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.Runtime.InteropServices.COMException
   at Microsoft.Office.Core.CommandBarControl.get_Parent()
   at Rubberduck.VBEditor.SafeComWrappers.Office.Core.CommandBarControl.get_Parent()
   at Rubberduck.VBEditor.SafeComWrappers.Office.Core.CommandBarButton.remove_Click(System.EventHandler`1<Rubberduck.VBEditor.SafeComWrappers.Office.Core.CommandBarButtonClickEventArgs>)
   at Rubberduck.UI.Command.MenuItems.CommandBars.AppCommandBarBase.RemoveChildren()
   at Rubberduck.UI.Command.MenuItems.CommandBars.RubberduckCommandBar.Dispose()
````

**Comment by A9G-Data-Droid** [comment] 2017-04-06 22:42
I'm getting a crash on exit that I believe is related. I am on version: 2.0.13.32288

 I get the Excel restart every time which is really annoying because I am trying to close Excel. I tried removing the config file to see if that would help and it does not. 

Each crash puts three entries in the Application Event Log:

1.
> Faulting application name: EXCEL.EXE, version: 15.0.4911.1000, time stamp: 0x58a2c0b7
> Faulting module name: ole32.dll, version: 6.1.7601.23392, time stamp: 0x56eb2f8f
> Exception code: 0xc0000005
> Fault offset: 0x0002f284
> Faulting process id: 0x1548
> Faulting application start time: 0x01d2af20f42bb206
> Faulting application path: C:\Program Files\Microsoft Office 15\Root\Office15\EXCEL.EXE
> Faulting module path: C:\Windows\syswow64\ole32.dll
> Report Id: f4e6a504-1b15-11e7-979f-989096db4196

2.

> Application: EXCEL.EXE
> Framework Version: v4.0.30319
> Description: The process was terminated due to an internal error in the .NET Runtime at IP 59C5FA8D (59B10000) with exit code 80131506.

3.

> Faulting application name: EXCEL.EXE, version: 15.0.4911.1000, time stamp: 0x58a2c0b7
> Faulting module name: clr.dll, version: 4.6.1055.0, time stamp: 0x563c0f73
> Exception code: 0xc0000005
> Fault offset: 0x0014fa8d
> Faulting process id: 0x1548
> Faulting application start time: 0x01d2af20f42bb206
> Faulting application path: C:\Program Files\Microsoft Office 15\Root\Office15\EXCEL.EXE
> Faulting module path: C:\Windows\Microsoft.NET\Framework\v4.0.30319\clr.dll
> Report Id: f8823d8c-1b15-11e7-979f-989096db4196

**Comment by MDoerner** [comment] 2018-02-13 13:47
This issue should have become less prevalent in the last prereleases. For more information, please see issue #3614 now being the main issue for the problems on host shutdown.

**Comment by bclothier** [comment] 2018-04-06 18:40
I no longer can reproduce this. I am going to close this as fixed. 

I also tested the bad scenario of shutting down Excel in a middle of parse and this still exits, albeit a bit delayed as I assume it has to do some cleanup but it does eventually die all nice and tidy. 

If there is any new incident, please open a new issue with updated details.

**Closed by bclothier** 2018-04-06 18:40 UTC
Labels: bug
