### ISSUE TITLE
Procedure *_Click is not used

### ISSUE THREAD

**Issue by peterennis** [rubberduck-vba/Rubberduck#2016] opened 2016-07-11 20:15 UTC
It is a proc in the form code. Not used? What is this trying to tell me?
![capture27](https://cloud.githubusercontent.com/assets/140737/16745140/5ad2e02c-4769-11e6-93cd-1ffb062dae76.PNG)

**Comment by Hosch250** [comment] 2016-07-11 20:16
Is `img_ae` the name of an image component?  This looks like a bug.  Basically, it is telling you that you never manually call the proc, but we aren't taking events into account correctly.

**Comment by daFreeMan** [comment] 2016-07-11 20:25
I reported this issue quite some time ago (before 2.x alpha). 

In Access, any button code is marked as not being called.
In Excel, and On* (Change, etc) code is marked as not being called.

I've put reminder comments in my code to ensure I don't accidentally delete a function based on RDs recommendation in these cases.

**Comment by retailcoder** [comment] 2016-07-11 20:26
Is this a UserForm's code-behind? We iterate controls in `UserForm`'s designer and generate a declaration for each one, and we know to treat `ControlName_EventName` procedures as handlers - e.g. a control named `Button1` with a `Button1_Click` handler could be refactor/renamed to `MyButton` and the handler would automatically adjust to `MyButton_Click` - however it doesn't work with all control types because COM is being a bit of a PITA here, and it doesn't work at all in MS-Access forms, because they aren't `UserForm` classes and they don't have a `.Designer` property that returns a `UserForm` instance.

The inspection sees no caller for the procedure, and doesn't see anything hinting at it being a handler for a control, and thus fires a result to warn about the procedure not being used - that's the one known false positive we'd really like to fix, but honestly unless we start accessing the internal `IStream` and poking at unmanaged memory to get ahold of the actual types involved here, I fear this will be the only "fix" available:

    '@Ignore ProcedureNotUsed

**Comment by retailcoder** [comment] 2016-07-11 20:28
@daFreeMan Excel workbook and worksheet event handlers are correctly picked up as such, since we managed to figure out how to tell Rubberduck that `ThisWorkbook` is implementing the `_Workbook` interface; ditto with `Sheet1` / `_Worksheet`.

**Comment by daFreeMan** [comment] 2016-07-11 20:30
@retailcoder - Cool! I haven't checked the code inspections lately. I'll do so ASAP.

**Comment by retailcoder** [comment] 2016-07-11 20:32
I also hereby confirm that an `Image` control's `Click` handler on a `UserForm`'s code-behind doesn't fire that inspection.

The problem is limited to Access forms it seems.

**Comment by peterennis** [comment] 2016-07-11 20:43
Yes, it is user CBF.

**Comment by ThunderFrame** [comment] 2016-10-03 10:00
Problem also occurs for ActiveX controls on Excel Sheets, Word documents and PowerPoint slides/masters.

Linking #389

**Closed** 2017-03-05 19:07 UTC
Labels: bug, feature-inspections, help-wanted
