### ISSUE TITLE
Splash Screen still shows version 2.5.1

### ISSUE THREAD

**Issue by maxwinkler13** [rubberduck-vba/Rubberduck#5857] opened 2021-09-21 18:27 UTC
**Rubberduck version information**
The info below can be copy-paste-completed from the first lines of Rubberduck's log or the About box:

Version 2.5.2.5958
OS: Microsoft Windows NT 10.0.19043.0, x64
Host Product: Microsoft Office x64
Host Version: 16.0.14228.20324
Host Executable: EXCEL.EXE

**Description**
After upgrading to version 2.5.2.5958 (and I believe the prior version as well), the yellow splash screen that shows when launching VBA Editor still shows the Version as 2.5.1

**To Reproduce**
Launch VBA Editor

**Expected behavior**
The yellow rubberduck splashscreen should show at least the major/minor version of 2.5.2 instead of 2.5.1. An indication of patch level 5958 would certainly be sweet as well.

**Screenshots**
![image](https://user-images.githubusercontent.com/29756616/134226872-79be8fd2-b216-4814-af56-dc9a6e57f73b.png)

![image](https://user-images.githubusercontent.com/29756616/134226905-a139963e-ba55-4ef7-aeb2-140bd156786d.png)

**Logfile**
There are no errors logged for this. It seems to be purely cosmetic. The actual version does indeed show the correct version in the About window.

**Additional context**

**Comment by Vogel612** [comment] 2021-09-21 20:24
*~sighs~*, it seems I misdiagnosed the issue. Ususually `GetType().Assembly` and `Assembly.GetExecutingAssembly()` should return the same object (according to the documentation of the latter), which implies that the issue is actually with the way the assembly version is defined and of course within Rubberduck.Core.csproj the AssemblyVersion property is set to `2.5.1`. That change was erroneously introduced in a merge commit updating the branch that was merged in the mentioned PR and snuck through our reviews.

**Closed** 2021-09-21 22:51 UTC
Labels: bug, user-interface, up-for-grabs, difficulty-01-duckling
