### ISSUE TITLE
Code metrics

### ISSUE THREAD

**Issue by SystemsModelling** [rubberduck-vba/Rubberduck#4101] opened 2018-06-18 10:25 UTC
Not an issue, but a request: I can click on one proc at a time and see its LOC and complexity. Is there a report for the whole project so I can rank procs for attention?  2.2.0.3398-pre

**Comment by Vogel612** [comment] 2019-04-08 22:58
I'm considering this a duplicate of #4358. Closing accordingly

**Closed by Vogel612** 2019-04-08 22:58 UTC
Labels: difficulty-02-ducky, duplicate, enhancement, feature-code-metrics, up-for-grabs, user-interface
