### ISSUE TITLE
`ByVal parameter is assigned` inspection fires even when parameter is an object.

### ISSUE THREAD

**Issue by daFreeMan** [rubberduck-vba/Rubberduck#2721] opened 2017-02-22 16:14 UTC
```VBA
Sub main()
  Dim Foo As Object
  Set Foo = New Object
  DoSomething Foo
End Sub

Sub DoSomething (ByVal Baz As Object)
  Baz.Bar = 'x'
End Sub
```
`Baz.Bar = x` triggers the `ByVal parameter is assigned` inspection. However, this is OK since `Baz` is an object and the result will show up at the call site as expected.

**Comment by retailcoder** [comment] 2017-02-22 16:16
Hmm, this feels like it could be the resolver annotating `Baz` with an `IdentifierReference` with the `IsAssignmentTarget` wrongly set to `true`.

**Comment by comintern** [comment] 2017-02-22 16:19
This is a duplicate of #2601.

**Closed by comintern** 2017-02-22 16:19 UTC
Labels: bug, parse-tree-processing
