### ISSUE TITLE
Folder Annotation Scope

### ISSUE THREAD

**Issue by bbarney213** [rubberduck-vba/Rubberduck#3393] opened 2017-09-25 14:59 UTC
The generated folder annotations puts it within scope of the subroutine which causes it to not work properly in some instances. The folder annotation should be generated above options (such as Option Explicit) instead to avoid this issue.

**Comment by retailcoder** [comment] 2017-09-25 15:06
So, *insert* module annotations at line 1, no matter what. Perhaps look for existing annotations and sort them alphabetically before deciding where to put what, e.g. `'@Folder` goes before `'@IgnoreModule` and after `'@Exposed`, which comes before `'@PredeclaredId`, and essentially rewrite the "module annotations" block every time.

**Comment by retailcoder** [comment] 2017-10-04 14:47
We are simply generating the annotation 1 line after where it needs to be. Should be a trivial fix.

**Comment by retailcoder** [comment] 2017-10-27 14:02
We're creating components from a string literal that contains nothing but the folder annotation, [here](https://github.com/rubberduck-vba/Rubberduck/blob/next/RetailCoder.VBE/UI/CodeExplorer/Commands/AddComponentCommand.cs#L40).

        public void AddComponent(CodeExplorerItemViewModel node, ComponentType type)
        {
            var components = node != null
                ? GetDeclaration(node).Project.VBComponents
                : _vbe.ActiveVBProject.VBComponents;

            var folderAnnotation = $"'@Folder(\"{GetFolder(node)}\")";

            var newComponent = components.Add(type);
            newComponent.CodeModule.AddFromString(folderAnnotation);
        }

So if the VBE isn't setup to *require variable declaration*, the annotation *is* inserted at the very top of the module.

The problem is that with *require variable declaration* turned on, the VBE adds `Option Explicit\r\n\r\n` to every new module, and so `AddFromString` isn't cutting it, because of that annoying extraneous empty line we have no control over.

A work-around would be to disable *require variable declaration*, but recommending that would be stupid.

One possible fix is to replace the `AddFromString` call with an actual line insert at the first empty line; this leaves `Option Explicit` at the top, but then the folder annotation could become illegal if the user puts the first procedure scope on the line immediately under it:

![image](https://user-images.githubusercontent.com/5751684/32107341-4c921df4-bafc-11e7-8841-cd2a308550ee.png) ![image](https://user-images.githubusercontent.com/5751684/32107390-6c80a54a-bafc-11e7-971a-f0512239be9a.png)

So a better fix would be to insert the annotation *at* line 1, so as to shift `Option Explicit` down, along with its extraneous line break. The result would always be valid:

![image](https://user-images.githubusercontent.com/5751684/32107691-6a47e062-bafd-11e7-8608-735ac81d6974.png) ![image](https://user-images.githubusercontent.com/5751684/32107737-827c5c9e-bafd-11e7-809e-e98cb6b49b69.png)

So by replacing `AddFromString(folderAnnotation)` with `InsertLines(1, folderAnnotation)`, we fix this issue.

**Comment by retailcoder** [comment] 2017-10-27 14:24
Let's add a `<summary>` XML comment on the `ICodeModule` interface's `AddFromString` method, too.

    ///<summary>
    /// Adds the specified code to the module after the VBE inserted Option Explicit and an extra empty line if "require variable declaration" is enabled.
    ///</summary>

**Comment by IvenBach** [comment] 2017-10-27 15:55
Based on my testing last night that's what I had seen. I just want to raise the issue of a possible edge case. We expect to see what's below, `Option Explicit` should never be turned off :wink:
```
'@Folder("Bar")
Option Explicit
Public Sub Foo()

End Sub
```
but knowing things aren't perfect what should we do about below? If there isn't `vbCrLf` (¿AKA `\r\n`?) there is no folder in CodeExplorer, there has to be the newline.
```
'@Folder("Bar")
'@ProcedureAnnotation("Duk")
Public Sub Foo()

End Sub
```
Is this worthy of worrying about it or just insert with `\r\n` and let users deal with no folder being created if they remove it?

**Comment by Vogel612** [comment] 2017-10-27 17:08
@IvenBach seems like an overthinking to me. 
If we create Folder annotations we should be able to expect there's an Option Explicit set ...

**Comment by IvenBach** [comment] 2017-11-01 18:28
Close now that the fix has been merged?

**Closed** 2017-11-01 18:58 UTC
Labels: bug, difficulty-01-duckling, feature-annotations, feature-inspection-quickfixes, hacktoberfest, up-for-grabs
