### ISSUE TITLE
Unhandled exception:  COM object that has been separated from its underlying RCW cannot be used.

### ISSUE THREAD

**Issue by Steve-Sexton** [rubberduck-vba/Rubberduck#5802] opened 2021-06-04 19:54 UTC
**Rubberduck version information**

```
Version 2.5.2.5906
OS: Microsoft Windows NT 10.0.19043.0, x64
Host Product: Microsoft Office x86
Host Version: 16.0.11901.20218
Host Executable: EXCEL.EXE
```

**Description**
Unhandled exception when closing Excel:  COM object that has been separated from its underlying RCW cannot be used.

**To Reproduce**
1. Exit Excel

**Expected behavior**
Close without error.  Excel process must be ended to recover.

**Screenshots**
![image](https://user-images.githubusercontent.com/32441527/120855519-98ff8100-c54c-11eb-9db0-4ff06fe8cd95.png)

**Logfile**

```
2021-03-09 11:23:53.4993;INFO-;Rubberduck._Extension;Rubberduck is shutting down.;
2021-03-09 11:23:53.5683;INFO-;Rubberduck._Extension;No exceptions were thrown.;
``` 

**Additional context**

```
See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.Runtime.InteropServices.InvalidComObjectException: COM object that has been separated from its underlying RCW cannot be used.
   at System.StubHelpers.StubHelpers.GetCOMIPFromRCW(Object objSrc, IntPtr pCPCMD, IntPtr& ppTarget, Boolean& pfNeedsRelease)
   at Microsoft.Office.Core.CommandBarControl.set_Enabled(Boolean pvarfEnabled)
   at Rubberduck.VBEditor.SafeComWrappers.Office12.CommandBarButton.set_IsEnabled(Boolean value) in C:\projects\rubberduck\Rubberduck.VBEditor.VBA\SafeComWrappers\Office\CommandBarButton.cs:line 192
   at Rubberduck.UI.Command.MenuItems.CommandBars.AppCommandBarBase.<>c__DisplayClass11_1.<EvaluateCanExecuteAsync>b__1() in C:\projects\rubberduck\Rubberduck.Core\UI\Command\MenuItems\CommandBars\AppCommandBarBase.cs:line 173
   at Rubberduck.Parsing.UIContext.UiDispatcher.<>c__DisplayClass2_0.<InvokeAsync>b__0(Object x) in C:\projects\rubberduck\Rubberduck.Parsing\UIContext\UiDispatcher.cs:line 26
```

**Comment by PhilCattivocaratere** [comment] 2021-06-05 04:06
Perhaps the same than this #5764 ?

**Comment by Vogel612** [comment] 2021-06-05 14:50
Closing as a duplicate of the mentioned issue. The exact location of the RCW disconnect is different, but the underlying issue is the same

**Closed by Vogel612** 2021-06-05 14:50 UTC
Labels: bug, duplicate
