### ISSUE TITLE
Form events picked up as "Unused Sub"

### ISSUE THREAD

**Issue by FuSoftware** [rubberduck-vba/Rubberduck#4570] opened 2018-11-28 08:17 UTC
Somewhat related to https://github.com/rubberduck-vba/Rubberduck/issues/4560

MS Access events (Both on form controls and form events) are picked up as unused Subs. That's to be expected since nothing calls them from VBA, but they are indeed used by the controls, and VBE is aware of that (the panel on top of the editor that shows Objects/Events).

MCVE : Create a new MS Access database, create a form, add a button, add a VBA event to the button, run RD.

**Comment by bclothier** [comment] 2018-11-28 11:56
Thanks for the report - that is also already tracked by other issues enumerated in the #4560, in particular #3924. Thus, closing it as a duplicate of #3924.

**Closed by bclothier** 2018-11-28 11:56 UTC
