### ISSUE TITLE
Code Explorer Doesn't sort modules alphabetically

### ISSUE THREAD

**Issue by CHR-IS-B** [rubberduck-vba/Rubberduck#4775] opened 2019-02-06 18:55 UTC
**Rubberduck version information**
Version 2.4.0.4488
OS: Microsoft Windows NT 6.1.7601 Service Pack 1, x64
Host Product: Microsoft Office 2016 x86
Host Version: 16.0.4795.1000
Host Executable: EXCEL.EXE

**Description**
I could not get the code explorer to sort -modules- by their names alphabetically when using the sort by name option.

**Expected behavior**
I expected the modules within folders in the RD Code Explorer to be sorted alphabetically.  Folders and procedures are sorted but not the modules.

**Screenshots**
Sorted by name
![image](https://user-images.githubusercontent.com/22154950/52365724-f88d0680-29fc-11e9-990a-8d288dcc7b81.png)

Sorted as in 
![image](https://user-images.githubusercontent.com/22154950/52365860-44d84680-29fd-11e9-8975-cc564ab2e97e.png)

**Logfile**
[RubberduckLog.txt](https://github.com/rubberduck-vba/Rubberduck/files/2837815/RubberduckLog.txt)

**Comment by comintern** [comment] 2019-02-06 19:11
This appears to be a duplicate of #4771, and should have been closed in the most recent build.  Can you grab that one and confirm that it sorts as expected?

**Comment by CHR-IS-B** [comment] 2019-02-06 19:28
You're right, it's the same issue.  I'll try the most recent build.

**Comment by CHR-IS-B** [comment] 2019-02-06 20:02
This is -not- an issue in v2.4.0.4511.

**Closed** 2019-02-06 20:03 UTC
Labels: bug
