### ISSUE TITLE
Error while refreshing for the first time

### ISSUE THREAD

**Issue by ebayol** [rubberduck-vba/Rubberduck#4031] opened 2018-05-23 08:40 UTC
Hi, I just installed rubberduck and tried to run it on an empty project.
When refreshing for the first time, I get the following message:
Unable to compile for parsing

the following project(s) cannot be compiled, which will most likely result in parser errors. Continue anyway?

VBAProject

this is the logfile generated:
[RubberduckLog.txt](https://github.com/rubberduck-vba/Rubberduck/files/2030187/RubberduckLog.txt)

**Comment by Vogel612** [comment] 2018-05-23 11:40
Is that really the complete logfile? Can you reproduce the error? If yes, could you please set the log-level to TRACE in the settings and upload that logfile? Thanks!

```
2018-05-23 10:10:38.3421;ERROR-2.2.6716.24410;Rubberduck.Parsing.VBA.ParseCoordinator;Unexpected exception thrown in parsing run. (thread 14).;System.Runtime.InteropServices.COMException (0x80029C4A): Erreur lors du chargement de la bibliothèque/DLL du type. (Exception de HRESULT : 0x80029C4A (TYPE_E_CANTLOADLIBRARY))
   à Microsoft.Vbe.Interop.Reference.get_IsBroken()
   à Rubberduck.VBEditor.SafeComWrappers.VBA.Reference.get_IsBroken() dans C:\projects\rubberduck\Rubberduck.VBEditor.VBA\SafeComWrappers\VB\Reference.cs:ligne 67
   à Rubberduck.Parsing.VBA.COMReferenceSynchronizerBase.GetReferencesToLoadAndSaveReferencePriority(IReadOnlyList`1 projects) dans C:\projects\rubberduck\Rubberduck.Parsing\VBA\COMReferenceSynchronizerBase.cs:ligne 106
   à Rubberduck.Parsing.VBA.COMReferenceSynchronizerBase.SyncComReferences(IReadOnlyList`1 projects, CancellationToken token) dans C:\projects\rubberduck\Rubberduck.Parsing\VBA\COMReferenceSynchronizerBase.cs:ligne 69
   à Rubberduck.Parsing.VBA.ParsingStageService.SyncComReferences(IReadOnlyList`1 projects, CancellationToken token) dans C:\projects\rubberduck\Rubberduck.Parsing\VBA\ParsingStageService.cs:ligne 99
   à Rubberduck.Parsing.VBA.ParseCoordinator.ExecuteCommonParseActivities(IReadOnlyCollection`1 toParse, IReadOnlyCollection`1 toReresolveReferencesInput, CancellationToken token) dans C:\projects\rubberduck\Rubberduck.Parsing\VBA\ParseCoordinator.cs:ligne 174
   à Rubberduck.Parsing.VBA.ParseCoordinator.ParseAllInternal(Object requestor, CancellationToken token) dans C:\projects\rubberduck\Rubberduck.Parsing\VBA\ParseCoordinator.cs:ligne 383
   à Rubberduck.Parsing.VBA.ParseCoordinator.ParseAll(Object requestor, CancellationToken token) dans C:\projects\rubberduck\Rubberduck.Parsing\VBA\ParseCoordinator.cs:ligne 313
```

**Comment by ebayol** [comment] 2018-05-23 11:44
there you go:
[RubberduckLog.txt](https://github.com/rubberduck-vba/Rubberduck/files/2030828/RubberduckLog.txt)

**Comment by MDoerner** [comment] 2018-05-23 11:57
Seems as if we need more localised exception handling in the COM reference synchroniser. For some reason the reference COM object is throwing.

**Comment by retailcoder** [comment] 2018-05-23 19:18
Would you happen to have any `<MISSING>` references? Does Debug/Compile succeed?

The "cannot be compiled" message is just a warning; you can disable it by un-ticking the "compile before parse" checkbox in the *general settings* tab of the settings dialog. Working with compilable code was always an assumption in Rubberduck, only recently we've been having the ability to instruct the VBE to attempt a compilation and report back to us before launching a parse task.

Ignoring the warning, or turning off "compile before parse", may confuse the parser, or produce resolver errors, depending on the exact nature of the reason why the code couldn't be compiled.

**Comment by bclothier** [comment] 2018-07-17 04:18
Tried to reproduce by deliberately introducing a missing reference - this does cause the symptom described but as indicated, if it's due to missing reference, then that's beyond Rubberduck's control and therefore I'm closing the issue as resolved as it seems to me expected behavior. If there is a reproduction to the contrary, feel free to reopen.

**Closed by bclothier** 2018-07-17 04:18 UTC
Labels: bug, support

**Comment by inDeev** [comment] 2018-08-20 06:32
Hi, I had a same issue with TYPE_E_CANTLOADLIBRARY and I've found a solution.
I searched through regedit. You need to go to "HKEY_CLASSES_ROOT\TypeLib\{2DF8D04C-5BFA-101B-BDE5-00AA0044DE52}" open latest sub-key (for me it is 2.8), then subkey 0 and subkey Win32. Check in file explorer if on shown path really MSO.dll exists. If not go to earlier version of subkey (like 2.7 or 2.6) and check file on paths defined there. If you find it, just copy the path to the latest subkey -> 0 -> Win32. It started to work for me, after excel was reopened. I hope, this will help.

**Comment by PeterMTaylor** [comment] 2018-08-20 07:03
Just a curious question to ask reading this...What’s the big thing about subkey in the registry is this the same as checkin for the bitness of MSO.dll when loaded or version management Of which version of MSO.dll to use?

**Comment by bclothier** [comment] 2018-08-20 11:09
This implies to me that there were multiple installations of Office on a single PC, and from my experience, while it's "supported" by Microsoft, it's not totally robust and heavy use can mess up the registration -- you know how changing versions shows that dialog about installing Office, slowing down the startup? That's basically doing registration. If one loads multiple versions concurrently or do not allow the "Installing" message to complete, it can corrupt the registry (among other things) which would result in strange behavior like the missing library as originally reported. 

In this case, I would prefer to either repair or even better, uninstall all and install only one version.
