### ISSUE TITLE
Rem without apostrophe should also be shown in the TODO Explorer

### ISSUE THREAD

**Issue by ricardoba13** [rubberduck-vba/Rubberduck#5223] opened 2019-10-15 16:06 UTC
**Justification**
VBA native syntax allows me to use the Rem keyword to create a comment for "REMmerbering" me something.

**Description**
 What the Explorer is doing is just showing me the comments marked as `<'Rem>`, and not also the `<Rem>` ones

**Additional context**
I have lots of things with the <Rem> keyword being used and I would love to see those in the Rubberduck Explorer.

**Comment by retailcoder** [comment] 2019-10-15 16:13
No repro with a rather outdated v2.4.1.5033 build:

![image](https://user-images.githubusercontent.com/5751684/66849414-d6149b00-ef44-11e9-9f66-990858ed0c8b.png)

Note that the `Rem`ark keyword is obsolete, and will be flagged as such in inspection results (unless the inspection is disabled): they can easily be converted to single-quote comments with a quick-fix.

**Comment by retailcoder** [comment] 2019-10-15 16:22
Ok I think I misread your post.

The role of `Rem` in `'Rem something something` and the role of `Rem` in `Rem something something` is different. In `'Rem`, the comment marker is `'` a single quote. In `Rem something`, the comment marker is the `Rem` keyword.

Grammatically, the comment marker is not part of the comment text, which is what TODO markers look at. If you're using `REM` as a TODO marker, you can't use `Rem` as a comment marker. Or you need to do `Rem Rem`, where the first is the syntactical comment marker, and the second is the TODO marker.

We are not going to be modifying TODO logic to look for TODO markers in the comment marker token.

**Comment by ricardoba13** [comment] 2019-10-15 16:41
I got your point, so basically the logic was built without taking the Rem native VBA comment marker into account. And, what I get from your comment is that adding such a marker as another way of creating comments is a lot of work to do. And I completely understand that point.

However, having such a change will be really great since as I have mentioned, the Rem marker was intended to be used for that from the VBA creators and now for Rubberduck is a good popint to address so that developers that use the Rem marker as initially intended by VBA, then gets really happy when seeing their TODO lists in the Rubberduck TODO explorer.

I mean, I love this AddIn and this is something that I would really love to have, I know I can use the Find and Replace to do all this stuff. But, for new Rubberduck users, that would be just great

**Comment by MDoerner** [comment] 2019-10-15 16:47
The logic was built with the `Rem` comment marker in mind as a comment marker: it is treated like the usual comment marker `'`. 

The logic of ToDo markers has been implemented to look for comment markers at the start of the comment, no matter whether it is a comment using the `Rem` keyword or the `'` keyword. In both cases, the comment marker itself is not part of the comment itself.

**Comment by bclothier** [comment] 2019-10-15 16:49
@ricardoba13  I'm happy to hear that you love the addin! 

I totally understand what you're getting at. However, as mentioned, we encourage people to avoid using deprecated / obsolete keywords and `Rem` keyword would be inspected as such. We also think of the ducky as a helpful guide to help us stay current and use the best practices. For that reason, I'd say that it's probably best for all users that `Rem` keyword was not re-purposed for some other purpose. It's totally fine to go ahead and find & replace `Rem` into `'Rem`, which makes it just a TODO marker... After all, you're `Rem`embering, not `Rem`arking. :)

**Comment by ricardoba13** [comment] 2019-10-15 16:57
@MDoerner hmm, so the `Rem` keyword is intended to "Remark" something and not to "Remember" something, if that is the actual case, that's a game changer then. And I have to admit I was wrong!

**Comment by Vogel612** [comment] 2019-10-15 17:12
I consider this behaviour by design (and it seems the other dev team members share my opinion there). As such I'm closing this issue. Thanks for your feedback :)

**Closed by Vogel612** 2019-10-15 17:12 UTC
Labels: enhancement, feature-todo-explorer, status-bydesign
