### ISSUE TITLE
Resolver Error in v2.0.1b

### ISSUE THREAD

**Issue by PeterMTaylor** [rubberduck-vba/Rubberduck#1791] opened 2016-06-11 04:16 UTC
Here's my resolver error using v2.0.1b. I used @retailcoder's ScreentoGif to show you what's happens. Big file I know, be patient to see all of it. I'll use a smaller screen next time. I had looked at the logs provided. No Errors or DEBUG given. I'll resync my branch and see.
![rd 2 0 1b resolve error demo](https://cloud.githubusercontent.com/assets/2254567/15983044/6f5e25f8-2fde-11e6-990d-e4c81c1f464d.gif)

**Comment by PeterMTaylor** [comment] 2016-06-11 05:27
Ok, here is my build result repeating the steps shown in the video using my VS2015 sync with commit https://github.com/rubberduck-vba/Rubberduck/commit/e00aa64579fa90f755edc996b5f2b3f0c19900e7 

[RD 2.0.1b Output-Debug.txt](https://github.com/rubberduck-vba/Rubberduck/files/310110/RD.2.0.1b.Output-Debug.txt)

Turns out the resolve error failed on binding, that is attempting to locate information regarding binding. 'EXCEL.EXE' (CLR v4.0.30319: DefaultDomain): Loaded 'C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\PresentationFramework-SystemCore\v4.0_4.0.0.0__b77a5c561934e089\PresentationFramework-SystemCore.dll'. Symbols loaded.
System.Windows.Data Error: 40 : BindingExpression path error: 'CanRefresh' property not found on 'object' ''CodeExplorerViewModel' (HashCode=52610097)'. BindingExpression:Path=CanRefresh; DataItem='CodeExplorerViewModel' (HashCode=52610097); target element is 'ToggleButton' (Name='DisplaySignatures'); target property is 'IsEnabled' (type 'Boolean')

..AND.. @comintern @retailcoder it threw an exception on close of Excel.com at the last minute not in my file but in my Error Debug when closing down Excel.

'EXCEL.EXE' (Win32): Unloaded 'C:\Program Files (x86)\Microsoft Power Query for Excel\bin\sqmapi_x86.dll'
Exception thrown at 0x755C2EFD (combase.dll) in EXCEL.EXE: 0xC0000005: Access violation reading location 0x184656F4.

The program '[5328] EXCEL.EXE' has exited with code 255 (0xff).

**Comment by PeterMTaylor** [comment] 2016-06-11 23:35
I learnt from the chat that there is a log option that can trace errors so repeated the steps again to be sure using 2.0.1b.

Error occurs 
```
2016-06-12 09:28:56.9324;ERROR;Rubberduck.Parsing.VBA.RubberduckParser;Exception thrown acquiring declarations for 'cDataSet' (thread 14).;System.NullReferenceException: Object reference not set to an instance of an object.
   at Rubberduck.Parsing.Symbols.DeclarationSymbolsListener.CreateDeclaration(String identifierName, String asTypeName, Accessibility accessibility, DeclarationType declarationType, ParserRuleContext context, Selection selection, Boolean isArray, AsTypeClauseContext asTypeContext, String typeHint, Boolean selfAssigned, Boolean withEvents) in C:\Users\hosch\Documents\Visual Studio 2015\Projects\Rubberduck\Rubberduck.Parsing\Symbols\DeclarationSymbolsListener.cs:line 185
   at Rubberduck.Parsing.Symbols.DeclarationSymbolsListener.EnterArgList(ArgListContext context) in C:\Users\hosch\Documents\Visual Studio 2015\Projects\Rubberduck\Rubberduck.Parsing\Symbols\DeclarationSymbolsListener.cs:line 656
   at Rubberduck.Parsing.Grammar.VBAParser.ArgListContext.EnterRule(IParseTreeListener listener) in C:\Users\hosch\Documents\Visual Studio 2015\Projects\Rubberduck\Rubberduck.Parsing\Grammar\VBAParser.cs:line 5393
   at Antlr4.Runtime.Tree.ParseTreeWalker.EnterRule(IParseTreeListener listener, IRuleNode r)
   at Antlr4.Runtime.Tree.ParseTreeWalker.Walk(IParseTreeListener listener, IParseTree t)
   at Antlr4.Runtime.Tree.ParseTreeWalker.Walk(IParseTreeListener listener, IParseTree t)
   at Antlr4.Runtime.Tree.ParseTreeWalker.Walk(IParseTreeListener listener, IParseTree t)
   at Antlr4.Runtime.Tree.ParseTreeWalker.Walk(IParseTreeListener listener, IParseTree t)
   at Antlr4.Runtime.Tree.ParseTreeWalker.Walk(IParseTreeListener listener, IParseTree t)
   at Antlr4.Runtime.Tree.ParseTreeWalker.Walk(IParseTreeListener listener, IParseTree t)
   at Rubberduck.Parsing.VBA.RubberduckParser.ResolveDeclarations(VBComponent component, IParseTree tree) in C:\Users\hosch\Documents\Visual Studio 2015\Projects\Rubberduck\Rubberduck.Parsing\VBA\RubberduckParser.cs:line 541
2016-06-12 09:28:57.5418;ERROR;Rubberduck.Parsing.VBA.RubberduckParser;Exception thrown acquiring declarations for 'cDataRow' (thread 14).;System.NullReferenceException: Object reference not set to an instance of an object.
   at Rubberduck.Parsing.Symbols.DeclarationSymbolsListener.CreateDeclaration(String identifierName, String asTypeName, Accessibility accessibility, DeclarationType declarationType, ParserRuleContext context, Selection selection, Boolean isArray, AsTypeClauseContext asTypeContext, String typeHint, Boolean selfAssigned, Boolean withEvents) in C:\Users\hosch\Documents\Visual Studio 2015\Projects\Rubberduck\Rubberduck.Parsing\Symbols\DeclarationSymbolsListener.cs:line 185
   at Rubberduck.Parsing.Symbols.DeclarationSymbolsListener.EnterArgList(ArgListContext context) in C:\Users\hosch\Documents\Visual Studio 2015\Projects\Rubberduck\Rubberduck.Parsing\Symbols\DeclarationSymbolsListener.cs:line 656
   at Rubberduck.Parsing.Grammar.VBAParser.ArgListContext.EnterRule(IParseTreeListener listener) in C:\Users\hosch\Documents\Visual Studio 2015\Projects\Rubberduck\Rubberduck.Parsing\Grammar\VBAParser.cs:line 5393
   at Antlr4.Runtime.Tree.ParseTreeWalker.EnterRule(IParseTreeListener listener, IRuleNode r)
   at Antlr4.Runtime.Tree.ParseTreeWalker.Walk(IParseTreeListener listener, IParseTree t)
   at Antlr4.Runtime.Tree.ParseTreeWalker.Walk(IParseTreeListener listener, IParseTree t)
   at Antlr4.Runtime.Tree.ParseTreeWalker.Walk(IParseTreeListener listener, IParseTree t)
   at Antlr4.Runtime.Tree.ParseTreeWalker.Walk(IParseTreeListener listener, IParseTree t)
   at Antlr4.Runtime.Tree.ParseTreeWalker.Walk(IParseTreeListener listener, IParseTree t)
   at Antlr4.Runtime.Tree.ParseTreeWalker.Walk(IParseTreeListener listener, IParseTree t)
   at Rubberduck.Parsing.VBA.RubberduckParser.ResolveDeclarations(VBComponent component, IParseTree tree) in C:\Users\hosch\Documents\Visual Studio 2015\Projects\Rubberduck\Rubberduck.Parsing\VBA\RubberduckParser.cs:line 541
```

**Comment by autoboosh** [comment] 2016-06-11 23:48
This might be fixed with the Debug.Print PR. Here's the line with the fix: https://github.com/autoboosh/Rubberduck/blob/ae7d72818f21ff493fe78b5f1649f7fe7e99f5ee/Rubberduck.Parsing/Symbols/DeclarationSymbolsListener.cs#L188. Ran into a null reference exception as well while testing that PR. The line numbers are a bit off though (difference between Debug and Release build?)

**Comment by retailcoder** [comment] 2016-06-11 23:55
@autoboosh the release build wouldn't include the nop codes, i.e. `Debug.WriteLine` and `Debug.Assert` calls.. could be that the .pdb is off a few lines for that reason.

**Comment by PeterMTaylor** [comment] 2016-06-15 12:01
Just to let you know that the latest commit https://github.com/rubberduck-vba/Rubberduck/commit/1ae56310cc55e0167b436e952d4ca66a82656534 repeats the same Resolve error on the same file I submitted with this issue. 

I am beginning to think that "Object reference not set to an instance of an object." errors I'm seeing alot of my code is something in my own reference are not resolved by the parser.  @Hosch250 is there a way to see what references have been obtained by RD when the resolver could not find it? To cross-check thanks.

```
`016-06-15 21:48:51.5886;DEBUG;Rubberduck.Parsing.VBA.RubberduckParserState;ParserState changed to 'Resolving', raising OnStateChanged;
2016-06-15 21:48:51.5886;DEBUG;Rubberduck.UI.Inspections.InspectionResultsViewModel;InspectionResultsViewModel handles StateChanged...;
2016-06-15 21:48:51.5886;DEBUG;Rubberduck.UI.Command.MenuItems.RubberduckCommandBar;RubberduckCommandBar handles StateChanged...;
2016-06-15 21:48:51.5886;DEBUG;Rubberduck.UI.Command.MenuItems.RubberduckCommandBar;RubberduckCommandBar status text changes to 'Resolving...'.;
2016-06-15 21:48:51.6046;DEBUG;Rubberduck.App;App handles StateChanged (Resolving), evaluating menu states...;
2016-06-15 21:48:52.6603;DEBUG;Rubberduck.Parsing.VBA.RubberduckParser;Module 'Module1' was NOT modified;
2016-06-15 21:48:52.6713;DEBUG;Rubberduck.Parsing.VBA.RubberduckParser;Creating declarations for module VBAProject.Module1.;
2016-06-15 21:48:52.6883;DEBUG;Rubberduck.Parsing.VBA.RubberduckParser;Module 'restLibrary' was NOT modified;
2016-06-15 21:48:52.6883;DEBUG;Rubberduck.Parsing.VBA.RubberduckParser;Creating declarations for module VBAProject.restLibrary.;
2016-06-15 21:48:52.7203;DEBUG;Rubberduck.Parsing.VBA.RubberduckParser;Module 'cDataSet' was NOT modified;
2016-06-15 21:48:52.7273;DEBUG;Rubberduck.Parsing.VBA.RubberduckParser;Creating declarations for module VBAProject.cDataSet.;
Exception thrown: 'System.NullReferenceException' in Rubberduck.Parsing.dll
2016-06-15 21:48:52.7743;ERROR;Rubberduck.Parsing.VBA.RubberduckParser;Exception thrown acquiring declarations for 'cDataSet' (thread 8).;System.NullReferenceException: Object reference not set to an instance of an object.
   at Rubberduck.Parsing.Symbols.DeclarationSymbolsListener.CreateDeclaration(String identifierName, String asTypeName, Accessibility accessibility, DeclarationType declarationType, ParserRuleContext context, Selection selection, Boolean isArray, AsTypeClauseContext asTypeContext, String typeHint, Boolean selfAssigned, Boolean withEvents) in C:\Users\hosch\Documents\Visual Studio 2015\Projects\Rubberduck\Rubberduck.Parsing\Symbols\DeclarationSymbolsListener.cs:line 185
   at Rubberduck.Parsing.Symbols.DeclarationSymbolsListener.EnterArgList(ArgListContext context) in C:\Users\hosch\Documents\Visual Studio 2015\Projects\Rubberduck\Rubberduck.Parsing\Symbols\DeclarationSymbolsListener.cs:line 656
   at Rubberduck.Parsing.Grammar.VBAParser.ArgListContext.EnterRule(IParseTreeListener listener) in C:\Users\hosch\Documents\Visual Studio 2015\Projects\Rubberduck\Rubberduck.Parsing\Grammar\VBAParser.cs:line 5393
   at Antlr4.Runtime.Tree.ParseTreeWalker.EnterRule(IParseTreeListener listener, IRuleNode r)
   at Antlr4.Runtime.Tree.ParseTreeWalker.Walk(IParseTreeListener listener, IParseTree t)
   at Antlr4.Runtime.Tree.ParseTreeWalker.Walk(IParseTreeListener listener, IParseTree t)
   at Antlr4.Runtime.Tree.ParseTreeWalker.Walk(IParseTreeListener listener, IParseTree t)
   at Antlr4.Runtime.Tree.ParseTreeWalker.Walk(IParseTreeListener listener, IParseTree t)
   at Antlr4.Runtime.Tree.ParseTreeWalker.Walk(IParseTreeListener listener, IParseTree t)
   at Antlr4.Runtime.Tree.ParseTreeWalker.Walk(IParseTreeListener listener, IParseTree t)
   at Rubberduck.Parsing.VBA.RubberduckParser.ResolveDeclarations(VBComponent component, IParseTree tree) in C:\Users\hosch\Documents\Visual Studio 2015\Projects\Rubberduck\Rubberduck.Parsing\VBA\RubberduckParser.cs:line 541
2016-06-15 21:48:52.8184;DEBUG;Rubberduck.Parsing.VBA.RubberduckParserState;Module 'cDataSet' state is changing to 'ResolverError' (thread 8);
2016-06-15 21:48:52.8264;DEBUG;Rubberduck.Parsing.VBA.RubberduckParserState;ParserState evaluates to 'ResolverError' (thread 8);
2016-06-15 21:48:52.8264;DEBUG;Rubberduck.Parsing.VBA.RubberduckParserState;ParserState changed to 'ResolverError', raising OnStateChanged;
2016-06-15 21:48:52.8374;DEBUG;Rubberduck.UI.Inspections.InspectionResultsViewModel;InspectionResultsViewModel handles StateChanged...;
2016-06-15 21:48:52.8374;DEBUG;Rubberduck.UI.Command.MenuItems.RubberduckCommandBar;RubberduckCommandBar handles StateChanged...;
2016-06-15 21:48:52.8374;DEBUG;Rubberduck.UI.Command.MenuItems.RubberduckCommandBar;RubberduckCommandBar status text changes to 'Resolver Error'.;
2016-06-15 21:48:52.8374;DEBUG;Rubberduck.App;App handles StateChanged (ResolverError), evaluating menu states...;
2016-06-15 21:48:53.0305;DEBUG;Rubberduck.Parsing.VBA.RubberduckParser;Module 'cHeadingRow' was NOT modified;
2016-06-15 21:48:53.0775;DEBUG;Rubberduck.Parsing.VBA.RubberduckParser;Creating declarations for module VBAProject.cHeadingRow.;
2016-06-15 21:48:53.0916;DEBUG;Rubberduck.Parsing.VBA.RubberduckParser;Module 'cStringChunker' was NOT modified;
2016-06-15 21:48:53.0916;DEBUG;Rubberduck.Parsing.VBA.RubberduckParser;Creating declarations for module VBAProject.cStringChunker.;
2016-06-15 21:48:53.1086;DEBUG;Rubberduck.Parsing.VBA.RubberduckParser;Module 'cDataColumn' was NOT modified;
2016-06-15 21:48:53.1086;DEBUG;Rubberduck.Parsing.VBA.RubberduckParser;Creating declarations for module VBAProject.cDataColumn.;
2016-06-15 21:48:53.1276;DEBUG;Rubberduck.Parsing.VBA.RubberduckParser;Module 'Sheet2' was NOT modified;
2016-06-15 21:48:53.1376;DEBUG;Rubberduck.Parsing.VBA.RubberduckParser;Creating declarations for module VBAProject.Sheet2.;
2016-06-15 21:48:53.1376;DEBUG;Rubberduck.Parsing.VBA.RubberduckParser;Module 'googleWireExample' was NOT modified;
2016-06-15 21:48:53.1519;DEBUG;Rubberduck.Parsing.VBA.RubberduckParser;Creating declarations for module VBAProject.googleWireExample.;
Exception thrown: 'System.NullReferenceException' in Rubberduck.Parsing.dll
2016-06-15 21:48:53.1519;ERROR;Rubberduck.Parsing.VBA.RubberduckParser;Exception thrown acquiring declarations for 'googleWireExample' (thread 8).;System.NullReferenceException: Object reference not set to an instance of an object.
   at Rubberduck.Parsing.Symbols.DeclarationSymbolsListener.CreateDeclaration(String identifierName, String asTypeName, Accessibility accessibility, DeclarationType declarationType, ParserRuleContext context, Selection selection, Boolean isArray, AsTypeClauseContext asTypeContext, String typeHint, Boolean selfAssigned, Boolean withEvents) in C:\Users\hosch\Documents\Visual Studio 2015\Projects\Rubberduck\Rubberduck.Parsing\Symbols\DeclarationSymbolsListener.cs:line 185
   at Rubberduck.Parsing.Symbols.DeclarationSymbolsListener.EnterArgList(ArgListContext context) in C:\Users\hosch\Documents\Visual Studio 2015\Projects\Rubberduck\Rubberduck.Parsing\Symbols\DeclarationSymbolsListener.cs:line 656
   at Rubberduck.Parsing.Grammar.VBAParser.ArgListContext.EnterRule(IParseTreeListener listener) in C:\Users\hosch\Documents\Visual Studio 2015\Projects\Rubberduck\Rubberduck.Parsing\Grammar\VBAParser.cs:line 5393
   at Antlr4.Runtime.Tree.ParseTreeWalker.EnterRule(IParseTreeListener listener, IRuleNode r)
   at Antlr4.Runtime.Tree.ParseTreeWalker.Walk(IParseTreeListener listener, IParseTree t)
   at Antlr4.Runtime.Tree.ParseTreeWalker.Walk(IParseTreeListener listener, IParseTree t)
   at Antlr4.Runtime.Tree.ParseTreeWalker.Walk(IParseTreeListener listener, IParseTree t)
   at Antlr4.Runtime.Tree.ParseTreeWalker.Walk(IParseTreeListener listener, IParseTree t)
   at Antlr4.Runtime.Tree.ParseTreeWalker.Walk(IParseTreeListener listener, IParseTree t)
   at Antlr4.Runtime.Tree.ParseTreeWalker.Walk(IParseTreeListener listener, IParseTree t)
   at Rubberduck.Parsing.VBA.RubberduckParser.ResolveDeclarations(VBComponent component, IParseTree tree) in C:\Users\hosch\Documents\Visual Studio 2015\Projects\Rubberduck\Rubberduck.Parsing\VBA\RubberduckParser.cs:line 541
2016-06-15 21:48:53.1980;DEBUG;Rubberduck.Parsing.VBA.RubberduckParserState;Module 'googleWireExample' state is changing to 'ResolverError' (thread 8);
2016-06-15 21:48:53.2191;DEBUG;Rubberduck.Parsing.VBA.RubberduckParserState;ParserState evaluates to 'ResolverError' (thread 8);
2016-06-15 21:48:53.2191;DEBUG;Rubberduck.Parsing.VBA.RubberduckParser;Module 'cOauth2' was NOT modified;
2016-06-15 21:48:53.2298;DEBUG;Rubberduck.Parsing.VBA.RubberduckParser;Creating declarations for module VBAProject.cOauth2.;
2016-06-15 21:48:53.2488;DEBUG;Rubberduck.Parsing.VBA.RubberduckParser;Module 'usefulStuff' was NOT modified;
2016-06-15 21:48:53.2488;DEBUG;Rubberduck.Parsing.VBA.RubberduckParser;Creating declarations for module VBAProject.usefulStuff.;
2016-06-15 21:48:53.2816;DEBUG;Rubberduck.Parsing.VBA.RubberduckParser;Module 'usefulEncrypt' was NOT modified;
2016-06-15 21:48:53.2816;DEBUG;Rubberduck.Parsing.VBA.RubberduckParser;Creating declarations for module VBAProject.usefulEncrypt.;
2016-06-15 21:48:53.2966;DEBUG;Rubberduck.Parsing.VBA.RubberduckParser;Module 'cCell' was NOT modified;
2016-06-15 21:48:53.2966;DEBUG;Rubberduck.Parsing.VBA.RubberduckParser;Creating declarations for module VBAProject.cCell.;
2016-06-15 21:48:53.3146;DEBUG;Rubberduck.Parsing.VBA.RubberduckParser;Module 'cDbabResult' was NOT modified;
2016-06-15 21:48:53.3236;DEBUG;Rubberduck.Parsing.VBA.RubberduckParser;Creating declarations for module VBAProject.cDbabResult.;
2016-06-15 21:48:53.3236;DEBUG;Rubberduck.Parsing.VBA.RubberduckParser;Module 'googleSheets' was NOT modified;
2016-06-15 21:48:53.3432;DEBUG;Rubberduck.Parsing.VBA.RubberduckParser;Creating declarations for module VBAProject.googleSheets.;
Exception thrown: 'System.NullReferenceException' in Rubberduck.Parsing.dll
2016-06-15 21:48:53.3572;ERROR;Rubberduck.Parsing.VBA.RubberduckParser;Exception thrown acquiring declarations for 'googleSheets' (thread 8).;System.NullReferenceException: Object reference not set to an instance of an object.
   at Rubberduck.Parsing.Symbols.DeclarationSymbolsListener.CreateDeclaration(String identifierName, String asTypeName, Accessibility accessibility, DeclarationType declarationType, ParserRuleContext context, Selection selection, Boolean isArray, AsTypeClauseContext asTypeContext, String typeHint, Boolean selfAssigned, Boolean withEvents) in C:\Users\hosch\Documents\Visual Studio 2015\Projects\Rubberduck\Rubberduck.Parsing\Symbols\DeclarationSymbolsListener.cs:line 185
   at Rubberduck.Parsing.Symbols.DeclarationSymbolsListener.EnterArgList(ArgListContext context) in C:\Users\hosch\Documents\Visual Studio 2015\Projects\Rubberduck\Rubberduck.Parsing\Symbols\DeclarationSymbolsListener.cs:line 656
   at Rubberduck.Parsing.Grammar.VBAParser.ArgListContext.EnterRule(IParseTreeListener listener) in C:\Users\hosch\Documents\Visual Studio 2015\Projects\Rubberduck\Rubberduck.Parsing\Grammar\VBAParser.cs:line 5393
   at Antlr4.Runtime.Tree.ParseTreeWalker.EnterRule(IParseTreeListener listener, IRuleNode r)
   at Antlr4.Runtime.Tree.ParseTreeWalker.Walk(IParseTreeListener listener, IParseTree t)
   at Antlr4.Runtime.Tree.ParseTreeWalker.Walk(IParseTreeListener listener, IParseTree t)
   at Antlr4.Runtime.Tree.ParseTreeWalker.Walk(IParseTreeListener listener, IParseTree t)
   at Antlr4.Runtime.Tree.ParseTreeWalker.Walk(IParseTreeListener listener, IParseTree t)
   at Antlr4.Runtime.Tree.ParseTreeWalker.Walk(IParseTreeListener listener, IParseTree t)
   at Antlr4.Runtime.Tree.ParseTreeWalker.Walk(IParseTreeListener listener, IParseTree t)
   at Rubberduck.Parsing.VBA.RubberduckParser.ResolveDeclarations(VBComponent component, IParseTree tree) in C:\Users\hosch\Documents\Visual Studio 2015\Projects\Rubberduck\Rubberduck.Parsing\VBA\RubberduckParser.cs:line 541
2016-06-15 21:48:53.3892;DEBUG;Rubberduck.Parsing.VBA.RubberduckParserState;Module 'googleSheets' state is changing to 'ResolverError' (thread 8);
2016-06-15 21:48:53.3892;DEBUG;Rubberduck.Parsing.VBA.RubberduckParserState;ParserState evaluates to 'ResolverError' (thread 8);
2016-06-15 21:48:53.3999;DEBUG;Rubberduck.Parsing.VBA.RubberduckParser;Module 'regXLib' was NOT modified;
2016-06-15 21:48:53.3999;DEBUG;Rubberduck.Parsing.VBA.RubberduckParser;Creating declarations for module VBAProject.regXLib.;
2016-06-15 21:48:53.4175;DEBUG;Rubberduck.Parsing.VBA.RubberduckParser;Module 'usefulcJobject' was NOT modified;
2016-06-15 21:48:53.4175;DEBUG;Rubberduck.Parsing.VBA.RubberduckParser;Creating declarations for module VBAProject.usefulcJobject.;
2016-06-15 21:48:53.4447;DEBUG;Rubberduck.Parsing.VBA.RubberduckParser;Module 'Sheet3' was NOT modified;
2016-06-15 21:48:53.4537;DEBUG;Rubberduck.Parsing.VBA.RubberduckParser;Creating declarations for module VBAProject.Sheet3.;
2016-06-15 21:48:53.4537;DEBUG;Rubberduck.Parsing.VBA.RubberduckParser;Module 'UAMeasure' was NOT modified;
2016-06-15 21:48:53.4657;DEBUG;Rubberduck.Parsing.VBA.RubberduckParser;Creating declarations for module VBAProject.UAMeasure.;
2016-06-15 21:48:53.4657;DEBUG;Rubberduck.Parsing.VBA.RubberduckParser;Module 'usefulSheetStuff' was NOT modified;
2016-06-15 21:48:53.4787;DEBUG;Rubberduck.Parsing.VBA.RubberduckParser;Creating declarations for module VBAProject.usefulSheetStuff.;
2016-06-15 21:48:53.4937;DEBUG;Rubberduck.Parsing.VBA.RubberduckParser;Module 'cRest' was NOT modified;
2016-06-15 21:48:53.4937;DEBUG;Rubberduck.Parsing.VBA.RubberduckParser;Creating declarations for module VBAProject.cRest.;
2016-06-15 21:48:53.5187;DEBUG;Rubberduck.Parsing.VBA.RubberduckParser;Module 'cDataRow' was NOT modified;
2016-06-15 21:48:53.5257;DEBUG;Rubberduck.Parsing.VBA.RubberduckParser;Creating declarations for module VBAProject.cDataRow.;
Exception thrown: 'System.NullReferenceException' in Rubberduck.Parsing.dll
2016-06-15 21:48:53.5257;ERROR;Rubberduck.Parsing.VBA.RubberduckParser;Exception thrown acquiring declarations for 'cDataRow' (thread 8).;System.NullReferenceException: Object reference not set to an instance of an object.
   at Rubberduck.Parsing.Symbols.DeclarationSymbolsListener.CreateDeclaration(String identifierName, String asTypeName, Accessibility accessibility, DeclarationType declarationType, ParserRuleContext context, Selection selection, Boolean isArray, AsTypeClauseContext asTypeContext, String typeHint, Boolean selfAssigned, Boolean withEvents) in C:\Users\hosch\Documents\Visual Studio 2015\Projects\Rubberduck\Rubberduck.Parsing\Symbols\DeclarationSymbolsListener.cs:line 185
   at Rubberduck.Parsing.Symbols.DeclarationSymbolsListener.EnterArgList(ArgListContext context) in C:\Users\hosch\Documents\Visual Studio 2015\Projects\Rubberduck\Rubberduck.Parsing\Symbols\DeclarationSymbolsListener.cs:line 656
   at Rubberduck.Parsing.Grammar.VBAParser.ArgListContext.EnterRule(IParseTreeListener listener) in C:\Users\hosch\Documents\Visual Studio 2015\Projects\Rubberduck\Rubberduck.Parsing\Grammar\VBAParser.cs:line 5393
   at Antlr4.Runtime.Tree.ParseTreeWalker.EnterRule(IParseTreeListener listener, IRuleNode r)
   at Antlr4.Runtime.Tree.ParseTreeWalker.Walk(IParseTreeListener listener, IParseTree t)
   at Antlr4.Runtime.Tree.ParseTreeWalker.Walk(IParseTreeListener listener, IParseTree t)
   at Antlr4.Runtime.Tree.ParseTreeWalker.Walk(IParseTreeListener listener, IParseTree t)
   at Antlr4.Runtime.Tree.ParseTreeWalker.Walk(IParseTreeListener listener, IParseTree t)
   at Antlr4.Runtime.Tree.ParseTreeWalker.Walk(IParseTreeListener listener, IParseTree t)
   at Antlr4.Runtime.Tree.ParseTreeWalker.Walk(IParseTreeListener listener, IParseTree t)
   at Rubberduck.Parsing.VBA.RubberduckParser.ResolveDeclarations(VBComponent component, IParseTree tree) in C:\Users\hosch\Documents\Visual Studio 2015\Projects\Rubberduck\Rubberduck.Parsing\VBA\RubberduckParser.cs:line 541
2016-06-15 21:48:53.5708;DEBUG;Rubberduck.Parsing.VBA.RubberduckParserState;Module 'cDataRow' state is changing to 'ResolverError' (thread 8);
2016-06-15 21:48:53.5798;DEBUG;Rubberduck.Parsing.VBA.RubberduckParserState;ParserState evaluates to 'ResolverError' (thread 8);
2016-06-15 21:48:53.5798;DEBUG;Rubberduck.Parsing.VBA.RubberduckParser;Module 'cDataSets' was NOT modified;
2016-06-15 21:48:53.5948;DEBUG;Rubberduck.Parsing.VBA.RubberduckParser;Creating declarations for module VBAProject.cDataSets.;
2016-06-15 21:48:53.6108;DEBUG;Rubberduck.Parsing.VBA.RubberduckParser;Module 'usefulColorStuff' was NOT modified;
2016-06-15 21:48:53.6198;DEBUG;Rubberduck.Parsing.VBA.RubberduckParser;Creating declarations for module VBAProject.usefulColorStuff.;
2016-06-15 21:48:53.6578;DEBUG;Rubberduck.Parsing.VBA.RubberduckParser;Module 'cregXLib' was NOT modified;
2016-06-15 21:48:53.6658;DEBUG;Rubberduck.Parsing.VBA.RubberduckParser;Creating declarations for module VBAProject.cregXLib.;
2016-06-15 21:48:53.6818;DEBUG;Rubberduck.Parsing.VBA.RubberduckParser;Module 'oauthExamples' was NOT modified;
2016-06-15 21:48:53.6818;DEBUG;Rubberduck.Parsing.VBA.RubberduckParser;Creating declarations for module VBAProject.oauthExamples.;
2016-06-15 21:48:53.7069;DEBUG;Rubberduck.Parsing.VBA.RubberduckParser;Module 'ThisWorkbook' was NOT modified;
2016-06-15 21:48:53.7139;DEBUG;Rubberduck.Parsing.VBA.RubberduckParser;Creating declarations for module VBAProject.ThisWorkbook.;
2016-06-15 21:48:53.7139;DEBUG;Rubberduck.Parsing.VBA.RubberduckParser;Module 'cDbab' was NOT modified;
2016-06-15 21:48:53.7139;DEBUG;Rubberduck.Parsing.VBA.RubberduckParser;Creating declarations for module VBAProject.cDbab.;
2016-06-15 21:48:53.7379;DEBUG;Rubberduck.Parsing.VBA.RubberduckParser;Module 'cJobject' was NOT modified;
2016-06-15 21:48:53.7459;DEBUG;Rubberduck.Parsing.VBA.RubberduckParser;Creating declarations for module VBAProject.cJobject.;
2016-06-15 21:48:53.7799;DEBUG;Rubberduck.Parsing.VBA.RubberduckParser;Module 'cUAMeasure' was NOT modified;
2016-06-15 21:48:53.7799;DEBUG;Rubberduck.Parsing.VBA.RubberduckParser;Creating declarations for module VBAProject.cUAMeasure.;
2016-06-15 21:48:53.7939;DEBUG;Rubberduck.Parsing.VBA.RubberduckParser;Module 'cBrowser' was NOT modified;
2016-06-15 21:48:53.7939;DEBUG;Rubberduck.Parsing.VBA.RubberduckParser;Creating declarations for module VBAProject.cBrowser.;
2016-06-15 21:48:53.8099;DEBUG;Rubberduck.Parsing.VBA.RubberduckParserState;ParserState changed to 'ResolvedDeclarations', raising OnStateChanged;
2016-06-15 21:48:53.8520;DEBUG;Rubberduck.UI.Inspections.InspectionResultsViewModel;InspectionResultsViewModel handles StateChanged...;
Exception thrown: 'System.NotSupportedException' in Rubberduck.dll
Exception thrown: 'System.NotSupportedException' in Rubberduck.dll
2016-06-15 21:48:56.1705;DEBUG;Rubberduck.UI.Command.MenuItems.RubberduckCommandBar;RubberduckCommandBar handles StateChanged...;
2016-06-15 21:48:56.2215;DEBUG;Rubberduck.App;App handles StateChanged (ResolvedDeclarations), evaluating menu states...;
2016-06-15 21:48:57.1772;TRACE;Rubberduck.Parsing.Symbols.ProjectReferencePass;Built-in project references linked up in 5ms.;
'EXCEL.EXE' (CLR v4.0.30319: DefaultDomain): Loaded 'C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\Microsoft.CSharp\v4.0_4.0.0.0__b03f5f7f11d50a3a\Microsoft.CSharp.dll'. Symbols loaded.
'EXCEL.EXE' (CLR v4.0.30319: DefaultDomain): Loaded 'C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Dynamic\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Dynamic.dll'. Symbols loaded.
2016-06-15 21:48:57.5344;DEBUG;Rubberduck.Parsing.Symbols.TypeHierarchyPass;Type hierarchies built in 286ms.;
2016-06-15 21:48:57.6555;WARN;Rubberduck.Parsing.Symbols.TypeAnnotationPass;Failed to resolve type cDataSet;
2016-06-15 21:48:57.6555;WARN;Rubberduck.Parsing.Symbols.TypeAnnotationPass;Failed to resolve type erRestType;
2016-06-15 21:48:57.6675;WARN;Rubberduck.Parsing.Symbols.TypeAnnotationPass;Failed to resolve type cDataSet;
2016-06-15 21:48:57.6675;WARN;Rubberduck.Parsing.Symbols.TypeAnnotationPass;Failed to resolve type cDataSet;
2016-06-15 21:48:57.6675;WARN;Rubberduck.Parsing.Symbols.TypeAnnotationPass;Failed to resolve type erRestType;
Exception thrown: 'Microsoft.CSharp.RuntimeBinder.RuntimeBinderException' in Microsoft.CSharp.dll
Exception thrown: 'Microsoft.CSharp.RuntimeBinder.RuntimeBinderException' in System.Core.dll`
```

**Comment by Hosch250** [comment] 2016-06-15 23:33
Could you provide the code for this project so I could find the source of the NRE?  It looks like something in `cDataRow` is consistently crashing the declarations resolver.

**Comment by PeterMTaylor** [comment] 2016-06-16 11:44
Sure, here it is @Hosch250 the actual file I used to test it. 
It's my modified version of Bruce McPherson's VBA framework.

[emptycdataset.zip](https://github.com/rubberduck-vba/Rubberduck/files/318280/emptycdataset.zip)

I would suggest to you to keep this file handy at hand to re-test a few times.

**Comment by Hosch250** [comment] 2016-06-16 16:29
No repro here.

**Comment by PeterMTaylor** [comment] 2016-06-18 04:44
With the new version of 2.0.2b. No Resolver error occured.
I accidently had Book1 open with no project in the system. It kept Pending more than 5 mins.
![capture pending with no projects](https://cloud.githubusercontent.com/assets/2254567/16169054/ff239e14-3562-11e6-93ca-47b90b42dc6c.PNG)

**Comment by Hosch250** [comment] 2016-06-20 21:30
Since the issue is no longer happening, I'm closing this as probably fixed.  It does say Pending by design when no projects are in the system, but I can change that.

**Closed by Hosch250** 2016-06-20 21:30 UTC
Labels: bug, code-parsing
