### ISSUE TITLE
If RD is disabled then enabled (via Addin Manager) Word will Crash

### ISSUE THREAD

**Issue by Stevefb** [rubberduck-vba/Rubberduck#1883] opened 2016-06-21 08:30 UTC
So far this has happened 3/3 times...

**Comment by retailcoder** [comment] 2016-06-21 14:01
This is a known issue; I think fixing teardown / shutdown issues will also fix hot-unloading/reloading the add-in.

**Comment by lkavicky** [comment] 2016-07-15 10:38
I have the same issue in Access.

**Comment by retailcoder** [comment] 2017-01-05 15:27
Ah, I forgot to include that in the "known issues" of 2.0.10 - the add-in is much more stable now, and normal shutdown appears to no longer consistently crash the host. However re-loading after unloading from the addins manager is still going to wreck the IDE and its host.

**Comment by retailcoder** [comment] 2017-01-13 05:11
duplicate of #1876

**Closed by retailcoder** 2017-01-13 05:11 UTC
Labels: bug, duplicate
