### ISSUE TITLE
comment seen as code

### ISSUE THREAD

**Issue by SystemsModelling** [rubberduck-vba/Rubberduck#3500] opened 2017-10-21 17:46 UTC
Error: Local variable 'testbatch' is not declared - (XLTest163a.xlsm) XLTest.Informations, line 227
```
Sub testAudit() '@notrace  testautotest testbatch
```

**Comment by Vogel612** [comment] 2017-10-21 20:22
Might be a bug in the grammar (I doubt it) or a bug in the inspection. I think the latter's more likely

**Comment by tommy9** [comment] 2017-12-29 19:52
This does look like a bug in the grammar. Stepping through the example code shows the part recognised as an annotation is just `'@notrace  testautotest`.
The `testbatch` part is considered to be a block statement inside the Sub. Here is a tree view from Antlr showing the problem (slightly cut down grammar to get it to compile on my computer but the key features are still there).
![antlr4_parse_tree](https://user-images.githubusercontent.com/4892984/34446128-97d5724c-ecd0-11e7-989d-f76a5708e2c8.png)

I think the problem is that the grammar is quite strict about what an annotation looks like and the test example doesn't fit, so the leftover part falls through. Not sure what the best solution is. Maybe remove the COLON separator from within the rule annotationList before a commentBody but I haven't been able to test yet.

**Comment by Vogel612** [comment] 2017-12-29 19:56
I see the problem ... 
AnnotationName is an `unrestrictedIdentifier`. These are used to match variable usages to their declarations. It seems that the inspection for "variable is not declared" doesn't exclude identifiers that are `annotationName`s, which results in this bug

**Comment by retailcoder** [comment] 2017-12-29 20:51
@Vogel612 it's not the inspection, it's the resolver walking the tree to locate variables and issue a `Declaration`. We're currently treating any unknown identifier as an undeclared variable, *and creating an on-the-spot declaration for that undeclared variable* - the inspection is just doing its job. It's the resolver that needs to smarten up and take annotations into account.

**Comment by Vogel612** [comment] 2018-03-01 12:16
This has been fixed as of #3791

**Closed by Vogel612** 2018-03-01 12:16 UTC
Labels: antlr, bug, difficulty-02-ducky, feature-inspections, parse-tree-processing, up-for-grabs
