### ISSUE TITLE
Code Explorer has no option to refresh a single module

### ISSUE THREAD

**Issue by AndrewM-** [rubberduck-vba/Rubberduck#840] opened 2015-10-20 00:43 UTC
I have just written a bunch of new subs in a form module and want to be able to see them in Code Explorer.  Right-clicking on the form module in Code Explorer and choosing refresh parses the whole project again which takes a few minutes.  Could the refresh launched from a context menu be a quick refresh of the current module only?  I guess that a single module refresh would not pick changes to references in other modules but often I only need to see procedure names for navigation purposes.  Consider a quick refresh option that does not hunt through all modules for references.

**Comment by retailcoder** [comment] 2015-10-20 01:41
Excellent timing, the Code Explorer is just about to be reimplemented in WPF/XAML! :smiley:  

The Rubberduck 1.4.3 parser is indeed not returning anything until all references are resolved. There's caching involved, and only the modules with a different content hash code will be re-processed with the ANTLR-generated parser... but unless *nothing* changed since the last parse, there's no way of knowing if the new code needs to add (or remove) references to declarations made in other modules, so all parse trees (cached or not) need to be resolved again - the painful part is unquestionably identifier resolution.

Say we have an Excel project with 3 spreadsheets, `ThisWorkbook` and a standard module; the 3 spreadsheets are empty, and `ThisWorkbook` has some event handlers calling into procedures defined in the standard module. When Rubberduck is instructed to parse, we pass the `VBProject` object to the parser, which finds the 5 `VBComponent` objects and gets a string for each corresponding code module; these strings are passed to the ANTLR parser, which spits out an `IParseTree` for each one.

Then we *walk* each parse tree once, using a `DeclarationSymbolListener`, which gives us a bunch of `Declaration` objects for each module - we add these declarations to a `VBProjectParseResult` object, and before we return that, we add a bunch of `Declaration` objects for the built-in declarations from the VBA standard library (2.0 will also add some declarations for the Excel object model, and if ADODB is referenced, some more declarations for that object model too).

Once we know about all the `Declaration` objects (both built-in and found in the `VBProject` we're parsing), we walk every single parse tree once more, this time using an `IdentifierReferenceListener`, which uses the `IdentifierReferenceResolver` to determine, when the *walker* finds a variable, member, or enum (or whatever) reference, depending on the current scope (procedure/module/class), whether we're in an assignment context, whether the identifier is the target of that assignment, or whether we're in a 3-layer nested `With` block, exactly which single `Declaration` the identifier is referring to.

The 1.4.x parser runs all that sequentially, and only returns the `VBProjectResult` after everything has completed. The larger the project, the longer it takes - lil' ducky is working pretty hard here, but that hard work is the only way to determine, for example, out of a random selection in the code pane, what variables are being used before, after, or inside the selection, which ones are *only* used inside that selection, and so which ones can become parameters and which one(s) need to be returned to the caller of an extracted method. It's also how an inspection can relatively quickly find all variables that are never assigned, or never referenced. Or how we can rename a parameter and correctly rename it at the call site when it's named (like `bar` in `GetFoo(bar:=42)`), and everywhere it's referenced in the procedure's body - without that painful step, Rubberduck couldn't do much.

In an ideal world, we would be maintaining the parse results and identifier references *as you're typing*, in a background thread. The problem is that the VBE API doesn't give us such a hook, so the parser was designed to give us everything at once, cache the results, and reuse them as much as possible - so when the Code Explorer or anything else asks for a parse result, the results are readily available for every other functionality that needs them.

The 2.0 parser has been slightly modified, and identifier resolution is running concurrently - because it's not true that I need a module resolved to start resolving the next. This introduces some new difficulties (read: bugs), but it's worth a shot.

If you're wondering where I'm going with this, don't worry - I'm <s>thinking out loud</s> *rubberducking* here.

This issue/request is sparking something.

I need to review/redesign the `IRubberduckParser` interface, the `RubberduckParser` implementation, the `VBProjectResult` and `VBComponentResult` classes have too many responsibilities - currently it's `VBProjectResult` that's responsible for adding in the built-in declarations and launching identifier resolution, and it's plain wrong.

I need to think a bit, but I'll come up with something. You're completely right: the Code Explorer couldn't care less about whether or not the declarations it's displaying are resolved or not. It could very well be working off declarations *still being resolved* for all it cares. The parser needs a better way to tell its clients what the parse status of each component is.

Consider this on the roadmap. For 2.0.

**Comment by AndrewM-** [comment] 2015-10-20 05:48
just a potential dirty hack, if the code in each code module was checksummed using an md5 or sha1 checksum, then you could easily tell which code modules had been edited and could parse just these modules.  This is how git works so we know this approach works.  The checksums could be persisted in a collection in memory for the duration of the session?

**Comment by retailcoder** [comment] 2015-10-20 05:57
I'm doing quite exactly that, except only with the `.GetHashCode()` method of the string that contains the module's code. Doing that with a proper hashing algorithm might actually reduce the risk of hash collision, although I'm fairly certain it would take quite a bit of bad luck to parse a module, and then change something and get the same hash code for the new module string.

**Closed** 2016-05-12 18:52 UTC
Labels: code-explorer, code-parsing, enhancement, feature-request
