### ISSUE TITLE
Parser error

### ISSUE THREAD

**Issue by wegidio** [rubberduck-vba/Rubberduck#5399] opened 2020-02-24 12:03 UTC
**Rubberduck version information**
The info below can be copy-paste-completed from the first lines of Rubberduck's log or the About box:
    Rubberduck version  2.5.0.5338
    Operating System: Microsoft Windows NT 10.0.18363.0, x64
    Host Product: Microsoft Office x86
    Host Version: 16.0.12430.20288
    Host Executable: EXCEL.EXE

**Description**
When I open my VBA code it is load on VBA Project as expected but the Code Explorer and other windows from Rubberduck do not load nothing. Then, I click Parse botton and it, after try to load code/others, show message (inside it) "PARSE ERROR". How can I solve this? I really would like to use Rubberduck. It working well when I open it with empty project (VBA MS-Excel).

**To Reproduce**
Only to load it

**Expected behavior**
It load and parse

**Screenshots**
No necessary

**Logfile**
Rubberduck generates extensive logging in TRACE-Level. If no log was created at `%APPDATA%\Rubberduck\Logs`, check your settings. Include this log for bug reports about the behavior of Rubberduck.

**Additional context**
No information

**Comment by daFreeMan** [comment] 2020-02-24 12:47
We'd really love for you to be able to use Rubberduck, too! Having a copy of Rubberduck's log file would be extremely helpful in helping us identify the issue - it could be a compile error in your code, or there could be an issue with the duck.

To that end, please look at the **Logfile** section of your original post to see the instructions on how to upload the log - i.e., ensure that logging is on and that it's set to TRACE. Recreate the problem, then _edit_ your original post to include the log file. (You can simply drag/drop the file into the editor window.)

**Comment by retailcoder** [comment] 2020-02-24 12:51
At this point assuming you're using the latest version I would be very surprised if you ran into any actual parser bugs (though not impossible) - much more likely is RD working exactly as intended and telling you about a syntax-level problem in your code.

Hard to tell without any info about the error: this issue will be closed as unreproducible if the OP isn't edited to include the critical details about the error.

**Comment by retailcoder** [comment] 2020-02-24 12:54
If you click the error icon, it should open a panel that lists the parser errors encountered. Double-click one to navigate there - including that code here would help us help you.

**Comment by MDoerner** [comment] 2020-02-25 13:38
In the attached log, I cannot find any indication of a failed parse. However, there is a problem with one inspection. More precisely, there is a problem with the following line of code.
https://github.com/rubberduck-vba/Rubberduck/blob/d2d3f1fbbb811af10a3efb669490ae7971f8ddec/Rubberduck.CodeAnalysis/Inspections/Concrete/OptionExplicitInspection.cs#L93

The inspection listener uses a dictionary indexed by the name of qualified module names to store the results. That fill throw whenever there are two projects with the same name that contain two modules with with the same name both not specifying `Option Explicit`.

**Comment by retailcoder** [comment] 2020-02-27 05:08
Without any information about the error you're reporting, we have nothing to go on.

Make sure your code compiles (Alt+D, Enter); Rubberduck generally cannot parse VBA code that does not compile. If the project *does* compile without any errors, and Rubberduck still cannot parse it, then we need to be able to reproduce the problem if we ever hope to be able to fix it. 

If you reproduce the parse error with logging enabled, then the logs will contain the details about the exception that was thrown, which token at which column on which line in which module caused the parser to fail - note that Rubberduck does not log any of the surrounding user code, so if all we have is the logs, we likely still could not reproduce the problem without seeing the VBA code that failed to parse.

If it's a legitimate parser error, look for VBA code that isn't quite standard-looking (Rubberduck's parser handles everything we could think to throw at it): are there line continuations? Multiple colon-separated instructions on the same line?

I'll close this issue as unactionable for now. Feel free to provide more information if you need assistance, we're always happy to help!

**Closed by retailcoder** 2020-02-27 05:08 UTC
Labels: support
