### ISSUE TITLE
After deleting a remote repository, Application will not run, stuck "Resolving Declarations"

### ISSUE THREAD

**Issue by bravesparrow** [rubberduck-vba/Rubberduck#2489] opened 2017-01-06 03:14 UTC
Problem persists even after full re-install of Rubberduck.
"Resolving Declarations" is on an infinite loop.
Perhaps there is a way to fix it from the registry?
Keen to find a solution as I am not able to use the application in its current state.

More detail:
-I deleted a repo from Github
-This repo was syncing with Rubberduck prior to deleting it; there was an unsynced branch at time of the deletion
-next time I opened the VBE the "Pending" label was showing, and all Rubberduck menu items were disabled.
-clicking the Sync icon results in this problem.
-I uninstalled and deleted the C:\programfiles\Rubberduck folder and the C:\users\appdata\roaming\rubberduck folders prior to reinstalling.

Thanks for your help with this one--hoping I can be of some help with the project, if only by findig silly ways to break it.

cheers, David.

**Comment by retailcoder** [comment] 2017-01-06 03:33
Hi! Sorry to hear that, let's try to fix it! Did you have logging enabled? Off the current/next build or the latest release (2.0.10)? Can you reproduce the issue with a small example?

**Comment by bravesparrow** [comment] 2017-01-06 03:37
Thanks so much for all you are doing.

More detail:
-I deleted a repo from Github
-This repo was syncing with Rubberduck prior to deleting it; there was an unsynced branch at time of the deletion
-next time I opened the VBE the "Pending" label was showing, and all Rubberduck menu items were disabled.
-clicking the Sync icon results in this problem.
-I uninstalled and deleted the C:\programfiles\Rubberduck folder and the C:\users\appdata\roaming\rubberduck folders prior to reinstalling.

Thanks for your help with this one--hoping I can be of some help with the project, if only by findig silly ways to break it.

cheers, David.

ps. It is the latest release (2.0.10) i did have logging enabled and I stupidly deleted the original log, but here is the single log entry from after the re-install: 2017-01-06 14:05:11.2513;INFO-2.0.10.36196;Rubberduck.App;Rubberduck version 2.0.10.36196 loading:
	Operating System: Microsoft Windows NT 10.0.14393.0 x64
	Host Product: Microsoft Office 2013 x64
	Host Version: 15.0.4885.1000
	Host Executable: WINWORD.EXE;

**Comment by retailcoder** [comment] 2017-01-06 03:49
👍 

Rubberduck stores the source control configuration file under `%appdata%\Rubberduck\SourceControl.rubberduck`, which is nothing more than an XML file with some serialized settings:

````xml
<?xml version="1.0" encoding="utf-8"?>
<Configuration>
  <SourceControlSettings>
    <UserName />
    <EmailAddress />
    <DefaultRepositoryLocation />
    <Repositories>
      <Repository>
        <LocalLocation>C:\Dev\VBA\RubberduckSC\MyProject\MyProject</LocalLocation>
        <RemoteLocation />
      </Repository>
    </Repositories>
    <CommandPromptLocation>cmd.exe</CommandPromptLocation>
  </SourceControlSettings>
</Configuration>
````

You should see your repository somewhere inside a `<Repository>` tag, possibly with a remote location; delete the poison tag and its contents, i.e. remote the `<Repository>` node for the broken repo. If that's your only repository, alternatively you can just outright delete the file, Rubberduck will just create a fresh new clean file.

**Comment by bclothier** [comment] 2018-07-17 03:32
Closing this because source code control integration is now deprecated.

**Closed by bclothier** 2018-07-17 03:32 UTC
Labels: feature-export, support
