### ISSUE TITLE
Renaming value set to object property also renames property itself

### ISSUE THREAD

**Issue by kpstolk** [rubberduck-vba/Rubberduck#962] opened 2016-01-22 21:35 UTC
I think I might have found a bug with renaming an argument. I'm not sure if this variant if known already.
I send mail [using CDO](http://www.rondebruin.nl/win/s1/cdo.htm) with this Sub:

    Public Sub Send(subjectArg As String, body As String, toAddress As String, bccAddress As String, attachmentLocation As String)
        
        Dim iMsg As Object
        Dim iConf As Object
        Dim Flds As Variant
    
        Set iMsg = CreateObject("CDO.Message")
        Set iConf = CreateObject("CDO.Configuration")
    
        iConf.Load -1    ' CDO Source Defaults
        Set Flds = iConf.Fields
        With Flds
            .Item("http://schemas.microsoft.com/cdo/configuration/smtpusessl") = True
            .Item("http://schemas.microsoft.com/cdo/configuration/smtpauthenticate") = 1
            .Item("http://schemas.microsoft.com/cdo/configuration/sendusername") = "me@gmail.com"
            .Item("http://schemas.microsoft.com/cdo/configuration/sendpassword") = "pwd"
            .Item("http://schemas.microsoft.com/cdo/configuration/smtpserver") = "smtp.gmail.com"
            .Item("http://schemas.microsoft.com/cdo/configuration/sendusing") = 2
            .Item("http://schemas.microsoft.com/cdo/configuration/smtpserverport") = 25
            .Update
        End With
    
        With iMsg
            Set .Configuration = iConf
            .To = toAddress
            .CC = ""
            .BCC = bccAddress
            ' Note: The reply address is not working if you use this Gmail example
            ' It will use your Gmail address automatic. But you can add this line
            ' to change the reply address  .ReplyTo = "Reply@something.nl"
            .From = """My Name"" <me@gmail.com>"
            .subjectArg = subjectArg ` <- the property itself also gets renamed
            .TextBody = body
            .AddAttachment attachmentLocation
            .Send
        End With
    
    End Sub

I tried to rename `subject As String` to `subjectArg As String` using Refactor -> Rename, but this also renames the 'subject' property of the `iConf` object:

![2016-01-22 22_31_50-clipboard](https://cloud.githubusercontent.com/assets/538170/12523610/337e0e44-c158-11e5-92ee-71846f0acb89.png)

Because the variable is unfortunately declared as `Object` the project still compiles..

**Comment by Hosch250** [comment] 2016-01-22 21:40
Thank you for bringing this to our attention.  This is not an issue with the refactoring itself, but an issue with the resolver.  There are other issues with the resolver being worked on, this will be addressed as well.

**Comment by retailcoder** [comment] 2016-01-22 21:50
Nice resolver bug!

The `.subject` member of `iMsg` should have been resolved as a member call on the unknown-type `iMsg` object, and left alone, indeed.

I'm treating this as a critical bug, no way I'm releasing 2.0 with it!

**Comment by retailcoder** [comment] 2016-01-22 21:54
Bug can be reproduced with this simple test code:

    Sub Test(ByVal foo As String)
        With New bar
            .foo = foo
        End With
    End Sub

Right-click on the `foo` parameter, "find all references": `.foo` shows up in the list, and shouldn't.

**Comment by kpstolk** [comment] 2016-01-22 22:07
Nice that this one will be in the 2.0 release!
Without the source control integration I wouldn't have found this issue so quickly ;)

I also just found that right clicking on the Sub `Send` itself, 'find all references' also shows `.Send`.
Expanding on @retailcoder sample, 'find all references' on `Test`:

    Sub Test(ByVal foo As String)
        With New bar
            .foo = foo
			.Test `<- This one is not the same
        End With
    End Sub

Is that the same issue as with `.foo`?

**Comment by retailcoder** [comment] 2016-01-22 22:17
@kpstolk  absolutely. Resolver knows it's in a `With` block, but because it can't find a `Declaration` for the type of `bar`, instead of giving up and leaving it alone it keeps searching for a matching in-scope identifier, finds the `Test` procedure (or the `foo` parameter) and calls it a day, and goes ahead and creates an `IdentifierReference` for that `Declaration` object it found. Shouldn't be too hard to fix.

**Comment by retailcoder** [comment] 2016-01-25 02:40
aaaaand... fixed!

    Sub Test(ByVal renamed As String)
        With New bar
            .foo = renamed
        End With
    End Sub

**Comment by kpstolk** [comment] 2016-01-25 14:03
That's nice! Can this issue be closed?

**Comment by retailcoder** [comment] 2016-01-25 14:24
It will close itself when I merge my  changes :-)

**Closed by retailcoder** 2016-01-25 14:24 UTC
Labels: bug, code-parsing, critical
