### ISSUE TITLE
Crash every time after inspection fix

### ISSUE THREAD

**Issue by SonGokussj4** [rubberduck-vba/Rubberduck#4897] opened 2019-04-04 19:16 UTC
**Rubberduck version information**
The info below can be copy-paste-completed from the first lines of Rubberduck's log or the About box:

```
Verze 2.4.1.33370
OS: Microsoft Windows NT 10.0.17763.0, x64
Hostitelský produkt: Microsoft Office x86
Hostitelská Verze: 16.0.11425.20202
Hostitelský spouštěč: EXCEL.EXE
```

**Description**
After I click on any Inspection fix, it will "fix it", but after the RD and inspection is reloaded, it crashes excel.

**To Reproduce**
1. Open Excel, Init RD, Open Inspection
2. Click on any inspection and select "Fix"
3. Wait
4. After RD is reloaded and Inspections are reloaded, Excel freezes and crashes without any error window. Just turns off and restarts.

**Expected behavior**
To not excel crash after fixing inspection :-)

**Logfile**
Appended
[RD_Trace_Output_Log.txt](https://github.com/rubberduck-vba/Rubberduck/files/3045107/RD_Trace_Output_Log.txt)

**Additional context**
Thinking it has something to do with the inspection:

> Variable 'References' is used but not assigned. 

When I click to fix this type of inspection, nothing happens. Trace log shows ERROR but excel does not crashes. Just "nothing happens".

**Comment by retailcoder** [comment] 2019-04-04 19:26
No repro here...

Version 2.4.1.4647
OS: Microsoft Windows NT 6.1.7601 Service Pack 1, x64
Host Product: Microsoft Office x64
Host Version: 16.0.11328.20222
Host Executable: EXCEL.EXE

**Comment by SonGokussj4** [comment] 2019-04-04 21:32
So it happens only if Czech or German language is selected. No problem if (RD) English is selected. Didn't try other languages. But I think there will be the same problem.

**Comment by MDoerner** [comment] 2019-04-04 21:35
I can repro this in German in a slightly different way.

inspect -> expand groups -> inspect -> fold one group -> inspect -> Excel crashes

**Comment by MDoerner** [comment] 2019-04-04 21:48
These repro steps work for all languages but English. 

One obersvation: for all languages but English, at least one group nema in the inspections result window contains a character outside the first 127 ASCII characters, more precisely, one with an accent.

**Comment by MDoerner** [comment] 2019-04-27 13:06
I can no longer reproduce since PR #4896 
However, the fix there was only a symptomatic fix. S, the underlying problem is probably still there.

**Comment by bclothier** [comment] 2019-11-03 23:47
Closing this as no-repro.  If there's a reproduction, feel free to reopen.

**Closed by bclothier** 2019-11-03 23:47 UTC
Labels: bug, hacktoberfest, status-norepro
