### ISSUE TITLE
Rename refactoring allows renamings that will rewrite dirty modules

### ISSUE THREAD

**Issue by comintern** [rubberduck-vba/Rubberduck#4592] opened 2018-12-01 19:59 UTC
Given a project with a class module `Class1` and the following code in a standard module...
```
Public Sub Foo()
    Dim bar As Class1
    Set bar = New Class1
End Sub
```
...running the rename refactoring results in this if you rename `Class1` to `FooBar`:
```
Public Sub Foo()
    Dim bar As FooBar
    Set bar = New FooBar
End Sub
```
If you edit the sub and change the types to, say `Collection`...
```
Public Sub Foo()
    Dim bar As Collection
    Set bar = New Collection
End Sub
```
... and the ***don't reparse*** and then rename `FooBar` again to, say, `Baz`, it rewrites over your changed and now dirty code:
```
Public Sub Foo()
    Dim bar As Baz
    Set bar = New Baz
End Sub
```
Note that this is just a trivial case - if there have been more extensive changes in a module that gets re-written since the last reparse, renaming could result in significant code mangling or loss of work. Given this behavior, the rename refactoring should do one of the following:

1. Reparse both before and after the rename. This would probably be the easiest way to avoid mangling code, but it unconditionally requires 2 parses instead of the single reparse we're doing now.
2. Check to make sure that none of the modules that would be re-written are dirty, and then prompt the user that they may be borking their code before proceeding - optionally proceeding with option 1 if the user wants to allow it.
3. Add code in all of the applicable `EvaluateCanExecute` methods to check whether or not there are identifier references to the selected identifier in dirty modules. This would side-step the requirement for the refactoring to parse twice, but would not be immediately obvious to the user why the refactoring was disallowed. It might also be an unacceptable performance hit in huge projects.
4. Something else entirely.

**Comment by comintern** [comment] 2018-12-01 20:01
Almost forgot - this might? be the root cause of #4588.

**Comment by MDoerner** [comment] 2018-12-02 16:34
Just to make this clear, it should be impossible to mangle the code this way. However, __every__ rewrite, both from refactorings and quickfixes, will disregart any changes made since the last parse. They all use the rewriters, which are based on the token streams underlying the parse trees. Thus, this problem is not exclusive to the rename refactoring.

I do not think that we can put a dirty check into the `EvaluateCanExecute` methods. This check includes getting the content hash from all affected components.

**Comment by bclothier** [comment] 2019-02-09 06:48
I cannot reproduce this anymore. This seems to have been fixed with Max's rewriter PR.

**Closed by bclothier** 2019-02-09 06:48 UTC
Labels: bug, feature-refactorings, refactoring-rename

**Comment by MDoerner** [comment] 2019-02-09 09:31
More precisely, PR #4693
