### ISSUE TITLE
Applying 'Implicitly Variant' fix causes error

### ISSUE THREAD

**Issue by kpstolk** [rubberduck-vba/Rubberduck#2327] opened 2016-10-25 19:44 UTC
I tried to apply a Constant 'x' is implicitly Variant warning, but got an error and the change was not made.
Before that I applied another fix so maybe that is relevant?

[RubberduckLog.txt](https://github.com/rubberduck-vba/Rubberduck/files/551627/RubberduckLog.txt)

Rubberduck version 2.0.9.0 with Excel 2016.

**Comment by Vogel612** [comment] 2016-10-26 10:03
Stacktrace: 

```
2016-10-25 21:26:40.4957;ERROR;Rubberduck.UI.Inspections.InspectionResultsViewModel;System.ArgumentOutOfRangeException: Index and count must refer to a location within the string.
Parameter name: count
   at System.String.Remove(Int32 startIndex, Int32 count)
   at Rubberduck.Inspections.DeclareAsExplicitVariantQuickFix.Fix() in c:\Users\Mathieu\Documents\GitHub\Rubberduck\RetailCoder.VBE\Inspections\DeclareAsExplicitVariantQuickFix.cs:line 44
   at Rubberduck.UI.Inspections.InspectionResultsViewModel.ExecuteQuickFixes(IEnumerable`1 quickFixes) in c:\Users\Mathieu\Documents\GitHub\Rubberduck\RetailCoder.VBE\UI\Inspections\InspectionResultsViewModel.cs:line 321
   at Rubberduck.UI.Inspections.InspectionResultsViewModel.ExecuteQuickFixCommand(Object parameter) in c:\Users\Mathieu\Documents\GitHub\Rubberduck\RetailCoder.VBE\UI\Inspections\InspectionResultsViewModel.cs:line 346
   at Rubberduck.UI.Command.DelegateCommand.ExecuteImpl(Object parameter) in c:\Users\Mathieu\Documents\GitHub\Rubberduck\RetailCoder.VBE\UI\Command\DelegateCommand.cs:line 26
   at Rubberduck.UI.Command.CommandBase.Execute(Object parameter) in c:\Users\Mathieu\Documents\GitHub\Rubberduck\RetailCoder.VBE\UI\Command\CommandBase.cs:line 60;
```

@kpstolk I assume this is the full log-file?  
Do you by any chance remember which quickfix you applied before?

**Comment by kpstolk** [comment] 2016-10-26 21:21
Yes, that's all, except when I move from Error to Warning I get a lot of `Failed to resolve` warnings but I guess that's normal?

I tried to resolve some vbNullString fixes, no issue.
When I try to apply a 'Implicitly Variant' fix it shows the error window.
Afterwards I can apply another vbNullString fix, but when I try an 'Implicitly Variant' fix again, nothing happens (no error window and no fix applied).

Hope this helps.

**Comment by Vogel612** [comment] 2016-10-26 22:01
So I cannot reproduce this from the latest latest code (the current tip of development).
Could you maybe share the code this happens on?

Note that I explicitly added some "" literals to run a vbNullString fix before trying the implicitly variant fix, too ...
This might already be fixed in "next release".

**Comment by kpstolk** [comment] 2016-10-27 15:13
Now I also see that it happens when I first open the Excel document and only try to apply an implicitly Variant fix.
I've a module with content like this:

```
Option Explicit

Private Const ColOneIndex = 1
Private Const ColTwoIndex = 2
Private Const ColThreeIndex = 3
' Other Consts and functions omitted
```

But if you are testing the latest version instead of  2.0.9.0 maybe it's already fixed?

**Comment by retailcoder** [comment] 2016-10-27 18:36
I have a repro - not with the error, but with the no-op nature of the `DeclareAsExplicitVariantQuickFix` applied to a `DeclarationType.Constant`.

My guess is that we're passing the wrong `ParserRuleContext` type (the quick-fix is expecting the context to be a `ConstSubStmtContext`), which makes the method return early (instead of crashing):

    fix = DeclareExplicitVariant(Context as VBAParser.ConstSubStmtContext, out originalInstruction);

The soft-cast would be sending a `null` context here:

        private string DeclareExplicitVariant(VBAParser.ConstSubStmtContext context, out string instruction)
        {
            if (context == null)
            {
                instruction = null;
                return null;
            }

            var parent = (VBAParser.ConstStmtContext)context.Parent;
            instruction = parent.GetText();

            var constant = context.GetText();
            var replacement = context.identifier().GetText() + ' '
                              + Tokens.As + ' ' + Tokens.Variant + ' '
                              + context.EQ().GetText() + ' '
                              + context.expression().GetText();

            var result = instruction.Replace(constant, replacement);
            return result;
        }
    }

**Comment by kpstolk** [comment] 2016-10-28 15:09
First time I get the error, second time nothing happens.
When there's a new release with this fix I could test again.

**Closed** 2016-10-29 14:25 UTC
Labels: bug, code-inspections

**Comment by retailcoder** [comment] 2016-10-29 16:50
Works great now, check out that commit... that quickfix was thoroughly broken! Works great now, next release should be good.
