### ISSUE TITLE
Extract Interface

### ISSUE THREAD

**Issue by retailcoder** [rubberduck-vba/Rubberduck#178] opened 2015-02-10 16:09 UTC
As a VBA programmer, I want to be able to extract public members of a class into an interface.

This feature will look at the active class module, find all public procedures (including `Sub`, `Function` and `Property` signatures), bring up a dialog that will let the user pick members to extract (and rename them, and to specify whether the member should remain `Public` or become `Private` or `Friend`), and then create a new class module with signatures (empty bodies) for the selected members.

Then the class module should get an `Implements [name-of-interface]` statement, and method stubs for the interface members should be added automatically.

The dialog should also let user decide how the interface is to be implemented:

 - Call extracted members (default?)
 - Method stubs that call `Err.Raise 5, "[class name]", "Method is not implemented."`
 - Empty method stubs

**Comment by ckuhn203** [comment] 2015-02-10 16:14
Duplicate of #119.

**Comment by Hosch250** [comment] 2015-12-22 20:05
* Display list of all members in the class
* Have an All Public button (R# has Dependent too, not sure what that does. Is it the public methods that are referenced, leaving out the ones that could be private?)
* Allow picking new name.  Default is `I` + current class name.

**Comment by retailcoder** [comment] 2015-12-22 20:28
Something like this:

![image](https://cloud.githubusercontent.com/assets/5751684/11965084/3829f76a-a8c0-11e5-99df-91658a17b0de.png)

 - Display only public members (we could change that in later releases if there's demand for it)
 - Definitely allow renaming, and yes, default to `ICurrentClassName`
 - Keep in mind that `Event`s cannot be on interfaces in VBA

**Closed** 2015-12-24 17:05 UTC
Labels: refactorings, user-interface
