### ISSUE TITLE
InvalidOperationException in resolver

### ISSUE THREAD

**Issue by Pitterling** [rubberduck-vba/Rubberduck#1145] opened 2016-02-24 17:18 UTC
Hi, during parsing i'm facing several exception throws. They always look like this:

> Exception thrown: 'System.InvalidOperationException' in System.Core.dll
Exception thrown resolving 'vbFnPivotItemPri': System.InvalidOperationException: Sequence contains more than one matching element
   at System.Linq.Enumerable.SingleOrDefault[TSource](IEnumerable`1 source, Func`2 predicate)
   at Rubberduck.Parsing.Symbols.IdentifierReferenceResolver.Resolve(ICS_B_MemberProcedureCallContext context) in C:\Code\Tools\Rubberduck\Rubberduck.Parsing\Symbols\IdentifierReferenceResolver.cs:line 730
   at Rubberduck.Parsing.Symbols.IdentifierReferenceListener.EnterICS_B_MemberProcedureCall(ICS_B_MemberProcedureCallContext context) in C:\Code\Tools\Rubberduck\Rubberduck.Parsing\Symbols\IdentifierReferenceListener.cs:line 155
   at Rubberduck.Parsing.Grammar.VBAParser.ICS_B_MemberProcedureCallContext.EnterRule(IParseTreeListener listener) in C:\Code\Tools\Rubberduck\Rubberduck.Parsing\Grammar\VBAParser.cs:line 13740
   at Antlr4.Runtime.Tree.ParseTreeWalker.EnterRule(IParseTreeListener listener, IRuleNode r)
   at Antlr4.Runtime.Tree.ParseTreeWalker.Walk(IParseTreeListener listener, IParseTree t)
   at Antlr4.Runtime.Tree.ParseTreeWalker.Walk(IParseTreeListener listener, IParseTree t)
   at Antlr4.Runtime.Tree.ParseTreeWalker.Walk(IParseTreeListener listener, IParseTree t)
   at Antlr4.Runtime.Tree.ParseTreeWalker.Walk(IParseTreeListener listener, IParseTree t)
   at Antlr4.Runtime.Tree.ParseTreeWalker.Walk(IParseTreeListener listener, IParseTree t)
   at Antlr4.Runtime.Tree.ParseTreeWalker.Walk(IParseTreeListener listener, IParseTree t)
   at Antlr4.Runtime.Tree.ParseTreeWalker.Walk(IParseTreeListener listener, IParseTree t)
   at Antlr4.Runtime.Tree.ParseTreeWalker.Walk(IParseTreeListener listener, IParseTree t)
   at Antlr4.Runtime.Tree.ParseTreeWalker.Walk(IParseTreeListener listener, IParseTree t)
   at Antlr4.Runtime.Tree.ParseTreeWalker.Walk(IParseTreeListener listener, IParseTree t)
   at Antlr4.Runtime.Tree.ParseTreeWalker.Walk(IParseTreeListener listener, IParseTree t)
   at Antlr4.Runtime.Tree.ParseTreeWalker.Walk(IParseTreeListener listener, IParseTree t)
   at Antlr4.Runtime.Tree.ParseTreeWalker.Walk(IParseTreeListener listener, IParseTree t)
   at Antlr4.Runtime.Tree.ParseTreeWalker.Walk(IParseTreeListener listener, IParseTree t)
   at Antlr4.Runtime.Tree.ParseTreeWalker.Walk(IParseTreeListener listener, IParseTree t)
   at Antlr4.Runtime.Tree.ParseTreeWalker.Walk(IParseTreeListener listener, IParseTree t)
   at Antlr4.Runtime.Tree.ParseTreeWalker.Walk(IParseTreeListener listener, IParseTree t)
   at Antlr4.Runtime.Tree.ParseTreeWalker.Walk(IParseTreeListener listener, IParseTree t)
   at Antlr4.Runtime.Tree.ParseTreeWalker.Walk(IParseTreeListener listener, IParseTree t)
   at Antlr4.Runtime.Tree.ParseTreeWalker.Walk(IParseTreeListener listener, IParseTree t)
   at Rubberduck.Parsing.VBA.RubberduckParser.ResolveReferences(VBComponent component, IParseTree tree, CancellationToken token) in C:\Code\Tools\Rubberduck\Rubberduck.Parsing\VBA\RubberduckParser.cs:line 301

I'm using the latest "next" commit ...

**Comment by Hosch250** [comment] 2016-02-24 17:27
Thank you for the bug report.  Could you provide the failing code so we could see exactly what our parser breaks on?

**Comment by retailcoder** [comment] 2016-02-24 17:29
That's a resolver bug - I *think* I've seen it too, but I can use some help coming up with the minimal VBA code required to cause it. The exception is thrown on [this line](https://github.com/rubberduck-vba/Rubberduck/blob/next/Rubberduck.Parsing/Symbols/IdentifierReferenceResolver.cs#L731):

            var identifierContext = context.ambiguousIdentifier();
            var member = _declarations.Where(d => d.IdentifierName == identifierContext.GetText())
                .SingleOrDefault(item => item.ComponentName == parentType.ComponentName);

It's assuming that there will only be one member with a given name under a module/class with the parent type's name. The problem seems to be that it's ignoring the fact that there can be more than 1 `Sheet1` class in `_declarations` if multiple projects are opened... I'm pretty sure I need to check the `Project` reference as well, and then since a given project cannot have a duplicate `ComponentName`, it should work... except I should also be checking the `DeclarationType` here, because it's perfectly legal to have a local variable named after a module.

**Comment by Pitterling** [comment] 2016-02-24 17:49
@Hosch250 would it be sufficient just to provide the failing module? There are a lot of dependencies ..
Any way to figure out .. which part the parser is failing?

**Comment by Hosch250** [comment] 2016-02-24 17:50
A minimal, verifiable example would be best.

**Comment by retailcoder** [comment] 2016-02-24 18:09
I *think* this would trip it:

**Class1**

    Private Type TSomething
        Foo As Integer
    End Type
    Private this As TSomething

    Public Property Get Foo() As Integer
        Foo = this.Foo
    End Sub

The identifier `Foo` exists twice in the module - once under `TSomething.Foo`, and once under `Class1.Foo`. Since all the `Where` call is checking for is that the `parentType.ComponentName` ("Class1") matches, and that the `identifierName` ("Foo") matches - the `SingleOrDefault` fails to resolve, because both declarations match the criteria.

@Pitterling can you confirm that the above snippet causes the same exception?

**Comment by Pitterling** [comment] 2016-02-24 18:16
@Hosch250 
[Rubberduck-Parser-Error.xlsm.zip](https://github.com/rubberduck-vba/Rubberduck/files/145178/Rubberduck-Parser-Error.xlsm.zip)

I extraced the failing part and the dependencies .. in total more then 20 modules ...

**Comment by Hosch250** [comment] 2016-02-24 18:17
Thanks.  We will look into it.

**Comment by Pitterling** [comment] 2016-02-24 18:39
@retailcoder the code snippet is causing a different exception

``Exception thrown: 'Rubberduck.Parsing.Symbols.SyntaxErrorException' in Rubberduck.Parsing.dll
Rubberduck.Parsing.Symbols.SyntaxErrorException: extraneous input 'End Sub' expecting {END_PROPERTY, NEWLINE, REMCOMMENT, COMMENT, ':', WS}
   at Rubberduck.Parsing.Symbols.ExceptionErrorListener.SyntaxError(IRecognizer recognizer, IToken offendingSymbol, Int32 line, Int32 charPositionInLine, String msg, RecognitionException e) in C:\Code\Tools\Rubberduck\Rubberduck.Parsing\Symbols\ExceptionErrorListener.cs:line 10
   at Antlr4.Runtime.ProxyErrorListener`1.SyntaxError(IRecognizer recognizer, Symbol offendingSymbol, Int32 line, Int32 charPositionInLine, String msg, RecognitionException e)
   at Antlr4.Runtime.Parser.NotifyErrorListeners(IToken offendingToken, String msg, RecognitionException e)
   at Antlr4.Runtime.DefaultErrorStrategy.ReportUnwantedToken(Parser recognizer)
   at Antlr4.Runtime.DefaultErrorStrategy.Sync(Parser recognizer)
   at Rubberduck.Parsing.Grammar.VBAParser.endOfStatement() in C:\Code\Tools\Rubberduck\Rubberduck.Parsing\Grammar\VBAParser.cs:line 17883
   at Rubberduck.Parsing.Grammar.VBAParser.block() in C:\Code\Tools\Rubberduck\Rubberduck.Parsing\Grammar\VBAParser.cs:line 1828
   at Rubberduck.Parsing.Grammar.VBAParser.propertyGetStmt() in C:\Code\Tools\Rubberduck\Rubberduck.Parsing\Grammar\VBAParser.cs:line 8141
   at Rubberduck.Parsing.Grammar.VBAParser.moduleBodyElement() in C:\Code\Tools\Rubberduck\Rubberduck.Parsing\Grammar\VBAParser.cs:line 1583
   at Rubberduck.Parsing.Grammar.VBAParser.moduleBody() in C:\Code\Tools\Rubberduck\Rubberduck.Parsing\Grammar\VBAParser.cs:line 1450
   at Rubberduck.Parsing.Grammar.VBAParser.module() in C:\Code\Tools\Rubberduck\Rubberduck.Parsing\Grammar\VBAParser.cs:line 452
   at Rubberduck.Parsing.Grammar.VBAParser.startRule() in C:\Code\Tools\Rubberduck\Rubberduck.Parsing\Grammar\VBAParser.cs:line 231
   at Rubberduck.Parsing.VBA.RubberduckParser.ParseInternal(ICharStream stream, IEnumerable`1 listeners, ITokenStream& outStream) in C:\Code\Tools\Rubberduck\Rubberduck.Parsing\VBA\RubberduckParser.cs:line 275
   at Rubberduck.Parsing.VBA.RubberduckParser.ParseInternal(String code, IEnumerable`1 listeners, ITokenStream& outStream) in C:\Code\Tools\Rubberduck\Rubberduck.Parsing\VBA\RubberduckParser.cs:line 259
   at Rubberduck.Parsing.VBA.RubberduckParser.ParseInternal(VBComponent vbComponent, String code, CancellationToken token) in C:\Code\Tools\Rubberduck\Rubberduck.Parsing\VBA\RubberduckParser.cs:line 225
   at Rubberduck.Parsing.VBA.RubberduckParser.Parse(VBComponent vbComponent, CancellationToken token, TokenStreamRewriter rewriter) in C:\Code\Tools\Rubberduck\Rubberduck.Parsing\VBA\RubberduckParser.cs:line 153
``

**Comment by retailcoder** [comment] 2016-02-24 18:50
lol, that was a typo. I meant to `End Property`, not `End Sub`!

**Comment by Pitterling** [comment] 2016-02-25 09:34
@retailcoder .. the reviewed snippet is still causing a different exception

> Exception thrown: 'Microsoft.CSharp.RuntimeBinder.RuntimeBinderException' in System.Core.dll 
("'Rubberduck.Parsing.Grammar.VBAParser.TypeContext' does not contain a definition for 'typeHint'")

> Exception caught: 'Microsoft.CSharp.RuntimeBinder.RuntimeBinderException' in System.Core.dll 
("'Rubberduck.Parsing.Grammar.VBAParser.TypeContext' does not contain a definition for 'typeHint'")

**Comment by retailcoder** [comment] 2016-02-26 02:51
@Pitterling ah, good one - I'm preventing that exception in the `Declaration` class, but not in `IdentifierReference`. Note that this `RuntimeBinderException` is handled though - and it's not thrown in the resolver. In other words, it's not reproducing the resolver error. I'm trying with your workbook now.

**Comment by retailcoder** [comment] 2016-02-26 04:47
Well, this is interesting:

> Rubberduck.Parsing.Symbols.SyntaxErrorException: no viable alternative at input 'Public Const' ---> Antlr4.Runtime.NoViableAltException: Exception of type 'Antlr4.Runtime.NoViableAltException' was thrown.
   at Antlr4.Runtime.Atn.ParserATNSimulator.HandleNoViableAlt(ITokenStream input, Int32 startIndex, SimulatorState previous)
   at Antlr4.Runtime.Atn.ParserATNSimulator.ExecATN(DFA dfa, ITokenStream input, Int32 startIndex, SimulatorState initialState)
   at Antlr4.Runtime.Atn.ParserATNSimulator.ExecDFA(DFA dfa, ITokenStream input, Int32 startIndex, SimulatorState state)
   at Antlr4.Runtime.Atn.ParserATNSimulator.AdaptivePredict(ITokenStream input, Int32 decision, ParserRuleContext outerContext, Boolean useContext)
   at Antlr4.Runtime.Atn.ParserATNSimulator.AdaptivePredict(ITokenStream input, Int32 decision, ParserRuleContext outerContext)
   at Rubberduck.Parsing.Grammar.VBAParser.moduleBodyElement() in c:\Users\Mathieu\Documents\GitHub\Rubberduck\Rubberduck.Parsing\Grammar\VBAParser.cs:line 1571

A **parser** error! (there's a resolver issue too, but the resolver isn't even supposed to kick in when the code can't be parsed - that's *another* issue, introduced by a recent change in the way parsing gets triggered) - looks like I have a grammar to fix!

**Comment by retailcoder** [comment] 2016-02-26 06:25
Several grammar/parser issues.

First one, a line ending with a colon trips the parser. This code reproduces the issue:

    Option Explicit
    
    Public Const Foo As String = "abc" & "def":
    Public Const Bar As Integer = 42
    
Removing the trailing colon fixes it, but the code is legal so the grammar/parser needs a fix.

**Comment by retailcoder** [comment] 2016-02-26 07:14
@autoboosh got a clue about this one? I'm stuck :unamused:

**Comment by autoboosh** [comment] 2016-02-26 12:28
The grammar issues are fixed. I'll add tests based on @Pitterling's code next so we can keep regressions like these to a minimum. The second issue isn't fully fixed, since there are probably a few other places where a WS is missing. I'll try to find a general fix.

With that said, there's still an open resolver issue (the one mentioned in the first comment). I'll leave that to you @retailcoder if that's OK.

**Comment by retailcoder** [comment] 2016-02-26 12:46
@autoboosh awesome, thanks! I'll deal with the resolver bug :-)

**Comment by retailcoder** [comment] 2016-02-26 16:32
@autoboosh got a PR for it?

**Comment by autoboosh** [comment] 2016-02-26 16:35
Not yet, found two more line continuation issues I'd like to fix first if you don't mind.

**Comment by retailcoder** [comment] 2016-02-26 16:39
Cool!

**Comment by autoboosh** [comment] 2016-02-26 17:03
PR is up at https://github.com/rubberduck-vba/Rubberduck/pull/1147.

Only added tests for a few cases so you can get an idea of what it could look like. Any feedback welcome.

**Comment by retailcoder** [comment] 2016-02-26 18:56
With the referencing commits now merged into [next] (thanks a bunch @autoboosh!), only the resolver bug should remain now. Consider it fixed!

**Comment by retailcoder** [comment] 2016-02-27 03:17
Update: the exception was thrown in the resolver because of a bug in the ...`ExcelObjectModel` class, which had the `Select` member existing 3 times under a different `ParentDeclaration`, but under the same `QualifiedModuleName`. The entire workbook parses and resolves correctly now.

Next step, get it to parse *once* - that'll considerably improve overall performance :-)

**Closed** 2016-02-27 03:23 UTC
Labels: bug, code-parsing, vba-grammar

**Comment by Pitterling** [comment] 2016-02-28 20:33
thx guys. great work.
unfortunately i'm facing now a NullReferenceException with the latest commits and the attached workbook. I'm going to create another issue.
