### ISSUE TITLE
3739-pre : Autocompletion disabled, still seems to affect the typing (Adding unwanted double quotes and parenthesis)

### ISSUE THREAD

**Issue by FuSoftware** [rubberduck-vba/Rubberduck#4339] opened 2018-08-31 08:26 UTC
While editing any type of text, pressing the key `"` to close a string produces 2 quotes instead of one.

For example, pressing the keys : `" Y "` should result in `"Y"`, but it actually results in `"Y""`, even with autocomplete disabled. The issue disappears with RD uninstalled.

I have not found any reference of this specific bug yet but I might be wrong

**Comment by FuSoftware** [comment] 2018-08-31 09:29
I will also add that again, with Autocompletion fully disabled, adding an open parenthesis automatically adds the closing parenthesis. It's like Autocompletion is still active

**Comment by FuSoftware** [comment] 2018-08-31 09:38
Another example, if I have the following code
`Obj.Item()` and I try to put a `"` in the parenthesis, it results in `Obj.Item()"` instead of `Obj.Item(")`

**Comment by Inarion** [comment] 2018-08-31 09:47
Just for reference: Which version are you using? From a quick test with 3739-pre it seems to me that either the autocomplete settings are 

- either not correctly representing their actual state 
- or not working at all.

(Meaning, I can reproduce the issue you described.)

**Comment by FuSoftware** [comment] 2018-08-31 09:50
It is 3739, yes

**Comment by retailcoder** [comment] 2018-08-31 14:18
Confirmed repro here.

I had this:

```xml
  <AutoCompleteSettings IsEnabled="false" CompleteBlockOnTab="true" CompleteBlockOnEnter="true" EnableSmartConcat="true">
```

Then changed it to this:

```xml
  <AutoCompleteSettings IsEnabled="false" CompleteBlockOnTab="false" CompleteBlockOnEnter="false" EnableSmartConcat="false">
```

And AC still somehow manages to wire up, and ignores its "master switch" `IsEnabled` setting. @FuSoftware by editing the .config file to set `EnableSmartConcat` to `false`, the bug/feature is no longer enabled though.

As for `obj.Item()`, the reason AC is struggling is because `obj.Item()` is because you're missing a space between `Item` and the opening `(`, that the VBE automatically inserts when RD's self-closing pairs (despite being disabled, but that's another issue) add the closing `)`.

So if you have this (where `|` represents the caret position):

    msgbox|

And type a `(`, RD attempts to get to this:

    msgbox(|)

However the VBE desperately wants to do this:

    MsgBox (|)

So if that whitespace isn't present, when you type the `"` here:

    msgbox("|)

The VBE does this:

    MsgBox ("|)

And then RD overwrites it to this:

    msgbox("|")

Except at that point it's fighting a lost battle against the VBE, and RD loses track of what's where, because it now finds a `"` where there was a `(` a split-second earlier - and `"` being the closing character of the `""` pair, drops the closing character because it's already there.

Everything falls into place if you drop the redundant parentheses, or type the whitespace the VBE slips in:

     msgbox ("|)

correctly results in

    MsgBox ("|")

And

    msgbox "|

correctly results in

    MsgBox "|"

The hard part is not accounting for that whitespace. The hard part is accounting for the *actual* behavior of the VBE, which will take this:

    msgbox                                                   ("wut")

And turn it into this:

    MsgBox ("wut")

Clearly autocompletion in the VBE is much harder than I originally thought. I'll probably altogether un-ship the feature for the v2.3.0 "green release", and re-include it (with a properly-working killswitch) in 2.3.x pre-release builds.

**Comment by FuSoftware** [comment] 2018-08-31 14:35
Thanks for the insight on why stuff happens. I am no VBE COM expert, but isn't there a way to disable VBE's own autocorrect at this point, so you can fully build yours without accounting for any possible undesirable behaviour from it ?

**Comment by MDoerner** [comment] 2018-08-31 14:46
There is no way to disable the VBE's 'autocrrect' because the result is exactly what the VBE thinks you entered on the first place.

Let me give a bit background regarding this. The VBE comes from a time where space was not abundant. So, whenever you enter a line of code, it gets compiled to an intermediate format, pcode, like IL for .Net or bytecode for Java. This gets saved and the actual gets thrown away. What you see in the code pane is basically a decompilation of the pcode. That is why the VBE 'pretty-prints' your code and you cannot do anything about it.

**Closed** 2018-09-27 11:52 UTC
Labels: bug, critical, feature-autocomplete
