### ISSUE TITLE
Properties passed as ByRef are actually ByVal

### ISSUE THREAD

**Issue by IvenBach** [rubberduck-vba/Rubberduck#5374] opened 2020-02-05 01:18 UTC
**What**
Picked up Excel Insights and naturally I started with Mug's section. Pg263 calls out that Let/Set parameters should always have an explicit `ByVal` modifier. A `ByRef` modifier isn't actually a reference. There should be an inspection result bringing this to the users attention.

**Why**
To educate the user about this contradictory behavior.

**Example**
This code should trigger the inspection:

```vb
'Module1
Option Explicit

Public Sub Bar()
    Dim duk As Something
    Set duk = New Something
    
    Dim notARef As String
    notARef = "bazz"
    duk.Foo = notARef
    
    Debug.Print duk.Foo
End Sub
```

```vb
'Class Something
Option Explicit

Private Type THelper
    Foo As String
End Type

Private this As THelper

Public Property Get Foo() As String
    Foo = this.Foo
End Property
Public Property Let Foo(ByRef value As String)
    this.Foo = value
    value = "not reflected"
End Property
```

---

**QuickFixes**
Change `ByRef` to `ByVal`.

1. **QuickFix Name**

    Example code, after quickfix is applied:

    ```vb
    Public Property Let Foo(ByVal value As String)
        this.Foo = value
        value = "not reflected"
    End Property
    ```

---

**Resources**
 - **InspectionNames**: LetSetPropertyParameterImplicitlyPassedByValInSpiteOfExplicitByRefModifier.
 - **InspectionInfo**: `ByVal` should be used since, irregardless of whether `ByRef` is used or not, the parameter is always passed by value.
 - **InspectionResults**: Use the explicit `ByVal` modifier to pass parameters.

**Comment by BZngr** [comment] 2020-05-09 00:53
I'm thinking the inspection should be be looking for an assignment of the `value` parameter within the `PropertyLet` in order to generate a flagged result.  Finding an assignment of the `value` parameter establishes that there was an intent/hope to modify the passed-in `value`.  Otherwise...it's kind of a 'no harm - no foul' scenario.  By looking for the assignment, RD may prevent a lurking bug (that should have revealed itself if the user tests the `ByRef`-ness return value at all).

**Comment by retailcoder** [comment] 2020-05-09 02:41
@BZngr I see this one more as a "hint"-type inspection; the goal here is just to point out that a `ByRef` modifier on the RHS parameter, is deceptive: it says `ByRef` but does `ByVal` - in the spirit of *write code that does what it says, and says what it does*, "no harm, no foul" isn't exactly correct: a lying token is definitely a readability issue.

**Comment by retailcoder** [comment] 2020-05-09 02:45
About flagging assignment of the RHS parameter... @MDoerner would you know off the top of your head if the resolver picks up property RHS parameters as ByVal regardless of what the token says? If so, then "ByVal parameter assignment" is already picking it up.

**Comment by BZngr** [comment] 2020-05-09 13:28
I'm in agreement that changing the signature to be explicit `ByVal` is the best option and fixes the 'lying token' issue.  The `QuickFix` may need to consider a bit more...changing only the parameter mechanism potentially ignores some intended functionality and trigger other inspections _IF_ there is an assignment of the RHS parameter in a `PropertyLet` - definitely a special case.  An intent to coerce an input seems to be a likely scenario of where someone may attempt to apply the invalid parameter mechanism in a `PropertyLet` signature:

A sequence of events (driven by RD Inspection results): 

Given:
```
Private lengthCompliantName As String
Public Property Let Name(value As String)
    value = Left(value, 10)   
    lengthCompliantName = value
End  Property
```
1. The above code flags the `ImplicitByRefModifierInspection` in which the Inspection's description encourages the user to apply the `ByRef` parameter mechanism if the intent is to modify the parameter.  (Note: Implicit `ByRef` parameters of  `PropertyLet` RHS parameters should be ignored by `ImplicitByRefModifierInspection` (bug?) and flagged up by this new Inspection).  

2. Following the `ImplicitByRefModifierInspection` suggestion, the user decides he wants to modify the parameter and adds the `ByRef` parameter mechanism which leads to a `PropertyLet` signature that would be flagged by this new Inspection.

3. In this scenario, only changing the RHS parameter to `ByVal` will now trigger the `AssignedByValParameterInspection`.  The Inspection's explanation encourages the user to change the parameter mechanism to `ByRef`(!) or to make a local copy to modify (`AssignedByValParameterMakeLocalCopyQuickFix`):

4. Applying the `AssignedByValParameterMakeLocalCopyQuickFix` results in:
```
Private lengthCompliantName As String
Public Property Let Name(ByVal value As String)
    Dim localValue As String
    localValue = value
    localValue = Left(localValue, 10)
    lengthCompliantName = localValue
End Property
```
Now, there are no Inspections flagged, but some intended functionality was lost.  

Perhaps, this falls into the category of 'too much help', but if the user's original intent was to make the coerced/truncated value available to the caller, then it could be possible to generate the following replacement `Function` as an option for the user:
```
Private lengthCompliantName As String

Public Function TryLetName(ByVal value As String, ByRef outValue As String) As Boolean

'outValue is used in a similar manner as localValue in AssignedByValParameterMakeLocalCopyQuickFix
    outValue = value
    outValue = Left(outValue , 10) 
   lengthCompliantName = outValue 

    TryLetName = StrComp(value, outValue) = 0
End  Function
```
And, move the 'Local Copy' to the call sites 
From:
```
Dim myName As String
myName = "Beetlejuice"
TheModule.Name = myName
'Do stuff with myName
```
    
To:
```
Dim myName As String
myName = "Beetlejuice"

Dim myName1 As String
myName1 = myName
TheModule.TryLetName(myName1 , myName)
'Do stuff with myName
```

**Comment by retailcoder** [comment] 2020-05-09 16:54
@BZngr but implementing this part of the spec at the resolver level changes the scenario...

1. *Implicit ByRef modifier* would no longer be flagged.
2. *Assigned ByVal parameter* would now be flagging the assigned parameter, *warning the user of a bug: the caller is not receiving the reassigned value as intended*

Changing the modifier to ByRef does not change the behavior of the parameter.

> § If the `<value-param>` of a `<property-LHS-declaration>` does not have a `<parameter-mechanism>` element or has a '<parameter-mechanism>' consisting of the keyword 'ByRef', ***it has the same meaning as if it instead had*** a `<parameter-mechanism>` element consisting of the keyword `ByVal`.

**Closed** 2020-10-24 03:37 UTC
Labels: enhancement, feature-inspections, up-for-grabs
