### ISSUE TITLE
Reorder Parameters misnames parameter at call site

### ISSUE THREAD

**Issue by daFreeMan** [rubberduck-vba/Rubberduck#845] opened 2015-10-26 15:02 UTC
I started with these parameters:

    Private Sub PrintIndustryChart(ByVal PageNumber As Integer, ByRef Report As Worksheet, ByRef ClinicList As ProcessClinic, ByRef CurrentReportRow As Integer)

![rd before reorder](https://cloud.githubusercontent.com/assets/11889733/10732485/baafe91e-7bd0-11e5-9617-d1b2ed08e3dc.PNG)

Executed `Refactor | Reorder Parameters` like this:
![rd reorder](https://cloud.githubusercontent.com/assets/11889733/10732524/e4a82010-7bd0-11e5-820a-7e82033e2f4d.PNG)

and ended up with this:

PrintIndustryChart Report, ClinicList, CurrentReportRow, CurrentPageNumberRow
![rd after reorder](https://cloud.githubusercontent.com/assets/11889733/10732548/f97fe996-7bd0-11e5-8f9f-0211003994cb.PNG)

**Comment by AndrewM-** [comment] 2015-10-27 04:09
Reorder parameters sometime gets non-target functions.  I changed the order of the Folder and DriveLetter.

    Public Function FolderExists(Folder As String, DriveLetter As String) As Boolean

    '///Returns True if folder exists, otherwise returns False
    '///Drive is optional, use an empty string if required if drive is not specified

    Dim fso As Object
    Dim FolderSpec As String
    
    If Folder = "" Then Exit Function
    
    FolderExists = False
    If Have(DriveLetter) Then
        FolderSpec = DriveLetter & Folder
    Else
        FolderSpec = Folder
    End If
    
    Set fso = CreateObject("Scripting.FileSystemObject")
    
     If fso.FolderExists(, FolderSpec) Then '***Error on this line***  should be no comma
        FolderExists = True
    End If
    
    Set fso = Nothing
    
    End Function

**Comment by AndrewM-** [comment] 2015-10-27 04:24
The reorder parameters also failed to swap the parameters in most/all other calling functions, probably because the are called like:

    If Not modFolders.FolderExists(Path, "") Then

The module name is used to prevent confusion with the inbuilt fso.folderexists function.

**Comment by Hosch250** [comment] 2015-10-27 04:38
This is not the only bug in the current release.  I fixed several bugs when I added the unit tests, and this may be working in the current build, but maybe not.  I cannot get Rubberduck to work on my machine at the moment, but if this is not fixed by some time in early December, I will address it.

**Comment by INOPIAE** [comment] 2015-10-27 10:25
I observe the reported behaviour in the current "Next" branch as well.
It does not matter if the called procedure has a module name infront of it or not.

**Comment by Hosch250** [comment] 2015-12-11 16:46
@daFreeMan I cannot reproduce this problem in the latest version.

**Closed** 2015-12-17 20:20 UTC
Labels: bug, refactorings
