### ISSUE TITLE
Unusably slow running tests in v2.5.0.5457-pre

### ISSUE THREAD

**Issue by Senipah** [rubberduck-vba/Rubberduck#5513] opened 2020-06-04 20:02 UTC
**Rubberduck version information**

```
Version 2.5.0.5457
OS: Microsoft Windows NT 10.0.18363.0, x64
Host Product: Microsoft Office x64
Host Version: 16.0.12730.20270
Host Executable: EXCEL.EXE
```

**Description**
As shown in the below screen shots, running unit tests which took 2:42 in 5443 takes 1:05:03 in 5457.

**To Reproduce**
1. To run exactly the same unit tests as me you can download the modules from here: https://github.com/Senipah/VBA-Better-Array/raw/master/releases/latest/WithTests.Zip
2. Import the modules into a fresh project
3. Parse the Project in Rubberduck
4. Open "Test Explorer" and click "Run all tests".
5. Wait a very long time...

**Expected behavior**
All previous RD versions ran these tests in around 2 minutes. The following recent versions I have tested today all perform the tests in around 2 minutes:

* 2.5.0.5443-pre
* 2.5.0.5435-pre
* 2.5.0.5436-pre
* 2.5.0.5432-pre

I would expect 5457 to deliver comparable performance. 

**Screenshots**
![5457](https://user-images.githubusercontent.com/4821959/83803982-58ed9000-a6a5-11ea-8fbf-762a5c06b82f.png)
![5443](https://user-images.githubusercontent.com/4821959/83803990-5d19ad80-a6a5-11ea-8a09-6ace0fab9c8d.png)

**Logfile**
[RubberduckLog.txt](https://github.com/rubberduck-vba/Rubberduck/files/4732401/RubberduckLog.txt)

**Additional context**

**Comment by Senipah** [comment] 2020-06-04 20:12
This would seem to be a UI issue as the individual tests have about the same duration as with previous versions. There are 4 long running tests that take around 600ms (because I couldn't be bothered to mock) and the rest are all ~15ms).
![durations](https://user-images.githubusercontent.com/4821959/83805421-c7cbe880-a6a7-11ea-8baa-10e1deb93a1e.png)

**Comment by MDoerner** [comment] 2020-06-04 20:16
Do you also experience the long run times when grouping by something else than the test outcome?

I ask because there is a known slowness issue when grouping that way.

**Comment by SteveLaycock** [comment] 2020-06-04 20:50
I have noticed that if you group the tests then the form does not reorganise itself whilst the tests are running.  If you do not group the tests then each test that passes is moved to the top of the list and the whole form is redrawn.  This slows down the testing quite a lot.

**Comment by Senipah** [comment] 2020-06-04 20:51
Hi @MDoerner 

Looks like that's the issue.

By location took around 20mins:
![5457-location](https://user-images.githubusercontent.com/4821959/83808620-044e1300-a6ad-11ea-8bcb-e2eeff82d582.png)

But by category took only 32 seconds!
![5457-category](https://user-images.githubusercontent.com/4821959/83808812-54c57080-a6ad-11ea-818e-57f7fc74add0.png)

I'll use category from now on I think 😄 

Assume this issue is a dupe so feel free to close.

**Comment by MDoerner** [comment] 2020-06-07 12:06
Closing as a duplicate of #5052.

It just seems that the recent fixes to the UI, which fixed a complete freeze of the VBE experienced by some users, made this problem worse again.

**Closed by MDoerner** 2020-06-07 12:06 UTC
Labels: duplicate
