### ISSUE TITLE
Code Inspection for "Procedure {x} is never used" should ignore event handlers for anything declared WithEvents.

### ISSUE THREAD

**Issue by comintern** [rubberduck-vba/Rubberduck#1182] opened 2016-03-11 17:55 UTC
Very similar to [issue #707](https://github.com/rubberduck-vba/Rubberduck/issues/707).  Consider the following add-in code used to set up an application-wide event hook:

```
Private WithEvents xlApp As Application

Private Sub Class_Initialize()
    Set xlApp = Application
End Sub

Private Sub xlApp_SheetActivate(ByVal Sh As Object)
    Dim win As Window
    Set win = Sh.Parent.Windows(1)
    win.Zoom = 80
End Sub
```

This results in "Procedure 'xlApp_SheetActivate' is never used." 

Custom events don't seem to have this issue - as long as the event is declared in the class. Related issue coming shortly.

**Comment by retailcoder** [comment] 2016-03-11 18:10
I have code in my fork, that's loading all referenced COM libraries and creating a `Declaration` object for literally *everything* referenced - including the whole entire Excel object model and its events.

If I got the events right (see [here](https://github.com/retailcoder/Rubberduck/blob/TypeInfo/Rubberduck.Parsing/Symbols/ReferencedDeclarationsCollector.cs#L288)), then built-in events from anything that can fire an event will be picked up as such, not any differently from user code.

**Comment by retailcoder** [comment] 2016-03-18 20:00
COM reflection stuff was merged, and I can confirm that workbook & worksheet events are not marked as "not used", which is great... but this issue remains: event handlers of object variables of COM types declared `WithEvents`, are picked up by the [`ProcedureNotUsedInspection`](https://github.com/rubberduck-vba/Rubberduck/blob/next/RetailCoder.VBE/Inspections/ProcedureNotUsedInspection.cs).

I believe the problem is here:

    var declarations = UserDeclarations.ToList();
    ...

    var withEventFields = declarations.Where(item => item.DeclarationType == DeclarationType.Variable && item.IsWithEvents);
    handlers.AddRange(withEventFields.SelectMany(field => declarations.FindEventProcedures(field)));

Notice `field => declarations.FindEventProcedures(field)` -- `declarations` only contains the user declarations. The [`FindEventProcedures`](https://github.com/rubberduck-vba/Rubberduck/blob/1c9e056b31be2ac44ee2083e52c54f7720dc389e/RetailCoder.VBE/Common/DeclarationExtensions.cs#L335-L362) extension method takes the declared type into account, and returns all events under it.. so, passing `AllDeclarations` to it would make it work, but would quite possibly be very slow - I need to fix these O(n) lookups.

**Closed** 2017-01-16 06:07 UTC
Labels: bug, feature-inspections
