### ISSUE TITLE
Can't enable autocompletion

### ISSUE THREAD

**Issue by DaveSandersFMI** [rubberduck-vba/Rubberduck#4301] opened 2018-08-24 09:48 UTC
Autocompletion is disabled by default; Checking the feature ON in settings > OK leaves feature disabled in reality (and the checkbox remains OFF if I check it again in settings).

**Comment by comintern** [comment] 2018-08-24 13:04
I've duplicated this with disabled inspection settings also.

**Comment by retailcoder** [comment] 2018-08-24 13:52
PR #4272 introduced a proper "killswitch" for the feature, ensuring it doesn't interfere with typing when it's disabled. It also removed the rather buggy block completion feature, but the block completion settings remained in place.

Enabling AC effectively only enables self-closing pairs (aka SCPs) for now... but indeed, the settings *should* reflect the "enabled" state of it. Bringing up the settings dialog after enabling SCPs *should* have that checkbox checked. This is indeed a regression bug.

**Comment by comintern** [comment] 2018-08-29 23:53
The "duplication" with inspection settings appears to be because I was messing around with my app config files. That apparently resolved itself with a rebuild clean?

Fix inbound for the AC settings.

**Closed** 2018-08-30 15:56 UTC
Labels: bug, critical, feature-autocomplete, feature-settings, regression
