### ISSUE TITLE
AssignmentIsNotUsed inspection caused by assigning to itself while concatenating

### ISSUE THREAD

**Issue by IvenBach** [rubberduck-vba/Rubberduck#5470] opened 2020-04-24 00:37 UTC
**Rubberduck version information**
Version 2.5.0.17253
OS: Microsoft Windows NT 10.0.18362.0, x64
Host Product: Microsoft Office 2016 x64
Host Version: 16.0.4978.1000
Host Executable: EXCEL.EXE

**Description**
When building up a string by assigning it a value and using that variable concatenated with more information yields a false positive on the first assignment. It's arguably better instead use the line continuation character `_` (underscore). Possible new inspection?

```vba
Public Sub MVCE()
    Dim latitude As Double
    latitude = 91
    Dim longitude As Double
    longitude = 181
    
    Dim query As String
    query = "www.foo.com/bar.php?" '<-- False positive
    query = query & "latitude=" & latitude
    query = query & "&longitude=" & longitude
    
    Debug.Print query
End Sub
```

A better option which yields no results
```vba
Public Sub MVCE_CleanedUp()
    Dim latitude As Double
    latitude = 91
    Dim longitude As Double
    longitude = 181
    
    Dim query As String
    query = "www.foo.com/bar.php?" & _
            "latitude=" & latitude & _
            "&longitude=" & longitude
    
    Debug.Print query
End Sub
```
**To Reproduce**
1. Add module, paste code, parse, Code Inspections

**Expected behavior**
Consider the first assignment used. Possibly prompt with a UseLineContinuationCharacterInspection instead?

**Comment by MDoerner** [comment] 2020-04-24 09:26
Duplicate of #4754

**Closed by MDoerner** 2020-04-24 09:26 UTC
Labels: duplicate
