### ISSUE TITLE
Copy to clipboard doesn't work

### ISSUE THREAD

**Issue by BitSprocket** [rubberduck-vba/Rubberduck#3648] opened 2017-12-27 14:47 UTC
Button on test explorer to copy to clipboard doesn't do anything.

**Comment by Vogel612** [comment] 2017-12-27 14:51
What version of Rubberduck are you running?

**Comment by BitSprocket** [comment] 2017-12-27 14:51
Rubberduck version: Version 2.1.1.2532
Operating System: Microsoft Windows NT 10.0.17046.0, x64
Host Product: Microsoft Office 2016 x64
Host Version: 16.0.8730.2127
Host Executable: MSACCESS.EXE

**Comment by IvenBach** [comment] 2017-12-30 19:18
Same issue for me.

Rubberduck version: Version 2.1.6572.17384
Operating System: Microsoft Windows NT 10.0.15063.0, x64
Host Product: Microsoft Office 2016 x86
Host Version: 16.0.8730.2127
Host Executable: EXCEL.EXE

**Comment by kwnwzlnd** [comment] 2018-01-12 15:02
Same issue.

Shortcut Ctrl+C in Rubberduck default Settings is set to "Code Explorer".
Also Ctrl+M is set to Ident and is VBE-Standard "Import Module" in Files.

Excel Version 14.0.7912 32Bit **German**
Rubberduck-Version 2.1.2.2718

**Comment by retailcoder** [comment] 2018-01-12 15:13
@kwnwzlnd the indenter hotkeys match the original *Smart Indenter* add-in's hotkey mappings, that's by design. .2718 *should* have the CE default mapping back to Ctrl+R though... :confused:

**Comment by CHR-IS-B** [comment] 2018-02-27 20:35
The CTRL+C mapping threw me off. I've been pressing CTRL+C, moving focus back to the code, and pressing CTRL+C again to copy.  This post helped me understand what was happening so I removed the hotkey in RD.

**Comment by Vogel612** [comment] 2018-03-31 19:22
This should be fixed, I can not reproduce this and I daresay nobody else can either :)

**Closed by Vogel612** 2018-03-31 19:22 UTC
Labels: bug, critical, feature-unit-testing, regression
