### ISSUE TITLE
No matter what functionality I chose, Rubberduck open Test Explorer

### ISSUE THREAD

**Issue by ndthanh** [rubberduck-vba/Rubberduck#4381] opened 2018-09-19 12:17 UTC
Hi Rubberduck team,

I am using Office 2016 on Windows 10.
I downloaded and installed Rubberduck to try it out. No matter what functionality I choose to open (Code Explorer, TODO Explorerer), It always open Test Explorer.

**Comment by daFreeMan** [comment] 2018-09-19 12:32
@ndthanh  - Which version, exactly, of RD are you using? Go to `Rubberduck | About`, then click the light-grey `Copy version information to clipboard` text in the top right box. 

I get no repo in:

Version 2.2.0.3751
OS: Microsoft Windows NT 10.0.15063.0, x64
Host Product: Microsoft Office 2016 x64
Host Version: 16.0.4732.1000
Host Executable: EXCEL.EXE

**Comment by ndthanh** [comment] 2018-09-19 12:37
Version 2.2.0.3795
OS: Microsoft Windows NT 10.0.17134.0, x64
Host Product: Microsoft Office x86
Host Version: 16.0.10730.20102
Host Executable: EXCEL.EXE

**Comment by Vogel612** [comment] 2018-09-19 12:46
#4370 could be very much related. Could you try using the keyboard shortcuts to open other windows (e.g Ctrl+Shift+I for the Inspections Window)?

**Comment by daFreeMan** [comment] 2018-09-19 12:47
Repo!

I just installed .3795 and confirm this behavior. Also in .3794, .3791, .3786, and .3782, but NOT in .3762.

As a workaround, install .3762 - you won't be missing much in functionality. Mostly it's been back-end reorganization stuff in between the releases.

**Comment by ndthanh** [comment] 2018-09-19 12:49
Thank you for your response. 
@Vogel612 , the shortcut works and the Inspections Window opens.

**Comment by Vogel612** [comment] 2018-09-19 12:53
For now I'll assume that this is a duplicate of #4370. If the issue persists after 4370 is closed, please open a new issue. Thanks!

**Closed by Vogel612** 2018-09-19 12:53 UTC
Labels: bug, critical
