### ISSUE TITLE
RubberDuck requires a Paste Special command

### ISSUE THREAD

**Issue by ThunderFrame** [rubberduck-vba/Rubberduck#1277] opened 2016-03-31 02:34 UTC
RubberDuck should allow a user to paste a multiline string literal, optionally applying double-quotes, line continuations, carriage-returns etc.

VBA developers will often need to paste string literals such as SQL, HTML, XML or other Lorem Ipsum. Those strings will often have multiple lines and meaningful indentation. It would be great if RubberDuck could "Paste" that literal so that VBE treats it with the correct VBA syntax. Ideally, a dialog/wizard would guide the creation of a variable or constant, and adhere to VBA rules around line length and continued lines.

Eg.

``` sql
  SELECT emp.*
    FROM emp
   WHERE emp.emp_id = 6
ORDER BY emp.emp_id asc;
```

Would paste into VBA as something like:

``` vb
Dim sSQL As String
sSQL = _
    "  SELECT emp.*" & vbCrLf & _
    "    FROM emp" & vbCrLf & _
    "   WHERE emp.emp_id = 6" & vbCrLf & _
    "ORDER BY emp.emp_id asc;"
```

**Comment by comintern** [comment] 2016-04-04 22:22
The use case that I would get the most out of would be pasting as commented text.

**Comment by ThunderFrame** [comment] 2016-04-04 23:41
I guess the return-trip treatment would be handy too, as in copy multi-line quoted string literal or apostophe'ed comment **as** the unquoted/uncommented, actual text.

**Comment by retailcoder** [comment] 2017-01-13 07:04
duplicate of #929

**Closed by retailcoder** 2017-01-13 07:04 UTC
Labels: feature-request
