### ISSUE TITLE
Rubberduck performance between v1.4.3 and v2.0.1a pre on exisiting VBA code

### ISSUE THREAD

**Issue by PeterMTaylor** [rubberduck-vba/Rubberduck#1420] opened 2016-05-02 11:26 UTC
I thought best to start a new (?interesting) conversation topic thread as per #1406 suggestion by @retailcoder. 

Some information/background details about my code.
- Have always uninstall old version before installing another version
- Running in 32-bit Excel 2010 on Windows 10 Intel i3-2100 CPU @ 3.10GHz 4GB RAM computer
- Exisiting code used with permission from owner Bartlomiej Dzik (2007-2009) 
- Planned to refactor his code over time as a hobby using modern software development practices.
- [Code Documentor](http://www.appspro.com/Utilities/Documentor.htm) from AppsPro gave the statistics of the existing VBA code as shown below. In additional is One main workbook that calls 3 externals workbooks and a few directories of assets (2 data files and 4 image files i.e. GIF/JPG's)
![code documentor rpg-075a](https://cloud.githubusercontent.com/assets/2254567/14952703/fd343442-10a5-11e6-83e8-3aea72e1194f.PNG)

The results/obersvations so far.
For v1.4.3 release
- Had to select one macro and click Edit to find the entire code listing.
- Parsing message took about 35 seconds roughly for the parser to finish processing
- Code Inspector suggests I have 11 information messages and 201 errors to fix up.
- The Parser shows 2 errors still persists in this version. Hence my original ticket #936 still there. :+1: 
![rubberduck v1 4 3 parse errors](https://cloud.githubusercontent.com/assets/2254567/14953018/df6e95ee-10a8-11e6-9305-d762c44fe4ec.PNG)

For v2.0.1a pre hot-fix release
- Virus error was discussed per #1406 with this release.
- Had to select one macro and click Edit to find the entire code listing.
- Parsing message took about a whooping over 3-4 mins! for the parser to finish processing
- Code Inspector suggests a larger number of messages. I'm happy allows the summary compared to previous version. 
![rubberduck v2 0 1a 2nd-run code inspection report](https://cloud.githubusercontent.com/assets/2254567/14953332/149c4e20-10ac-11e6-9459-541d27429b80.PNG)

- An unusual behaviour noted that the Excel file is "locked" by another user other than myself after closing the Excel file. So I worked around this by ensuring my Excel file is closed, changed the file properity to re-tick the Read only file and reopened the file and it works again.

Hope this helps. :)

**Comment by retailcoder** [comment] 2016-05-02 13:42
Hmm.. v1.4.3 doesn't parse it then.. 35 seconds is the time it took for it to blow up, not to complete; the time comparison isn't conclusive, although 3-4 minutes is pretty long indeed, to process 5K lines in 34 components. Something isn't right.

**Comment by PeterMTaylor** [comment] 2016-05-02 21:18
@retailcoder Fair enough.You know Rubberduck better than I do at the moment, I am open to some discussion of ideas to complete this test that satisfies the comparison as conclusive as this makes a good gauge documentation wise. 

My follow up question for me would be to ask which VBA code for the timer or any other means that works as a timer like in Powershell? can I put in my code that is practical that picks up that the code inspector starts and finishes duration that works for both versions.

**Comment by retailcoder** [comment] 2016-05-02 22:06
hmm.. the 1.4.3 parser limitations would have to be addressed one by one in the VBA code, until 1.4.3 can parse it. Here's a completely non-exhaustive list:

 - Subscript access after a function call, e.g. `GetFoo(42)(1)` won't parse in 1.4.3; requires extracting a local variable for the function result first.
 - Combined (comma-separated) syntax for `Case` blocks won't parse in 1.4.3; requires splitting into multiple `Case` labels.
 - Instruction separator breaks the 1.4.3 parser (e.g. `Dim foo: foo = 42`); requires splitting into multiple lines.
 - Line continuations aren't supported everywhere in 1.4.3; can't remember where exactly, but for comparison purposes they're best avoided.
 - Precompiler constants break the 1.4.3 parser - they're simply not defined at all (yeah, an oversight), so there's not really any work-around.
 - Precompiler directives aren't handled very well with 1.4.3; better only leave the "live" code for the parser to intake.
 - Project-wide precompiler variables/constants aren't handled in either version.

There's definitely (lots) more than that, but that covers the most common parser failures of 1.4.3 I think.

The "race" shouldn't include code inspections; 2.0's should be faster anyway (better caching and lookups), but 2.0 also introduce 15 new inspections, which makes more code to run. Also at this point there's a number of resolver problems (although some of them seem to be new regression bugs that haven't shipped in 2.0.1a), which slows down the resolver a bit... and 2.0 is in a completely different league as far as resolving is concerned.

 - v1.4.3 resolver only works off user declarations (give or take 2K objects, in a rather large project), and is very, very, very inefficient. The built-in declarations it uses, are hard-coded - and there are less than 700. Identifier lookups are basically iterating *all* declarations. *Every time* an identifier needs to be looked up.
 - v2.0 resolver works off user *and* built-in declarations, acquired by iterating the actual referenced COM type libraries; it works off anywhere between 40K and 60K declarations, for *any* project, and is much, much, much, much more efficient than its predecessor. Identifier names are cached in a dictionary, so identifeir lookups are pretty much instant (O(1) complexity), and then only the matching names are iterated when the resolver looks for a match in a visible scope.

There's not really any way of "scientifically" timing the two - but running them against the same VBA code base on comparable hardware should *feel* much faster in 2.0 than 1.4.3; v2.0 has completed parsing/resolving when the status bar says "Inspecting..." (it actually says "Ready" a few milliseconds before that!); assuming no parser errors, v1.4.3 has completed parsing/resolving when the modal "Please wait" dialog is hidden, making the VBE available again.

A good way to trigger a reparse in 1.4.3, is to select the "find symbol" command - this (or any context menu command, actually) will trigger a reparse because 1.4.3 has no way of knowing whether the project was modified since the last parse - so it caches `VBComponent` instances and their corresponding parse tree, and only reparses a module when its contents' hashcode mismatches that of the cached instance.

In 2.0 the commands are only enabled when parser state is "ready", because we now know (with the win32 hooks) when a module can be marked as "dirty".. and we're no longer blocking the UI when we work, so the best way to see how long it takes, is to open up the macro-enabled document in Excel, *and then* bring up the VBE and load up Rubberduck; it will parse everything at startup; the "Loading references" step should be factored out, since it happens before any module gets parsed - that's when Rubberduck iterates all opened projects, fetches their references, loads the COM types, and creates the 40K declarations; the actual parsing begins immediately after that.

**Comment by PeterMTaylor** [comment] 2016-05-04 11:41
Makes sense, lots of possiblities. Where to start....
Ok fix the parser! then re-test both versions. 
I have been watching that a possible hotfix for version 2 is coming that may resolve the virus. 
Sounds good.
I have managed to resolve some parser errors tonite but stumped what the parser error is getting at now, see the snip.
![rb v1 4 3 parser error 1167 extraneous input if](https://cloud.githubusercontent.com/assets/2254567/15013053/682c8ab0-1240-11e6-84df-b69fe97ce1df.PNG)
what your seeing is the code sub XAct_Lock and the line number 1167 is at IF NOT XMap_LineofSight

Any ideas?

**Comment by retailcoder** [comment] 2016-05-04 12:06
Hmm.. not sure, but try extracting local variables for `XS.YX(1,0)` and `XS.YX(1,1)`.

**Comment by PeterMTaylor** [comment] 2016-05-14 11:25
ok @retailcoder! I confess to you humble sire! that the scope of my work I had being working with on exisiting 5K code is taking me more effort to do a simple straight forward test for discussion purposes. 

After re-re-re-re-reading what you meant by extracting local variables for XS.YX(1,0) the code base its not practical for me at the moment. So to this end, I went ahead and change the scope of this test with different VBA file that enables a better picture of comparsion.

The details and conclusion of this test are as follows:
* Have always uninstall old version before installing another 
* Running in 32-bit Excel 2010 on Windows 10 Intel i3-2100 CPU @ 3.10GHz 4GB RAM computer
* Exisiting code used is RoadmapGenerator.xlm credited and attritubed to Bruce McPherson
* I decided to use the real Github details of Rubberduck releases to present a Roadmap diagram.
* Project Summary details, basically 5K down to 3K codebase.
![capture project summary](https://cloud.githubusercontent.com/assets/2254567/15268031/ffe017d2-1a15-11e6-9e44-cceeea8054de.PNG)
* I learnt and managed these tests using Windows 10 Performance Monitor under a 5 min fixed time duration. Just enough to touch CPU, Disk and Memory info. Networking is out of scope for this.

The results/obersvations as follows of three tests.
![capture test results](https://cloud.githubusercontent.com/assets/2254567/15268043/9614d5a8-1a16-11e6-9099-6a96a28bdba0.PNG)

With test 2, got an error running v1.4.3 when I opened the Excel file with RD loaded.
![capture rd 1 4 3 error](https://cloud.githubusercontent.com/assets/2254567/15268106/1c20e0ce-1a17-11e6-98b7-f80a171b65ce.PNG)

With test 2, the 554 issues was suggested.
![capture rd 1 4 3 results](https://cloud.githubusercontent.com/assets/2254567/15268130/fc1ac280-1a17-11e6-9041-aeb7921c3ff3.PNG)

Now, with test 3, loading references kept going..going.. so I gave up waiting for over 4 mins then started the code inspection which gave up after 3 mins as it stuck on loading references.
![capture rd 2 0 1a pre reference](https://cloud.githubusercontent.com/assets/2254567/15268140/4bc9b520-1a18-11e6-8b4a-7096a465de14.PNG)
![capture rd 2 0 1a pre still processing](https://cloud.githubusercontent.com/assets/2254567/15268141/4bd645f6-1a18-11e6-83c1-485a4e1a2257.PNG)

Finally, to show the interesting thing, the roadmap regarding the history of releases rubberduck took, the length of the arrow bar could be a show of stable releases or more time fixing in betwen releases. You're welcome to look at my [repo](https://github.com/PeterMTaylor/RoadmapGenerator) if you want to see the excel file.

![capture rd roadmap](https://cloud.githubusercontent.com/assets/2254567/15268153/c9220be4-1a18-11e6-85a3-3e2c56eb7ccb.PNG)

Not sure why reference is take that longer to complete though.

**Comment by Hosch250** [comment] 2016-06-14 23:50
Is this going anywhere, or can it be closed?

**Comment by retailcoder** [comment] 2016-06-14 23:58
@PeterMTaylor that *loading references* stuck state was a resolver bug, fixed in the beta.

**Closed by retailcoder** 2016-06-14 23:58 UTC
Labels: discussion

**Comment by Vogel612** [comment] 2016-06-15 13:37
@retailcoder I'd still be interested in a performance comparison between 1.4.3 and 2.0.1b.
It would need a proper-ish benchmark to check what we managed to win by making the Parser asynchronous....
