### ISSUE TITLE
Comment in UDT is ignored

### ISSUE THREAD

**Issue by Stevefb** [rubberduck-vba/Rubberduck#3789] opened 2018-02-25 06:06 UTC
With ver: 2.1.2.2886

If I create a UDT like:

```
Private Type tX
    foo As String
    bar As Long
    'foobar as shouldNotBeVisible
End Type
```
then in the **code explorer** `foobar` shows up the same as `foo` and `bar`.

**Comment by Vogel612** [comment] 2018-02-25 14:09
Reproduced off next. Interestingly the following code does not reproduce the problem:

```
Private Type tX
    foo As String
    bar As Long
    'foobar
End Type
``` 

Additionally interesting: This only appears with the last comment. 

```
Private Type TestTypeWithCommentDeclaration
    foo As String
    bar As Long
    'foobar as check
    'apparently that's only in the last line as wtf
End Type
```

It also only appears when the comment "ends" with the "variable definition":

```
Private Type TestTypeWithCommentDeclaration
    foo As String
    bar As Long
    'asdf as check
    'baz as check
    'foobar as check with more text
End Type
```

This shows the members `foo`, `bar` and `baz`, not asdf though ...

**Comment by Vogel612** [comment] 2018-02-25 14:25
The underlying problem here is that the `endOfStatement` after every UDT Member will consume all text, including the **starting** apostrophe of the last line, but not correctly parse it as comment.

A solution must make sure that the `endOfStatement` does not incorrectly stop parsing comments.... Because that's a **huge** failure...

I'm pretty sure that this will only happen in user-defined types, though. I'm not sure whether it will also appear in public member types, but it might...

**Comment by Vogel612** [comment] 2018-02-25 14:27
While we're at: the current parser rules also imply that we do not parse annotations on user-defined type members as annotations... Which is somewhat problematic...

**Comment by Vogel612** [comment] 2018-02-25 15:14
So the "correct" fix for this is to change the definition of `commentBody` to enforce a finishing newline, as mandated by section 3.3.1 in the VBA Language Spec like so:

```
// commentBody must terminate with a NEWLINE, see VBA Language spec, section 3.3.1 and 3789
commentBody : (LINE_CONTINUATION | ~NEWLINE)* NEWLINE; 
```

Unfortunately this has widespread implications around the whole grammar, resulting in around 50 parse failures in unrelated tests, as well as 8 failures *after* fixing the tests that incorrectly assume that comments do not in fact need to end with a newline...

**Comment by MDoerner** [comment] 2018-02-26 12:20
I think there is one exception to the rule that a comment must end with a newline: an `EoF` should be legal as well.

**Comment by MDoerner** [comment] 2018-02-26 12:40
After having a short look at the grammar, the actual culprit here is `udtMemberList` currently defined as `udtMember (endOfStatement udtMember)*`. This means that the last statement in the member list cannot be a comment. We try to match this in the surrounding rule but the inner rule always has precedence. 

The rule should rather be `(udtMember endOfStatement)+`,  which requires that the last `endOfStatement` in `udtDeclaration` gets removed.

**Comment by Vogel612** [comment] 2018-02-26 16:55
Re EOF: while not directly mentioned in the VBAL that is included in the Grammr change in the PR.

I will adjust the PR with the proposed solution later today

**Closed** 2018-02-27 13:15 UTC
Labels: bug, difficulty-03-duck
