### ISSUE TITLE
Fatal Error opening MSProject VBE, Crashes in flames

### ISSUE THREAD

**Issue by ThunderFrame** [rubberduck-vba/Rubberduck#1685] opened 2016-06-03 15:54 UTC
MSProject loads with a blank project and a `Global.mpt` project. Opening Project leads to the VBE appearing briefly, before:

> System.Runtime.InteropServices.COMException occurred
  _HResult=-2147417846
  _message=The message filter indicated that the application is busy. (Exception from HRESULT: 0x8001010A (RPC_E_SERVERCALL_RETRYLATER))
  HResult=-2147417846
  IsTransient=false
  Message=The message filter indicated that the application is busy. (Exception from HRESULT: 0x8001010A (RPC_E_SERVERCALL_RETRYLATER))
  ErrorCode=-2147417846
  InnerException: 

on this line in `RubberduckModule.cs`:

```
Bind<Func<IVBAPreprocessor>>().ToMethod(p => () => new VBAPreprocessor(double.Parse(_vbe.Version, CultureInfo.InvariantCulture)));
```
Followed by some AggregateExceptions, and then more exceptions and then....

death.

**Comment by retailcoder** [comment] 2016-06-03 15:57
Looks like we **really** need to mitigate the `HOST_IS_BUSY` issue. This is caused by COM having a hard time keeping up with requests coming from multiple threads.

**Comment by Hosch250** [comment] 2016-06-03 15:57
Dupe of https://github.com/rubberduck-vba/Rubberduck/issues/1414

**Closed** 2016-06-03 15:58 UTC
Labels: bug, critical, duplicate
