### ISSUE TITLE
Annotations

### ISSUE THREAD

**Issue by pcarnet** [rubberduck-vba/Rubberduck#6138] opened 2023-07-22 05:24 UTC
Can not add some annotations, for example, ModuleDescription: there is no way to add (write) the description.

**Comment by Crazylegs85** [comment] 2023-09-18 15:33
Hi there...generally for the annotations you have to enclose the description in parenthesis and quotation marks.
```
'@ModuleDescription("Description of the module's purpose")
```

Have you had a look at the [annotations documentation](https://github.com/rubberduck-vba/Rubberduck/wiki/VB_Attribute-Annotations)?

**Comment by MDoerner** [comment] 2023-10-21 21:40
I will close this as a duplicate of #6162, although that is actually the duplicate of this issue. However, the description there better conveys what the problem is.

**Closed as not planned by MDoerner** 2023-10-21 21:40 UTC
Labels: duplicate
