### ISSUE TITLE
ComInterface ignores property-list of dispinterfaces.

### ISSUE THREAD

**Issue by robodude666** [rubberduck-vba/Rubberduck#3353] opened 2017-09-04 22:08 UTC
It appears that `ComInterface` does not look at "properties" defined by a [dispinterface](https://msdn.microsoft.com/en-us/library/windows/desktop/aa366802(v=vs.85).aspx):
```
[
    [attributes]
]
dispinterface dispinterface-name
{
    properties:
        property-list
    methods:
        method-list
};
```

This seems due to the fact it only looks at `FUNCDESC` records. The "properties" section is what [`ComModule`](https://github.com/rubberduck-vba/Rubberduck/blob/next/Rubberduck.Parsing/ComReflection/ComInterface.cs#L76) considers as "Fields" (and are stored as `VARDESC` records).

While it is certainly confusing being able to define properties in two places, Microsoft does claim it is legal:
>You can declare properties in either the properties or methods lists.

By not importing both "Fields" and "Members" we're potentially missing a lot of an interface's capabilities.

**Comment by robodude666** [comment] 2017-09-04 22:09
Would there be any better solution besides adding a `Fields` member to `ComInterface`/`ComMember` ? Looking through the docs of `VARDESC` and `FUNCDESC` they seem different enough that it may be challenging (i.e. messy) maintaining only a single class that's capable of importing from both structures.

**Comment by ThunderFrame** [comment] 2017-09-04 22:32
Duplicate of #3326

**Closed** 2017-11-25 00:09 UTC
Labels: bug, duplicate, feature-reference-explorer
