### ISSUE TITLE
"Move closer to usage" QuickFix wrecks the code

### ISSUE THREAD

**Issue by Stevefb** [rubberduck-vba/Rubberduck#3259] opened 2017-08-15 04:21 UTC
The following code is majorly cut down and modified but still produces the same issues as my original code.  Two of other issues can be reproduced by a simpler example see: #3257 & #3258  

Here the issues are Quick Fix for moving to a smaller scope:
 - introduces a random line
 - modifies Select Case
 - modifies Case 

Steps to reproduce (MS Word 2010, RD v2.1.2057) in an otherwise blank document add a standard module with:
```
Option Explicit

Private aRange1 As Word.Range
Private arrExample2() As String

Private Sub duckOuttaLuck()

    ReDim arrExample2(0 To 1)
    arrExample2(0) = "3"
                             
    Set aRange1 = ActiveDocument.Paragraphs(1).Range
                             
    ActiveDocument.Fields(arrExample2(lngIndex, 0)).Update
        
    Select Case ActiveDocument.Bookmarks("xxxxxx" & arrExample2(0, 0)).Range.Fields(1).result
        Case aRange1.ListFormat.ListString
            Debug.Print "aRange1"

    End Select

End Sub
```
Run code inspection, click on `Move module-level variable to smaller scope`: 
```
Option Explicit

Private Sub duckOuttaLuck()

    Dim arrExample2 As String                   ' see #3258
    ReDim arrExample2(0 To 1)
    arrExample2(0) = "3"
                             
    Dim aRange1 As Word.Range
    Set aRange1 = ActiveDocument.Paragraphs(1).Range
                             
    arrExample2                                 ' Random line
        
    Select Case arrExample2.Fields(1).result    ' was: ActiveDocument.Bookmarks("xxxxxx" & arrExample2(0, 0)).Range.Fields(1).result
        Case aRange1.ListString                 ' missing .ListFormat
            Debug.Print "aRange1"

    End Select

End Sub
```

**Comment by retailcoder** [comment] 2017-08-16 18:15
Closing as a duplicate of #3257

**Closed by retailcoder** 2017-08-16 18:15 UTC
Labels: bug, duplicate, feature-inspections, feature-refactorings
