### ISSUE TITLE
Repeatedly clicking the "Fix" dropdown in code inspections breaks the VBE

### ISSUE THREAD

**Issue by ckuhn203** [rubberduck-vba/Rubberduck#621] opened 2015-06-14 07:03 UTC
No, seriously. It really does break the VBE. You can't open the menus or type in the code pane.

Repro:
1. Open Code Inspections.
2. Repeatedly and quickly click on the "Fix" dropdown arrow.
3. Try to open a menu on the menu bar.
4. Repeat as necessary.

You can see this happen [in this screencast @Rossco created](https://www.youtube.com/watch?v=SCKjD3k8vH8). I've independently reproduced this.

**Comment by Hosch250** [comment] 2015-06-14 19:29
I just duplicated this too, and I couldn't yesterday.

**Comment by Hosch250** [comment] 2015-06-14 20:39
I can't duplicate this any more.  @ckuhn203 @RossKnudsen please reopen if this doesn't fix the issue.

**Comment by rossknudsen** [comment] 2015-06-26 23:56
@Hosch250 Last time I checked, I still had this problem.  I didn't re-open this bug because I'm not sure if its just me.  I suggest that you get confirmation from someone else, since you can't reproduce.  It makes it hard to fix a bug when you can't reproduce it yourself.  Also this bug is reasonably easy to avoid in the meantime.

At some point I plan on reinstalling my machine, as I have some issues which may be contributing.  I'll be more confident in reporting the issue then.

**Comment by retailcoder** [comment] 2015-06-26 23:58
This issue is closed because it's fixed in next release - button is
disabled after clicking, and only re-enabled when application is ready to
handle it :)

Sent from my Samsung mobile

**Comment by retailcoder** [comment] 2015-06-27 00:00
Wait, it's still opened? WTF?

**Comment by ckuhn203** [comment] 2015-06-27 00:04
@retailcoder I don't know how it got reopened. Last I checked I the fix Hosch put in had fixed it. No repro, but now I feel like we need to confirm it.

**Comment by Hosch250** [comment] 2015-12-24 20:41
What is this doing open still?

**Comment by retailcoder** [comment] 2015-12-24 20:42
@Hosch250 No idea!

**Closed by retailcoder** 2015-12-24 20:42 UTC
Labels: bug, code-inspections, user-interface
