### ISSUE TITLE
Code Inspections window refresh button intermittently not clickable

### ISSUE THREAD

**Issue by connerk** [rubberduck-vba/Rubberduck#2194] opened 2016-08-17 22:51 UTC
build 2.0.8.23905 (MSIL)

* hovering does not generate a hover action
* symptom occurs with window docked or not

**Comment by retailcoder** [comment] 2016-08-17 23:59
That's sort-of by design; the button is disabled (but the icon doesn't get grayed out for some reason) if requesting a reparse wouldn't do anything because nothing changed in any module since the last parse - although, I'm starting to think that was a mistake. @Hosch250 thoughts?

**Comment by Hosch250** [comment] 2016-08-18 00:14
I never liked that.  I thought it was a mistake from the start--especially clicking doesn't have any response since our parser checks whether there were any changes before starting.

**Comment by connerk** [comment] 2016-08-18 14:07
I can see not re-parsing if RD knows nothing is different. From a UX perspective it feels broken when a button does nothing but is present. 
Even if it were to re-parse when RD knows there's no changes it's comforting to the user to be able to feel confident that the list is up to date. Quells the OCD in all of us:grey_exclamation:

**Comment by retailcoder** [comment] 2016-08-18 14:33
Alright, let's revert this.

**Comment by retailcoder** [comment] 2016-09-04 07:00
Fixed with PR #2214

**Closed by retailcoder** 2016-09-04 07:00 UTC
Labels: enhancement, user-interface
