### ISSUE TITLE
COM Error when closing 2 Excel files in rapid sucession

### ISSUE THREAD

**Issue by daFreeMan** [rubberduck-vba/Rubberduck#2533] opened 2017-01-13 20:53 UTC
Excel 2010 RD 2.0.11

I frequently get interrupted to look something up in a spreadsheet while I'm busy working on some VBA code for a different spreadsheet. (PHI data - limited access to it).

This has happened a couple of times over the last couple of days, and each time, I've received this error when closing the 2nd of the new files I've opened:
![rd com error - quick file close](https://cloud.githubusercontent.com/assets/11889733/21945167/c22b5b20-d9a7-11e6-8305-8ea27f36d056.PNG)

I'll have an .XLSM open with the IDE open. I'll open another couple of workbooks (of various formats) and/or .CSVs, look up the relevant information and reply. When I'm done, I hit <kbd>Ctrl-F4</kbd> (then <kbd>N</kbd> if necessary to not save the changes) on each of the newly opened files to get them out of my way. I get that error after hitting <kbd>Ctrl-F4</kbd> on the 2nd file. 

My theory is that RD has started refreshing itself on file close (a welcome addition!), then pukes when Excel closes a file that it's attempting to parse (or was, at least, queued to parse). 

[RubberduckLog.txt](https://github.com/rubberduck-vba/Rubberduck/files/705298/RubberduckLog.txt)

I end up (at least this time) with a Resolver error, and Excel is not responding.

Attempting to close out (saving as appropriate) all my workbooks to close Excel & get a clean start, I received this message:
![rd com error - quick file close mem error](https://cloud.githubusercontent.com/assets/11889733/21945377/f12f67f8-d9a8-11e6-8666-e3a76f3d99ab.PNG)

The updated log after clicking OK on that message:
[RubberduckLog.txt](https://github.com/rubberduck-vba/Rubberduck/files/705310/RubberduckLog.txt)

Finally, after closing the last workbook & exiting Excel, Excel crashed on closing then restarted itself with a blank workbook

**Comment by retailcoder** [comment] 2017-01-13 21:09
Definitely involves parse task cancellation.

**Comment by daFreeMan** [comment] 2017-01-13 21:20
Short term workaround: remember to wait until the reparse is finished before closing the next file.
Likely course of action: continue to quickly close files, generate errors, then mutter under my breath.

**Comment by retailcoder** [comment] 2017-01-13 21:28
Mid-term workaround: introduce a toggle button on the RD commandbar to manually activate/deactivate the `VBComponents` and `VBProjects` event handling, which is what's triggering the reparse here.

**Comment by daFreeMan** [comment] 2017-01-13 21:43
And the likelihood of me remembering to hit that toggle before closing out files after I've been interrupted for the 5th time today with some irritating question about something that was sent out 4 months ago is: Zero.

But others may be more on the ball than I am...

**Comment by ThunderFrame** [comment] 2017-01-13 21:46
Short term workaround: close the files programmatically. Refresh shouldn't fire if code is running.

**Comment by comintern** [comment] 2017-01-13 21:52
The second error is an access violation originating in the Hotkey handler:

`2017-01-13 15:54:29.6653;ERROR-2.0.11.2453;Rubberduck.Common.WinAPI.RawInput;Error sizing the rawinput buffer: The handle is invalid;System.ComponentModel.Win32Exception (0x80004005): The handle is invalid`

I'm also a bit puzzled by why `App` is handling 2 back to back state changes here...
```
2017-01-13 15:35:57.3110;DEBUG-2.0.11.2453;Rubberduck.App;App handles StateChanged (ResolverError), evaluating menu states...;
2017-01-13 15:35:57.3671;DEBUG-2.0.11.2453;Rubberduck.App;App handles StateChanged (ResolverError), evaluating menu states...;
```
...and doubling up on the click handler here (note the different hash codes):
```
2017-01-13 15:54:38.0831;DEBUG-2.0.11.2453;Rubberduck.UI.Command.MenuItems.CommandBars.AppCommandBarBase;(49526440) Executing click handler for commandbar item 'Resolver Error', hash code 1980527;
2017-01-13 15:55:22.3445;DEBUG-2.0.11.2453;Rubberduck.UI.Command.MenuItems.CommandBars.AppCommandBarBase;(49526440) Executing click handler for commandbar item 'Resolver Error', hash code 23137511;
```
Did you have 2 RDs open when this happened?

**Comment by daFreeMan** [comment] 2017-01-16 13:40
@comintern - I may possibly have had Access open with the VBE open at that time, but it had happened several times during the later part of last week, and I'm pretty certain that I didn't have Access open the whole time. This was just the one opportunity that I had to capture the error and get it reported. 

I did **not** have 2 instances of Excel running, each with their own VBE open. I just discovered, however that this is possible. I'll just be nice and presume ('cause we all know what happens when you _assume_) that this condition has been tested and RD handles it well. ;)

**Comment by comintern** [comment] 2017-01-16 13:49
Generous presumption :looks for multi-ducking tag:.  May or may not be the entirety of the issue, but Linking #2493

**Comment by daFreeMan** [comment] 2017-01-26 13:46
I just got this error when closing _one_ xlsx while having another one open. I did _not_ close 2 files in rapid succession...
[RubberduckLog.txt](https://github.com/rubberduck-vba/Rubberduck/files/732400/RubberduckLog.txt)

**Comment by comintern** [comment] 2017-01-26 13:57
Hotkeys again:
```
2017-01-26 08:41:16.7458;ERROR-2.0.11.2453;Rubberduck.Common.WinAPI.RawInput;Error sizing the rawinput buffer: The handle is invalid;System.ComponentModel.Win32Exception (0x80004005): The handle is invalid
2017-01-26 08:41:18.7220;ERROR-2.0.11.2453;Rubberduck.Common.WinAPI.RawInput;Error sizing the rawinput buffer: The handle is invalid;System.ComponentModel.Win32Exception (0x80004005): The handle is invalid
2017-01-26 08:41:18.9540;ERROR-2.0.11.2453;Rubberduck.Common.WinAPI.RawInput;Error sizing the rawinput buffer: The handle is invalid;System.ComponentModel.Win32Exception (0x80004005): The handle is invalid
2017-01-26 08:41:19.1541;ERROR-2.0.11.2453;Rubberduck.Common.WinAPI.RawInput;Error sizing the rawinput buffer: The handle is invalid;System.ComponentModel.Win32Exception (0x80004005): The handle is invalid
2017-01-26 08:41:19.9701;ERROR-2.0.11.2453;Rubberduck.Common.WinAPI.RawInput;Error sizing the rawinput buffer: The handle is invalid;System.ComponentModel.Win32Exception (0x80004005): The handle is invalid
2017-01-26 08:41:20.7382;ERROR-2.0.11.2453;Rubberduck.Common.WinAPI.RawInput;Error sizing the rawinput buffer: The handle is invalid;System.ComponentModel.Win32Exception (0x80004005): The handle is invalid
```
For some reason it also looks like 3 ducks in the air this time:
```
2017-01-26 08:45:53.7825;TRACE-2.0.11.2453;Rubberduck.UI.Inspections.InspectionResultsViewModel+<RefreshInspections>d__35;Inspections loaded in 333696ms;
2017-01-26 08:46:15.7487;TRACE-2.0.11.2453;Rubberduck.UI.Inspections.InspectionResultsViewModel+<RefreshInspections>d__35;Inspections loaded in 344258ms;
2017-01-26 08:46:35.9717;TRACE-2.0.11.2453;Rubberduck.UI.Inspections.InspectionResultsViewModel+<RefreshInspections>d__35;Inspections loaded in 322598ms;
```

**Comment by bclothier** [comment] 2018-04-06 19:16
I tried this 3 times with recent version and only once got zombified process. However, this may have to do the fact that the first time I did it, I had to enable contents because you know, "trust issues". 

Once they were trusted, I could exit cleanly, closing 3 macro-heavy workbook in rapid succession.

Please re-open if this can be reproduced reliably.

**Closed by bclothier** 2018-04-06 19:16 UTC
Labels: bug, parse-tree-processing
