### ISSUE TITLE
Rubberduck stuck on "Pending" Status.. Sub menu disabled

### ISSUE THREAD

**Issue by ishita799** [rubberduck-vba/Rubberduck#3033] opened 2017-05-24 04:34 UTC
![issue](https://cloud.githubusercontent.com/assets/22786555/26353040/f6165c2e-3fdb-11e7-93e9-eb3cacd549ed.png)

Rubberduck is not working properly. 
Sub menus are disabled(Greyed out). 
"Pending" button is stuck.

Thank you in advance!

**Comment by ThunderFrame** [comment] 2017-05-24 04:41
Have you clicked on the Refresh icon next to the Pending button, in order to trigger the parse?

**Comment by ishita799** [comment] 2017-05-24 04:51
Yes, I have tried clicking it many times!
But nothing happens!
It is stuck on "Pending".

**Comment by Inarion** [comment] 2017-05-24 06:50
Can you reproduce the issue after restarting Excel? If so, you should activate logging (set to TRACE) from the Rubberduck options menu. The log file might shed some light on what is happening.

**Comment by ishita799** [comment] 2017-05-24 08:34
Now the Pending state has been changed to Parse Error..
This is the log file!

[RubberduckLog.txt](https://github.com/rubberduck-vba/Rubberduck/files/1024868/RubberduckLog.txt)

**Comment by Vogel612** [comment] 2017-05-24 12:07
Exception from the log:

```
2017-05-24 14:02:09.3969;ERROR-2.0.13.32288;Rubberduck.Parsing.VBA.ParseCoordinator;Unexpected exception thrown in parsing run. (thread 8).;System.InvalidCastException: Unable to cast COM object of type 'System.__ComObject' to interface type 'Microsoft.Vbe.Interop.VBE'. This operation failed because the QueryInterface call on the COM component for the interface with IID '{0002E166-0000-0000-C000-000000000046}' failed due to the following error: Error loading type library/DLL. (Exception from HRESULT: 0x80029C4A (TYPE_E_CANTLOADLIBRARY)).
   at System.StubHelpers.StubHelpers.GetCOMIPFromRCW(Object objSrc, IntPtr pCPCMD, IntPtr& ppTarget, Boolean& pfNeedsRelease)
   at Microsoft.Vbe.Interop.VBE.get_VBProjects()
   at Rubberduck.VBEditor.SafeComWrappers.VBA.VBE.get_VBProjects() in C:\Users\Mathieu\Documents\GitHub\Rubberduck (main)\Rubberduck\Rubberduck.VBEEditor\SafeComWrappers\VBA\VBE.cs:line 88
   at Rubberduck.Parsing.VBA.RubberduckParserState.RefreshProjects(IVBE vbe) in C:\Users\Mathieu\Documents\GitHub\Rubberduck (main)\Rubberduck\Rubberduck.Parsing\VBA\RubberduckParserState.cs:line 242
   at Rubberduck.Parsing.VBA.ParseCoordinator.ParseAllInternal(Object requestor, CancellationToken token) in C:\Users\Mathieu\Documents\GitHub\Rubberduck (main)\Rubberduck\Rubberduck.Parsing\VBA\ParseCoordinator.cs:line 705
   at Rubberduck.Parsing.VBA.ParseCoordinator.ParseAll(Object requestor, CancellationToken token) in C:\Users\Mathieu\Documents\GitHub\Rubberduck (main)\Rubberduck\Rubberduck.Parsing\VBA\ParseCoordinator.cs:line 682
```

**Comment by ishita799** [comment] 2017-05-25 05:14
I am using Rubberduck inside corporate environment. I tried installing it on my colleague's PC and was successful.  **Can you please provide detailed resolution regarding the exception you pointed.**

"System.InvalidCastException: Unable to cast COM object of type 'System.__ComObject' to interface type 'Microsoft.Vbe.Interop.VBE'. This operation failed because the QueryInterface call on the COM component for the interface with IID '{0002E166-0000-0000-C000-000000000046}' failed due to the following error: Error loading type library/DLL. 

Why is installation failing on some machines and not others, is there any specific dependency on machine configuration.

**Comment by retailcoder** [comment] 2017-05-25 13:42
That exception essentially says the `Microsoft.Vbe.Interop` assembly couldn't be loaded. Not sure how that could happen, although I *did* see contributors having problems with that library *when setting up the project for a debug build*... not sure how that happens in a release build, but one thing strikes me in your screenshot:

![image](https://cloud.githubusercontent.com/assets/5751684/26452451/050e52ce-412e-11e7-82bf-d7ebf19b1c78.png)

These no-name modules in the VBE's *Project Explorer* aren't normal, and typically weird stuff going on in the project explorer indicate a somehow corrupt VBA project.

I'd give it a shot with an empty workbook.

**Comment by ishita799** [comment] 2017-05-26 04:15
No!Actually it is the company data so i have to hide the names of the modules and everything!
It's not a corrupt project.. 
And I have tried running Rubberduck in an empty workbook also. That didn't work also.

**Comment by retailcoder** [comment] 2017-05-29 15:45
@ishita799 can you expand a bit on exactly what you mean with "'Pending' button is stuck"? Does clicking it not do anything?

**Comment by ishita799** [comment] 2017-06-08 09:47
Clicking on it does not do anything.
I understand that in an empty workbook, it should work but it is stuck on "Pending" status only. Clicking on it does not even change to "Loading declarations" or to any other state.

**Comment by retailcoder** [comment] 2017-06-08 11:56
The only thing I'm seeing would be some glitch with the reference to the VBIDE API library... I seem to recall having issues with that specific reference at one point, but AFAICT the current build doesn't. The weird part is that it works on most installs... Try re-installing?

**Comment by PaulWalkerUK** [comment] 2017-07-26 15:10
Just to let you know, I'm getting the same issue on a new Windows 10 64-bit machine, running Excel 2007 32-bit and RD 2.0.13. This is from my log file when I click the "refresh" button:

```
2017-07-26 15:41:18.9627;INFO-2.0.13.32288;Rubberduck.App;Rubberduck version 2.0.13.32288 loading:
	Operating System: Microsoft Windows NT 6.2.9200.0 x64
	Host Product: 2007 Microsoft Office system x86
	Host Version: 12.0.6771.5000
	Host Executable: EXCEL.EXE;
2017-07-26 15:41:19.3914;INFO-2.0.13.32288;DynamicInjectorecbb804698af418098b925a7c4c1f589;Executing version check.;
2017-07-26 15:41:26.2593;DEBUG-2.0.13.32288;Rubberduck.UI.Command.MenuItems.CommandBars.AppCommandBarBase;(43084780) Executing click handler for commandbar item 'Pending', hash code 39717249;
2017-07-26 15:41:26.2784;DEBUG-2.0.13.32288;Rubberduck.Parsing.VBA.ParseCoordinator;Parsing run started. (thread 6).;
2017-07-26 15:41:26.3406;ERROR-2.0.13.32288;Rubberduck.Parsing.VBA.ParseCoordinator;Unexpected exception thrown in parsing run. (thread 6).;System.InvalidCastException: Unable to cast COM object of type 'System.__ComObject' to interface type 'Microsoft.Vbe.Interop.VBE'. This operation failed because the QueryInterface call on the COM component for the interface with IID '{0002E166-0000-0000-C000-000000000046}' failed due to the following error: Error loading type library/DLL. (Exception from HRESULT: 0x80029C4A (TYPE_E_CANTLOADLIBRARY)).
   at System.StubHelpers.StubHelpers.GetCOMIPFromRCW(Object objSrc, IntPtr pCPCMD, IntPtr& ppTarget, Boolean& pfNeedsRelease)
   at Microsoft.Vbe.Interop.VBE.get_VBProjects()
   at Rubberduck.VBEditor.SafeComWrappers.VBA.VBE.get_VBProjects() in C:\Users\Mathieu\Documents\GitHub\Rubberduck (main)\Rubberduck\Rubberduck.VBEEditor\SafeComWrappers\VBA\VBE.cs:line 88
   at Rubberduck.Parsing.VBA.RubberduckParserState.RefreshProjects(IVBE vbe) in C:\Users\Mathieu\Documents\GitHub\Rubberduck (main)\Rubberduck\Rubberduck.Parsing\VBA\RubberduckParserState.cs:line 242
   at Rubberduck.Parsing.VBA.ParseCoordinator.ParseAllInternal(Object requestor, CancellationToken token) in C:\Users\Mathieu\Documents\GitHub\Rubberduck (main)\Rubberduck\Rubberduck.Parsing\VBA\ParseCoordinator.cs:line 705
   at Rubberduck.Parsing.VBA.ParseCoordinator.ParseAll(Object requestor, CancellationToken token) in C:\Users\Mathieu\Documents\GitHub\Rubberduck (main)\Rubberduck\Rubberduck.Parsing\VBA\ParseCoordinator.cs:line 682
2017-07-26 15:41:26.3466;DEBUG-2.0.13.32288;Rubberduck.Parsing.VBA.RubberduckParserState;RubberduckParserState raised StateChanged (Error);
2017-07-26 15:41:32.8393;DEBUG-2.0.13.32288;Rubberduck.UI.Command.MenuItems.ParentMenus.ParentMenuItemBase;(34745524) Executing click handler for menu item 'S&ettings', hash code 45207585;
```

For me, I can't get RubberDuck to do anything at all. When I click the button, nothing happens (apart from this log being generated) and most of the menu options, eg "Rename", "Extract Interface", are greyed out (I assume because it hasn't been able to complete a parse), though the "Settings" and "About" options work fine. I also get the splash screen when opening up the editor. There was nothing to indicate a problem during the install. I've reinstalled RD several times - same result.

Note that I did have this working on a previous Windows 7 64-bit machine with Excel 2007 32-bit though I don't remember what version of RD that was. I don't _recall_ having any difficulties getting that working, but it was a while ago...

**Comment by PaulWalkerUK** [comment] 2017-07-26 15:30
I just tried the latest "pre-release" version (v2.1.2003). Same result when trying to parse:

```
2017-07-26 16:25:54.3734;TRACE-2.0.14.33947;Rubberduck.Common.LogLevelHelper;
	Rubberduck version 2.0.14.33947 loading:
	Operating System: Microsoft Windows NT 6.2.9200.0 x64
	Host Product: 2007 Microsoft Office system x86
	Host Version: 12.0.6771.5000
	Host Executable: EXCEL.EXE;
2017-07-26 16:25:54.3840;TRACE-2.0.14.33947;Rubberduck.App;Checking for legacy Smart Indenter settings.;
2017-07-26 16:25:54.6317;INFO-2.0.14.33947;DynamicInjectoraf19b2b9adcf4b5e9c37ce9fca39bfea;Executing version check.;
2017-07-26 16:26:10.4718;DEBUG-2.0.14.33947;Rubberduck.UI.Command.MenuItems.CommandBars.AppCommandBarBase;(22483623) Executing click handler for commandbar item 'Pending', hash code 22122153;
2017-07-26 16:26:10.4918;DEBUG-2.0.14.33947;Rubberduck.Parsing.VBA.ParseCoordinator;Parsing run started. (thread 8).;
2017-07-26 16:26:10.4918;INFO-2.0.14.33947;Rubberduck.Parsing.VBA.RubberduckParserState;RubberduckParserState (1) is invoking StateChanged (Pending);
2017-07-26 16:26:10.4998;ERROR-2.0.14.33947;Rubberduck.Parsing.VBA.ParseCoordinator;Unexpected exception thrown in parsing run. (thread 8).;System.InvalidCastException: Unable to cast COM object of type 'System.__ComObject' to interface type 'Microsoft.Office.Core.CommandBarControl'. This operation failed because the QueryInterface call on the COM component for the interface with IID '{000C0308-0000-0000-C000-000000000046}' failed due to the following error: Library not registered. (Exception from HRESULT: 0x8002801D (TYPE_E_LIBNOTREGISTERED)).
   at System.StubHelpers.StubHelpers.GetCOMIPFromRCW(Object objSrc, IntPtr pCPCMD, IntPtr& ppTarget, Boolean& pfNeedsRelease)
   at Microsoft.Office.Core.CommandBarControl.set_Enabled(Boolean pvarfEnabled)
   at Rubberduck.VBEditor.SafeComWrappers.Office.Core.CommandBarControl.set_IsEnabled(Boolean value) in C:\projects\rubberduck\Rubberduck.VBEEditor\SafeComWrappers\Office.Core\CommandBarControl.cs:line 40
   at Rubberduck.UI.Command.MenuItems.CommandBars.AppCommandBarBase.EvaluateCanExecute(RubberduckParserState state) in C:\projects\rubberduck\RetailCoder.VBE\UI\Command\MenuItems\CommandBars\AppCommandBarBase.cs:line 100
   at Rubberduck.UI.Command.MenuItems.CommandBars.RubberduckCommandBar.OnParserStateChanged(Object sender, EventArgs e) in C:\projects\rubberduck\RetailCoder.VBE\UI\Command\MenuItems\CommandBars\RubberduckCommandBar.cs:line 90
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at Rubberduck.Parsing.VBA.RubberduckParserState.OnStateChanged(Object requestor, ParserState state) in C:\projects\rubberduck\Rubberduck.Parsing\VBA\RubberduckParserState.cs:line 329
   at Rubberduck.Parsing.VBA.RubberduckParserState.SetStatusAndFireStateChanged(Object requestor, ParserState status) in C:\projects\rubberduck\Rubberduck.Parsing\VBA\RubberduckParserState.cs:line 553
   at Rubberduck.Parsing.VBA.ParserStateManagerBase.SetStatusAndFireStateChanged(Object requestor, ParserState status, CancellationToken token) in C:\projects\rubberduck\Rubberduck.Parsing\VBA\ParserStateManagerBase.cs:line 51
   at Rubberduck.Parsing.VBA.ParseCoordinator.ParseAllInternal(Object requestor, CancellationToken token) in C:\projects\rubberduck\Rubberduck.Parsing\VBA\ParseCoordinator.cs:line 331
   at Rubberduck.Parsing.VBA.ParseCoordinator.ParseAll(Object requestor, CancellationToken token) in C:\projects\rubberduck\Rubberduck.Parsing\VBA\ParseCoordinator.cs:line 304
2017-07-26 16:26:10.4998;INFO-2.0.14.33947;Rubberduck.Parsing.VBA.RubberduckParserState;RubberduckParserState (2) is invoking StateChanged (Error);
```

**Comment by MDoerner** [comment] 2017-07-26 16:15
Somehow we seem to not be able to load some libraries.

@PaulWalkerUK Which .Net version do you have installed?

**Comment by PaulWalkerUK** [comment] 2017-07-26 16:37
According to the "registry" method described on Microsoft's "[How to: Determine Which .NET Framework Versions Are Installed](https://docs.microsoft.com/en-us/dotnet/framework/migration-guide/how-to-determine-which-versions-are-installed)", I seem to have:

- 2.0
- 3.0
- 3.5
- 4.0
- 4.7

Having said that, I don't mind trying to (re)install if there's a particular version I need

**Comment by retailcoder** [comment] 2017-07-26 16:48
Huh, looks like an exception was thrown trying to disable a commandbar button, in reaction to parser state changing to 'Pending'.

The end result is the same, but the cause is different. 2.0.13 was somehow failing to get the projects collection from the VBE; latest build seems to fail with a commandbar. God I hate these stupid random COM exceptions...

.net framework seems in order, RD runs off CLR 4.0.

**Comment by PaulWalkerUK** [comment] 2017-07-27 09:17
... and just to be sure, I tried running the .NET 4.0 installer, but I got this:

```
1. Microsoft .NET Framework 4 is already a part of this operating system.  You do not need to install the .NET Framework 4 redistributable. <A HREF="http://go.microsoft.com/fwlink/?LinkId=164207">More information</A>. 

2. Same or higher version of .NET Framework 4 has already been installed on this computer.
```

Is there anything I can do to try to collect any more details for you?

**Comment by PaulWalkerUK** [comment] 2017-08-18 14:15
Just an update from my specific occurrence... I've been upgraded to Office 365 and it's now working (I don't know whether any other patches, etc have been applied as well in the interim).

**Comment by retailcoder** [comment] 2017-08-18 14:19
@PaulWalkerUK sounds like there was a problem with the Office or VBIDE interop type library; upgrading Office would have repaired it.. makes sense. Thanks for the update!

**Comment by casey-little** [comment] 2017-11-01 19:53
I have the same issue. Mine error is associated with the commandbar object:

>2017-11-01 14:36:39.2780;ERROR-2.1.0.2382;Rubberduck.Parsing.VBA.ParseCoordinator;Unexpected exception thrown in parsing run. (thread 7).;System.InvalidCastException: Unable to cast COM object of type 'System.__ComObject' to interface type 'Microsoft.Office.Core.CommandBarControl'. This operation failed because the QueryInterface call on the COM component for the interface with IID '{000C0308-0000-0000-C000-000000000046}' failed due to the following error:  could not be found. (Exception from HRESULT: 0x80030002 (STG_E_FILENOTFOUND)).

If you click the update button the text remains "Pending". However, if you open/close the settings window, the refresh button text will change to display "Parse Error"

**Comment by retailcoder** [comment] 2017-11-01 21:41
@casey-little are you running multiple versions of Office side by side? If they weren't installed in chronological order (per Microsoft), it could very well be the cause of such interop problems.

For example if you had Office 2013 installed, and then installed Access 2010, your Office install gets broken.

This unfortunately isn't something we can do anything about, other than gracefully handling the exceptions.

**Comment by sushrut91** [comment] 2018-04-30 21:33
I tried rubber duck in Corel Draw X7 VBE today. Facing the same issue. My exception is with command bar too as follows:

`2018-04-30 17:19:45.9533;INFO-2.2.6672.28001;Rubberduck.Parsing.VBA.RubberduckParserState;RubberduckParserState (4) is invoking StateChanged (UnexpectedError);
2018-04-30 17:19:52.6104;TRACE-2.2.6672.28001;Rubberduck.VBEditor.SafeComWrappers.Office.Core.CommandBarButton;Executing handler for: CommandBar 'Code Metrics' (tag: Custom Popup 13025890::ToolsMenu::CodeMetricsCommandMenuItem, hashcode:64076263);
2018-04-30 17:19:52.6104;DEBUG-2.2.6672.28001;Rubberduck.UI.Command.MenuItems.ParentMenus.ParentMenuItemBase;(21985640) Executing click handler for menu item 'Code Metrics', hash code 61249726;
2018-04-30 17:19:52.6260;TRACE-2.2.6672.28001;Rubberduck.UI._DockableWindowHost;IOleObject::DoVerb() called with iVerb OLEIVERB_SHOW.;
2018-04-30 17:19:52.6416;TRACE-2.2.6672.28001;Rubberduck.Common.Hotkeys.Hotkey;Hotkey for the associated command Rubberduck.UI.Command.Refactorings.CodePaneRefactorRenameCommand was registered with id 49567;
2018-04-30 17:19:52.6416;TRACE-2.2.6672.28001;Rubberduck.Common.Hotkeys.Hotkey;Hotkey for the associated command Rubberduck.UI.Command.Refactorings.RefactorEncapsulateFieldCommand was registered with id 49284;
2018-04-30 17:19:52.6573;TRACE-2.2.6672.28001;Rubberduck.Common.Hotkeys.Hotkey;Hotkey for the associated command Rubberduck.UI.Command.Refactorings.RefactorExtractMethodCommand was registered with id 49280;
2018-04-30 17:19:52.6729;TRACE-2.2.6672.28001;Rubberduck.Common.Hotkeys.Hotkey;Hotkey for the associated command Rubberduck.UI.Command.Refactorings.RefactorMoveCloserToUsageCommand was registered with id 49555;
2018-04-30 17:19:52.6729;TRACE-2.2.6672.28001;Rubberduck.Common.Hotkeys.Hotkey;Hotkey for the associated command Rubberduck.UI.Command.CodeExplorerCommand was registered with id 49609;
2018-04-30 17:19:52.6921;TRACE-2.2.6672.28001;Rubberduck.Common.Hotkeys.Hotkey;Hotkey for the associated command Rubberduck.UI.Command.ExportAllCommand was registered with id 49534;
2018-04-30 17:19:52.6921;TRACE-2.2.6672.28001;Rubberduck.Common.Hotkeys.Hotkey;Hotkey for the associated command Rubberduck.UI.Command.FindSymbolCommand was registered with id 49425;
2018-04-30 17:19:52.6921;TRACE-2.2.6672.28001;Rubberduck.Common.Hotkeys.Hotkey;Hotkey for the associated command Rubberduck.UI.Command.IndentCurrentModuleCommand was registered with id 49395;
2018-04-30 17:19:52.7107;TRACE-2.2.6672.28001;Rubberduck.Common.Hotkeys.Hotkey;Hotkey for the associated command Rubberduck.UI.Command.IndentCurrentProcedureCommand was registered with id 49282;
2018-04-30 17:19:52.7107;TRACE-2.2.6672.28001;Rubberduck.Common.Hotkeys.Hotkey;Hotkey for the associated command Rubberduck.UI.Command.InspectionResultsCommand was registered with id 49568;
2018-04-30 17:19:52.7263;TRACE-2.2.6672.28001;Rubberduck.Common.Hotkeys.Hotkey;Hotkey for the associated command Rubberduck.UI.Command.ReparseCommand was registered with id 49489;
2018-04-30 17:19:52.7263;TRACE-2.2.6672.28001;Rubberduck.Common.Hotkeys.Hotkey;Hotkey for the associated command Rubberduck.UI.Command.TestExplorerCommand was registered with id 49613;
2018-04-30 17:19:52.7419;TRACE-2.2.6672.28001;Rubberduck.UI._DockableWindowHost;IOleObject::DoVerb() called with iVerb OLEIVERB_SHOW.;
2018-04-30 17:19:59.5807;TRACE-2.2.6672.28001;Rubberduck.Common.Hotkeys.Hotkey;Hotkey for the associated command Rubberduck.UI.Command.Refactorings.CodePaneRefactorRenameCommand was registered with id 49614;
2018-04-30 17:19:59.5807;TRACE-2.2.6672.28001;Rubberduck.Common.Hotkeys.Hotkey;Hotkey for the associated command Rubberduck.UI.Command.Refactorings.RefactorEncapsulateFieldCommand was registered with id 49613;
2018-04-30 17:19:59.5999;TRACE-2.2.6672.28001;Rubberduck.Common.Hotkeys.Hotkey;Hotkey for the associated command Rubberduck.UI.Command.Refactorings.RefactorExtractMethodCommand was registered with id 49615;
2018-04-30 17:19:59.5999;TRACE-2.2.6672.28001;Rubberduck.Common.Hotkeys.Hotkey;Hotkey for the associated command Rubberduck.UI.Command.Refactorings.RefactorMoveCloserToUsageCommand was registered with id 49489;
2018-04-30 17:19:59.5999;TRACE-2.2.6672.28001;Rubberduck.Common.Hotkeys.Hotkey;Hotkey for the associated command Rubberduck.UI.Command.CodeExplorerCommand was registered with id 49401;
2018-04-30 17:19:59.6185;TRACE-2.2.6672.28001;Rubberduck.Common.Hotkeys.Hotkey;Hotkey for the associated command Rubberduck.UI.Command.ExportAllCommand was registered with id 49568;
2018-04-30 17:19:59.6185;TRACE-2.2.6672.28001;Rubberduck.Common.Hotkeys.Hotkey;Hotkey for the associated command Rubberduck.UI.Command.FindSymbolCommand was registered with id 49282;
2018-04-30 17:19:59.6341;TRACE-2.2.6672.28001;Rubberduck.Common.Hotkeys.Hotkey;Hotkey for the associated command Rubberduck.UI.Command.IndentCurrentModuleCommand was registered with id 49616;
2018-04-30 17:19:59.6341;TRACE-2.2.6672.28001;Rubberduck.Common.Hotkeys.Hotkey;Hotkey for the associated command Rubberduck.UI.Command.IndentCurrentProcedureCommand was registered with id 49395;
2018-04-30 17:19:59.6497;TRACE-2.2.6672.28001;Rubberduck.Common.Hotkeys.Hotkey;Hotkey for the associated command Rubberduck.UI.Command.InspectionResultsCommand was registered with id 49297;
2018-04-30 17:19:59.6497;TRACE-2.2.6672.28001;Rubberduck.Common.Hotkeys.Hotkey;Hotkey for the associated command Rubberduck.UI.Command.ReparseCommand was registered with id 49617;
2018-04-30 17:19:59.6654;TRACE-2.2.6672.28001;Rubberduck.Common.Hotkeys.Hotkey;Hotkey for the associated command Rubberduck.UI.Command.TestExplorerCommand was registered with id 49645;
2018-04-30 17:20:20.2455;TRACE-2.2.6672.28001;Rubberduck.Common.Hotkeys.Hotkey;Hotkey for the associated command Rubberduck.UI.Command.Refactorings.CodePaneRefactorRenameCommand was registered with id 49312;
2018-04-30 17:20:20.2611;TRACE-2.2.6672.28001;Rubberduck.Common.Hotkeys.Hotkey;Hotkey for the associated command Rubberduck.UI.Command.Refactorings.RefactorEncapsulateFieldCommand was registered with id 49618;
2018-04-30 17:20:20.2767;TRACE-2.2.6672.28001;Rubberduck.Common.Hotkeys.Hotkey;Hotkey for the associated command Rubberduck.UI.Command.Refactorings.RefactorExtractMethodCommand was registered with id 49645;
2018-04-30 17:20:20.2767;TRACE-2.2.6672.28001;Rubberduck.Common.Hotkeys.Hotkey;Hotkey for the associated command Rubberduck.UI.Command.Refactorings.RefactorMoveCloserToUsageCommand was registered with id 49617;
2018-04-30 17:20:20.2924;TRACE-2.2.6672.28001;Rubberduck.Common.Hotkeys.Hotkey;Hotkey for the associated command Rubberduck.UI.Command.CodeExplorerCommand was registered with id 49620;
2018-04-30 17:20:20.2924;TRACE-2.2.6672.28001;Rubberduck.Common.Hotkeys.Hotkey;Hotkey for the associated command Rubberduck.UI.Command.ExportAllCommand was registered with id 49586;
2018-04-30 17:20:20.3145;TRACE-2.2.6672.28001;Rubberduck.Common.Hotkeys.Hotkey;Hotkey for the associated command Rubberduck.UI.Command.FindSymbolCommand was registered with id 49297;
2018-04-30 17:20:20.3145;TRACE-2.2.6672.28001;Rubberduck.Common.Hotkeys.Hotkey;Hotkey for the associated command Rubberduck.UI.Command.IndentCurrentModuleCommand was registered with id 49395;
2018-04-30 17:20:20.3301;TRACE-2.2.6672.28001;Rubberduck.Common.Hotkeys.Hotkey;Hotkey for the associated command Rubberduck.UI.Command.IndentCurrentProcedureCommand was registered with id 49616;
2018-04-30 17:20:20.3458;TRACE-2.2.6672.28001;Rubberduck.Common.Hotkeys.Hotkey;Hotkey for the associated command Rubberduck.UI.Command.InspectionResultsCommand was registered with id 49282;
2018-04-30 17:20:20.3458;TRACE-2.2.6672.28001;Rubberduck.Common.Hotkeys.Hotkey;Hotkey for the associated command Rubberduck.UI.Command.ReparseCommand was registered with id 49568;
2018-04-30 17:20:20.3770;TRACE-2.2.6672.28001;Rubberduck.Common.Hotkeys.Hotkey;Hotkey for the associated command Rubberduck.UI.Command.TestExplorerCommand was registered with id 49401;
2018-04-30 17:24:42.0256;TRACE-2.2.6672.28001;Rubberduck.VBEditor.SafeComWrappers.Office.Core.CommandBarButton;Executing handler for: CommandBar 'Pending' (tag: Rubberduck.UI.Command.MenuItems.CommandBars.ReparseCommandMenuItem, hashcode:46625744);
2018-04-30 17:24:42.0396;DEBUG-2.2.6672.28001;Rubberduck.UI.Command.MenuItems.CommandBars.AppCommandBarBase;(63788400) Executing click handler for commandbar item 'Pending', hash code 50454834;
2018-04-30 17:24:42.4680;DEBUG-2.2.6672.28001;Rubberduck.Parsing.VBA.ParseCoordinator;Parsing run started. (thread 16).;
2018-04-30 17:24:42.4790;INFO-2.2.6672.28001;Rubberduck.Parsing.VBA.RubberduckParserState;RubberduckParserState (5) is invoking StateChanged (Started);
2018-04-30 17:24:42.4940;ERROR-2.2.6672.28001;Rubberduck.Parsing.VBA.ParseCoordinator;Unexpected exception thrown in parsing run. (thread 16).;System.InvalidCastException: Unable to cast COM object of type 'System.__ComObject' to interface type 'Microsoft.Office.Core.CommandBarControl'. This operation failed because the QueryInterface call on the COM component for the interface with IID '{000C0308-0000-0000-C000-000000000046}' failed due to the following error: No such interface supported (Exception from HRESULT: 0x80004002 (E_NOINTERFACE)).
   at System.StubHelpers.StubHelpers.GetCOMIPFromRCW(Object objSrc, IntPtr pCPCMD, IntPtr& ppTarget, Boolean& pfNeedsRelease)
   at Microsoft.Office.Core.CommandBarControl.set_Enabled(Boolean pvarfEnabled)
   at Rubberduck.VBEditor.SafeComWrappers.Office.Core.CommandBarControl.set_IsEnabled(Boolean value) in C:\projects\rubberduck\Rubberduck.VBEEditor\SafeComWrappers\Office.Core\CommandBarControl.cs:line 59
   at Rubberduck.UI.Command.MenuItems.CommandBars.AppCommandBarBase.EvaluateCanExecute(RubberduckParserState state) in C:\projects\rubberduck\Rubberduck.Core\UI\Command\MenuItems\CommandBars\AppCommandBarBase.cs:line 157
   at Rubberduck.UI.Command.MenuItems.CommandBars.RubberduckCommandBar.OnParserStateChanged(Object sender, EventArgs e) in C:\projects\rubberduck\Rubberduck.Core\UI\Command\MenuItems\CommandBars\RubberduckCommandBar.cs:line 91
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at Rubberduck.Parsing.VBA.RubberduckParserState.OnStateChanged(Object requestor, CancellationToken token, ParserState state) in C:\projects\rubberduck\Rubberduck.Parsing\VBA\RubberduckParserState.cs:line 348
   at Rubberduck.Parsing.VBA.RubberduckParserState.SetStatusAndFireStateChanged(Object requestor, ParserState status, CancellationToken token) in C:\projects\rubberduck\Rubberduck.Parsing\VBA\RubberduckParserState.cs:line 562
   at Rubberduck.Parsing.VBA.ParserStateManagerBase.SetStatusAndFireStateChanged(Object requestor, ParserState status, CancellationToken token) in C:\projects\rubberduck\Rubberduck.Parsing\VBA\ParserStateManagerBase.cs:line 51
   at Rubberduck.Parsing.VBA.ParseCoordinator.ParseAllInternal(Object requestor, CancellationToken token) in C:\projects\rubberduck\Rubberduck.Parsing\VBA\ParseCoordinator.cs:line 340
   at Rubberduck.Parsing.VBA.ParseCoordinator.ParseAll(Object requestor, CancellationToken token) in C:\projects\rubberduck\Rubberduck.Parsing\VBA\ParseCoordinator.cs:line 313
`

**Comment by retailcoder** [comment] 2018-04-30 21:35
Seems updating the CommandBar button's caption (to reflect parser state) is throwing a COM exception again.

**Comment by sushrut91** [comment] 2018-04-30 22:18
Hello Mathieu,

I don't have any version of MS Office installed on my machine. My machine has Windows 10 Pro 64 bit. I am unable to exactly see which version of Office CommandBar Corel Draw X7 is using but please take a look at the screenshots maybe it may give some pointers towards the version. 

Is office installation necessary for RubberDuck to work ? I don't want to spend on buying MS office. Is there a work around ?
![img1](https://user-images.githubusercontent.com/15870575/39453157-d14251ee-4ca2-11e8-9fb3-b7f135559045.png)
![img2](https://user-images.githubusercontent.com/15870575/39453160-d564879c-4ca2-11e8-978e-ed858d550417.png)

**Comment by sushrut91** [comment] 2018-05-07 00:01
Any update on the issue @retailcoder ? Is the info in my last post useful ?

**Comment by retailcoder** [comment] 2018-05-07 02:02
As far as I can see it *should* work...  Rubberduck does not require a MS-Office install to work, however if repairing an Office install fixed it for others, maybe installing a trial version (free) could do the same? Just grasping at straws here..

**Comment by Gitsanto** [comment] 2019-03-29 02:01
I also got stuck with this issue.
```
2019-03-29 10:50:40.1520;ERROR-2.3.1.4308;Rubberduck.Parsing.VBA.ParseCoordinator;Unexpected exception thrown in parsing run. (thread 4).;System.InvalidCastException: 型 'System.__ComObject'
```
How to solve this issues?
:sob:

**Comment by bclothier** [comment] 2019-09-02 15:14
Closing this issue in favor of #3837 and #4192.

**Closed by bclothier** 2019-09-02 15:14 UTC
Labels: bug, parse-tree-processing
