### ISSUE TITLE
With blocks break identifier reference resolution

### ISSUE THREAD

**Issue by joshuader6** [rubberduck-vba/Rubberduck#1539] opened 2016-05-19 11:57 UTC
Here is some code and the output from vs ^^
Note how the Refactorings (specifically rename)  get confused by it ^^

```
Option Explicit

Function PastePictureXLModOV(PicturePath As String, targetcell As Excel.Range, Optional bLink As Boolean = False) As Boolean
'---------------------------------------------------------------------------------------
' Procedure : PastePictureXLModOV
' Author    : Joshua Kreuder
' Date      : 29.04.2015
'---------------------------------------------------------------------------------------
'
    Dim dTop As Double, dLeft As Double, objPicture As Object, lngBorderOffset As Long

    
    'On Error Resume Next
    If bLink Then
        Set objPicture = targetcell.Parent.Pictures.Insert(PicturePath)
        If Not objPicture.ShapeRange.Type = msoLinkedPicture Then
            objPicture.Delete
            Exit Function
        End If
    Else
        targetcell.Parent.Activate
        targetcell.Parent.Range("a1").Select
        Set objPicture = targetcell.Parent.Pictures.Insert(PicturePath)
        objPicture.Copy
        objPicture.Delete
        Set objPicture = targetcell.Parent.Pictures.Paste
        If Not objPicture.ShapeRange.Type = msoPicture Then
            objPicture.Delete
            Exit Function
        End If
    End If
    With targetcell
    
        lngBorderOffset = 5
        'center and position horzontal
        'scale
        objPicture.Top = .Top - lngBorderOffset
        objPicture.Height = .Height - lngBorderOffset
        If objPicture.Width > .Width Then
            objPicture.Left = .Left + lngBorderOffset
            objPicture.Width = .Width - lngBorderOffset
        End If
        'position H
        dLeft = (.Left + .Width / 2 - objPicture.Width / 2) + 0.25
        If dLeft < 1 Then dLeft = 1
        objPicture.Left = dLeft
        'position V
        dTop = (.Top + .Height / 2 - objPicture.Height / 2) + 0.25
        If dTop < 1 Then dTop = 1
        objPicture.Top = dTop
        'fix in cell
        objPicture.Placement = xlMoveAndSize
    End With
    
    'changepicsize
    objPicture.OnAction = "Onaction"
    PastePictureXLModOV = True

    On Error GoTo 0
    Exit Function


End Function
```

```
> 'Failed to resolve targetcell.Parent.Pictures.Insert(PicturePath). Possible causes include: COM Coclass/Interface mixup / Alias / Bug in the resolver.
> 'Failed to resolve Not objPicture.ShapeRange.Type = msoLinkedPicture. Possible causes include: COM Coclass/Interface mixup / Alias / Bug in the resolver.
> 'Failed to resolve objPicture.Delete. Possible causes include: COM Coclass/Interface mixup / Alias / Bug in the resolver.
> 'Failed to resolve targetcell.Parent.Activate. Possible causes include: COM Coclass/Interface mixup / Alias / Bug in the resolver.
> 'Failed to resolve targetcell.Parent.Range("a1").Select. Possible causes include: COM Coclass/Interface mixup / Alias / Bug in the resolver.
> 'Failed to resolve targetcell.Parent.Pictures.Insert(PicturePath). Possible causes include: COM Coclass/Interface mixup / Alias / Bug in the resolver.
> 'Failed to resolve objPicture.Copy. Possible causes include: COM Coclass/Interface mixup / Alias / Bug in the resolver.
> 'Failed to resolve objPicture.Delete. Possible causes include: COM Coclass/Interface mixup / Alias / Bug in the resolver.
> 'Failed to resolve targetcell.Parent.Pictures.Paste. Possible causes include: COM Coclass/Interface mixup / Alias / Bug in the resolver.
> 'Failed to resolve Not objPicture.ShapeRange.Type = msoPicture. Possible causes include: COM Coclass/Interface mixup / Alias / Bug in the resolver.
> 'Failed to resolve objPicture.Delete. Possible causes include: COM Coclass/Interface mixup / Alias / Bug in the resolver.
> 'Failed to resolve objPicture.Top . Possible causes include: COM Coclass/Interface mixup / Alias / Bug in the resolver.
> 'Failed to resolve objPicture.Height . Possible causes include: COM Coclass/Interface mixup / Alias / Bug in the resolver.
> 'Failed to resolve objPicture.Width > .Width. Possible causes include: COM Coclass/Interface mixup / Alias / Bug in the resolver.
> 'Failed to resolve objPicture.Left . Possible causes include: COM Coclass/Interface mixup / Alias / Bug in the resolver.
> 'Failed to resolve objPicture.Width . Possible causes include: COM Coclass/Interface mixup / Alias / Bug in the resolver.
> 'Failed to resolve (.Left + .Width / 2 - objPicture.Width / 2) + 0.25. Possible causes include: COM Coclass/Interface mixup / Alias / Bug in the resolver.
> 'Failed to resolve objPicture.Left . Possible causes include: COM Coclass/Interface mixup / Alias / Bug in the resolver.
> 'Failed to resolve (.Top + .Height / 2 - objPicture.Height / 2) + 0.25. Possible causes include: COM Coclass/Interface mixup / Alias / Bug in the resolver.
> 'Failed to resolve objPicture.Top . Possible causes include: COM Coclass/Interface mixup / Alias / Bug in the resolver.
> 'Failed to resolve objPicture.Placement . Possible causes include: COM Coclass/Interface mixup / Alias / Bug in the resolver.
> 'Failed to resolve objPicture.OnAction . Possible causes include: COM Coclass/Interface mixup / Alias / Bug in the resolver.
```

**Comment by autoboosh** [comment] 2016-05-19 18:09
The problem is that the types in question are all of declared type "Object" so we don't know what methods they call:

`objPicture As Object`

targetCell has a proper declared type but e.g. the Parent property returns an Object.

**Comment by joshuader6** [comment] 2016-05-19 18:43
Yeah this method originally pasted from the clipboard so this was the first way I thought of preventing an error when there was e.g text in the clipboard.
Now I've kept it because of the difference between picture and linkedpicture. 
It was some time ago I last changed this function .

**Comment by autoboosh** [comment] 2016-05-21 16:51
The latest changes might have helped with this issue. @joshuader6 can you give it a try again? Or at least give a quick summary of what you tried to rename?

**Comment by retailcoder** [comment] 2016-05-27 02:33
Okay, so I gave that code to the latest build, and the resolver logs these:

	2016-05-26 22:02:28.9234;TRACE;Rubberduck.Parsing.Symbols.IdentifierReferenceResolver;IdentifierReferenceResolver/Type Context: Failed to resolve Excel.Range. Binding all successfully resolved expressions anyway.;
	2016-05-26 22:02:28.9474;TRACE;Rubberduck.Parsing.Symbols.IdentifierReferenceResolver;IdentifierReferenceResolver/Type Context: Failed to resolve Object. Binding all successfully resolved expressions anyway.;
	2016-05-26 22:02:29.0120;TRACE;Rubberduck.Parsing.Symbols.IdentifierReferenceResolver;IdentifierReferenceResolver/Default Context: Failed to resolve targetcell.Parent.Pictures.Insert(PicturePath). Binding all successfully resolved expressions anyway.;
	2016-05-26 22:02:29.0390;TRACE;Rubberduck.Parsing.Symbols.IdentifierReferenceResolver;IdentifierReferenceResolver/Default Context: Failed to resolve Not objPicture.ShapeRange.Type = msoLinkedPicture. Binding all successfully resolved expressions anyway.;
	2016-05-26 22:02:29.0501;TRACE;Rubberduck.Parsing.Symbols.IdentifierReferenceResolver;IdentifierReferenceResolver/Default Context: Failed to resolve objPicture.Delete. Binding all successfully resolved expressions anyway.;
	2016-05-26 22:02:29.0501;TRACE;Rubberduck.Parsing.Symbols.IdentifierReferenceResolver;IdentifierReferenceResolver/Default Context: Failed to resolve targetcell.Parent.Activate. Binding all successfully resolved expressions anyway.;
	2016-05-26 22:02:29.0501;TRACE;Rubberduck.Parsing.Symbols.IdentifierReferenceResolver;IdentifierReferenceResolver/Default Context: Failed to resolve targetcell.Parent.Range("a1").Select. Binding all successfully resolved expressions anyway.;
	2016-05-26 22:02:29.0621;TRACE;Rubberduck.Parsing.Symbols.IdentifierReferenceResolver;IdentifierReferenceResolver/Default Context: Failed to resolve targetcell.Parent.Pictures.Insert(PicturePath). Binding all successfully resolved expressions anyway.;
	2016-05-26 22:02:29.0621;TRACE;Rubberduck.Parsing.Symbols.IdentifierReferenceResolver;IdentifierReferenceResolver/Default Context: Failed to resolve objPicture.Copy. Binding all successfully resolved expressions anyway.;
	2016-05-26 22:02:29.0621;TRACE;Rubberduck.Parsing.Symbols.IdentifierReferenceResolver;IdentifierReferenceResolver/Default Context: Failed to resolve objPicture.Delete. Binding all successfully resolved expressions anyway.;
	2016-05-26 22:02:29.0621;TRACE;Rubberduck.Parsing.Symbols.IdentifierReferenceResolver;IdentifierReferenceResolver/Default Context: Failed to resolve targetcell.Parent.Pictures.Paste. Binding all successfully resolved expressions anyway.;
	2016-05-26 22:02:29.0621;TRACE;Rubberduck.Parsing.Symbols.IdentifierReferenceResolver;IdentifierReferenceResolver/Default Context: Failed to resolve Not objPicture.ShapeRange.Type = msoPicture. Binding all successfully resolved expressions anyway.;
	2016-05-26 22:02:29.0621;TRACE;Rubberduck.Parsing.Symbols.IdentifierReferenceResolver;IdentifierReferenceResolver/Default Context: Failed to resolve objPicture.Delete. Binding all successfully resolved expressions anyway.;
	2016-05-26 22:02:29.0786;TRACE;Rubberduck.Parsing.Symbols.IdentifierReferenceResolver;IdentifierReferenceResolver/Default Context: Failed to resolve objPicture.Top. Binding all successfully resolved expressions anyway.;
	2016-05-26 22:02:29.0786;TRACE;Rubberduck.Parsing.Symbols.IdentifierReferenceResolver;IdentifierReferenceResolver/Default Context: Failed to resolve .Top - lngBorderOffset. Binding all successfully resolved expressions anyway.;
	2016-05-26 22:02:29.0786;TRACE;Rubberduck.Parsing.Symbols.IdentifierReferenceResolver;IdentifierReferenceResolver/Default Context: Failed to resolve objPicture.Height. Binding all successfully resolved expressions anyway.;
	2016-05-26 22:02:29.0786;TRACE;Rubberduck.Parsing.Symbols.IdentifierReferenceResolver;IdentifierReferenceResolver/Default Context: Failed to resolve .Height - lngBorderOffset. Binding all successfully resolved expressions anyway.;
	2016-05-26 22:02:29.0972;TRACE;Rubberduck.Parsing.Symbols.IdentifierReferenceResolver;IdentifierReferenceResolver/Default Context: Failed to resolve objPicture.Width > .Width. Binding all successfully resolved expressions anyway.;
	2016-05-26 22:02:29.0972;TRACE;Rubberduck.Parsing.Symbols.IdentifierReferenceResolver;IdentifierReferenceResolver/Default Context: Failed to resolve objPicture.Left. Binding all successfully resolved expressions anyway.;
	2016-05-26 22:02:29.0972;TRACE;Rubberduck.Parsing.Symbols.IdentifierReferenceResolver;IdentifierReferenceResolver/Default Context: Failed to resolve .Left + lngBorderOffset. Binding all successfully resolved expressions anyway.;
	2016-05-26 22:02:29.0972;TRACE;Rubberduck.Parsing.Symbols.IdentifierReferenceResolver;IdentifierReferenceResolver/Default Context: Failed to resolve objPicture.Width. Binding all successfully resolved expressions anyway.;
	2016-05-26 22:02:29.0972;TRACE;Rubberduck.Parsing.Symbols.IdentifierReferenceResolver;IdentifierReferenceResolver/Default Context: Failed to resolve .Width - lngBorderOffset. Binding all successfully resolved expressions anyway.;
	2016-05-26 22:02:29.1163;TRACE;Rubberduck.Parsing.Symbols.IdentifierReferenceResolver;IdentifierReferenceResolver/Default Context: Failed to resolve (.Left + .Width / 2 - objPicture.Width / 2) + 0.25. Binding all successfully resolved expressions anyway.;
	2016-05-26 22:02:29.1281;TRACE;Rubberduck.Parsing.Symbols.IdentifierReferenceResolver;IdentifierReferenceResolver/Default Context: Failed to resolve objPicture.Left. Binding all successfully resolved expressions anyway.;
	2016-05-26 22:02:29.1281;TRACE;Rubberduck.Parsing.Symbols.IdentifierReferenceResolver;IdentifierReferenceResolver/Default Context: Failed to resolve (.Top + .Height / 2 - objPicture.Height / 2) + 0.25. Binding all successfully resolved expressions anyway.;
	2016-05-26 22:02:29.1281;TRACE;Rubberduck.Parsing.Symbols.IdentifierReferenceResolver;IdentifierReferenceResolver/Default Context: Failed to resolve objPicture.Top. Binding all successfully resolved expressions anyway.;
	2016-05-26 22:02:29.1281;TRACE;Rubberduck.Parsing.Symbols.IdentifierReferenceResolver;IdentifierReferenceResolver/Default Context: Failed to resolve objPicture.Placement. Binding all successfully resolved expressions anyway.;
	2016-05-26 22:02:29.1281;TRACE;Rubberduck.Parsing.Symbols.IdentifierReferenceResolver;IdentifierReferenceResolver/Default Context: Failed to resolve objPicture.OnAction. Binding all successfully resolved expressions anyway.;
	2016-05-26 22:02:29.1421;TRACE;Rubberduck.Parsing.Symbols.IdentifierReferenceResolver;IdentifierReferenceResolver/Default Context: Failed to resolve True. Binding all successfully resolved expressions anyway.;
	2016-05-26 22:02:29.1421;DEBUG;Rubberduck.Parsing.VBA.RubberduckParser;Binding Resolution done for component 'Module1' in 219ms (thread 5);

A number of these messages are surprising (e.g. why is it trying to resolve `True`?), and `Range.Top` and `Range.Left` aren't resolving as they should, but the `With` block doesn't seem to break anything, and I could successfully rename `objPicture` to `pic`, and locate all references to `targetCell`, and given the results documented in #1572 it appears the resolver *is* picking up the member calls as calls to members of `targetCell`.

I deem this issue resolved.

**Closed by retailcoder** 2016-05-27 02:33 UTC
Labels: bug, code-parsing, critical
