### ISSUE TITLE
Outlook Not Responding when opening VBE

### ISSUE THREAD

**Issue by aberger91** [rubberduck-vba/Rubberduck#3540] opened 2017-11-07 21:48 UTC
Outlook 2013
Windows 7

Outlook freezes when I try to open VBE (Alt+F11) after installing Rubberduck

I have 1 instance of Outlook running

**Comment by retailcoder** [comment] 2017-11-08 00:57
Duplicate of #3539

**Closed by retailcoder** 2017-11-08 00:57 UTC
Labels: duplicate
