### ISSUE TITLE
Hidden Enum member references are not associated with their declaration

### ISSUE THREAD

**Issue by BZngr** [rubberduck-vba/Rubberduck#5228] opened 2019-10-16 15:09 UTC
**Rubberduck version information**
Version 2.4.1.23886
OS: Microsoft Windows NT 10.0.18362.0, x64
Host Product: Microsoft Office x86
Host Version: 16.0.12026.20320
Host Executable: EXCEL.EXE

Rubberduck does not find/recognize hidden enum member references.

**To Reproduce**
1. Create module with the following content:
```
Option Explicit
Enum FruitTypes
    [_First] = 1
    Apple = 1
    Orange = 2
    Plum = 3
    [_Last] = 3
End Enum

Public Sub Test()
    MsgBox CStr(FruitTypes.[_First])
End Sub
```
2.  Rename  Enum member `[_First]` using `RenameRefactoring`  with a breakpoint set within `DeclarationFinder.FindSelectedDeclaration`.  This will yield the following declaration information.

![image](https://user-images.githubusercontent.com/16185628/66930510-8dfb8400-efe9-11e9-90e5-c3b30056a64b.png)

3.  Note that `[_First]` is listed in the `declarationsInModule` collection, but the reference to this member is not listed in the `referencesInModule `collection.

**Expected behavior**
References to a hidden enum member should be associated with the Declaration.  Otherwise, it is not possible to use RenameRefactoring without creating broken code.  Renaming `[_First]` (to anything) changes the name of the declaration but not the reference(s).  After renaming `[_First]`, executing `Sub Test()` generates the compile error -  "External name not defined" when the line of code is executed that still has the original name: `[_First]`

**Comment by MDoerner** [comment] 2019-10-16 15:15
This seems to be a duplicate of #3238.

**Closed by MDoerner** 2019-10-16 15:15 UTC
Labels: bug
