### ISSUE TITLE
consider renaming variables, too much noise for hungarian notation

### ISSUE THREAD

**Issue by peterennis** [rubberduck-vba/Rubberduck#2005] opened 2016-07-09 06:13 UTC
tbl, rst, dsb, cnn, etc.
Hungarian Notation Wars? https://optionexplicitvba.com/2014/02/17/its-time-to-say-goodbye-to-hungarian-notation/

There is a lot of code (old and new) that has this methodology. Blanket recommendations
for change seem excessively opinionated.

i, j, k are recognized as looop counters etc.

Is there an option to tone down this "noise". I tried the ignore link but it seems to
turn off all info of this type so good suggestions also disappear.

How about check boxes next to items the user may want to ignore?

![capture19](https://cloud.githubusercontent.com/assets/140737/16706445/986d49ea-4561-11e6-9fca-d9a230beec9b.PNG)

**Comment by Vogel612** [comment] 2016-07-09 10:41
Maybe interesting: We could provide a whitelist for names in the settings that are based on a pattern. This would allow users to cull the results for that inspection.  
Then again it seems basically everyone in the VBA world that's considered "expert" agrees that hungarian notation is to be avoided...

Overall I think it's good Rubberduck complains about hungarian notation, but there is such a thing as SNR, which is basically killed twice over if we get thousands of results for the same thing that everybody already knows is bad :unamused:

**Comment by retailcoder** [comment] 2016-07-09 15:10
ref.#1681

**Comment by Hosch250** [comment] 2016-07-14 14:53
Closing as duplicate of https://github.com/rubberduck-vba/Rubberduck/issues/1681.

**Closed** 2016-07-14 14:53 UTC
Labels: duplicate

**Comment by retailcoder** [comment] 2017-01-20 03:34
Just reviving this one to mention that *it's not a war on Hungarian Notation* - inspection results are always mere *suggestions*, albeit sometimes more warmly recommended than others (inspection severity is completely configurable, too): it's by *looking for* Hungarian prefixes that we can get Rubberduck to either report... *or* ignore them.

https://github.com/rubberduck-vba/Rubberduck/blob/next/RetailCoder.VBE/Inspections/HungarianNotationInspection.cs#L21-L82

As of v2.0.12 (next release), there's a `HungarianNotationInspection` that uses the identifier white-list of #1681 to white-list Hungarian prefixes specifically - note that any prefix in that list is *also* an ignored identifier on its own, too. And we're introducing an `AggregateInspectionResult`, to limit the number of individual results from a given single inspection:

![aggregate inspection results](https://cloud.githubusercontent.com/assets/5751684/22134067/6209921c-de92-11e6-88bd-abb969bc417f.png)

I hope this helps!
