### ISSUE TITLE
ParserError reports incorrect location

### ISSUE THREAD

**Issue by ThunderFrame** [rubberduck-vba/Rubberduck#1661] opened 2016-06-02 03:05 UTC
As per #1660 when the ParseError is inspected, the line and column number appear to be relative to the raw text file (which would seemingly include the VB Attributes). Could it be that Line/Column values are out of Sync in the Declarations section?

**Comment by retailcoder** [comment] 2016-06-02 03:13
they're not out of sync. see #1662 for more details - the problem is that the error listener we're using for the attributes pass is throwing the exact same exception type as the regular code-pane pass, which makes it next to impossible, once the exception is in the parser state against the faulting module, to tell whether the exception was thrown parsing attributes (i.e. the exported code file) or parsing the actual code pane contents (which *does* have correct line numbers - actually both do, but they're working off different data).

**Comment by comintern** [comment] 2016-06-02 03:14
Could this be the cause of the annoying RTrim while typing in the CodePane?

**Comment by retailcoder** [comment] 2016-06-02 03:20
@comintern I don't think so. Commenting-out the `RawKeyboard` hook seems to completely fix the issue. I think the "RTrim" issue is caused by the key hook messing something up somewhere - and that needs to be fixed, creating an issue for it.

**Comment by retailcoder** [comment] 2016-06-07 18:38
The "out-of-sync-ness" of token position is by design, since the source string for attribute tokens is not the same source string as the one used for codepane code. What we need is another way of reporting parsing errors in the attributes pass.

**Comment by retailcoder** [comment] 2016-06-07 18:41
@Hosch250 any ideas about this one?

**Comment by Hosch250** [comment] 2016-06-07 20:36
No, I haven't.  I'll think about it and see if I come up with something.

**Comment by Hosch250** [comment] 2016-06-09 16:05
No repro.

**Comment by retailcoder** [comment] 2016-06-09 16:06
@Hosch250 export a module, pick add an invalid member attribute somewhere - you'll have a repro.

**Comment by retailcoder** [comment] 2017-04-05 21:29
linking #2665

**Comment by Vogel612** [comment] 2017-07-24 14:38
is this fixed?

**Comment by retailcoder** [comment] 2017-07-24 14:41
@Vogel612 I have an idea, to make the attributes pass throw a different exception type in case of a parse error - that should fix all the "empty parser errors" toolwindows.. And offset line positions being reported.

**Comment by shadowofsilicon** [comment] 2017-08-15 15:30
It looks like I just reproduced this.  Reported position is off by ~18 lines.
![image](https://user-images.githubusercontent.com/28154402/29322885-c180262e-81a4-11e7-99f2-edff0e9ebe44.png)

**Comment by retailcoder** [comment] 2017-08-15 15:32
The 18 lines offset are the module attributes. I bet this is a class module =)

**Comment by shadowofsilicon** [comment] 2017-08-15 15:39
That's correct, it is a form module.

**Comment by MDoerner** [comment] 2018-02-13 13:44
Does this bug still persis, now that we run the code pane parse first?

**Comment by bclothier** [comment] 2018-07-17 05:32
I believe this is fixed now.
![image](https://user-images.githubusercontent.com/2367644/42798316-e7ae7c76-8958-11e8-9b9b-3c889cb1b63b.png)

**Closed by bclothier** 2018-07-17 05:32 UTC
Labels: bug, parse-tree-processing, status-deferred, user-interface
