### ISSUE TITLE
Parse Error due to removed declaration of variable

### ISSUE THREAD

**Issue by RaymondWise** [rubberduck-vba/Rubberduck#3752] opened 2018-02-05 00:31 UTC
This is similar to https://github.com/rubberduck-vba/Rubberduck/issues/3384 but not due to a module change

**Version 2.1.2.2809**

Code inspection found:
    

> Variable `listLength` is not used

Code Inspection Fix:
>  *remove unused declaration* (or something similar)

     Dim listLength as Long

Error:
> Populate Module L75C6 extraneous input '=' expecting{ABS, ANY, ARRAY, CBOOL. ...}

Parse issue at line

     listLength = UBound(IngredientList, 2)

`listLength` was removed, leaving
 
    = Ubound(IngredientList,2)

Which caused a syntax error and then a parse error. Both this line and the declaration line were in the same module, same routine.

**Comment by retailcoder** [comment] 2018-02-05 03:15
Hmm, I always wanted to fix that misleading wording.. what the inspection is saying is that it couldn't find a *reference* to that variable that wasn't an assignment.. But the problem isn't only with the resource string.

The quickfix shouldn't be available for that inspection, if the identifier is *assigned*. *That* is the problem I think.

**Comment by retailcoder** [comment] 2018-02-05 03:17
wait is the variable referenced elsewhere? could be a resolver bug if that's the case...

**Comment by RaymondWise** [comment] 2018-02-05 05:57
@retailcoder no, I hadn't used the variable aside from the setting it to a value, it was left over. Maybe there was also an "not assigned" error on the inspection *after* the first one. I'll mess around to see if I can reproduce

**Comment by RaymondWise** [comment] 2018-02-05 06:09
Reproduced with - 
```
Option Explicit

Sub RubberTest()
    Dim longVar As Long
    Dim newArray As Variant
    ReDim newArray(5)
    Dim i As Long
    For i = 0 To 5
        newArray(i) = i
    Next
    longVar = UBound(newArray)
End Sub
```
> Rubberduck says Variable 'longVar' is not referred to
> Rubberduck says Fix: remove unused declaration
Rubberduck removes `Dim longVar as Long`
Rubberduck refreshes
> Rubberduck says: Variable 'longVar' is not used
> Rubberduck says fix: remove unused declaration
Rubberduck removes 'longVar' from line 9 leaving it `= Ubound(newArray)`

**Comment by MDoerner** [comment] 2018-02-05 09:59
Let me explain what is the problem here. Currently, the quickfix does not take into account that there can be assignments to the variable; it simply removes the variable declaration.

At your first application of the quickfix, you can observe this clearly. Since there is an assignment left, you end up with an implicitly defined variable.

Then again the quickfix does not take into account the existence of implicitly declared variables and thus only removes the _declaration_, i.e. the first instance of the variable name in the code. 

So, in principle there are either two bugs in the code, if we want the quickfix to deal with these situations, or one,  if it should be deactivated in the presence of assignments.

The second option would make sense, but it would require providing the possibility to deactivate quickfixes based on the inspection result, not just its type.

**Comment by retailcoder** [comment] 2018-02-05 12:17
Hosch introduced this possibility a little while back - we can do this! =)

**Comment by MDoerner** [comment] 2018-03-08 07:10
Ref #2427

**Comment by comintern** [comment] 2018-10-28 20:31
Disabling the reporting of this inspection if there are any assignments. Those are now inspected by the `AssignmentNotUsedInspection`. Closing as duplicate of #2427.

**Closed by comintern** 2018-10-28 20:31 UTC
Labels: bug, difficulty-01-duckling, feature-inspection-quickfixes, good first issue, up-for-grabs
