### ISSUE TITLE
Adding test method creates un-parse-able code

### ISSUE THREAD

**Issue by IvenBach** [rubberduck-vba/Rubberduck#5059] opened 2019-07-19 21:51 UTC
Version 2.4.1.26520
OS: Microsoft Windows NT 6.1.7601 Service Pack 1, x64
Host Product: Microsoft Office 2013 x86
Host Version: 15.0.5023.1000
Host Executable: EXCEL.EXE

**Description**
As title says.

**To Reproduce**
1. Insert a new test module.
2. Insert a test method.
3. Un-parse-able code.

**Expected behavior**
Inserted test method should not be within the body of another test method.

**Additional context**
Inserted module before test method:
```
Option Explicit
Option Private Module

'@TestModule
'@Folder("Tests")

Private Assert As Object
Private Fakes As Object

'@ModuleInitialize
Private Sub ModuleInitialize()
    'this method runs once per module.
    Set Assert = CreateObject("Rubberduck.AssertClass")
    Set Fakes = CreateObject("Rubberduck.FakesProvider")
End Sub

'@ModuleCleanup
Private Sub ModuleCleanup()
    'this method runs once per module.
    Set Assert = Nothing
    Set Fakes = Nothing
End Sub

'@TestInitialize
Private Sub TestInitialize()
    'this method runs before every test in the module.
End Sub

'@TestCleanup
Private Sub TestCleanup()
    'this method runs after every test in the module.
End Sub
```

Module after test method:
```
Option Explicit
Option Private Module

'@TestModule
'@Folder("Tests")

Private Assert As Object
Private Fakes As Object

'@ModuleInitialize
Private Sub ModuleInitialize()
    'this method runs once per module.
    Set Assert = CreateObject("Rubberduck.AssertClass")
    Set Fakes = CreateObject("Rubberduck.FakesProvider")
End Sub

'@ModuleCleanup
Private Sub ModuleCleanup()
    'this method runs once per module.
    Set Assert = Nothing
    Set Fakes = Nothing
End Sub

'@TestInitialize
Private Sub TestInitialize()
    'this method runs before every test in the module.
End Sub

'@TestCleanup
Private Sub TestCleanup()
    'this method runs after every test in the module. '<~~~~~ Insertion starts following this line
'@TestMethod("Uncategorized")
Private Sub TestMethod1()                        'TODO Rename test
    On Error GoTo TestFail
    
    'Arrange:

    'Act:

    'Assert:
    Assert.Succeed

TestExit:
    Exit Sub
TestFail:
    Assert.Fail "Test raised an error: #" & Err.Number & " - " & Err.Description
End Sub
End Sub
```

**Comment by IvenBach** [comment] 2019-08-08 20:20
Adding an extra line just after `TestCleanup`'s `End Sub` then inserting the test method will insert without issue.

```
'@TestCleanup
Private Sub TestCleanup()
    'this method runs after every test in the module.
End Sub

| '<--- cursor here
```
Produces the code below.
```
'@TestCleanup
Private Sub TestCleanup()
    'this method runs after every test in the module.
End Sub

'@TestMethod("Uncategorized")
Private Sub TestMethod2()                        'TODO Rename test
    On Error GoTo TestFail
    
    'Arrange:

    'Act:

    'Assert:
    Assert.Succeed

TestExit:
    Exit Sub
TestFail:
    Assert.Fail "Test raised an error: #" & Err.Number & " - " & Err.Description
End Sub
```

**Comment by bclothier** [comment] 2019-11-04 00:26
Closing this as a duplicate of #4169

**Closed by bclothier** 2019-11-04 00:26 UTC
Labels: bug, hacktoberfest, has-workaround
