### ISSUE TITLE
False Positive: Parameter X is never used

### ISSUE THREAD

**Issue by puzzlepiece87** [rubberduck-vba/Rubberduck#3691] opened 2018-01-11 04:50 UTC
Code Inspection Result: “Parameter SourceReportsFolderPath is never used”

classModel Class Module
```vba
Option Explicit
 
Private pSourceReportsFolderPath As String
 
'pSourceReportsFolderPath Properties
Public Property Get SourceReportsFolderPath() As String
    SourceReportsFolderPath = pSourceReportsFolderPath
End Property
Public Property Let SourceReportsFolderPath(ByVal SourceReportsFolderPath As String)
    If Right(SourceReportsFolderPath, 1) <> "\" Then SourceReportsFolderPath = SourceReportsFolderPath & "\"
    pSourceReportsFolderPath = SourceReportsFolderPath
End Property
 
 
Public Sub Setup()
 
    Dim FSO As Scripting.FileSystemObject
    Set FSO = CreateObject("Scripting.FileSystemObject")
 
    Dim SourceReportsTestPath As String
    SourceReportsTestPath = "(directory)"
    Dim folderSourceReports As Scripting.Folder
    Set folderSourceReports = FSO.GetFolder(SourceReportsTestPath)
    If folderSourceReports Is Nothing Then
        MsgBox "Cannot find source reports folder at expected path: " & SourceReportsTestPath
        Cancel
    Else
        SourceReportsFolderPath = SourceReportsTestPath
    End If
    
End Sub
```

**Comment by Vogel612** [comment] 2018-01-11 10:54
Could you please add which version of Rubberduck you're running? Thanks

**Comment by MDoerner** [comment] 2018-01-16 12:37
This is a duplicate of issue #3499.

**Closed by MDoerner** 2018-01-16 12:37 UTC
Labels: bug, duplicate, inspection-false-positive, resolver
