### ISSUE TITLE
Right click in code explorer not showing Add Module contexts

### ISSUE THREAD

**Issue by djrivers** [rubberduck-vba/Rubberduck#4716] opened 2019-01-16 16:28 UTC
I am trying to add a class module by right-clicking in the folder inside the code explorer and it's showing nothing.

![right click issue](https://user-images.githubusercontent.com/40927759/51263037-212f5c80-1979-11e9-803a-45b9e3260994.png)

Version 2.3.1.4431
OS: Microsoft Windows NT 10.0.17134.0, x64
Host Product: Microsoft Office x64
Host Version: 16.0.11126.20196
Host Executable: MSACCESS.EXE

**Comment by comintern** [comment] 2019-01-17 13:57
I must have spent an hour and a half right-clicking last night and was only able to replicate this once. It appears that something? is causing the bind on `AddModuleCommands` to either break or recycle in a way that causes the visibility of the commands to toggle off. We did [identify some potential casting issues](https://chat.stackexchange.com/transcript/message/48539377#48539377) in the templates sub-menu that is addressed in #4718, but I can't definitively declare that as the cause.

Would it be possible to set your logging level to "trace" in the settings and post the log file if this happens again?  I doubt there will be much relevant information logged (binding problems don't tend to show up there), but it would at least help rule out things like exceptions in the `EvaluateCanExecute` procedures.

**Comment by djrivers** [comment] 2019-01-17 14:39
I reverted back to version 2.3.1.4414 after I discovered this. I'll install the latest version and see if this is still there then comment back.

**Comment by djrivers** [comment] 2019-01-17 14:46
Everything is good now. I discovered another bug though. Will open another ticket with the log.

**Closed** 2019-01-17 14:49 UTC
Labels: bug, feature-code-explorer
