### ISSUE TITLE
COM collector: Built-in declarations should probably not all be marked as "GlobalNamespace"

### ISSUE THREAD

**Issue by autoboosh** [rubberduck-vba/Rubberduck#1491] opened 2016-05-13 18:39 UTC
Right now this does not resolve at all because Range is resolved to a class module because all collected class modules in type libraries are marked as default instance variables / in the global namespace.

```
Public Sub Test()
  a = Range("A1")
End Sub
```

Do we have that information somewhere in the type libraries?

**Comment by retailcoder** [comment] 2016-05-13 19:05
Not sure where that `GlobalNamespace` is coming from; I'm looking at `TYPEATTR.wTypeFlags`, and assuming `TYPEFLAG_FPREDCLID` means there's a `PredeclaredId` attribute:

                var typeAttributes = (TYPEATTR)Marshal.PtrToStructure(typeAttributesPointer, typeof(TYPEATTR));

                var attributes = new Attributes();
                if (typeAttributes.wTypeFlags.HasFlag(TYPEFLAGS.TYPEFLAG_FPREDECLID))
                {
                    attributes.AddPredeclaredIdTypeAttribute();
                }

**Comment by autoboosh** [comment] 2016-05-13 19:15
Ah, my bad I actually broke that part then.

Here's the description of default instance variables: [5.2.4.1.2 Default Instance Variables Static Semantics](https://msdn.microsoft.com/en-us/library/ee199159.aspx).

From what I understand if VB_GlobalNamespace is not set to true you shouldn't be able to access the members of the class in a different project.

According to [TYPEFLAGS enumeration](https://msdn.microsoft.com/en-us/library/windows/desktop/ms221509(v=vs.85).aspx) under "Remarks" this might be the case if TYPEFLAG_FAPPOBJECT is set.

What about VB_Exposed though? I'm not sure which flag specifies that. There's one that hides the type from the object browser. Or should we simply assume that all types are accessible?

**Comment by retailcoder** [comment] 2016-05-13 19:18
Oh wow, nice catch there - looks like `TYPEFLAG_FAPPOBJECT` is indeed what I need to look at!

Let's assume all types are accessible... until it creates problems :)

**Comment by autoboosh** [comment] 2016-05-13 19:29
OK, just a heads up, the current ClassModuleDeclaration has a parameter isGlobalClassModule which should probably deleted if we only use attributes (it's only used because of the COM collector).

**Comment by retailcoder** [comment] 2016-05-13 19:30
Bah, I find they make a convenient getter that checks for a specific attribute.... no?

**Comment by autoboosh** [comment] 2016-05-13 19:33
Yes, I agree. Sorry if I wasn't clear. What I meant was that ClassModuleDeclaration has constructor parameter that overrides what is in the attributes. The COM collector currently sets that parameter to true, so it might not work if you're testing the new COM collector if you don't remove this parameter.

**Comment by retailcoder** [comment] 2016-06-02 14:26
I remember working on this a little while ago, but not sure if it ended up merged or overwritten. @autoboosh is this still an issue or it's fixed?

**Comment by autoboosh** [comment] 2016-06-02 17:21
Just had a look at the com collector and it doesn't look like it doesn't add the global namespace attribute, so yes I think this is still an open issue.

**Comment by retailcoder** [comment] 2017-01-13 05:39
Deemed fixed. @comintern can you confirm?

**Closed** 2017-01-13 05:38 UTC
Labels: bug, code-parsing

**Comment by comintern** [comment] 2017-01-13 13:11
Confirmed.

```
                if (module.IsAppObject)
                {
                    attributes.AddGlobalClassAttribute();
                }
```
