### ISSUE TITLE
Range() function resolves to Range class

### ISSUE THREAD

**Issue by retailcoder** [rubberduck-vba/Rubberduck#1573] opened 2016-05-24 05:06 UTC
This will trip the *implicit reference to ActiveSheet* inspection:

    Public foo As Range

That's a false positive, this instruction is using `Range` as a type, not as a global/static method.

Fix is easy: the inspection shouldn't look at *classes*, but at *functions*.

Problem is, it resolves to a `Class` here too:

    Range("B1").Select

...which makes `.Select` resolve to nothing.

I think things be easier if `Range` resolved to the function when it's in a function call context, and to the class when it's in a type context :smiley:

**Comment by autoboosh** [comment] 2016-05-24 19:10
Isn't the `Range("B1").Select` the problem that's still open? I think it should resolve to the Range property in _Worksheet if you're typing this while inside a worksheet. But it doesn't because the resolver probably has to check for argument compatibility when deciding what to do. But that doesn't work yet because we need to make some changes to the COM collector (support parameter types, etc.).

**Comment by retailcoder** [comment] 2016-05-24 19:12
ugh. right. I never got to that. is the COM collector part the only thing that's left to do for it to work?

**Comment by autoboosh** [comment] 2016-05-24 20:46
We'll probably have to add declared types to each expression to make it robust. We already have the "as type" but the problem is binary expressions and so forth which can lead to a different declared type. As soon as declared types are there we can add argument compatibility checking. And then we could perhaps take a stab at creating variables if "Option Explicit" is not specified.

**Comment by retailcoder** [comment] 2016-05-25 15:30
@autoboosh now that the COM collector resolves field, member, and parameter types.. is this automagically "fixed"?

**Comment by autoboosh** [comment] 2016-05-26 23:44
Not yet, it looks like _Worksheet.Range is missing the second parameter for some reason, plus we need argument compatibility checking, otherwise the default member gets resolved instead.

**Comment by comintern** [comment] 2016-06-02 02:18
The second parameter gets missed because the `memberDescriptor.cParams` is 2, and the parameter count is subtracting one from the total.  The member names are "Range", "Cell1", and "Cell2", but the return value isn't declared as an [out] parameter or included in the cParams count.  

![screenshot from 2016-06-01 20 59 24](https://cloud.githubusercontent.com/assets/8944005/15731842/aa62c9c2-283d-11e6-97d4-83194335b74c.png)

Instead, it seems to be accounted for with the cParamsOpt of 1. Per the documentation of [FUNCDESC](https://msdn.microsoft.com/en-us/library/windows/desktop/ms221425%28v=vs.85%29.aspx):

> A value of 0 specifies that no optional arguments are supported.
> 
> A value of –1 specifies that the method's last parameter is a pointer to a safe array of variants. Any
> number of variant arguments greater than cParams –1 must be packaged by the caller into a safe 
> array and passed as the final parameter. This array of optional parameters must be freed by the 
> caller after control is returned from the call.
>  
> Any other number indicates that the last n parameters of the function are variants and do not
> need to be specified by the caller explicitly. The parameters left unspecified should be filled in by 
> the compiler or interpreter as variants of type VT_ERROR with the value DISP_E_PARAMNOTFOUND.

I think we're missing a flag somewhere that indicates how cParams needs to be interpreted vis-a-vis the return value.

**Closed** 2016-06-02 03:20 UTC
Labels: bug, code-parsing
