### ISSUE TITLE
Find All References fails when working across multiple Modules

### ISSUE THREAD

**Issue by byronwall** [rubberduck-vba/Rubberduck#912] opened 2015-12-30 21:17 UTC
I am trying to use the Find All References feature to detect locations where a given `Function` is used.  (Specifically, I want to find usages of [`Chart_GetObjectsFromObject`](https://github.com/byronwall/bUTL/blob/master/src/code/Chart_Helpers.bas#L45) used throughout the other modules in the bUTL add-in).  

**Problem**: Rubberduck is not correctly finding references in modules outside of the module where the `Function` is declared.

I don't think the problem is specific to that add-in, however, because a simple test case with two modules reveals the same behavior.  I am trying to use this for a `Function`, but it appears to behave with similar issues when working on a `Sub` as well.

When I select Find All References (right click in the `Function` signature) for the add-in function, Rubberduck will select the single "usage" of the function name where the return value is assigned.  I guess this is technically true, but I was hoping for it to find the usages of the `Function` throughout the rest of the add-in.

Using the test code at the end, you will get different behavior because the `test` `Function` is used in `Module1`.  It will not detect the references of that `Function` in different modules, however.  If I go to `Module2` and use the Find All References feature on the `test` function, it will fail silently.  Normally if there are no references found, Rubberduck gives a prompt indicating such.  In this case, there is no prompt or popup with the usages of `test`.

---
```vba
'Module1 code
Public Function test() As String 'find all references pops up a list of 3 usages in this module
    test = "test"
End Function
Sub runTest()
    Range("A1") = test()
    runTest2
End Sub
Public Sub runTest2() 'find all references selects the single usage above
    Range("A2") = test()
End Sub
```
---
```vba
'Module2 code
Sub runTest5()
    Range("A5") = test() 'find all references fails quietly on this one
    runTest2 'find all references fails quietly on the Sub call
End Sub
```

**Comment by retailcoder** [comment] 2015-12-30 21:41
Thanks for this! I pasted the two supplied snippets in a new VBA project, in their respective module.

For some reason that I need to investigate, the `'Module2 Code` comment stalls the 2.0 parser. Anyway so I removed the heading comments and finally got the parser into a "ready" state. I suspect that weird glitch might have something to do with a `COMException` @Hosch250 identified in the comment parser earlier this week.

Anyway so I right-clicked the reference to the `test()` function inside `Module2.runTest5`, and refactor/renamed the `test` function to `renamed`. Then I did the same for `runTest2` and renamed it to `AlsoRenamed`. This is the result:

    'Module1 code
    Public Function renamed() As String 'find all references pops up a list of 3 usages in this module
        renamed = "test"
    End Function
    Sub runTest()
        Range("A1") = renamed()
        alsoRenamed
    End Sub
    Public Sub alsoRenamed() 'find all references selects the single usage above
        Range("A2") = renamed()
    End Sub

---

    
    Sub runTest5()
        Range("A5") = renamed() 'find all references fails quietly on this one
        alsoRenamed 'find all references fails quietly on the Sub call
    End Sub

I'm happy to confirm that everything seems to work as intended in the 2.0 build... well except for that weird comment glitch that breaks the parser.

**Comment by retailcoder** [comment] 2015-12-30 22:00
(I had to do a refactor/rename to verify if all references were effectively found, since the "find all references" UI for 2.0 isn't, well, designed yet)

**Comment by byronwall** [comment] 2015-12-31 00:57
Thanks for looking into this.  Is there a workaround for the current parser?  Or is this a limitation until 2.0 is released?

**Comment by Hosch250** [comment] 2015-12-31 01:01
We are pretty much locked in until 2.0 with all the changes we've made.  We've fixed lots of other bugs as well.  I think we are planning on doing a preview release after a few more critical changes are made.  It may take a few months, though.

**Comment by retailcoder** [comment] 2015-12-31 01:02
^^ what he said :neutral_face:

**Comment by retailcoder** [comment] 2015-12-31 02:33
I'll close this issue, seeing that the depicted behavior isn't reproducible with the 2.0 build.

**Closed by retailcoder** 2015-12-31 02:33 UTC
Labels: bug, navigation
