### ISSUE TITLE
QuickFix for "Variable {x} is not used" inspection doesn't fix enough.

### ISSUE THREAD

**Issue by daFreeMan** [rubberduck-vba/Rubberduck#4321] opened 2018-08-29 19:00 UTC
Win10, Excel2016 (desktop), RD .3723

Starting with this code:

    Dim apptAddress As String
    apptAddress = projSettings.ApptPlusTableName

Applying the QuickFix for the `Variable 'apptAddress' is not used` inspection leaves this uncompilable code behind:

    apptAddress = projSettings.ApptPlusTableName

`apptAddress` is _assigned_, but not used, and the QuickFix should remove assignments for it, as well as the `Dim` statement.

Oddly, after the automatic reparse, it also triggered a false `Object variable 'apptAddress' is assigned without the 'Set' keyword` inspection. (see #4318).

**Comment by retailcoder** [comment] 2018-08-29 19:06
This is *sort-of* by-design: we *chose* not to remove assignments, because there's no easy (or cheap) way of knowing for sure whether the RHS expression of an assignment will have side-effects, i.e. removing RHS expressions could change the behavior of the code.

    Dim result As GridState
    result = CurrentTarget.GameGrid.TryHit(position)

Here if `result` isn't referenced further down that scope, the inspection will fire a result, and applying the quick-fix will result in the internal state of `CurrentTarget.GameGrid` to no longer be affected, which would introduce a bug.

IMO this definitely needs to be improved, but the enhancement needs to get the user's confirmation for every affected RHS expression. Maybe a (tabbed? or how do we deal with cross-module refs?) preview box would be the best UX here.

**Comment by MDoerner** [comment] 2018-08-29 19:15
I think the actual fix here would be to deactivate the quickfix in case there are assignments.

**Comment by retailcoder** [comment] 2018-08-29 19:18
@MDoerner that might spawn questions / "support" issues, but it's probably the most sensible solution.

**Comment by MDoerner** [comment] 2018-10-08 06:16
This is a duplicate of #2427.

**Closed** 2018-10-08 06:20 UTC
Labels: bug, duplicate, feature-inspection-quickfixes, up-for-grabs
