### ISSUE TITLE
Memory consumption

### ISSUE THREAD

**Issue by Gener4tor** [rubberduck-vba/Rubberduck#4652] opened 2018-12-18 16:13 UTC
The memory consumption of rubberduck is far to high for me.

Im my case - a  100 mb access-mdb with >100 Forms - MS-access uses ~110 MB RAM (open VBE but no rubberduck refresh)

After clicking "Refresh" in the code explorer, the Memory consumption grows and grows and grows and stops at ~ 680 MB.

This is far to much in my case because when I start working with my program, I get OutOfMemory-Errors soon. 

Even worse:  Features like e.g. intender or some renames tends to open a lot of forms in design mode. In some cases ms-access closes because of memory problems while Rubberduck is still working. After reopen the database, there were only half the changes done.

**Comment by retailcoder** [comment] 2018-12-18 16:18
32-bit host?

**Comment by Gener4tor** [comment] 2018-12-18 16:21
Version 2.3.0.4221
OS: Microsoft Windows NT 10.0.16299.0, x64
Host Product: Microsoft Office 2016 x86
Host Version: 16.0.4711.1000
Host Executable: MSACCESS.EXE

**Comment by bclothier** [comment] 2018-12-18 17:22
We acknowledge that this is a big issue and agree something needs to be done about it. However, it is not easy to fix and frankly, we need help with it. That's why we still have the issue #3347 open. Note that it has a number of linked issues. I will close this as a duplicate of that issue. Even so, we do welcome any assistance, especially on identifying what is really inside the large blob of unmanaged memory in order to resolve it.

**Closed by bclothier** 2018-12-18 17:22 UTC
