### ISSUE TITLE
False positive `Variable Foo is used but not assigned` when passed ByRef and assigned

### ISSUE THREAD

**Issue by IvenBach** [rubberduck-vba/Rubberduck#3770] opened 2018-02-16 19:45 UTC
Have the ability to pick up if a variable is passed `ByRef` and assigned where it's passed to.

```
Public Sub Test()
    Dim counter As Long
    If Foo(counter) Then
        Dim i As Long
        For i = 1 To counter
            ' ... Code that does stuff ...
            Debug.Print i
        Next
    End If
End Sub

Private Function Foo(ByRef barCount As Long) As Boolean
    barCount = 5
    Foo = True
End Function
```

**Comment by Vogel612** [comment] 2018-02-16 20:03
IIRC that's a known issue with the assignment recognition

**Comment by retailcoder** [comment] 2018-02-16 20:56
Not quite a resolver issue (not the resolver's job to track arguments)... the inspection once implemented these lookups - they were dropped (hmm, commit history is apparently clipped) for being WAY too expensive back then, *might* be worth giving it another go now that name lookups have been very much optimized... but then, it's still a recursive search:

 - Encounter an unassigned variable/parameter being passed `ByRef` as an argument
 - Figure out the `ParameterDeclaration` for that `ByRef` argument (use the declaration of the invoked member for that)
    - Mind named arguments, optional arguments, `ParamArray` arguments
 - Determine whether *that* declaration is assigned
 - Recurse until parameter is known to be assigned (or *unassigned*, actually)

**Comment by retailcoder** [comment] 2018-02-16 21:03
Tweaking the resolver could help though; if an `IdentifierReference` had an `AsArgument` property/method that would return the `ParameterDeclaration` (or `null` when not applicable - meta question for @Hosch250: how do non-nullable ref types deal with that??), then the inspection could skip that expensive lookup and simply (still recursively) iterate the applicable `reference.AsArgument.IdentifierReferences`  (the ones where `AsArgument.IsByRef` is true)... #FoorForThought

**Comment by Vogel612** [comment] 2018-02-16 21:09
If we were to implement an execution graph traversal, we should do it with lazy recursive initialization anyways. Everything else is computationally nonsensical.

We should have the memory to spare for most projects. I think we actually want to find assignments along the execution graph. That should be easier than proving there are no assignments.

**Comment by MDoerner** [comment] 2018-02-17 02:17
I mentioned this before, in particular in another issue for the same problem, which is closed by now, but I would like to mention it here again.

As soon as the method to which the variable is passed ByRef is a class method, in general, the question whether it will be assigned to in the method cannot be answered at compile time. There is no guarantee which implementation of the interface will be executed.

**Comment by bclothier** [comment] 2018-02-17 02:54
Are we sure? With Wayne's typelib API, it should be now possible, no? It includes a method to enumerate all possible interface implemented by that type.

**Comment by Vogel612** [comment] 2018-02-17 02:57
@bclothier the problem is that we need to go the other way round. Going from implementation to interface is trivial, the other way round is not generally solvable, especially not at compile time

**Comment by bclothier** [comment] 2018-02-17 03:03
No, but there are two strategies available to us.

1) We can inspect the typelib's flag and determine if it has `nonextensible` flag set. If so, then we know that it cannot call any random methods that don't exist on any interfaces.

2) Otherwise, we can consider all interfaces that a coclass implements from the typelib, assess if the method is defined on one of those interfaces. If it's not, then we can issue a warning that it may not exist at the runtime. 

That should cover the majority of the use cases where this is considered undesirable, I think.

**Comment by MDoerner** [comment] 2018-02-19 12:06
Please let me give two examples why it is not possible to determine whether a variable has been assigned at compile time (when passed ByRef).

The first problem is the general problem that whether a variable gets assigned can depend on some conditional.

```
Private Sub Whatever(ByRef foo As Long)
    If Len(InputBox("Write something!")) < 15 Then
        foo = 12
    End If
End Sub
```

Whether an assignment happens depends on the user input at runtime. Here, some code path analysis is necessary to determine whether the code falls into the category _might not be assigned_ or _is never assigned_.

The second problem is inheritence. Assume you have a class `MessageProvider` as below.

```
Public Function TryGetMessage(ByRef message As String) As Boolean
    'Do some stuff to retrieve the message.
    If success Then 
        message = retrievedMessage
    End If

    TryGetMessage = success
End Function
```

Moreover, you have the following subtypes.

`NullMessageProvider`:
```
Implements MessageProvider

Private Function MessageProvider_TryGetMessage(ByRef message As String) As Boolean
    MessageProvider_TryGetMessage = false
End Function
```

`StubMessageProvider`:
```
Implements MessageProvider

Private successValue As Boolean
Private messageValue As String

Private Function MessageProvider_TryGetMessage(ByRef message As String) As Boolean
    message = messageValue
    MessageProvider_TryGetMessage = successValue
End Function

Public Sub SetSuccess(success As Boolean)
    successValue = success
End Property

Public Sub SetReturnedMessage(message As String)
    messageValue = message
End Property
``` 

Now the question whether the variable in the following sub gets assigned depends entirely on the concrete type passed in, which again might depend on user input or other external factors not known at compile time.

```
Public Sub PrintProvidedMessage(messageProvider As MessageProvider)
    Dim providedMessage As String
    If messageProvider.TryGetMessage(message) Then
        Debug.Print message
    End If
End Sub
```

**Comment by retailcoder** [comment] 2018-02-19 16:34
@MDoerner you're absolutely correct. So, the best solution would be to determine if a variable/parameter is passed as a `ByRef` argument, and if so, ignore it. Right?

**Comment by Vogel612** [comment] 2018-02-19 16:59
@retailcoder that's definitely the simplest solution to the problem we're facing right now...

**Comment by MDoerner** [comment] 2018-02-19 17:20
Since the stated goal of the inspection is to find variables that are not defined, which has I would interpretas _never asdigned_, ignoring variables passed as arguments for (maybe just explicit?) ByRef parameters would make sense.

One edge case coming to mind is passing the variable explicitly ByVal for the ByRef parameter. This cannot be an assignment, but is a bit complicated to determine, I think.

**Comment by retailcoder** [comment] 2018-12-07 19:52
`ByRef` assignments are now handled to the best of resolver's knowledge AFAIK; code in the original post would no longer trigger the inspection.

**Closed by retailcoder** 2018-12-07 19:52 UTC
Labels: code-path-analysis, difficulty-03-duck, enhancement, resolver
