### ISSUE TITLE
Code parser stuck

### ISSUE THREAD

**Issue by TZubiri** [rubberduck-vba/Rubberduck#2121] opened 2016-07-22 17:47 UTC
[rubberduck.txt](https://github.com/rubberduck-vba/Rubberduck/files/378777/rubberduck.txt)

Stuck at "Loading References"

**Comment by TZubiri** [comment] 2016-07-22 17:50
I'm sorry if I am being vague, let me know what other info I can provide.

**Comment by Vogel612** [comment] 2016-07-22 17:58
hmmm... From the log I take that this is not happening directly at startup, but rather after you clicked onto "Test Explorer", correct?

Because interestingly the Parser seems to be stuck in a loop starting the parse-process for all your modules after the process was completed...

The same 5 modules are changing to "Pending" over and over in the last lines of the log. Before that there's a short time where the RawInput API has a few `invalid handle` messages. Aside from that this should *definitely* not be stuck at "Loading References"

**Comment by TZubiri** [comment] 2016-07-22 18:03
Each loop corresponds to each time I hit the refresh button next to the parsing state.
On another project this is the debug message that appears each time I refresh. Same problem
2016-07-22 15:02:03.0400;DEBUG;Rubberduck.App;App handles StateChanged (ResolvingReferences), evaluating menu states...;

**Comment by TZubiri** [comment] 2016-07-22 18:04
This is happening at startup

**Comment by Hosch250** [comment] 2016-07-22 18:05
I fixed a bug with this not too long ago when the Rubberduck Source Control 1.0 library is referenced.  Do you have a reference to this library?

**Comment by TZubiri** [comment] 2016-07-22 18:08
No. The only Rubberduck library I have is called rubberduck.
I installed it with this script because I didn't have admin privileges:
https://github.com/rubberduck-vba/Rubberduck/issues/2086

**Comment by Hosch250** [comment] 2016-07-22 18:09
OK.  I'm not sure what's up with this.  Is it a consistent issue in this project, or does it only happen randomly?

**Comment by TZubiri** [comment] 2016-07-22 18:11
[rubberduck.txt](https://github.com/rubberduck-vba/Rubberduck/files/378798/rubberduck.txt)
I tried it on a 3rd project and it is still stuck at "resolving references".

**Comment by Hosch250** [comment] 2016-07-22 18:12
Peculiar.  That log should result in a parser error.

**Comment by Vogel612** [comment] 2016-07-22 18:23
Same `NoViableAltException` shows up in the log attached in #2113

**Comment by TZubiri** [comment] 2016-07-22 18:23
The test explorer being empty is what originally caused this.
I added a test module with a testMethod1 stub, nothing appears in the test explorer, no clue how to run it.
Run all tests doesn't runn the testModule1 I just added which should fail.
[rubberduck.txt](https://github.com/rubberduck-vba/Rubberduck/files/378816/rubberduck.txt)

**Comment by Hosch250** [comment] 2016-07-22 18:25
If there is a parser/resolve declarations error, the tests won't be able to run.

**Comment by TZubiri** [comment] 2016-07-22 18:27
[rubberduck.txt](https://github.com/rubberduck-vba/Rubberduck/files/378825/rubberduck.txt)
Actions done on this log:
Deleted old test method
Opened test explorer
Added new test module (with test method stub and early binding)
Ran all tests.

**Comment by Hosch250** [comment] 2016-07-22 18:27
Did it work?

**Comment by TZubiri** [comment] 2016-07-22 18:28
No. Test should fail, but nothing happens

**Comment by Hosch250** [comment] 2016-07-22 18:29
Would it be possible to share the project?  It sounds like there is a parser error somewhere that should be addressed.

**Comment by TZubiri** [comment] 2016-07-22 18:32
I'll see what I can do.

**Comment by TZubiri** [comment] 2016-07-22 18:39
What files do you need?

**Comment by Hosch250** [comment] 2016-07-22 18:39
The .xlsx/.xlsm file should be good.

**Comment by TZubiri** [comment] 2016-07-22 18:45
[rubberduck.txt](https://github.com/rubberduck-vba/Rubberduck/files/378853/rubberduck.txt)
I added a test method on a healthy file that was showing "ready" and it is stuck on pending now.
[Macro - Copy.xlsm.txt](https://github.com/rubberduck-vba/Rubberduck/files/378862/Macro.-.Copy.xlsm.txt)

**Comment by TZubiri** [comment] 2016-07-22 18:47
Note: I can't upload any of the original projects.

**Comment by Hosch250** [comment] 2016-07-22 18:56
I can't reproduce this.  It may be because the PS script you ran did not install Rubberduck correctly.

**Comment by TZubiri** [comment] 2016-07-22 19:00
Any clue as to how I might have access to unit tests from a clean install with no admin privileges?

**Comment by Hosch250** [comment] 2016-07-22 19:01
Not really.  I will probably be doing a release later today (unless some super serious bug shows its ugly head), so you could try uninstalling and installing the new release.

**Comment by TZubiri** [comment] 2016-07-22 19:02
Ok

**Comment by Hosch250** [comment] 2016-07-29 14:42
Is this still an issue?

**Comment by TZubiri** [comment] 2016-07-29 18:12
Yes. I reinstalled.
Here is the new log 
[RubberduckLog.txt](https://github.com/rubberduck-vba/Rubberduck/files/391099/RubberduckLog.txt)
And here is the .xlsm file
[Dev.txt](https://github.com/rubberduck-vba/Rubberduck/files/391101/Dev.txt)

**Comment by Hosch250** [comment] 2016-07-29 18:25
![untitled](https://cloud.githubusercontent.com/assets/6299719/17259173/ee147cb8-558f-11e6-80c1-db90da7c9e54.png)

**Comment by Hosch250** [comment] 2016-07-29 18:25
Seems to work fine here.

**Comment by TZubiri** [comment] 2016-07-29 20:17
What excel version is that?
I have 2010

**Comment by Hosch250** [comment] 2016-07-29 20:18
2016 on Windows 10, but the same IDE.

**Comment by Hosch250** [comment] 2016-07-29 20:18
It doesn't make a difference.

**Comment by camosborn21** [comment] 2016-10-28 02:32
I'm having the same issue. Program hangs on "Resolving References" when I parse open projects. The hang up seems to be, for me, directly tied to having the Rubberduck reference turned on in the reference library. If I use late binding it works just fine.

**Comment by retailcoder** [comment] 2016-10-28 02:38
@camosborn21 interesting. can you confirm the build number? 2.0.9?

**Comment by camosborn21** [comment] 2016-10-28 02:55
Yes 2.0.9

Also, I'm having frequent, though not as near as I can tell consistent, crash to desktop errors when I close Access. Which you have noted in the build notes for 2.0.9; just thought I'd let you know I'm seeing the same glitch on both my Windows7/Office 2010 machine as well as Windows 10/Office 2016 machine.

**Comment by retailcoder** [comment] 2016-10-28 03:06
@camosborn21 that crash on exit has been narrowed down to the dockable toolwindows and the commandbar, see the teardown timeline in #2322: *something* is preventing proper destruction of these objects. The crash is host-independent.

**Comment by camosborn21** [comment] 2016-10-28 05:39
@retailcoder Thanks for the info on the crashing. Let me know if there's any additional info I can provide you for you to see what's going on with the "Resolving References" hang up.

**Comment by retailcoder** [comment] 2017-01-05 15:25
ref. #2459

**Closed by retailcoder** 2017-01-05 15:25 UTC
Labels: bug, code-parsing
