### ISSUE TITLE
Refactor: Rename triggers reparsing every time

### ISSUE THREAD

**Issue by scorchio** [rubberduck-vba/Rubberduck#1233] opened 2016-03-23 12:54 UTC
This is actually the first time I've tried to use this functionality and I realized that it's re-parsing my complete project every try I try to rename a variable. This takes quite a long time (more than a minute per var) as we're talking about a project with 40+ modules. It would be really nice to speed this up somehow, as it's not quite usable for me as it is.

**Comment by retailcoder** [comment] 2016-03-23 14:32
Thanks for your feedback!

[This article](https://rubberduckvba.wordpress.com/2016/02/06/what-do-parsing-and-resolving-mean-anyway/) explains how parsing/resolving works.

The *parsing* will (should?) only re-process modules that have been modified by the refactoring (if an identifier is used *everywhere*, that would be all modules indeed) - the *resolving* though, needs to re-process *everything*. From that article:

> We still need to re-walk every parse tree and resolve every identifier usage, every time a single module’s been parsed. The resolver task needs to start when all modules have completed parsing, and to cancel when any module starts a re-parse. If we could somehow examine a diff of the pre and post parse trees, and determine exactly what declarations and what identifier references have been added or removed, perhaps we wouldn’t need to do the whole thing.

> But because we can’t know if the modified code is referring to things declared in another module, we need to make sure everything is kept in sync, …and the cost of this is to walk the parse trees and re-resolve everything again.

The good news is that the 2.0 resolver completes in a fraction of the time (like, between 100% and 3000% faster) the 1.x resolver does, and it's not blocking the UI while it's doing that.

The plan for 3.0 (boy we're not there yet!) is to restructure things in such a way that we can be more surgical about how resolving works, and figure out a way to no longer have to treat an entire module as a "unit", so that we could be re-parsing only the modified procedure and still keep everything in sync with the actual code in the code panes.

Most VBE add-ins work at the *code pane* level, treating the code as, essentially, text. Rubberduck turns the code into a parse tree and walks the parse tree to create a *symbol table*, and using that *symbol table* and literally *implementing* VBA's scoping rules, it walks the parse trees and resolves all identifier references to a *declaration*, which is what allows it to perform things like *refactor/rename* and *refactor/extract method*.

Picture this (legal!) code in `Module1`:

    Option Explicit
    
    Private Type Module1
        Foo As Integer
        Bar As Integer
    End Type
    
    Private Module1 As Module1
    
    Private Foo As Integer
    Private Bar As Integer
    
    Public Sub DoSomething()
        Dim Foo As Integer
        Bar = 42
        Foo = Bar
        Module1.Foo = Foo
    End Sub

Renaming the `Foo` UDT member to `RENAMED` results in this (with the current [next] build at least):

    Option Explicit
    
    Private Type Module1
        RENAMED As Integer
        Bar As Integer
    End Type
    
    Private Module1 As Module1
    
    Private Foo As Integer
    Private Bar As Integer
    
    Public Sub DoSomething()
        Dim Foo As Integer
        Bar = 42
        Foo = Bar
        Module1.RENAMED = Foo
    End Sub

This is what the resolver does - it makes the difference between Ctrl+H, and an *actual* "rename" refactoring. The thing is, after the rename refactoring is completed, the symbol table needs to be updated - there's no longer a UDT member named `Foo` under the `Module1` private type, and the identifier is now 7 characters, not 3; in the line `Module1.RENAMED = Foo`, the reference to the `Foo` local variable has now shifted 4 characters to the right, and if we don't adjust that immediately, the next operation will completely wreck the code.

The problem is that "adjusting that", the way things are in v1.4.3, involves re-processing everything. Same goes for anything that modifies code - including refactorings, and inspection [not-so-]quick-fixes.

We definitely want to work toward figuring out a more efficient way to do these adjustments - consider it on the roadmap.

**Closed** 2016-07-20 17:10 UTC
Labels: code-parsing, enhancement, status-bydesign
