### ISSUE TITLE
Refactor|Rename doesn't do anything on name collision

### ISSUE THREAD

**Issue by daFreeMan** [rubberduck-vba/Rubberduck#3371] opened 2017-09-12 13:55 UTC
Starting with:

```VBA
Private pFoo as String

Public Property Get Foo() As String
  Foo = pFoo
End Property
Public Property Let Foo(ByVal value As String)
  pFoo = value
End Property
```

Refactoring to:

```VBA
Private Type TBar
  Foo as String
End Type
Private this as TBar

Public Property Get Foo() As String
  Foo = this.Foo
End Property
Public Property Let Foo(ByVal value As String)
  this.Foo = value
End Property
```

As a midpoint step, I've got:

```VBA
Private Type TBar
  pFoo as String
End Type
Private this as TBar

Public Property Get Foo() As String
  Foo = pFoo
End Property
Public Property Let Foo(ByVal value As String)
  pFoo = value
End Property
```

Attempting to `Refactor|Rename` `pFoo` to `Foo`, I get a name conflict warning message from RD which is expected. Clicking `Continue` does continue, but yields no code change. I would expect to see:

```VBA
Private Type TBar
  Foo as String
End Type
Private this as TBar

Public Property Get Foo() As String
  Foo = Foo
End Property
Public Property Let Foo(ByVal value As String)
  Foo = value
End Property
```
Which wouldn't compile cleanly, but I could then type or S&R for `Foo` -> `this.Foo` where appropriate.

**Comment by retailcoder** [comment] 2017-09-12 14:00
linking #875

**Comment by BZngr** [comment] 2020-01-19 18:05
Perhaps something changed in the `RenameRefactoring` since this issue opened.  In v2.5 I can `RenameRefactor` `pFoo` to `Foo` successfully starting from the midpoint step and get the expected result described above.  But, I'm thinking that renaming `pFoo` to `Foo` should only rename the single, local, (undeclared) instance of `pFoo` (whichever was selected) and leave all others untouched.  

So...Although this issue can be closed as not reproducable, I'm wondering if there is a different issue identified by fact that both `pFoo`'s in the properties are renamed in the above scenario?

**Comment by retailcoder** [comment] 2020-01-19 18:20
Yeah the name validation / clash-verification logic was revised at some point leading up to 2.5.0; this one is probably a dupe of an issue about the clash-verification logic that was closed with the merge of a PR, leaving this one open.

Not sure I'm following the local `pFoo` problem - assuming a parse happened, I'm not seeing how the resolver could possibly treat these local undeclared variables as anything other than undeclared locals (does the toolbar not say something to that effect? or it wrongly says the local undeclared pFoo is a UDT member?)

**Comment by MDoerner** [comment] 2020-01-19 18:28
The new problem is a bug in the resolver. When we resolve undeclared variables, we [reuse already found instances of the variable](https://github.com/rubberduck-vba/Rubberduck/blob/5d7369a3c8ed8df1848bd3583c0fb6a0e97887b7/Rubberduck.Parsing/VBA/DeclarationCaching/DeclarationFinder.cs#L989). Unfortunately, the check is by the qualified name of the enclosing procedure, which is identical for Let, Set and Get. We will have to split that according to declaration type.

**Closed** 2020-01-19 19:47 UTC
Labels: bug, feature-refactorings, refactoring-rename, resolver
