### ISSUE TITLE
Source Control Issue - crash on init, selecting working directory or cloning

### ISSUE THREAD

**Issue by JonTheNiceGuy** [rubberduck-vba/Rubberduck#1814] opened 2016-06-14 09:56 UTC
I am trying to use RubberDuck VBA to perform GIT commits of my database. I am able to perform a repeatable crash on my machine when trying to perform any actions to start the connection from MS Access to Git.

1. Starting from a new database file (C:\Users\SpriggsJ\Documents\Database1.accdb)
1. Close the initial table
1. Select the "Create" Tab on the ribbon, select "Visual Basic"
1. Create a new module, by right clicking on "Database1 (Database1)", select "Insert", select "Module"
1. Save the new module, by pressing Ctrl+S
1. Name the module "Module 1"
1. Select "Rubberduck" menu.
1. Select "Source Control option"
1. Select the "Settings" tab, and set the settings for User Name, Email Address, Default Repository Location. Click Update.
1. Click the unlabelled button, with the tool tip "Init New Repo from this Project"
1. Select a path (C:\Users\spriggsj\Documents\RD-Demo), click OK
1. Crash.

[Trace rubberduck.log.txt](https://github.com/rubberduck-vba/Rubberduck/files/313570/rubberduck.log.txt)
[Debug rubberduck.log.txt](https://github.com/rubberduck-vba/Rubberduck/files/313632/rubberduck.log.txt)

Similarly:
1. Pre-initialize the Git Repo using the Github application.
2. re-open the database file mentioned before
3. go into VBA
4. Select "Rubberduck" menu
5. Select "Source Control"
6. Click the unlabelled button, with the tool tip "Open working directory"
7. Select the same path as before, click OK.
8. Crash

[rubberduck.log.txt](https://github.com/rubberduck-vba/Rubberduck/files/313621/rubberduck.log.txt)

I've noticed the same when trying to clone a repo.

This is on Windows 7 Professional, using Microsoft Office Professional 2013.

**Comment by Hosch250** [comment] 2016-06-14 20:00
No repro.

**Comment by JonTheNiceGuy** [comment] 2016-06-14 21:02
What can I do to help? Would something like process explorer help, is there a version with enhanced debugging I could run (or you could build) that might identify where the issues are?

I'm behind a corporate proxy with little unfettered internet access, so if there are online resources it's calling out to, that might be an issue?

The machine is an x64, but the version of office is the x86 version, so that might not be helping?

I don't know what else to suggest? Might it be worth populating the repo section of the config file to circumvent any initialisation issues and see if it just "appears"? Fortunately I'm just working on this one project, so if there's a small manual work-around on this issue, I don't mind using it.

**Comment by Hosch250** [comment] 2016-06-14 21:11
It shouldn't be calling out to any external resources, except for Clone.  If you could provide a stack trace, or maybe a minimal, verifiable example, it would help.  I wonder if there is a stray COM exception I need to catch somewhere?  How far does it get in it?  Does it crash trying to reparse after the repo is created, or does it crash instantly?

**Comment by JonTheNiceGuy** [comment] 2016-06-14 21:27
I'm not sure how to provoke a stack trace, and the example I gave before you can't reproduce.

It doesn't create the repo files in the directory when you perform the init, and I can't see anything from the debug or trace files submitted before that would imply it was or wasn't working during opening an existing repo.

I'll run it up in process explorer tomorrow (it's 10:30pm here now) and see if anything screams at me.

**Comment by Hosch250** [comment] 2016-06-14 21:29
Can you enable all logging (Trace level in the settings) and upload the log file from "C:\Users\{username}\AppData\Roaming\Rubberduck"?

**Comment by JonTheNiceGuy** [comment] 2016-06-14 21:29
Forgot to add, it does crash immediately.

**Comment by JonTheNiceGuy** [comment] 2016-06-14 21:30
It's in the original bug report

**Comment by Hosch250** [comment] 2016-06-14 21:30
Oh, right.  Thanks for the report, one way or another.

**Comment by JonTheNiceGuy** [comment] 2016-06-14 21:31
I'll re-run that tomorrow as well though.

**Comment by Hosch250** [comment] 2016-06-14 21:32
Do you know which build you are running?  Is it the latest 2.0 beta update 1, or are you building from VS?

**Comment by JonTheNiceGuy** [comment] 2016-06-14 21:36
Beta1

**Comment by Hosch250** [comment] 2016-06-14 21:37
Cool.  At this point, I'm really kind of stumped, but I'll keep an eye out for potential causes.

**Comment by JonTheNiceGuy** [comment] 2016-06-14 21:44
I don't have access to VS to step through, but might it be worth adding more trace lines to the git sequences of code for a custom build for just me and I can try running that to see what happens?

**Comment by Hosch250** [comment] 2016-06-14 21:48
I'll probably do another release this Friday--would that be soon enough?

**Comment by JonTheNiceGuy** [comment] 2016-06-14 22:21
Sure :) that would be awesome! This project is 3 years old now, it would
just be useful to keep it in git :)

**Comment by daFreeMan** [comment] 2016-06-15 15:26
I just hit this too.

Existing project
A few forms, LOTS of code
"Init new repo from this project"
immediate crash.

Here are the Doc Watson logs in the hopes that some of this is useful:
[RD Access crash.zip](https://github.com/rubberduck-vba/Rubberduck/files/316451/RD.Access.crash.zip)

It seems that the logging was not turned on when it crashed, so I don't have the RD logs. I will attempt to reproduce and provide logs.

**Comment by Hosch250** [comment] 2016-06-15 16:09
This build has some trace-level logging: https://1drv.ms/u/s!Arb7hwtzEkcogssrOHvqs8sRkrjUMQ

It won't tell me what the error is, but it might show me where the error is so I can figure out the what.

**Comment by Hosch250** [comment] 2016-06-15 20:09
I *think* I finally solved this.  The VBE's ActiveProject is probably null.  I'll need to check if it is, and if there is only one VBProject, I'll replace it with that.  Otherwise, I'll raise an error.

**Comment by Hosch250** [comment] 2016-06-15 20:36
I won't close this until you guys verify it, but I'm pretty sure this is the issue.

**Comment by JonTheNiceGuy** [comment] 2016-06-16 09:03
That build you provided doesn't work - I get "Rubberduck Could not be loaded, Remove it from the list of available add-ins?" Yes/No.

If I swap back to the Beta1 build, is there something I can perform from the "Immediate Window" to determine whether the condition you're referring to is set?

**Comment by Hosch250** [comment] 2016-06-16 15:25
Just make sure that the VBE.ActiveProject isn't Nothing.

**Comment by JonTheNiceGuy** [comment] 2016-06-17 10:01
On my version of MS Access, here's what I've got.
![capture](https://cloud.githubusercontent.com/assets/228671/16147379/aa79b7ec-347a-11e6-829d-96f6d7516826.PNG)

Note, VBE.ActiveProject doesn't exist, but VBE.ActiveVBProject does.

**Comment by guyfletch** [comment] 2016-06-17 10:10
I'm getting a similar issue - every time I try to create a new repository, or import one that I've created using git, the VBE and Excel crash and have to restart.

**Comment by Hosch250** [comment] 2016-06-17 15:22
Well, I can't reproduce.  I did make a change that might address this, and added logging to try to help me figure out where/what is happening.  I'll make a release tonight, so please check it sometime next week.

**Comment by JonTheNiceGuy** [comment] 2016-06-17 15:24
Will do. Very many thanks for your help so far!

--
Jon "The Nice Guy" Spriggs

**Comment by Hosch250** [comment] 2016-06-18 04:21
Please download the updated release and try again.

**Comment by mmorrisisund** [comment] 2016-06-20 01:44
I hate to pile on, but I'm experiencing the same issue with Excel.  Just used the most recent updated release.  I used the Init Repo method and it did create the working directory and a copy of all files in the project.  It also added a specific log file that is not the in the project which is attached below.  Not sure if you need any more specific details, but the RD log is attached as well.


[DataSourceManagerForm.zip](https://github.com/rubberduck-vba/Rubberduck/files/322600/DataSourceManagerForm.zip)

[rubberduck.zip](https://github.com/rubberduck-vba/Rubberduck/files/322601/rubberduck.zip)

**Comment by retailcoder** [comment] 2016-06-20 03:08
@mmorrisisund there is a rubberduck.sourcecontrol.config xml file that gets saved in your user's `AppData` folder if I recall correctly; this file contains information about the repositories Rubberduck knows about - there have been instances in (much) earlier versions, of that file containing illegitimate data that wrecked the whole SC feature... is that file in the .zip?

We need to make that file more accessible and discoverable... @Hosch250 what do you think?

**Comment by mmorrisisund** [comment] 2016-06-20 03:12
Nope, but here you go.

[SourceControl.zip](https://github.com/rubberduck-vba/Rubberduck/files/322667/SourceControl.zip)

**Comment by Hosch250** [comment] 2016-06-20 04:05
Sorry you are having this trouble.  I'm running the debug build and cannot reproduce any of this--maybe it is specific to the release build?  This seems really, really strange.  I don't use many events for this, but I'll check for potential events that are running out of order.  It apparently is crashing when the branches tab is refreshing, according to the log--can the rest of you see if you can duplicate the issue with the latest release and upload your logs?  I'll definitely keep looking into this.

**Comment by JonTheNiceGuy** [comment] 2016-06-20 14:59
Latest release works for me :)

Thanks Hosch250

I'm happy for this to be closed, should the other people with issues also have had them resolved in this release.

**Comment by Zak-Michael-Armstrong** [comment] 2016-06-20 15:01
I've still has this with beta (1 and 2). But it appears to be just me.

**Comment by mmalixi** [comment] 2016-06-21 18:39
I installed the beta today and was consistently crashing when trying to initialize a repo or open a working directory.  Based on the earlier comments, I tried to turn on the logging but it would not save any changes I made to the log level selection and clicking on "Show Log Folder" would silently fail.  Looking in ~/AppData/Roaming, there was no Rubberduck folder.  I uninstalled and tried Beta 1 with the same issue.  After uninstalling THAT and then installing 1.4.3, the profile folder was created.  After seeing that, I decided to try my luck with the beta again.

I have now upgraded to Beta 2 again and can now set the logging levels but it is now successfully allowing me to connect to my local git and perform commits and such. 

Just wanted to put that out there as a possible approach to anyone else experiencing crashing problems.

**Comment by retailcoder** [comment] 2016-06-21 18:41
@Hosch250  this is definitely starting to look like a permission issue - e.g. we're trying to write the SourceControl config file in a place not all users have permission to write. What was the reason to not put that file in the same folder as the settings file? @ckuhn203?

**Comment by Hosch250** [comment] 2016-06-21 18:44
*Jaw hits the floor*  So *that's* it!!!!  @retailcoder The file *is* in the same directory as the settings file.  @Zak-Michael-Armstrong @mmalixi the way we handle settings changed so the folder is not correctly created on first install.  There is an unreleased patch for this that creates the folder when RD boots.

**Comment by Hosch250** [comment] 2016-06-21 18:46
Credit to @comintern for implementing the patch.  I'm closing this issue--if it happens again after the next release, please make a new issue.

**Closed by Hosch250** 2016-06-21 18:46 UTC
Labels: bug, source-control-integration

**Comment by ckuhn203** [comment] 2016-06-21 18:59
Anyone know which PR it was for posterity?

**Comment by Vogel612** [comment] 2016-06-21 19:00
That'd be #1870

**Comment by ckuhn203** [comment] 2016-06-21 19:23
:+1:
