### ISSUE TITLE
AssignmentIsNotUsed inspection result caused by declaring variable within If...Then...Else statement

### ISSUE THREAD

**Issue by IvenBach** [rubberduck-vba/Rubberduck#5469] opened 2020-04-24 00:12 UTC
**Rubberduck version information**
Version 2.5.0.17253
OS: Microsoft Windows NT 10.0.18362.0, x64
Host Product: Microsoft Office 2016 x64
Host Version: 16.0.4978.1000
Host Executable: EXCEL.EXE

**Description**
When the declaration for a variable is within an If...Then...Else statement it comes up as an AssignmentNotUsedInspection result. Declared outside yields no inspection result. This leads me to believe that it's not taking the If statement into consideration and assuming the True assignment is being overridden by the False assignment.

**To Reproduce**
```vba
Public Sub MVCE_YeldsResult()
    If True Then
        Dim foundAsNotUsed As String '<-- inside statement
        foundAsNotUsed = "Yep"
    Else
        foundAsNotUsed = "Nope"
    End If
    Const SomeConstant As String = "FooBar"
    Debug.Print SomeConstant & " " & foundAsNotUsed
End Sub

Public Sub MVCE_YieldsNoResult()
    Dim foundAsNotUsed As String '<-- outside statement
    If True Then
        foundAsNotUsed = "Yep"
    Else
        foundAsNotUsed = "Nope"
    End If
    Const SomeConstant As String = "FooBar"
    Debug.Print SomeConstant & " " & foundAsNotUsed
End Sub
```

1. Add code above to a module and parse. Then view Code Inspections window.

**Expected behavior**
When variable declaration is inside an If...Then...Else statement the inspection should be able to understand the conditional assignment and not bring up an inspection.

**Comment by MDoerner** [comment] 2020-04-24 09:27
Duplicate of #4754

**Closed by MDoerner** 2020-04-24 09:27 UTC
Labels: duplicate
