### ISSUE TITLE
ArgumentNullException was unhandled by usercode

### ISSUE THREAD

**Issue by PeterMTaylor** [rubberduck-vba/Rubberduck#1553] opened 2016-05-20 11:48 UTC
Just documentating here an error (the second time I used it) within Visual Studio after closing down Excel application (32-bit 2010) within Visual Studio when doing a small test. The fail occurs with the dispatcher section of Rubberduck app.

This may not be that important but I am learning...

![2016-05-20 3](https://cloud.githubusercontent.com/assets/2254567/15426781/24634a9e-1ed4-11e6-9509-e38cf3740fec.png)
![2016-05-20 2](https://cloud.githubusercontent.com/assets/2254567/15426782/2465c5ee-1ed4-11e6-9883-c94493ac8e9c.png)
![2016-05-20 1](https://cloud.githubusercontent.com/assets/2254567/15426784/24694958-1ed4-11e6-8fea-c07830b89c04.png)
![2016-05-20](https://cloud.githubusercontent.com/assets/2254567/15426783/2466e848-1ed4-11e6-8567-94016a7df481.png)

**Comment by Hosch250** [comment] 2016-06-10 02:18
Is this still an issue?  I've not been having any trouble here.

**Comment by Hosch250** [comment] 2016-06-29 23:29
Duplicate of https://github.com/rubberduck-vba/Rubberduck/issues/1611

**Closed by Hosch250** 2016-06-29 23:29 UTC
Labels: bug, duplicate
