### ISSUE TITLE
After exiting and reentering Access, add-ins are listed but menus are missing

### ISSUE THREAD

**Issue by mkrause01** [rubberduck-vba/Rubberduck#3799] opened 2018-02-27 20:53 UTC
Rubberduck version: Version 2.1.2.2897
Operating System: Microsoft Windows NT 10.0.16299.0, x64
Host Product: Microsoft Office 2016 x64
Host Version: 16.0.8431.2153
Host Executable: MSACCESS.EXE

After closing and reopening Access, add-in menus aren't available.

Using MZTools and RubberDuckVBA.  Both are listed in the add-ins list but neither appears anywhere in the Access VBA IDE.  Still no menus after exiting and reentering Access, even after closing Outlook (but it's probably still resident) and Excel.

I checked in Task Manager and found an Access instance but that wasn't displaying on the screen.  Upon killing that instance and restarting Access, RD and MZ menus are now available but I needed to refresh my project in RD Code Explorer.

**Comment by Vogel612** [comment] 2018-02-27 20:56
Could you please attach the full log? Also were you able to reproduce the problem more than once?

**Comment by bclothier** [comment] 2018-10-26 03:02
Closing this as a duplicate of #3095

**Closed by bclothier** 2018-10-26 03:02 UTC
Labels: bug
