### ISSUE TITLE
[Feature Request] Have inspections ignore specific Variable Names.

### ISSUE THREAD

**Issue by Zak-Michael-Armstrong** [rubberduck-vba/Rubberduck#1995] opened 2016-07-08 13:21 UTC
I have a couple of variable names which I use extensively throughout my projects but which get flagged by the naming inspection. 

As an example, this Code Block:

    Dim LB1 As Long, UB1 As Long
    Dim LB2 As Long, UB2 As Long
    AssignArrayBounds Array, LB1, UB1, LB2, UB2

    Dim ix As Long, iy As Long
    For ix = LB1 To UB1
        For iy = LB2 to UB2

Appears **extensively** throughout my projects. 

Those statements (along with `i, j, k`) account for **96%** of all "Maintainability and Readability Issues" that get flagged by the Code Inspections. I don't want to disable the inspections because the handful of other things they flag are often invaluable, but wading through 433 inspections to find the 17 that **aren't** triggered by the above is irritating and difficult.

Is it possible to have RD maintain a list of Variables / Entire Lines to ignore from inspections?

**Comment by retailcoder** [comment] 2016-07-08 13:41
[status-planned] / duplicate of #1681

**Closed by retailcoder** 2016-07-08 13:41 UTC
Labels: code-inspections, duplicate, feature-request

**Comment by retailcoder** [comment] 2016-07-08 13:54
That said... those *are* terrible names :wink:
