### ISSUE TITLE
Hotkeys Working when in Background

### ISSUE THREAD

**Issue by addohm** [rubberduck-vba/Rubberduck#2993] opened 2017-04-28 15:52 UTC
The hotkeys seem to work regardless of whether or not the program is in the foreground.  i.e. When I press Ctrl+T in another program, the find symbol popup opens up in the background and stops the code from running.

**Comment by retailcoder** [comment] 2017-04-28 15:55
Hmm, that's a regression. The hotkeys are *supposed* to disengage whenever the VBE is no longer the active window.

**Comment by addohm** [comment] 2017-04-28 18:19
I did an up date yesterday but that didn't seem to change anything.

**Comment by retailcoder** [comment] 2017-04-28 18:21
Which version are you running?

**Comment by addohm** [comment] 2017-04-28 18:38
2.0.13 and VBA 6.5

**Comment by retailcoder** [comment] 2017-05-03 14:36
Can't reproduce with 2.0.13.32288 release build on Office 2010 x86 (32-bit) / Win7 x64. Hotkeys behave exactly as intended here.

**Comment by addohm** [comment] 2017-05-03 17:15
You may or may not remember, but I'm not producing this error with MS
Office.  Rockwell Automation's FactoryTalk View SE.



Adam

**Comment by ThunderFrame** [comment] 2017-05-03 20:29
I seem to remember Carlos Q saying Rockewell Automation was special. I'll need to find the email/reference.

**Comment by addohm** [comment] 2017-05-03 21:11
@retailcoder @ThunderFrame Here is a photo of it happening to me.  If I press Ctrl+T to toggle a tag in Logix Studio, the find symbol popup opens and it stops all my VB code.  I've changed the hotkey to prevent it for now.

![thisjusthappened](https://cloud.githubusercontent.com/assets/25333107/25681736/68fee080-3023-11e7-8cff-78e6ec62a797.png)

**Comment by addohm** [comment] 2017-05-05 00:22
Is uninstalling RubberduckVBA safe?

**Comment by retailcoder** [comment] 2017-05-10 00:18
@addohm sorry I missed that last notification, our chatbot was offline for a while.. You can safely uninstall RD from the control panel's *add/remove programs* screen. Just make sure all VBE host applications are closed (including via task manager) first.

With the Rockwell dll we could implement host-specific functionality, including unit testing support and host-specific inspections, if you can think of any.

**Comment by bclothier** [comment] 2018-10-26 04:38
Closing this as cannot reproduce and may be host-specific. If this is a issue that needs fixing in the Rockwell host, any PR would be welcome.

**Closed by bclothier** 2018-10-26 04:38 UTC
Labels: bug, critical, feature-hotkeys, status-norepro
