### ISSUE TITLE
Code inspections should identify use of standard constants, and variables in compiler directives

### ISSUE THREAD

**Issue by ThunderFrame** [rubberduck-vba/Rubberduck#1013] opened 2016-02-01 19:34 UTC
I seem to recall inheriting code that made use of a const or variable in a compiler directive. IIRC, depending on the state of the compiler, sometimes the value would evaluate in the directive and drop into the *If*, and other times it would be uninitialized and drop into the *Else*, so it was a hard bug to find...

```
'Mybyte will be 100, most of the time
Const MyConst As Long = 6

#If MyConst = 6 Then
  Const Mybyte As Byte = 50
#Else
  Const Mybyte As Byte = 100
#End If
```

**Comment by Vogel612** [comment] 2016-02-02 11:09
Probably blocked by Parser support for Compiler directives for now. See #1012 and related

**Comment by retailcoder** [comment] 2016-02-02 16:57
@Vogel612  is correct. There is no reason for the parser to "miss" identifier usages within `#PrecompilerDirectives` at all. The problem is that, well, `#PrecompilerDirectives` completely break the parser and the entire module ends up unparsed/unresolved.

**Comment by retailcoder** [comment] 2016-02-02 16:57
Closing as a dupe of #1012

**Closed by retailcoder** 2016-02-02 16:57 UTC
Labels: bug, duplicate, vba-grammar

**Comment by ThunderFrame** [comment] 2016-02-02 19:26
I didn't raise this one as a bug. It was more a suggestion for a specific inspection warning. Looking back, I wasn't very clear...

Using a standard constant (or variable) in a compiler directive is valid syntax, but it is not logically valid because the standard constant will not have a value at the time the compiler directive is pre-compiled. Although in weird pre-pre-compiling cache situations, *sometimes* VBE does have a value assigned to the constant, but the behaviour is unpredictable. 

So I think this should be a special inspection warning, once compiler directives can be parsed properly.
