### ISSUE TITLE
False `FunctionReturnValueDiscarded` report on a sub call

### ISSUE THREAD

**Issue by Lx** [rubberduck-vba/Rubberduck#6043] opened 2022-10-21 22:12 UTC
**Rubberduck version information**
```text
Version 2.5.2.5906
OS: Microsoft Windows NT 10.0.22621.0, x64
Host Product: Microsoft Office x64
Host Version: 16.0.15629.20208
Host Executable: EXCEL.EXE
```

**Description**
In a function of mine (shown below), I set the function's return value to an instance of some class module in my project, but then I call a sub on that instance before finishing.  This causes Rubberduck to erroneously believe that I'm discarding a function return value.

**To Reproduce**
1. Have a class module called `TemporarySheetObject`, with a `Public Sub Init(OneParam As Variant)`.
2. Have this subroutine in a standard module:
    ```vba
    Public Function TemporarySheet(ByVal ParentBook As Excel.Workbook) As TemporarySheetObject
        Set TemporarySheet = New TemporarySheetObject
        TemporarySheet.Init ParentBook
    End Function
    ```
3. Review issues generated for the `TemporarySheet.Init ParentBook` line.
4. Double-click the issue, and observe that Rubberduck highlights `TemporarySheet` within the abovementioned line, confirming that the issue is being reported within the function itself (and not at its call sites).

**Expected behavior**
No `FunctionReturnValueDiscarded` issue generated for the `TemporarySheet.Init` line.

**Additional context**
Likely somewhat related to (and possibly a regression of) #5853.

**Comment by retailcoder** [comment] 2022-10-22 00:07
> confirming that the issue is being reported within the function itself (and not at its call sites).

The identifier reference to `TemporarySheet` in the `TemporarySheet.Init` statement has to refer to _something_ - and Rubberduck correctly considers it a reference to the function.

The bug here is that without any arguments, that reference should be ignored by the inspection because it isn't a call to that function, even if it does reference it. However, a fix can't simply be looking for an argument list, because a function does not necessarily have parameters.

I think a simple solution would involve potentially ignoring possible recursive functions (possible false _negatives_ here), and simply ignore all identifier references within the function itself.

**Comment by retailcoder** [comment] 2022-10-22 00:09
Again, the simplest mitigation would be to avoid treating the function identifier as a local variable, and only use it to assign a return value.

**Comment by MDoerner** [comment] 2022-10-22 07:18
Unfortunately, we cannot simply do that because the function identifier can be used as a local variable inside the function body, as demonstrated in this issue.

**Comment by MDoerner** [comment] 2022-10-31 22:35
I am quite sure that this issue is a duplicate of #5853.
The version in the version info is the same as in that issue; it is the last release, which is from May of last year.
This should be fixed in a later version, i.e. in later pre-releases.

**Closed by MDoerner** 2022-10-31 22:35 UTC
Labels: duplicate
