### ISSUE TITLE
False positive for 'Assignment without Set' inspection

### ISSUE THREAD

**Issue by CHR-IS-B** [rubberduck-vba/Rubberduck#5007] opened 2019-06-13 19:24 UTC
**Rubberduck version information**

    Version 2.4.1.4734
    OS: Microsoft Windows NT 10.0.17763.0, x64
    Host Product: Microsoft Office 2016 x64
    Host Version: 16.0.4834.1000
    Host Executable: EXCEL.EXE

**Description**
Inspection results show a false positive for the 'Assignment without Set' inspection when setting the ForeColor property of a UserForm Label.

**To Reproduce**
1. Insert a blank UserForm.
2. Add a Label to the UserForm.
3. Add the following code to the UserForm:

```
Private Sub UserForm_Initialize()
    Me.Label1.ForeColor = 255
End Sub
```

4. Refresh Rubberduck.

**Comment by retailcoder** [comment] 2019-06-13 19:28
Duplicate of #4997

**Closed by retailcoder** 2019-06-13 19:28 UTC
Labels: bug, duplicate
