### ISSUE TITLE
VBA Code Snippet tool

### ISSUE THREAD

**Issue by tyysoft** [rubberduck-vba/Rubberduck#5902] opened 2021-11-21 04:42 UTC
**Justification**
Need  a VBA code snippet tool to manage favorite code for VBA

**Description**
1. A tree window with parent nodes and children nodes.
2. The parent nodes are category nodes
3. Each parent node can contains many children nodes.
4. Each children node contains a piece of VBA code
5. When double click the children node, the VBA code will insert to VBE window.

**Additional context**
N/A

**Comment by MDoerner** [comment] 2021-11-21 10:05
Closing as duplicate of #4855

**Closed by MDoerner** 2021-11-21 10:05 UTC
Labels: enhancement
