### ISSUE TITLE
 Local variable 'Is' is not declared 

### ISSUE THREAD

**Issue by SystemsModelling** [rubberduck-vba/Rubberduck#2619] opened 2017-02-03 12:00 UTC
Select Case … Case Is > 1  etc

**Comment by SystemsModelling** [comment] 2017-02-03 12:00
Same for Space function
 Local variable 'Space' is not declared 
eg Space(3)

**Comment by comintern** [comment] 2017-02-03 13:34
I can't replicate an result with `Case Is ...`.  The grammar was changed after 2.0.11 to pick up those cases.

The `Space` function is different, and I can repro it with this code:

```
Sub foo()
    Dim x As String
    x = Space(3)
End Sub
```

**Comment by comintern** [comment] 2017-02-03 14:38
` Case Is > 1` is a duplicate of #2514, which is fixed in next.  The second referenced issue duplicates #2618.  Closing in favor of that issue.

**Closed by comintern** 2017-02-03 14:38 UTC
Labels: bug, parse-tree-processing
