### ISSUE TITLE
False Positive Inspection: 'TestMethod' was expected to have less arguments. 

### ISSUE THREAD

**Issue by Randalliser** [rubberduck-vba/Rubberduck#5460] opened 2020-04-15 08:16 UTC
**Rubberduck version information**
Version 2.5.0.5410
OS: Microsoft Windows NT 10.0.18363.0, x64
Host Product: Microsoft Office x64
Host Version: 16.0.12430.20184
Host Executable: EXCEL.EXE

**Description**
The 'Code Inspections' pane reports a **False Positive** inspection result.
> Warning: The annotation 'TestMethod' was expected to have less arguments. 

Even if the following annotation is used
```
'@Ignore SuperfluousAnnotationArgument
```

**To Reproduce**
Steps to reproduce the behaviour:
1.  create a standard module (.bas)
1.  insert the code (below)
1.  refresh the 'Code Inspections' pane
1.  view the false positive result
1.  open the 'Test Explorer'
1.  the category field on the test _correctly_ shows: 'TheCategory'
1.  back in the  'Code Inspections' pane, select 'Ignore Once'
1.  refresh the 'Code Inspections' pane
1.  view the false positive result

**Example Code**
```
'@TestModule
'@Folder("Tests")

Option Explicit
Option Private Module

'@TestMethod("TheCategory")
Private Sub TheTestMethod()                        'TODO Rename test
    On Error GoTo TestFail
    
    'Arrange:

    'Act:

    'Assert:
    'Assert.Succeed

TestExit:
    'Exit Sub
TestFail:
    'Assert.Fail "Test raised an error: #" & Err.number & " - " & Err.Description
End Sub
```
**Expected behaviour**
Code inspection pane should not report an exception.

**Screenshot**
![Screenshot](https://user-images.githubusercontent.com/8215393/79312852-db2dc380-7f42-11ea-9db4-b8a9aea1e4fb.PNG)

**Logfile**
[RubberduckLog.txt](https://github.com/rubberduck-vba/Rubberduck/files/4479886/RubberduckLog.txt)

**Additional context**
n/a

**Comment by SmileyFtW** [comment] 2020-04-15 16:52
In fact, it appears that the annotation does indeed use the argument in the "Category" of the Test Explorer.

**Comment by Vogel612** [comment] 2020-04-16 00:40
The root cause here seems to be that optional arguments and nullable value types interact in a way that was not correctly accounted for. As can be observed in the [TestMethodAnnotation constructor](https://github.com/rubberduck-vba/Rubberduck/blob/5fec4adff9b43206f2339fadb040a6129583a397/Rubberduck.Parsing/Annotations/Concrete/TestMethodAnnotation.cs#L12-L14), we do not explicitly specify a required number of arguments.  
In the [AnnotationBase constructor](https://github.com/rubberduck-vba/Rubberduck/blob/5fec4adff9b43206f2339fadb040a6129583a397/Rubberduck.Parsing/Annotations/AnnotationBase.cs#L14-L21) this is then passed as an optional parameter defaulting to 0, making all annotations that do not explicitly specify the number of arguments they require assume that they require 0 arguments.

In and of itself that default is sensible, but it's incorrect for `@TestMethod`.
Because the default value of the optional argument is 0, the `SuperfluousAnnotationArgumentInspection` classifies the annotation as a result [here](https://github.com/rubberduck-vba/Rubberduck/blob/5fec4adff9b43206f2339fadb040a6129583a397/Rubberduck.CodeAnalysis/Inspections/Concrete/SuperfluousAnnotationArgumentInspection.cs#L67-L68).

I would assume that the problem with the ignore annotation comes from the incorrect assumption in the base inspection code that only processes ignore annotations as attached to a declaration or a line, assuming inspections will only target those specific syntactic elements and not "other annotations" as well.

Additionally this surfaces the problem that `@TestMethod` only allows a single category to be specified. I'm not sure whether that was intended.

**Comment by MDoerner** [comment] 2020-04-16 07:21
This will be fixed after my next PR. It was a misconception on my side when setting up the max allowed arguments for annotations.

**Comment by retailcoder** [comment] 2020-05-01 13:41
Side note, "expected to have less arguments" should be "expected to have *fewer* arguments".

**Closed** 2020-06-07 19:33 UTC
Labels: bug, difficulty-01-duckling, up-for-grabs
