### ISSUE TITLE
The VBEsetting "Compile On Demand" is currently enabled.

### ISSUE THREAD

**Issue by SystemsModelling** [rubberduck-vba/Rubberduck#3904] opened 2018-04-09 08:42 UTC
RD 2.2.6672.28001
If I uncheck VBA Tools > Options > General > Compile on demand checkbox, I still get this warning.
I note that "Background Compile" is greyed out but still checked.
If I check COD, uncheck BC and COD, click Parse error again, I still get this warning.
Can't get past this first base.

FWIW some people use COD to have modules that are only used depending on the version number of Excel, to get conditional compilation without having to use #IF constants which are not defined for different versions of Excel on the same platform.

**Comment by bclothier** [comment] 2018-04-09 10:24
@SystemsModelling 

Few follow up questions.

1) When you edited COD, and restart, do you still get this?
2) What version of host? 

Background:

We introduced a new setting, `Compile Before Parse` which will attempt to compile the project before parsing it, which helps us avoid parser errors. However, due to a bug in the internal implementation of VBE, if `Compile On Demand` is enabled, the compilation only happens at high level and actual compilation errors are ignored. Consequently, we would be told that the project compiled but proceed to get parser errors since the code is not actually in a compilable state. By turning off the COD, we are able to accurately identify if the project was successfully compiled or otherwise alert the user before proceeding to parse.

Using COD as a way to write project that cannot be compiled has many problems. I maintain that a project that can't be compiled is a unverifiable project. If there needs to be modules that contains calls to certain methods that might not exist, then compilation constants should be used instead of relying on COD and never compiling the project.

That said, I will investigate further and see why the check is failing. Thank you for the bug report!

**Comment by Indigo744** [comment] 2018-09-16 10:10
Hello,

Just installed RubberDuck v2.2.0.3086 and currently facing the same issue.

I tried to uncheck "Compile On Demand", and completely restart the software (e.g. Excel or Access) and I still get the warning.
I also get a dialog when trying to enter Rubberduck settings (asking to deactivate "Compile Before Parse" feature). But I have no clue if I will need this feature or not... 

Some more information: Office 2016 Pro Plus 32 bits (French).

VBA version: 
![image](https://user-images.githubusercontent.com/7137528/45595251-0dfb8880-b9a9-11e8-8c4a-e10907ca24f8.png)

**Comment by bclothier** [comment] 2019-10-11 01:45
I cannot reproduce this using the current build. Closing.

**Closed by bclothier** 2019-10-11 01:45 UTC
Labels: bug, difficulty-01-duckling, feature-settings, hacktoberfest

**Comment by jkorchok** [comment] 2019-12-03 15:44
I can still repro this issue in Word  for Windows 2019 Version 1920 (Build 12130.20410 Click-to-Run) running Rubberduck 2.4.1.4627. Please try testing on more then one machine before concluding there is no problem.
![image](https://user-images.githubusercontent.com/40743423/70065981-ec8cb980-15b9-11ea-96bc-958e695d954e.png)

**Comment by retailcoder** [comment] 2019-12-03 15:54
Hi @jkorchok, build .4627 is getting pretty old, have you tried the latest pre-release build? We close issues when a pull request that fixes a problem is merged into [next], but "green releases" are off the [master] branch.

**Comment by jkorchok** [comment] 2019-12-03 16:41
.4627 is what I get when I install the most recent stable release. I'm not interested in beta-testing, but in actually using the software in programming. Maybe it's time to fold thousands of pre-releases into a working version.

**Comment by wqweto** [comment] 2019-12-03 17:00
@jkorchok: It's going to get fixed in one of those pre-releases that you are not going to install anyway.

@RD devs:  Thank you all for your hard work and sorry if we users sounds a bit ungrateful sometimes.

**Comment by Vogel612** [comment] 2019-12-03 17:09
For what it's worth, we're currently working towards the next stable release, meaning the last half-dozen or so pre-releases are even more stable than usual.

In general it should be okay for "actually using the software in programming" to use the prereleases, as all prereleases are vetted by our extensive automated tests **as well as** manual reviews. 

Note that we're closing issues as soon as they are fixed (or no longer reproducible) in the latest prerelease to reduce our workload when choosing the next issue to work on. As such we may close issues that are still appearing in the latest stable release.

**Comment by jkorchok** [comment] 2019-12-03 17:15
Thanks, I'll wait until the next stable release.

**Comment by daFreeMan** [comment] 2019-12-03 18:17
@jkorchok "I'm not interested in beta-testing, but in actually using the software in programming." I'm with you there in most things - like my home server software. 

To be honest, I run the latest beta build (I've installed 3 updates in one day before!) and haven't run into a significant, show-stopping issue since before the last stable release (2.4). There was a point when there were significant issues (like leaving a ghost Excel process hanging that you had to kill from the task manager), but most of these really ugly things have been resolved. That memory consumption issue is still outstanding, but, fortunately, that one hasn't bitten me!

If you don't have to go through major hassles to get a new release installed (many corporate environments make it painful to update, I understand that), I'd suggest grabbing the latest beta build. I think the majority of the commits of late have been translations of new strings into other languages, so as an English speaker, you won't even notice the changes. 

Of course, you're always free to go from stable release to stable release. You'll just have to live with the level of outstanding, known issues that remain in whichever release version you've chosen, until the next "release" is released.
