### ISSUE TITLE
COM object separated from underlying RCW

### ISSUE THREAD

**Issue by vincehardwick** [rubberduck-vba/Rubberduck#5771] opened 2021-05-12 16:33 UTC
**Rubberduck version information**
Version 2.5.2.5906
OS: Microsoft Windows NT 10.0.19042.0, x64
Host Product: Microsoft Office x64
Host Version: 16.0.13929.20296
Host Executable: EXCEL.EXE

**Description**
.NET Runtime unhandled exception - COM object separated from underlying RCW cannot be used

**To Reproduce**
Unknown - intermittent issue occurring when closing .xlsm workbooks

**Expected behavior**
Lack of unhandled exception.

**Screenshots**
See attached.
![Screenshot 2021-05-12 173059](https://user-images.githubusercontent.com/83643096/118011383-e02c9480-b347-11eb-8dd6-1af7ee8052c3.jpg)

**Logfile**
Rubberduck generates extensive logging in TRACE-Level. If no log was created at `%APPDATA%\Rubberduck\Logs`, check your settings. Include this log for bug reports about the behavior of Rubberduck.
[RubberduckLog.txt](https://github.com/rubberduck-vba/Rubberduck/files/6467638/RubberduckLog.txt)

**Comment by vincehardwick** [comment] 2021-05-12 16:35
[Rubberduck unhandled exception - error trace.txt](https://github.com/rubberduck-vba/Rubberduck/files/6467690/Rubberduck.unhandled.exception.-.error.trace.txt)

**Comment by retailcoder** [comment] 2021-05-12 16:47
Duplicate of #5766

**Closed by retailcoder** 2021-05-12 16:47 UTC
Labels: bug
