### ISSUE TITLE
RD had an error, #3

### ISSUE THREAD

**Issue by daFreeMan** [rubberduck-vba/Rubberduck#2131] opened 2016-07-25 19:01 UTC
Installed 2.0.7 this morning. Have received several "RD has had an error" messages.

[RubberduckLog.txt](https://github.com/rubberduck-vba/Rubberduck/files/382272/RubberduckLog.txt)

**Comment by Hosch250** [comment] 2016-07-25 19:03
The elusive Rename bug.  Can you share the project you got this on?

**Comment by daFreeMan** [comment] 2016-07-25 19:19
For posterity:  I'm close to being able to clean up the workbook to eliminate client-specific info from it. I hope to start that tomorrow or Wed.

**Comment by Vogel612** [comment] 2016-08-20 22:53
is this still relevant to 2.0.8?

**Comment by daFreeMan** [comment] 2016-08-22 13:24
Holy carp, Batfish! This has been sitting for a while... I've been so swamped with other stuff, I haven't had a chance to look at it.

**Comment by retailcoder** [comment] 2017-01-13 04:27
deemed a duplicate of #2098

**Closed by retailcoder** 2017-01-13 04:27 UTC
Labels: bug, duplicate, support
