### ISSUE TITLE
Assignment Not Used False Positive - Range Object using a property in RHS

### ISSUE THREAD

**Issue by SmileyFtW** [rubberduck-vba/Rubberduck#5491] opened 2020-05-05 17:21 UTC
**Rubberduck version information**
Version 2.5.0.5422
OS: Microsoft Windows NT 10.0.18362.0, x64
Host Product: Microsoft Office x86
Host Version: 16.0.12730.20236
Host Executable: EXCEL.EXE

**Description**
Setting a range variable and using that as the RHS with the value property to put values in another range flags the assigned range as not used. Using the cells property to loop a range also flags as not used.

**To Reproduce**
```
Public Sub AssignmentNotUsedFalsePositive()
    With Sheet1
        Dim sourceRange As Range
        Set sourceRange = .Range(.Cells(1, 1), .Cells(10, 1)) 'Flagged as not used
        Dim targetRange As Range
        Set targetRange = .Range(.Cells(1, 2), .Cells(10, 2)) 'Flagged as not used
    End With
    targetRange.Value = sourceRange.Value
    Dim currCell As Range
    For Each currCell In targetRange.Cells
        Debug.Print currCell.Value
    Next currCell
End Sub
```

**Expected behavior**
The inspection should not flag as not used.

**Comment by SmileyFtW** [comment] 2020-05-05 17:28
A similar thing happens if sub or function call uses an object variable as an argument. Flags the variable as not used. I am seeing other instances on typed variables (String, etc.) when the variable is used as the RHS in assigning a value to a property of an object.

**Comment by retailcoder** [comment] 2020-05-05 18:19
@MDoerner the inspection is hopelessly broken, but could this particular problem actually be a resolver issue? @SmileyFtW if you select `targetRange` in the `targetRange.Value =` instruction, is the RD commandbar saying that's the local `targetRange:Excel.Range` variable?

Recommendation would be to disable that inspection at the moment.

#5125 
#5128

**Comment by SmileyFtW** [comment] 2020-05-05 18:33
Commandbar says: VBAProject.Module1.Book1:targetRange (variable:Range)

**Comment by SmileyFtW** [comment] 2020-05-05 18:34
I've disabled the inspection

**Comment by SmileyFtW** [comment] 2020-05-05 18:38
I edited the declaration to be As Excel.Range and the commandbar now says variable:Excel.Range if that means anything.

**Comment by MDoerner** [comment] 2020-05-05 18:52
This is essentially a duplicate of #4754.
The inspection works on the assumption that variables are scoped to the containing block, which is completely wrong in VBA.

**Closed by MDoerner** 2020-05-05 18:52 UTC
Labels: duplicate
