### ISSUE TITLE
RPC_E_SERVERCALL_RETRYLATER exception pressing Refresh too many times

### ISSUE THREAD

**Issue by ThunderFrame** [rubberduck-vba/Rubberduck#1602] opened 2016-05-27 08:20 UTC
I'm trying to get Rubberduck to parse an empty project in MSProject *2003* (yes, it's old, but it's all I have, so if you get no repro, close this issue), although MSProject loads ProjectGlobal (Global.mpt) too, so there *are* components to parse.

On open, RD toolbar freezes on Parsing. Hitting refresh causes it o freeze on Pending. Hitting refresh again, and again, finally got me to Parse Error, but when inspecting the errors, there were none.

Hitting refresh again resulted in `Inspecting` and then crash, but on another try it reached `Ready`, but when I tried viewing Inspections it was empty.

Frustrated, I hit refresh several times, until I got this exception:

```
************** Exception Text **************
System.Runtime.InteropServices.COMException (0x8001010A): The message filter indicated that the application is busy. (Exception from HRESULT: 0x8001010A (RPC_E_SERVERCALL_RETRYLATER))
   at Microsoft.Vbe.Interop._VBComponent.get_Type()
   at Rubberduck.Common.DeclarationExtensions.<FindFormEventHandlers>b__32(Declaration item) in c:\Users\Andrew\Documents\GitHub\Rubberduck\RetailCoder.VBE\Common\DeclarationExtensions.cs:line 278
   at System.Linq.Enumerable.WhereListIterator`1.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Rubberduck.Common.DeclarationExtensions.FindFormEventHandlers(IEnumerable`1 declarations) in c:\Users\Andrew\Documents\GitHub\Rubberduck\RetailCoder.VBE\Common\DeclarationExtensions.cs:line 278
   at Rubberduck.Inspections.ParameterCanBeByValInspection.GetInspectionResults() in c:\Users\Andrew\Documents\GitHub\Rubberduck\RetailCoder.VBE\Inspections\ParameterCanBeByValInspection.cs:line 51
   at Rubberduck.Inspections.Rubberduck.Inspections.Inspector.<>c__DisplayClass6.<>c__DisplayClass8.<FindIssuesAsync>b__3() in c:\Users\Andrew\Documents\GitHub\Rubberduck\RetailCoder.VBE\Inspections\Inspector.cs:line 78
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()


```

**Comment by ThunderFrame** [comment] 2016-05-27 08:30
The error seems to occur in the Inspecting state, as that is what I see briefly before the exception.

I just got repro of the `Parser Error` state and empty Error dialog:

![proj](http://i.imgur.com/16AcYDF.png)

The *next* refresh after that zombie Parser Error results in an almost instant `Ready` state, but the Inspections window is empty, and subsequent refreshes leave the state at `Ready` until I add a module and hit refresh again.

**Comment by comintern** [comment] 2016-05-27 15:13
I believe this is a threading issue with COM.  [This link](https://msdn.microsoft.com/en-us/library/ms228772.aspx) might be relevant.

**Comment by retailcoder** [comment] 2016-06-01 19:38
Closing as a dupe of #1617; outright disabling the refresh commands when refreshing isn't possible should fix this issue.

**Closed by retailcoder** 2016-06-01 19:38 UTC
