### ISSUE TITLE
Code Explorer - Is the Visual Studio still waiting for thread to finish in UI?

### ISSUE THREAD

**Issue by PeterMTaylor** [rubberduck-vba/Rubberduck#1702] opened 2016-06-05 04:32 UTC
Another photo to "show and tell" using Code Explorer. I'm initially thought this is a cool feature to show the user that there is a wait icon but realised later when I think this through could be my local VS2015 letting me know that threads are still processing. Does anything need to be done here?

![capture code explorer display](https://cloud.githubusercontent.com/assets/2254567/15803612/2980f898-2b2a-11e6-8791-9858bb29be1c.PNG)

**Comment by ThunderFrame** [comment] 2016-06-05 08:07
The icon is part of the design of the form. You should only see it while the form is refreshing. I can't see your status toolbar, so I assume you got stuck on a Parse? IIRC this icon *remaining* visible is indicative of a parse failing because there is more than 1 workbook open

**Comment by PeterMTaylor** [comment] 2016-06-05 21:58
To be honest, this was the only workbook open.

**Comment by Hosch250** [comment] 2016-06-07 16:43
This is part of the form, as stated by ThunderFrame.  However, this will not stay visible even if there is a parse error.  Finally, is this an issue, or just to request that this be built into the form if it wasn't already?

**Comment by retailcoder** [comment] 2016-06-11 01:34
Likely caused by a resolver error and inconsistent parser state reporting - that's now fixed.

**Closed by retailcoder** 2016-06-11 01:34 UTC
