### ISSUE TITLE
Code Explorer should display protected projects

### ISSUE THREAD

**Issue by ThunderFrame** [rubberduck-vba/Rubberduck#1018] opened 2016-02-02 10:52 UTC
Even if you can't expand a protected project, it's still useful to see the project alongside your other projects.
Currently, protected projects aren't visible in Code Explorer, but they are visible in Project Explorer.

**Comment by retailcoder** [comment] 2016-02-02 16:16
That's definitely a regression issue that needs to be fixed. Thanks!

**Comment by retailcoder** [comment] 2016-02-02 16:19
I'll close this one as a dupe of #1020, it's the same issue and the other one is more detailed.

**Closed by retailcoder** 2016-02-02 16:19 UTC
Labels: bug, code-explorer, code-parsing, duplicate
