### ISSUE TITLE
Code inspection classifies Excel functions as variables

### ISSUE THREAD

**Issue by halcwb** [rubberduck-vba/Rubberduck#2484] opened 2017-01-05 10:32 UTC
In the latest 2.0.10 build, local Excel functions, like Date, Format, etc.. are classified as unassigned variables.

I switched to explicit use, like DateTime.Date. This works fine.

**Comment by retailcoder** [comment] 2017-01-05 13:27
Most likely related to #2349.

**Comment by retailcoder** [comment] 2017-01-05 18:57
The fixing of #2349 partially fixes this one. #2350 will finalize it.

**Comment by retailcoder** [comment] 2017-01-05 19:00
Closing as a duplicate of #2350

**Closed by retailcoder** 2017-01-05 19:00 UTC
Labels: bug, code-parsing, duplicate
