### ISSUE TITLE
Parser bug

### ISSUE THREAD

**Issue by sshikov** [rubberduck-vba/Rubberduck#1022] opened 2016-02-03 08:55 UTC
When trying to open Code Explorer, I'm getting error message instead:

VBAProject.VBE(51,9): extraneous input 'For' expecting NEWLINE.

Here is line 51 (last one):

        Dim mn:  mn = 0
        For Each VBComp In VBProj.VBComponents

**Comment by Vogel612** [comment] 2016-02-03 11:21
Seems to be the same issue as #900 and #861 . I assume this has been fixed on the current `next` but it might be worthwhile to look into this.

Thanks for reporting :)

**Comment by sshikov** [comment] 2016-02-03 15:54
Yea, looks like its the same as #861. I have Open statements right before this.

Should I attach sample code here?

**Comment by retailcoder** [comment] 2016-02-06 21:09
The colon is tripping the parser here:

    Dim mn:  mn = 0

This would fix it:

    Dim mn
    mn = 0

Annoying, I know. The good news is that it's fixed in the current parser, so next release will see a fix for this bug. Closing as a duplicate of #861.

**Comment by sshikov** [comment] 2016-02-12 10:35
In my case, for 1.4.3.27555 version

        Dim mn As Integer
        mn = 0
        
        For Each VBComp In VBProj.VBComponents

Doesn't help. I have no colons now before line in error.

So, may be this is yet another issue.

**Comment by ThunderFrame** [comment] 2016-02-12 10:43
@sshikov 1.4.3 is not receiving updates or parser fixes. If you want to benefit from the latest fixes and features (and bugs), then you'll need to build from the GitHub source.

**Comment by sshikov** [comment] 2016-02-12 11:17
Does it matter in this case? I mean that proposed fix (to remove colon) doesn't help. 

So, I'm not yet sure that fix for #861 is relevant in this case. Another bug may exists in 1.4.3.27555, and this issue is **not** duplicate for #861.

**Comment by retailcoder** [comment] 2016-02-12 13:53
@sshikov we've knocked down the last know grammar issue just yesterday, if you can post more sample code, would be great we could confirm it fixed for 2.0 :-)

**Comment by retailcoder** [comment] 2016-02-12 15:03
I mean, I have no repro on 1.4.3 with this code:

    Sub DoSomething()
        Dim mn As Integer
        mn = 0
    
        For Each VBComp In VBProj.VBComponents
        Next
    End Sub

Parses fine; the problem has to be elsewhere.

**Comment by sshikov** [comment] 2016-02-18 09:13
[vbe.txt](https://github.com/rubberduck-vba/Rubberduck/files/135890/vbe.txt)

Here is vba code with issue.

**Comment by ThunderFrame** [comment] 2016-02-18 10:04
@sshikov It looks like your code has non-ascii characters in your comments. I don't think 1.4 can handle that.

**Comment by retailcoder** [comment] 2016-02-18 15:19
@ThunderFrame the comments don't get to the parser, and IIRC the lexer rule for comments doesn't care whether they're ASCII characters or not.

Anyway, I can't get the module to parse with v1.4.3, even after getting the code to compile, adding an early-bound reference to the Scripting library, changing all one-line declaration+assignment into two-liners, and removing all comments.

It's complaining about *extraneous input 'With'*, and if I remove it, it complains about the `Do` block, which makes no sense. I'm removing the [duplicate] label here, something else is going on.

I'm saving that workbook into my dropbox and will let the 2.0 parser have a shot at it tonight.

2.0 can't release if it can't parse this code - yet I'm confident we've already fixed whatever the problem is. I'll update tonight.

**Comment by retailcoder** [comment] 2016-02-19 03:30
Okay... so I pasted the module into my VBE, as-is.

The non-ASCII comments turned into gibberish like this:

    ' ïîñòðîåí ñïèñîê âñåõ ïðîöåäóð (â âèäå module-> dictionary), ïîïðîáóåì ïîñòðîèòü xref

But the parser didn't blow up, and everything works. In other words: I'm confirming that next release will handle your code without any issues! :smiley:

**Closed by retailcoder** 2016-02-19 03:30 UTC
Labels: bug, code-parsing

**Comment by sshikov** [comment] 2016-02-20 09:04
I can confirm that everything works fine when build from next branch.
