### ISSUE TITLE
Parser Error with extra ()

### ISSUE THREAD

**Issue by dimitrimitropulos** [rubberduck-vba/Rubberduck#1121] opened 2016-02-19 15:14 UTC
The following code returns parser error "extraneous input '(' expecting {.....}"

    Public Sub DictTest()

    Dim x As New Dictionary
    x.Add "k1", "v1"

    Dim thisKey As Variant
    thisKey = x.Keys()(0)

    End Sub

Although the following code runs fine if you just use x.Keys(0), I have other code (which this error was found in) that doesn't work without the x.Keys()(0) syntax (returns "Run-time error '451': Property let procedure not defined and property get procedure did not return an object" if you change only that one thing but works as expected otherwise).

**Comment by autoboosh** [comment] 2016-02-19 15:28
This seems to have been fixed in version 2.0 at least...

**Comment by retailcoder** [comment] 2016-02-19 15:28
Thanks for your feedback! That's a known issue of 1.4.3, which is already fixed for next release.

Formally, the problem is that a member/procedure call followed by a subscript is not supported by the parser.

A work-around is to separate the return result from the subscript access, by introducing a local variable:

    Dim tmp
    tmp = x.Keys()
    thisKey = tmp(0)

That said I'm not sure I understand why you would need the empty parens there.

**Closed** 2016-02-19 15:29 UTC
Labels: bug, duplicate, vba-grammar

**Comment by dimitrimitropulos** [comment] 2016-02-19 15:43
I'm not sure either!  I picked up the technique here:

`14.3 The indexnumber of a key

The function .Keys is a 1-dimensional array.
The population order of the Dictionary determines the indexnumbers in the array .items.
The first element gets indexnumber 1, the last indexnumber is identical to the property .count.
You'd expect that .Keys(2) would result in the second key in the Dictionary.
This syntax however doesn't work.
Instead you need a slightly different one: .keys()(2).

With CreateObject("scripting.dictionary")
For Each it In Array("aa1", "aa2", "aa1", "aa3", "aa4", "aa2")
.Item(it) = it & "_inhoud"
Next

MsgBox .item(.keys()(1)) ' the first key
MsgBox .item(.keys()(2)) ' the second key
MsgBox .item(.keys()(.count)) ' the last key
End With`

In any case I am getting a similar parse error for something like this:

`Private Function ListThingNames() As Variant

Dim tempArr As Variant
tempArr = Array(Array("VBA", "other things"), Array("Excel", "other things"))

Dim things As Variant
ReDim things(1)

things(0) = tempArr(0)(0)
things(1) = tempArr(1)(0)

ListThingNames = things
End Function`

is this a duplicate (or has already been fixed), or should I follow a separate issue?  Hoping I didn't miss where this was addressed before.

**Comment by retailcoder** [comment] 2016-02-19 15:49
Yup, it's the exact same issue:

    foo = bar(x)(y)

The problem is with the consecutive subscript accesses, the old grammar simply doesn't pick it up. Sorry for the inconvenience, we're working hard on getting 2.0 completed and stable ASAP :-)
