### ISSUE TITLE
Odd CE Behavior

### ISSUE THREAD

**Issue by SmileyFtW** [rubberduck-vba/Rubberduck#5385] opened 2020-02-13 19:55 UTC
**Rubberduck version information**
Version 2.5.0.5336
OS: Microsoft Windows NT 10.0.18362.0, x64
Host Product: Microsoft Office x86
Host Version: 16.0.12430.20184
Host Executable: EXCEL.EXE

**Description**
Odd top-level workbook name in CE

**To Reproduce**
Don't know if it's reproducible,
1) Opened a file, then Alt-F11 to begin working
2) Did the refresh to update CE. 
3) Added a worksheet and renamed it
4) Clicked to refresh CE
5) Noticed the odd names

**Expected behavior**
Normal filenames in CE

**Screenshots**
![image](https://user-images.githubusercontent.com/42221335/74472804-1f7be500-4e68-11ea-83f2-bf814d6a7083.png)

**Logfile**
[RubberduckLog.txt](https://github.com/rubberduck-vba/Rubberduck/files/4200688/RubberduckLog.txt)

Other: I will restart and am guessing the issue will be resolved. If it isn't I'll report back

**Comment by MDoerner** [comment] 2020-02-13 20:13
This is a duplicate of #4811.

**Closed by MDoerner** 2020-02-13 20:13 UTC
Labels: duplicate
