### ISSUE TITLE
AutoCompletion will not be turned off

### ISSUE THREAD

**Issue by mertYz01** [rubberduck-vba/Rubberduck#4317] opened 2018-08-29 08:38 UTC
I am running

```
Version 2.2.0.3723
OS: Microsoft Windows NT 6.1.7601 Service Pack 1, x64
Host Product: Microsoft Office 2010 x86
Host Version: 14.0.7212.5000
Host Executable: EXCEL.EXE
```

I wanted to try out using this awesome tool, but now it is driving me crazy.
I cannot deactivate the autocompletion. I have read some related issues here, the problem seems to prevail.
Even though the "Enable AutoCompletion" box is unticked, the autocompletion is still working. (Esp. the "" autocompletion and the () are buggy. Brackets will always cut off the last letter of my function name, "" will conflict with adjacent () heavily.)

When I click on the uninstall rubberduck icon in the start folder, it only happens my computer overview (the explorer overview where C:, D: etc. are listed.)
Deinstalling over the exe within the install folder works.

**Comment by Vogel612** [comment] 2018-08-29 11:05
2.2.0.3723 is the currently latest **pre**release. It includes all the latest code as it is written.

While that means you get all the latest features :tada:, it also means you get all the latest bugs :beetle:.

You should have a much better time with the current "green release", [Rubberduck 2.2.0](https://github.com/rubberduck-vba/Rubberduck/releases/tag/Rubberduck-v2.2.0.3086). Note that that release does not contain any Autocompletion and a few other things have not been implemented...

**Comment by mertYz01** [comment] 2018-08-29 13:06
Thank you for your reply, sorry for overreading that important part!

**Comment by comintern** [comment] 2018-08-29 23:57
This is a duplicate of #4301 and a fix is coming in my next PR. In the meantime, you can change the setting by manually editing your rubberduck.config file (it's in your user's appdata\roaming\rubberduck directory).

Find this line...

`<AutoCompleteSettings IsEnabled="true" CompleteBlockOnTab="true" CompleteBlockOnEnter="true" EnableSmartConcat="true">`

...and change `IsEnabled="true"` to `IsEnabled="false"`.

**Closed by comintern** 2018-08-29 23:57 UTC
Labels: bug, feature-autocomplete, support

**Comment by mertYz01** [comment] 2018-08-30 07:14
Thanks for your help and sorry for the duplicate.
