### ISSUE TITLE
RD Crashes when refreshing after xlsm with bad code was parsed with errors and closed

### ISSUE THREAD

**Issue by SonGokussj4** [rubberduck-vba/Rubberduck#3760] opened 2018-02-12 12:20 UTC
Hello, maybe found a bug.

Video for that with timestamp comments:
https://www.useloom.com/share/6939ec3ce4284c73a2fc910aab408d2b 

1) Open Workbook with good code, Load up RD
2) Open Workbook with bad code, automatically "Parse Error"
3) If I click on Refresh, nothing happens
4) Close Workbook with bad code, "Parse Error" still displays, clicking on it does nothing
4.5 ) if I click on red (X), the Excel crashes right away
5) After a while, the RD is forced to automatically refresh, crashing Excel in a few moments

Log [Trace] in attachment.
[RubberduckLog.txt](https://github.com/rubberduck-vba/Rubberduck/files/1716243/RubberduckLog.txt)

**Comment by MDoerner** [comment] 2018-02-13 14:16
This is probably the same isssue as #3384.

The basic problem seems to be the `ShowParserErrorsCommand` caches COM objects, more precisely instances of `VBComponent`. After the project gt closed, the COM objects do not exist anymore. 

Since the dialog is not inside the parsing process, which stops exceptions from bubbling to the host and the dialog does not prevent this itself, the host crashes on the COM exception encountered because the component does not exist anymore.

The solution should be to remove all references to COM objects from the command and use QMNs instead. In case navigation is needed, the navigate commend should be employed for this action.

**Comment by MDoerner** [comment] 2018-03-21 23:08
After trying to reproduce this issue, I found out that the `ShowParserErrorsCommand` no longer seems to be the problem. Instead, the `CodeMetricsAnalyst` is throwing because it cannot find a declaration for a context. (It uses `First` and the exception is caught nowhere.)

**Comment by bclothier** [comment] 2019-08-12 22:37
No longer can reproduce - this most likely was fixed in the linked issue but this issue fell by wayside, so closing.

**Closed by bclothier** 2019-08-12 22:37 UTC
Labels: bug
