### ISSUE TITLE
Unqualified 'Range' used in a Worksheet module isn't resolving to ThatSheet.Range

### ISSUE THREAD

**Issue by retailcoder** [rubberduck-vba/Rubberduck#3295] opened 2017-08-25 19:08 UTC
```
Private Sub Worksheet_SelectionChange(ByVal Target As Range)
    Debug.Print Range("A1")
End Sub
```

The unqualified `Range` call is referring to `Me.Range`, but RD resolves it to `Excel._Global.Range`, which is wrong. This is a resolver issue, causing inspection false positives.

**Comment by MDoerner** [comment] 2017-08-25 20:39
This is a duplicate of #3154

**Closed by MDoerner** 2017-08-25 20:39 UTC
Labels: bug, duplicate, false-positive, feature-inspections, library-specific, parse-tree-processing
