### ISSUE TITLE
Code Inspections doesn't open or crashes VBE 

### ISSUE THREAD

**Issue by joshuader6** [rubberduck-vba/Rubberduck#1237] opened 2016-03-24 06:19 UTC
When i try to Open the Code inspections (Via menu or the toolbar) either the vbe freezes and after some time excel aborts with this message: 
> excel is waiting for another application to complete an ole action

or it just happens nothing.

Ican see how many issues i have and can switch between them.

**Comment by Vogel612** [comment] 2016-03-24 12:29
@joshuader6 Could you please share which version you are using? This would greatly help narrowing down the problem. Thanks

**Comment by joshuader6** [comment] 2016-03-24 12:46
Oh im sorry im ofcourse on the latest Version ( Build 1.4.3.2343 (MSIL))

**Comment by retailcoder** [comment] 2016-03-24 14:12
> *I can see how many issues I have and can switch between them*

If there are parser errors, the resolver can't do its thing, and the inspections won't run. You need to fix the parser errors - note that they're not *your* fault, they're bugs in the grammar we used to generate the parser (these bugs are now fixed, will release with 2.0).

Common parser issues include:

 - #749 
 - #1165 
 - #861 
 - #718
 - #417 
 - #750 

If you have trouble working around v1.4's grammar issues, don't hesitate to give us some of the faulty code, we can help.

**Comment by Talorthain** [comment] 2016-04-27 13:54
The code inspector crashs or reports the same error. I was only testing the file to see how it works and if it would benefit me in my current project over other tools from 3rd parties.

Code was 

dim a as integer

for a=0 to 100

debug.print a

next a

As you can see nothing impressive. additionally the slowness / crash etc. was when I run the check from the tool bar. When I run the check from the right click on the project it is very quick, but when I then open test window and close it, excel crashes. All right click menus fail.

**Comment by retailcoder** [comment] 2016-04-27 14:32
@Talorthain thanks for your feedback. I believe that would be fixed with commit a2f18e1d3a3b52aecbbb7abc5b668856acbf59db, which essentially prevents the inspections toolwindow from turning on its `IsBusy` flag and then requesting a parse task when there's no modified code to parse, which meant that the parser state never changed to `Ready` (since it was already there), and so the `IsBusy` flag would just remain there until code was modified and reparsed.

I've copied your sample code to a new standard module in a new project in Excel VBA; everything seems to work as is should:

![image](https://cloud.githubusercontent.com/assets/5751684/14855159/ae18ff1c-0c60-11e6-95e1-2fbc6796c854.png)

Can you expand a bit about "crashes"? I'm not sure what you mean either with "running the check from the right click on the project" and "running the check from the toolbar" - what is "running the check" exactly?

I'm working on the parser state caching issues that make it remain stuck in `Parsed` state after a module is added and parsed, and also I noticed some commands' `CanExecute` method (which controls whether a menu item is enabled or not) doesn't work as it should, which makes some refactorings disabled when they should be enabled, or enabled when they should be disabled. But disabled menu items when parser state isn't `Ready` is completely by design, it prevents Rubberduck from modifying code modules when it knows that its in-memory representation of the code mismatches the actual code in the editor.

Also note, we've narrowed down sluggishness to the Win32 mouse hook, we'll "get it right" soon!

**Comment by Talorthain** [comment] 2016-04-27 15:02
Hi,

 

                Thank you for the quick response. I am really looking forward to where this tool goes, plus the indenter in the next release will be very welcome.

 

                I will try the commit today. So hoping it works.

 

                I have tried to replicate the problem of the crash, caused when;

 

1)      Right click on the project,

2)      Select inspect

3)      Close inspect

4)      Right click on project

5)      Select run all tests

6)      Close the test window

7)      Right click menu then fails (flashes but closes instantly)

 

But I can’t replicate it this time. I was trying to get a video so you can see it occur. The only issue this time was

 



 

When I exited excel.

 

I did previously uninstall rubberduck and with your reply reinstalled it. On this install though there was no HREF error on the first run of excel.

 

Slightly different note: The fix for general vbaproject name. Can the additional information be added to which project it is asking to rename. E.g. VBAProject(Book1). I only ask because when I first run the inspector, it said one issue VBAProject and give me the option to change it. I change it to TEST. It then changed the addin VBAProject(funcres) to TEST, gave me no other options for the actual project I added and then excel crashed because VBAProject(funcres) no longer existed (was call TEST). Maybe an option to include and exclude projects from the check.

 

Regards

 

Anthony

**Comment by Talorthain** [comment] 2016-04-27 15:03
Hi,

 

                Just restarted excel to try and test again, but this time;

 

                

 

Regards

 

Anthony

**Comment by retailcoder** [comment] 2016-04-27 15:08
@Talorthain wait a bit, I haven't merged that commit yet ;-)

**Comment by Talorthain** [comment] 2016-04-27 15:10
No problem..

 

I will look later or tomorrow. Had to uninstall again, due to now regular crashes as I try and enter the VBE

 

Regards

 

Anthony

**Comment by Hosch250** [comment] 2016-06-07 18:31
Is this still an issue?

**Comment by retailcoder** [comment] 2016-06-07 18:33
obviously not :wink:

**Closed by retailcoder** 2016-06-07 18:33 UTC
Labels: support, vba-grammar

**Comment by Talorthain** [comment] 2016-06-07 19:28
I have not had chance to try it due to a large project that is taking my time. Had the release been updated, if do I will try tomorrow.

-----Original Message-----

**Comment by retailcoder** [comment] 2016-06-07 19:29
@Talorthain thanks! We'll try to issue a beta release tonight (shhh! it's a seekrit!) :wink:
