### ISSUE TITLE
Refactor|Rename only partially deals with labels

### ISSUE THREAD

**Issue by daFreeMan** [rubberduck-vba/Rubberduck#3218] opened 2017-08-03 14:20 UTC
Given:

```vb
Public Sub testErrorHandlerRename()

  On Error GoTo EH
  Debug.Print 1 / 0
  
EH:
  Debug.Print "I'm sorry, Dave, I can't do that"
  
End Sub
```

A `Refactor|Rename`  yields:

```vb
Public Sub testErrorHandlerRename()

  On Error GoTo ErrorHandler
  Debug.Print 1 / 0
  
EH:
  Debug.Print "I'm sorry, Dave, I can't do that"
  
End Sub
```

Interesting to note that while VBA won't compile it, RD _will_ parse it without complaint! _Maybe this should be a parse error, too._

Note that it doesn't matter whether the cursor is on the `On Error` line or on the line label itself, the `On Error` line is updated while the label is ignored.

If this is [status-by-design], then `Refactor|Rename` should be disabled on labels _and_ `On Error` lines.

_An additional side note: it is_ very _disconcerting to <kbd>Ctrl-Z</kbd> after a rename! Doing it once gives an empty code pane! =8O Another <kbd>Ctrl-Z</kbd>, of course, returns to the previous code. I realize this is due to the token stream rewriter (right?), but WOW what an initial shock!_

**Comment by retailcoder** [comment] 2017-08-03 15:37
It can't be a parse error; whether the `On Error` statement is valid depends on whether the specified label exists, and the label is defined well after the `On Error` statement - grammatically, there's nothing wrong with this code. Note that RD *does* flag the label as never referred to.

This isn't by design, it was probably an oversight in the refactoring of the *rename* functionality, which definitely can (abd should) handle labels. It's an identifier, it can be renamed, from its declaration or any of its call sites - this is a bug.

Ctrl-Z will do the same thing for any rewriter operation - sorry, no way around that one. Previously, a refactoring could entirely fill up the VBE's undo buffer, leaving you with impossible-to-undo operations. Every rewrite is now 2 operations: wipe everything out, dump the modified code. *That* is totally by design, and will never outgrow the undo buffer.

**Comment by Vogel612** [comment] 2017-08-03 15:48
@retailcoder so... we do have an inspection for "label never used". But do we also have one for "Label reference is undefined"? Or will we just leave that for the VBE to sort out?

**Comment by ThunderFrame** [comment] 2017-08-03 22:28
I don't think a non-existent label should cause a Parse Error (or resolver error) but it should generate an inspection. In any event, the module won't compile, but RD should be able to identify the missing label usages.

**Comment by BZngr** [comment] 2017-08-03 23:01
I'm working on #3176 which revealed that rename\refactoring of enums work (or fail to work) much in the same way as the above issue with labels.  I will have a fix for this issue along with the enums when I am done with #3176 (hopefully soon).

**Closed** 2017-08-10 16:25 UTC
Labels: bug, difficulty-02-ducky, feature-refactorings, refactoring-rename, regression, up-for-grabs
