### ISSUE TITLE
Inspection for boolean comparison to Boolean literals

### ISSUE THREAD

**Issue by ThunderFrame** [rubberduck-vba/Rubberduck#2220] opened 2016-09-06 08:05 UTC
Comparing True to True just adds operations, and makes the code less readable.

```vb
    If Foo = True Then
    'If Foo Then
    End If
    
    If Foo = False Then
    'If Not Foo Then
    End If
    
    If Foo = Not True Then
    'If Not Foo Then
    End If
    
    If Not Foo = False Then
    'If Foo Then
    End If
    
    If Not Foo = Not True Then
    'If Foo Then
    End If
    
    While Foo = True
    'While Foo
    Wend
    
    Do While Foo = False
    'Do While Not Foo
    Loop
    
    Do
    Loop Until Foo = True
    'Loop Until Foo
    
    Do
    Loop Until Foo = False
    'Loop Until Not Foo
```

**Comment by retailcoder** [comment] 2016-09-06 14:13
This would be a duplicate of #2222

**Closed** 2016-09-06 14:13 UTC
Labels: code-inspections, duplicate, enhancement
