### ISSUE TITLE
Com Exception while closing workbook

### ISSUE THREAD

**Issue by joshuader6** [rubberduck-vba/Rubberduck#1633] opened 2016-05-31 05:59 UTC
on commit: 4b185eea63de5f16f3573822713a9d3e87322791 

Ran into this: 

Open workbooks:

WorkbookTest: 1 test sub parses fine 
WorkbookMuchCode: very much code (opened afterwards and doesnt parse at all btw)
but when opening it directly via the explorer it parses correctly

When i close  WorkbookMuchCode the exception occurs

![image](https://cloud.githubusercontent.com/assets/10895412/15664583/7aeb628c-2705-11e6-8ee2-a67edabbd0a3.png)

```

        public QualifiedModuleName(VBComponent component)
        {
            _project = null; // field is only assigned when the instance refers to a VBProject.

            _component = component;
            _componentName = component == null ? string.Empty : component.Name;
            _componentDisplayName = GetDisplayName(component);
            _project = component == null ? null : component.Collection.Parent;
            _projectName = _project == null ? string.Empty : _project.Name;
            _projectDisplayName = GetDisplayName(_project);
            _projectPath = string.Empty;
            _projectId = GetProjectId(_project);

            _contentHashCode = 0;
            if (component == null)
            {
                return;
            }

            var module = component.CodeModule;
            _contentHashCode = module.CountOfLines > 0
                // ReSharper disable once UseIndexedProperty
                ? module.get_Lines(1, module.CountOfLines).GetHashCode()
                : 0;
        }
```

**Comment by retailcoder** [comment] 2016-06-01 19:27
Can you confirm a repro with the latest changes? Thanks!

**Comment by joshuader6** [comment] 2016-06-02 05:39
Well the exception still seems to occure but it doesn't break anymore ^^

Getting this like 100 times when closing: 

```
Exception thrown: 'System.Runtime.InteropServices.COMException' in Rubberduck.VBEditor.dll
Exception thrown: 'System.Runtime.InteropServices.COMException' in Rubberduck.VBEditor.dll
Exception thrown: 'System.Runtime.InteropServices.COMException' in Rubberduck.VBEditor.dll
```

**Comment by PeterMTaylor** [comment] 2016-06-02 06:50
Including my bug here for reference #1649

**Comment by comintern** [comment] 2016-06-04 03:30
I suspect these are being caused by a timing issue as VBE tears objects down.  That specific exception basically means that the object the `VBComponent` reference (or `CodePane`, `VProject`, or whatever) was destroyed on the COM side, but not released on the managed side.

**Comment by Hosch250** [comment] 2016-06-04 15:22
This is the same exception as in https://github.com/rubberduck-vba/Rubberduck/issues/1414, but with a different cause.  Could you check to see if the fix for that also fixed this?

**Comment by Hosch250** [comment] 2016-06-07 16:37
Can you check this with the latest build to see if it is fixed?

**Comment by Hosch250** [comment] 2016-06-07 18:26
If comintern is handling this, then I'll unassign myself.

**Comment by Hosch250** [comment] 2016-06-15 20:53
This *may* be because the sink events fire when we remove components and projects, triggering reparses, which try to access components removed immediately afterward.  If this is the case, we will likely need to find a way to figure out when a project remove is starting and when it is finishing and disable the component commands (at least for that project) during that time period.

**Comment by Hosch250** [comment] 2016-07-05 23:53
Can you still reproduce this?  We fixed a bunch of things that caused this, so I wouldn't be surprised if this is an obsolete issue.

**Comment by joshuader6** [comment] 2016-07-06 05:09
I'll test later today. 
I can't seem to figure out how to get the debgugging working with VS Express on this PC.

Strangely at the Current commit nothing parses at all ...

#1710 is still existent though

**Comment by PeterMTaylor** [comment] 2016-07-07 12:20
Interestly with the latest build dated 07/07/2016 when I closed down Excel restarted itself after closing down the workbook with code.

`The thread 0x1204 has exited with code 0 (0x0).
The thread 0x2b64 has exited with code 0 (0x0).
2016-07-07 22:17:44.6083;ERROR;Rubberduck.Common.WinAPI.RawInput;Error getting the rawinput buffer: The handle is invalid;System.ComponentModel.Win32Exception (0x80004005): The handle is invalid
2016-07-07 22:17:46.3406;ERROR;Rubberduck.Common.WinAPI.RawInput;Error getting the rawinput buffer: The handle is invalid;System.ComponentModel.Win32Exception (0x80004005): The handle is invalid
The thread 0x1d04 has exited with code 0 (0x0).
The thread 0x2ae8 has exited with code 0 (0x0).
The thread 0x2074 has exited with code 0 (0x0).
The thread 0x2028 has exited with code 0 (0x0).
Exception thrown: 'System.Runtime.InteropServices.COMException' in Rubberduck.Parsing.dll
Exception thrown: 'System.ObjectDisposedException' in mscorlib.dll
Exception thrown: 'System.Runtime.InteropServices.ExternalException' in System.Windows.Forms.dll
Exception thrown: 'System.Runtime.InteropServices.ExternalException' in System.Windows.Forms.dll
Exception thrown: 'System.Runtime.InteropServices.ExternalException' in System.Windows.Forms.dll
Exception thrown: 'System.Runtime.InteropServices.ExternalException' in System.Windows.Forms.dll
Exception thrown: 'System.Runtime.InteropServices.ExternalException' in System.Windows.Forms.dll
Exception thrown: 'System.Runtime.InteropServices.ExternalException' in System.Windows.Forms.dll
Exception thrown: 'System.Runtime.InteropServices.ExternalException' in System.Windows.Forms.dll
Exception thrown: 'System.Runtime.InteropServices.ExternalException' in System.Windows.Forms.dll
Exception thrown: 'System.Runtime.InteropServices.ExternalException' in System.Windows.Forms.dll
Exception thrown: 'System.Runtime.InteropServices.ExternalException' in System.Windows.Forms.dll
Exception thrown: 'System.Runtime.InteropServices.ExternalException' in System.Windows.Forms.dll
Exception thrown: 'System.Runtime.InteropServices.ExternalException' in System.Windows.Forms.dll
The program '[4720] Excel.exe' has exited with code 255 (0xff).
`

**Comment by Hosch250** [comment] 2016-07-12 18:38
Looks like this might be caused by closing a workbook in the middle of parsing it.

**Comment by Hosch250** [comment] 2016-07-23 00:27
I can't reproduce this.

**Closed** 2016-11-03 01:35 UTC
Labels: bug, code-parsing, critical
