### ISSUE TITLE
Tag Annotations

### ISSUE THREAD

**Issue by ThunderFrame** [rubberduck-vba/Rubberduck#1001] opened 2016-01-31 06:35 UTC
There are currently 4 annotation styles, that I'm aware of:

**Todo-Explorer type annotations (the *text* being configurable/extensible *by the user*)**
```
'Note:
'Todo:
'Bug:
```
**Folder annotations**
```
@Folder Foo.Bar
```

**Ignore annotations - the names being pre-defined by RD**
```
'@Ignore ProcedureNotUsed
```

**TDD annotations - the names being pre-defined by RD**
```
'@TestModule
```
And there's open issue #818 for XML annotations

But, as per [chat](http://chat.stackexchange.com/transcript/message/27205186#27205186), what if we added a tag-style annotation, where we could have some pre-defined tagnames (for specific Rubberduck functionality), and ad-hoc tag names for user-defined usage?
```
'@Tag BookmarkSet-4, Todo
'...
'@Tag BreakPointSet-4
'...
'@Tag TeamA, Sprint12, Defect128
'...
'@Tag Deprecated, RibbonCallback, HandlesButton
'...
'@Tag ExcelUDF
```

The pre-defined tags, like `BookmarkSet-n` and `BreakPointSet-n` could implement functionality like:

 - Persist/Reinstate different sets of *bookmarks* between VBE sessions
 - Persist/Reinstate different sets of *breakpoints* between VBE sessions (the breakpoint would be the next instruction line, or the current instruction line if the tag is in a trailing comment)
 - Persist/Reinstate a set of *watches* between VBE sessions

The user-defined tags like `Todo`, `TeamA` and `Deprecated` *don't* need to be pre-configured (like the current TODO Explorer texts do), but allow a user/team to use their own naming conventions, and then quickly find all instances of that tag, or combinations of tags.

Rubberduck could easily scan a project to find all tag names, and then offer an explorer for navigating to tags. Examples:
 - Explore all `RibbonCallback` tags
 - Explore all `Defect128` tags
 - Explore all tags with `TeamA AND Sprint12`
 - Explore all tags with `TeamA AND NOT Deprecated`

**Comment by retailcoder** [comment] 2016-01-31 15:03
IMO that sounds eerily similar to custom *todo* markers, which amount to *navigatable comments*.

**Comment by ThunderFrame** [comment] 2016-01-31 21:02
Except this lets you put multiple tags in the same comment. It's the same benefits that tagging has over discrete allocation. Eg. Tagging photos is better than keeping them in some arbitrary folder hierarchy, although a mix of folders and tags is often the most flexible approach.

The TODO explorer functionality does indeed allow for navigable comments. They're really just a special case of tagging, but they only permit one *meaningful* tag per comment, they add descriptive text to the tag (eg. `'TODO: remove hard-coded meaning of life`), and they require the tag to be pre-configured in Rubberduck by *every* Developer that works with the code.

The @Folder annotation is really just a way of tagging a module into a folder hierarchy.

I think the current TODO explorer style commenting is useful, and should be kept as is, but tagging could provide an augmented navigation capability.

You could, for example, have a virtual *Tags* folder in Code Explorer, and expand an individual tag, within Code Explorer, to find all instances of that tag. Or you could even create a virtual tag composite folder, by annotating with something like: `'@TagFolder Defect AND Sprint12`

You could also have RubberDuck create implied/virtual tags, for various declaration types, like `Function` or `PropertyGet` that don't need to be explicitly added within comments, and you could then search for:
 - Explore all tags with`Function AND Defect`

Being able to reinstate bookmarks, breakpoints and watches almost qualifies them for their own feature requests.

**Comment by ckuhn203** [comment] 2016-02-01 00:03
I'm not entirely sold on this idea, but I *do* like the idea of a `'@Deprecated` or `'@Obsolete` annotation and an accompanying inspection.

**Comment by ckuhn203** [comment] 2016-02-01 00:05
As for the permanent bookmark idea, I like it, but IIRC toggling bookmarks is beyond what's capable via the VBIDE API.

**Comment by ThunderFrame** [comment] 2016-02-01 02:09
@Deprecated is a good annotation in its own right, but it's just adding another annotation syntax that has meaning to RubberDuck, and has localization issues. We could quickly run into issues around the number of *special* annotation words, and each would potentially require its own line.

The @Tag annotation allows a user/team to assign their own "annotations", with their own meanings, in an extensible way, and without Rubberduck having to have them pre-defined, or handled. You can add multiple tags on a single line, and keep the code uncluttered.

**Comment by Hosch250** [comment] 2016-02-01 02:12
As for ad-hoc ones, just add a todo comment with a note there.  If it doesn't have any meaning for RD, it will be exactly the same functionality.  I agree that a few custom ones would be good, such as deprecated.  If we decide to implement these, they should get their own issue, however.

**Comment by ThunderFrame** [comment] 2016-02-01 02:14
As for persisted bookmarks, there isn't a method in the VBIDE, but there is a CommandButton that you can `Execute` when the cursor is on the right line.

Being able to Execute Command buttons opens up extra VBIDE methods and properties (if you read the captions/enabled states of the command buttons). It is, for example, one way of making the hidden members visible in Object Explorer and Intellisense.

**Comment by retailcoder** [comment] 2016-02-01 02:24
> *they only permit one meaningful tag per comment*

That's entirely an implementation detail. This:

    'TODO: Fix this bug

Could very well and fairly easily show up under *both* `todo` and `bug` markers. And the todo explorer could very well feature a toolbar button to toggle a bookmark... I fail to see how this feature fundamentally differs from todo markers.

**Comment by retailcoder** [comment] 2016-02-01 02:33
As for `deprecated` markers, if someone wants to have them they can make a `deprecated` todo marker, and mark methods as "deprecated" as they see fit - but IMO an add-in that provides refactoring tools and integrated source control shouldn't encourage the use of such markers.

**Comment by ckuhn203** [comment] 2016-02-01 10:42
A `Deprecated` TODO marker will show you the places where you have an obsolete method, but not all of its *callers*. I'll open a separate issue for it later and try to convince you of that one @retailcoder. 

I agree that *this* feature request is essentially a duplicate of existing functionality.

**Closed by ckuhn203** 2016-02-01 10:42 UTC
