### ISSUE TITLE
Inconsistent Result from "Set assignment with incompatible object type" Inspection

### ISSUE THREAD

**Issue by CHR-IS-B** [rubberduck-vba/Rubberduck#5138] opened 2019-09-04 23:28 UTC
**Rubberduck version information**
The info below can be copy-paste-completed from the first lines of Rubberduck's log or the About box:

    Version 2.4.1.4848
    OS: Microsoft Windows NT 10.0.17763.0, x64
    Host Product: Microsoft Office 2016 x64
    Host Version: 16.0.4834.1000
    Host Executable: EXCEL.EXE

**Description**
I'm getting an inconsistent and possibly false positive result from the "Set assignment with incompatible object type" inspection.

**To Reproduce**
1. Paste these two procedures into a standard code module and refresh RD.
```
Sub Test1_Passes_Inspection()
    Dim myShape As Excel.Shape
    Set myShape = Excel.ActiveSheet.Shapes("Button 1")
    
    Debug.Print TypeName(Excel.ActiveSheet.Shapes("Button 1")) ' prints "Shape"
End Sub
```

```
Sub Test2_Fails_Inspection()
    Dim rng As Excel.Range
    Set rng = Excel.ActiveSheet.Cells(1, 1) 
    
    Dim TEST_SHAPE As Excel.Shape
    Set TEST_SHAPE = rng.Worksheet.Shapes("Button 1")       ' RD INSPECTION-ERROR
    
    Debug.Print TypeName(rng.Worksheet.Shapes("Button 1"))  ' prints "Shape"
End Sub
```
2. Only the second procedure produces this inspection result:  _To the variable 'TEST_SHAPE' of declared type 'EXCEL.EXE;Excel.**Shape**' a value is set assigned with the incompatible declared type 'EXCEL.EXE;Excel.**Shapes**'._

**Expected behavior**
I wasn't expecting this inspection result for either procedure since both assign an Excel.Shape object to a variable of the same declared type.

**Comment by retailcoder** [comment] 2019-09-04 23:39
The first snippet is late-bound and thus unresolved - that's why there is no result. Looks like we're resolving the type of the RHS expression without accounting for the indexed default member call.

**Comment by MDoerner** [comment] 2019-09-05 07:17
I cannot reproduce this on the current version.
Could you please try whether you still have this problem on the newest prerelease?
In the past 21 days, since release of version 2.4.1.4848 you use, a lot of changes around the resolution of default member accesses have been merged.

**Comment by CHR-IS-B** [comment] 2019-09-05 17:56
@MDoerner I also could not reproduce this on the current version.  Good call!

**Closed** 2019-09-05 17:56 UTC
Labels: bug, resolver
