### ISSUE TITLE
Copy from Code Inspections as a delimited list

### ISSUE THREAD

**Issue by AndrewM-** [rubberduck-vba/Rubberduck#830] opened 2015-10-12 01:03 UTC
I have about 900 code issues to work through.  Most are small matters like implicit variable typing or passing by ref instead of by value.  I tried to copy and paste the list of issues into a spreadsheet but the list of issues comes out as a single column.  Could you format the data that gets placed on the clip board so that it is a delimited list?  That would let me paste the data into columns and then sort of the columns.  Being able to sort the issues into my preferred order would benefit my work flows.  I could also just sort and delete any non-issues such as the Cancel parameter in a sub declaration not being used.  I tend to use pipes as separators as they are not used in code or in data as a rule.

**Comment by Vogel612** [comment] 2015-10-12 07:04
Fwiw if you want to ignore certain inspections, the current development state allows ignoring them from the relevant 'details' dialogue  

Exporting something to a csv format would be something I personally wanted to keep separate, since it breaks the standard expected behavior for copy paste.  
But that's for the owners to decide.

**Comment by AndrewM-** [comment] 2015-10-12 07:09
Could add a save to text file button then?  That would allow a CSV file to be obtained,which is what I want anyway.

**Comment by retailcoder** [comment] 2015-10-12 15:03
@Vogel612 @AndrewM- I *did* consider adding an 'Export' command, but I deemed the 'Copy' button good enough... making it comma-separated is really a 1-line change, I think I might just do that. Or, add the export command and allow exporting the results in csv and xml...

**Comment by retailcoder** [comment] 2015-10-12 15:04
Same applies to test results

**Comment by Hosch250** [comment] 2016-06-09 16:42
Is this done with Thunderframe's XML/HTML/whatever copy formats?

**Comment by ThunderFrame** [comment] 2016-06-09 20:48
Closed by #1149 and #1589

**Closed by ThunderFrame** 2016-06-09 20:48 UTC
Labels: feature-request
