### ISSUE TITLE
RD Reparse Before Using Rename

### ISSUE THREAD

**Issue by bbarney213** [rubberduck-vba/Rubberduck#3591] opened 2017-12-05 19:12 UTC
RD should prevent the user from using Rename until the project has been re-parsed. Ideally, RD would re-parse before allowing for a Rename (ideally, check if a reparse is needed first), but at the least there should be a warning, or a disabling of the option. Not reparsing beforehand can result in code changes being removed once the RD rename runs.

**Comment by IvenBach** [comment] 2017-12-05 19:18
Clean parse with code.
![cleanparse](https://user-images.githubusercontent.com/26076874/33625842-c8017dd4-d9ad-11e7-8979-0fc35c3c2489.PNG)

Some edits made without reparsing
![lineschangedwithoutparse](https://user-images.githubusercontent.com/26076874/33625845-cd7a73f6-d9ad-11e7-993a-ad769b1f55d2.PNG)

Running `Rename` without reparse produces. `bar` changed to `duk`. Note elimination of `SomeMethodCalled` along with lines being squashed back together.
![renamerun](https://user-images.githubusercontent.com/26076874/33625848-cfd54842-d9ad-11e7-9214-bf68dc1f1ef9.PNG)

**Comment by retailcoder** [comment] 2017-12-05 23:59
That's how v1.x worked: before you could use any feature it would reparse, showing a blocking dialog so that there weren't code changes during the parse. As 2.x introduced asynchronous parsing the blocking dialog was eliminated, a manual *refresh* button was added, and the user is now in charge of deciding when RD should parse.

Now that the parser only processes modules that need to be processed, the cost of a reparse has significantly dropped, but we would have to reimplement the blocking dialog in order for a forced reparse to be of any use.

I'm not sure if it would be an enhancement or a regression, but it's definitely not a bug. Current behavior is entirely by design.

**Comment by bbarney213** [comment] 2017-12-06 12:35
From the user perspective, I see more value in a blocking dialog preventing me from losing work, than I do a blocking dialog that may interrupt my workflow (for my own protection).

It is far more costly, as a user, to have ‘mysterious’ behavior and to have to retrace my steps to figure out what happened, than it is to dismiss a dialog because I didn’t know to ‘Refresh’ first.

Ideally, in lieu of a blocking dialog a reparse would occur before displaying the option that the user asked for. This would prevent the cost of a blocking dialog, but also avoid the cost of lost code.


[Description: Description: Southern New Hampshire University]<https://my.snhu.edu/>

[Description: Description: facebook]<http://www.facebook.com/OfficialSNHU>  [Description: Description: Twitter] <http://twitter.com/snhu>   [Description: Description: Linkedin] <http://www.linkedin.com/groups?mostPopular=&gid=3688403>


________________________________
Brandon Barney, MFA | Academic Analyst | COCE
Southern New Hampshire University | 33 South Commercial Street | Manchester, NH 03101
| f. 603.645.9706 |

**Comment by retailcoder** [comment] 2017-12-06 12:41
Asynchronous/ non-blocking parse cannot guarantee that there aren't any code changes made; parsing before the dialog is shown but without blocking the editor / UI thread wouldn't ensure we're working with the most up-to-date code.

Also the canexecute logic for all commands needs to change to a default `return true` if every command will trigger a blocking parse.

**Comment by bbarney213** [comment] 2017-12-06 12:44
What about an option within the RD menu that allows the user to disable the blocking dialog if they so choose? That would allow for regular users to get the blocking message reminding them to re-parse before using commands, but a power user to disable the warning since they will be aware of the risks. From a UX standpoint it would be a compromise that prevents a regression, but adds additional protection for users who want/need it.



[Description: Description: Southern New Hampshire University]<https://my.snhu.edu/>

[Description: Description: facebook]<http://www.facebook.com/OfficialSNHU>  [Description: Description: Twitter] <http://twitter.com/snhu>   [Description: Description: Linkedin] <http://www.linkedin.com/groups?mostPopular=&gid=3688403>


________________________________
Brandon Barney, MFA | Academic Analyst | COCE
Southern New Hampshire University | 33 South Commercial Street | Manchester, NH 03101
| f. 603.645.9706 |

**Comment by MDoerner** [comment] 2017-12-06 13:03
I would like to propose a somewhat different approach. We could display a dialog before trying to execute a refactoring command indicating that a reparse is required, provided the loaded projects are dirty at that point. We could also put  a _reparse now_ button on the dialog.

One reason why I prefer this to an automatic parse is that, in the eyes of RD,  the user might have selected something to refactor that is entirly different from what he intended; the selection that RD sees corresponds to the state of the code at the last reparse.

**Comment by bbarney213** [comment] 2017-12-06 13:05
I agree with this approach, this would present the user with what they need to avoid code loss, explain what is happening, and also prevent any accidental reparsing.


[Description: Description: Southern New Hampshire University]<https://my.snhu.edu/>

[Description: Description: facebook]<http://www.facebook.com/OfficialSNHU>  [Description: Description: Twitter] <http://twitter.com/snhu>   [Description: Description: Linkedin] <http://www.linkedin.com/groups?mostPopular=&gid=3688403>


________________________________
Brandon Barney, MFA | Academic Analyst | COCE
Southern New Hampshire University | 33 South Commercial Street | Manchester, NH 03101
| f. 603.645.9706 |

**Comment by MDoerner** [comment] 2019-02-09 16:25
Fixed by PR #4693

**Closed by MDoerner** 2019-02-09 16:25 UTC
Labels: difficulty-03-duck, enhancement, up-for-grabs, user-interface
