### ISSUE TITLE
Implement interface misses Optional keyword

### ISSUE THREAD

**Issue by Greedquest** [rubberduck-vba/Rubberduck#5075] opened 2019-07-31 17:30 UTC
**Rubberduck version information**

```
Version 2.4.1.4795
OS: Microsoft Windows NT 10.0.17763.0, x64
Host Product: Microsoft Office x86
Host Version: 16.0.11328.20368
Host Executable: EXCEL.EXE
```

**Description**
When using the `Rubberduck.Refactor.Implement Interface` method, the `Optional` keyword seems to be missed out resulting in code that cannot compile

**To Reproduce**

_Class `ITest`:_

```vb
Option Explicit

Sub test(Optional ByVal blah As Variant)
End Sub
```

_Class `TestImplementation`_
```vb
Option Explicit

Implements ITest
```
_Right Click > Rubberduck > Refactor > Implement Interface_

**Result:**

```vb
Option Explicit

Implements ITest

Private Sub ITest_test(ByVal blah As Variant)
    Err.Raise 5 'TODO implement interface member
End Sub
```

**Expected:**

```vb
Option Explicit

Implements ITest

Private Sub ITest_test(Optional ByVal blah As Variant)
    Err.Raise 5 'TODO implement interface member
End Sub
```

**Comment by bclothier** [comment] 2019-08-12 12:04
Closing this as a duplicate of #4774

**Closed by bclothier** 2019-08-12 12:04 UTC
Labels: bug
