### ISSUE TITLE
2.2.0 warnings from  Redim ... As 

### ISSUE THREAD

**Issue by SystemsModelling** [rubberduck-vba/Rubberduck#4107] opened 2018-06-18 13:24 UTC
ReDim Result(StringLen) As String
gets me several warnings:
Variable 'Result' is used but not assigned
Local variable 'Result' is not declared.

This gives no warnings:

    Dim Result() As String
    ReDim Result(StringLen)

**Comment by Vogel612** [comment] 2018-06-18 15:26
Could you add the extended version information from the logs, please? Thank You :)

**Comment by retailcoder** [comment] 2018-06-20 17:53
That's a tough one. The resolver currently isn't treating `ReDim` statements as declarations, because it literally can't *know* whether the identifier is or isn't `Dim`'d elsewhere (e.g. a global array declared in another module) in scope.

VBA `ReDim` statements are dual-purposed: they serve as executable declaration statements, *and* as a statement that resizes a dynamic array.

Rubberduck can't treat them as executable declaration statements, so "variable 'Results' is not declared" isn't entirely wrong, but it's not per language specs either. So yes, it's a bug, but I don't see how we can fix it without introducing an entire parse pass dedicated to finding what array identifiers are available in global scope - which isn't impossible, but feels overkill, when adding an explicit `Dim` statement removes it.

"Variable not assigned" inspection needs to ignore arrays though.

**Comment by CHR-IS-B** [comment] 2019-02-07 02:27
This might be a duplicate of #2522.

**Closed** 2019-05-12 14:35 UTC
Labels: bug, duplicate, feature-inspections, inspection-false-positive, resolver
