### ISSUE TITLE
Clicking on the error in parser error windows misses the line the error is in

### ISSUE THREAD

**Issue by BobTB** [rubberduck-vba/Rubberduck#1768] opened 2016-06-10 11:36 UTC
The title says it all. After clicking on the error in parser error window, the cursor in the VBA editor misses the line for a few lines (seems random). It does work some times, but mostly in my case it is not putting the cursor in the right position in the VBE

![linemiss](https://cloud.githubusercontent.com/assets/15887688/15967282/4ca7814c-2f27-11e6-87da-588b015eccc4.gif)

**Comment by retailcoder** [comment] 2016-06-10 14:35
Tempted to mark as a duplicate of another known issue: the attributes parser, which works off an exported-to-temp-file version of the module to pick up module and member attributes, will also throw its own `SyntaxErrorException`s, which has the same lexer tokens positioned at different lines than what the VBE is showing. We haven't decided on what the best solution might be for this and we're open to ideas!

I'm not going to mark as a duplicate though, because there's a grammar bug / oversight here: `Print` statements (`Debug.Print`, `Write#`, `Print#`, etc.) accept commas and semicolons anywhere (they control print layout), and I believe our grammar would choke on semicolons, and only accept commas as arguments separators.

@autoboosh what would be the best way to handle this?

**Comment by Hosch250** [comment] 2016-06-10 15:17
https://github.com/rubberduck-vba/Rubberduck/issues/1661

**Closed by Hosch250** 2016-06-10 15:17 UTC
Labels: bug, duplicate, vba-grammar

**Comment by retailcoder** [comment] 2016-06-10 15:25
@Hosch250 ok, so the parser error fix will be referring to #1766
