### ISSUE TITLE
Adding whitelisted identifier showed error but was indeed added

### ISSUE THREAD

**Issue by djrivers** [rubberduck-vba/Rubberduck#4908] opened 2019-04-09 17:14 UTC
**Rubberduck version information**
Version 2.4.1.4651
OS: Microsoft Windows NT 10.0.17763.0, x64
Host Product: Microsoft Office x64
Host Version: 16.0.11425.20202
Host Executable: MSACCESS.EXE

**Description**
After running the code inspection and applying fix (Add to whitelist) via the fix button, popped up an error but upon checking, the identifier was added in the whitelisted identifier

**To Reproduce**
1. Declare a variable with unmeaningful name such as "db".
2. Refresh RD to identify the issue
3. Select "add to whitelist" from the fix button.

**Expected behavior**
Expected to show a confirmation message box.

**Screenshots**
![01](https://user-images.githubusercontent.com/40927759/55819861-61593380-5abf-11e9-89fe-1037750bdfaa.png)

![02](https://user-images.githubusercontent.com/40927759/55819873-65855100-5abf-11e9-8934-f6e2b4a46e0e.png)

![03](https://user-images.githubusercontent.com/40927759/55819885-69b16e80-5abf-11e9-972f-f20e321ccdf2.png)

**Logfile**
[RubberduckLog.txt](https://github.com/rubberduck-vba/Rubberduck/files/3060180/RubberduckLog.txt)

**Comment by MDoerner** [comment] 2019-04-09 18:13
Thanks for reporting this. 

We found another related issue earlier this week. The root cause has been identified and a fix will come in when PR #4896 gets merged.

**Comment by djrivers** [comment] 2019-04-09 18:30
Thank you. :)

**Comment by MDoerner** [comment] 2019-04-11 13:27
This should be fixed with PR #4896 merged now.

**Closed by MDoerner** 2019-04-11 13:27 UTC
Labels: bug
