### ISSUE TITLE
empty lines added to all files on Source Control Refresh

### ISSUE THREAD

**Issue by wernerbarnard** [rubberduck-vba/Rubberduck#2343] opened 2016-11-02 12:54 UTC
Whenever I refresh from the source control window, it's exporting all modules/forms (makes sense) ... but the issue is that it consistently adds 2 empty lines at the end of only some of the files - not all.  Sometimes it removes empty lines, sometimes it adds.

This is an issue, because it's changing files that shouldn't and didn't have any code changes to them.  Why is this happenning? ( MS Office 2007 with Rubberduck 2.0.9.0 )

**Comment by Vogel612** [comment] 2016-11-02 13:39
#2299 could be related

**Comment by retailcoder** [comment] 2016-11-02 14:19
That's a bug in the VBE's own *import module* functionality, that is messing up the diffs and making git think every `UserForm` module is "modified" when it's not.

Repro:

- Create a new VBA project
- Add a new `UserForm`
- Make sure the **very first line** of the form's code module contains `Option Explicit`
- Using the VBE's *project explorer*, right-click the form and remove it; click YES when prompted whether to export.

  The file looks good:

   ```
	VERSION 5.00
	Begin {C62A69F0-16DC-11CE-9E98-00AA00574A4F} UserForm1 
	   Caption         =   "UserForm1"
	   ClientHeight    =   3180
	   ClientLeft      =   45
	   ClientTop       =   375
	   ClientWidth     =   4710
	   OleObjectBlob   =   "UserForm1.frx":0000
	   StartUpPosition =   1  'CenterOwner
	End
	Attribute VB_Name = "UserForm1"
	Attribute VB_GlobalNameSpace = False
	Attribute VB_Creatable = False
	Attribute VB_PredeclaredId = True
	Attribute VB_Exposed = False
	Option Explicit
   ```
- Right-click an empty area of the VBE's *project explorer*, and select "Import File..."; import the exported `UserForm`.
- Right-click the imported `UserForm` module and select *view code*.
- `Option Explicit` is no longer the first line in the code module.

   ```
        
	Option Explicit
   ```

A new line will be added every time a `UserForm` is imported; if nothing is done to counter this, successively exporting and importing the same form module will keep shifting the code down one line, until the module exceeds 65535 lines and the project no longer compiles.

---

Rubberduck is working around this VBE bug by **removing** exactly one empty line (only if it's empty) at the **top** of a `UserForm` module, when we're re-importing it into the project.

Please clarify whether this issue is affecting module types other than `UserForm`.

It's entirely possible that you've just found another VBE bug that we need to work around, we just need to narrow down on the actual issue.

**Comment by wernerbarnard** [comment] 2016-11-03 05:56
Hi @retailcoder 

Seems to be happening with ".doccls" files, files for forms of type "Form".

Also, the line issues are at the **bottom** in our case, _**not the top.**_

Would it not be a better option to always clear all empty lines at the bottom of the code files, since you don't need those anyways?

**Comment by rubberduck203** [comment] 2018-03-09 10:41
This seems to be an issue with the import/export, so I think we should leave this one open. #3758.

**Comment by bclothier** [comment] 2019-01-16 23:22
I cannot reproduce this so closing it.

**Closed by bclothier** 2019-01-16 23:22 UTC
Labels: bug, feature-export
