### ISSUE TITLE
Encoding issues with French in 3110-pre Installer

### ISSUE THREAD

**Issue by FuSoftware** [rubberduck-vba/Rubberduck#3946] opened 2018-04-19 11:37 UTC
Might be present in previous installers, it's just the only one I tested since it's the last, previous ones are irrelevant.

Setting the language to French gives encoding issues while running the installer. Note that Deutsch and English are unaffected (even though Deutsch also uses accentuated characters.

Might have to do with how the text was set in the installer's files. Maybe the file wasn't encoded in UTF-8, I'd look myself, but I don't know where the files are.

![capture2](https://user-images.githubusercontent.com/11671860/38989212-5bcfff9e-43d6-11e8-82b1-0552ea254303.PNG)

**Comment by FuSoftware** [comment] 2018-04-19 11:38
During the installation, the encoding was fine. But at the last window, it's partially wrong. Note that some characters are properly rendered.

![capture2](https://user-images.githubusercontent.com/11671860/38989345-dd1d9642-43d6-11e8-9657-79e32bd55e64.PNG)

**Comment by Vogel612** [comment] 2018-04-19 11:44
This should be easily fixed by checking the encoding of https://github.com/rubberduck-vba/Rubberduck/blob/next/Rubberduck.Deployment/InnoSetup/Includes/French.CustomMessages.iss ... there has been a change to the encoding 11 days ago

**Comment by FuSoftware** [comment] 2018-04-19 11:49
It looks like it's already UTF-8, maybe the intaller itself tries to render it as ANSI ?

**Comment by bclothier** [comment] 2018-04-19 12:40
That would be ironic since I explicitly use unicode version of InnoSetup precisely to support internationalization. 

We can confirm that we are building w/ the unicode because [this line](https://ci.appveyor.com/project/retailcoder/rubberduck/build/2.2.0.3110#L477) indicates `(u)` which indicates unicode compiler is being used to compile the installer.

[Reference for Unicode InnoSetup](http://www.jrsoftware.org/ishelp/index.php?topic=unicode)

Just for reference - the dialog in first screenshot is supposed to have this message...
```
French.UninstallOldVersionPrompt=Il semble y avoir une version antérieure de Rubberduck installée sur ce système pour %s.There seems to be a previous version of Rubberduck, qui devra d'abord être désinstallée. Procéder à la désinstallation?
```

So it is rendering correctly _here_ but not _there_. I'm not sure what's going on.

**Comment by FuSoftware** [comment] 2018-04-19 12:43
Seems plausible to me, this is what happends when I put the text in an UTF-8 document, then make it be read as ANSI

![capture2](https://user-images.githubusercontent.com/11671860/38992116-089b0706-43e0-11e8-937a-f25385c05eeb.PNG)

**Comment by bclothier** [comment] 2018-04-19 12:48
Can you provide the steps? I tried to do the same (at least I hoped) with Notepad++ but I could not reproduce the artifacts?

**Comment by bclothier** [comment] 2018-04-19 13:25
Reproduced. In Notepad++ I had to save the file using UTF-8 then use *Encoding* -> *Encode In ANSI*`, _not_ *Encoding* -> *Convert to ANSI*. 

Now I need to understand why this is apparently happening in an *Unicode* inno setup installer.

**Comment by FuSoftware** [comment] 2018-04-19 13:26
Maybe some intermediate files are ANSI during the installer's compilation ? I haven't used Innosetup in a while so I'm not sure

**Comment by retailcoder** [comment] 2018-04-19 13:55
> Might be present in previous installers, it's just the only one I tested since it's the last, previous ones are irrelevant.

Stupid question: "last" stands for "latest 2.2 pre-release build" or "last 2.2 green release build"?

Because the last commit to the resource file was made *after* the 2.2 "green release", specifically to attempt to address this issue.

**Comment by bclothier** [comment] 2018-04-19 13:58
The title says 3110 so that's the pre-release after 2.2

FWIW, you did commit the encoding issue before the green release. From master:
https://github.com/rubberduck-vba/Rubberduck/blob/master/Rubberduck.Deployment/InnoSetup/Includes/French.CustomMessages.iss

You can see that it has the "Fixing ???? encoding" commit already.

**Comment by bclothier** [comment] 2018-04-19 14:11
According to the [SO thread](https://stackoverflow.com/questions/49922735/inno-setup-unicode-encoding-issue-with-messages-in-iss-script#49923030) the issue seems to be that all `.iss` files should have the BOM mark. Even though the documentation did not specify that BOM was required, we need to create a PR that adds the BOM mark to all `.iss` files to avoid this issue.

**Closed** 2018-04-20 13:06 UTC
Labels: bug, difficulty-02-ducky, installer, up-for-grabs
