### ISSUE TITLE
Creating "Next" After Comment

### ISSUE THREAD

**Issue by DevulskyA** [rubberduck-vba/Rubberduck#4266] opened 2018-08-10 22:48 UTC
'BEFORE:
```
Option Explicit
Public myRibbon As IRibbonUI
Sub Onload(ribbon As IRibbonUI)
       'Create a ribbon instance for use in this project ' HIT ENTER HERE ->
       Set myRibbon = ribbon
End Sub
```
'AFTER:
```
Option Explicit
Public myRibbon As IRibbonUI
Sub Onload(ribbon As IRibbonUI)
       'Create a ribbon instance for use in this project ' HIT ENTER HERE->
       
       Next
       Set myRibbon = ribbon
End Sub
```

**Comment by retailcoder** [comment] 2018-08-10 23:04
Thanks for the feedback!

That's a known autocompletion issue... that an earlier PR  meant to fix... except the current implementation isn't covered with unit tests and therefore prone to regression bugs - long story short, I'll be completing the rewrite of self-closing pairs first (decoupled from the codepane, with unit tests this time), and the subsequent following 2.2.x prereleases will no longer have block completion, until it's rewritten - this time leveraging the shiny new `CodeStringParser`, which will make block completion *syntactically* aware of the surroundings of the current line of code... which has very powerful implications =)

I take full ownership of this cowboying: autocompletion thoroughly nerd-sniped me, I whipped up a quick half-baked feature as soon as I could thinking I could get away with it, and the subtle challenges and complexities of it are making it utterly annoying to work with existing code. I'd recommend disabling all block completions for the time being; self-closing pairs aren't *too* bad, but backspacing to delete a `(` or a `"` can be frustrating. "Smart Concat" works exactly as intended though.

**Comment by bclothier** [comment] 2019-08-12 12:37
The issue was labeled as a duplicate but didn't link to one - going to link to #4676 and #4289 and use those instead and close this issue.

**Closed by bclothier** 2019-08-12 12:37 UTC
Labels: duplicate, feature-autocomplete, feature-block-completion, work-item
