### ISSUE TITLE
VBAProjects Name is not actuell after rename Workbook

### ISSUE THREAD

**Issue by VBAndito** [rubberduck-vba/Rubberduck#5158] opened 2019-09-26 13:05 UTC
**Rubberduck version information**
The info below can be copy-paste-completed from the first lines of Rubberduck's log or the About box:

    Rubberduck version [2.4.1.4954]
    Operating System: [W10 1903 356]
    Host Product: [...]
    Host Version: [...]
    Host Executable: [...]

**Description**

VBAProjects Name is not actuell after rename Workbook

![VBAProject](https://user-images.githubusercontent.com/55839987/65690319-1502af80-e06f-11e9-934a-b17174ab1fa7.jpg)

**Comment by retailcoder** [comment] 2019-09-26 13:08
Just to confirm, the host workbook was "saved as" under a new name?

**Comment by VBAndito** [comment] 2019-09-26 13:17
Yes, Sir (Zalando2a) und aktualisiert, after that i load an older version of excelbook (Zalando2)

**Comment by VBAndito** [comment] 2019-09-26 13:19
sorry, for komplett information:
Version 2.4.1.4954
Betriebssystem: Microsoft Windows NT 10.0.18362.0, x64
Hostprodukt: Microsoft Office x64
Hostversion: 16.0.11929.20254
Hostprogramm: EXCEL.EXE

**Comment by MDoerner** [comment] 2019-09-26 14:17
I think the problem here is that a change of the document name actually does not trigger any event the VBE API exposes. The name of the document is not part of the actual project name; we just display it for convenience.

Das Problem hier ist voraussichtlich, dass der VBE uns nicht mitteilt, dass sich etwas geändert hat. Der Dateiname ist eigentlich kein Teil des Projektnamens.

**Comment by retailcoder** [comment] 2019-09-26 14:43
This is likely the culprit:

https://github.com/rubberduck-vba/Rubberduck/blob/b25e5be36b444601dc574becb843bfbe41b08975/Rubberduck.VBEditor.VB6/SafeComWrappers/VB/VBProject.cs#L170-L217

The cached "display name" of a project is not getting updated. This is a very tricky case of cache invalidation, because as the comment indicates getting this information from the host document involves annoying side-effects. Because the VBE doesn't tell us when the host document is saved (or renamed), our only hope to invalidate this cached name would likely be to invalidate it *every time we parse*, just to be sure we're still showing the correct name.

So this *is* a bug, but a very minor one - a project's `DisplayName` is really only ever used, as @MDoerner indicated, for convenience, in the Code Explorer: there is no other impact.

A work-around could be to force cache invalidation by... closing and re-opening the host application.

**Comment by bclothier** [comment] 2019-09-26 14:54
That said, we do have support for `IHostApplication`, which in theory can be extended to provide a mechanism for acquiring the current document name, which definitely will require separate implementations for each host's object model. Furthermore, not all hosts expose an event that can be used to know that a document was renamed which means we cannot be notified in all cases anyway.

I seem to recall someone at a point suggesting using a `FileWatcher` which would enable a host-independent manner of observing the renames but that may just open a can of worm (e.g. what if it has been renamed _and_ moved? Needs to be tested and handled for)

**Comment by retailcoder** [comment] 2019-09-26 15:01
Can of worms indeed! I'd prefer the `IHostApplication` approach, much fewer moving parts... besides if we only implement Excel, Word, and Access, we'll already cover 99% of the needs. A `FileSystemWatcher` would be something we would use, say, to detect changes to code files made outside the editor (and prompt to reload/replace the code file), say, in VB6 (or, in VBA, in a source control / repository scenario).

Plus `hostApp.ActiveDocument.Name` might be a COM hit, but it shouldn't involve any flickering, and then I believe it would also solve that obscure glitch with long file names when we pull the caption out of the VBE's MainWindow. We could still keep the VBE MainWindow as a fallback implementation in `HostApplicationBase`...

**Comment by MDoerner** [comment] 2019-09-26 15:34
I think we can even enhance this quite easily by first trying to get the filename. That will fail for unsaved files, but then we can still fall back to the displyname.

IIRC, comintern went with the display name because getting the name via COM required iterating the properties of the COM object, which takes ages. This change saved a significant amount of time per reparse.

**Comment by SmileyFtW** [comment] 2019-09-28 15:09
You appear to get the filename because the ThisWorkbook entry in CE shows it in parenthesis... am I off base and missing something obvious?
![image](https://user-images.githubusercontent.com/42221335/65818544-fcfa6f80-e1d7-11e9-99af-24a884cca1cb.png)

**Comment by retailcoder** [comment] 2019-09-28 15:27
@SmileyFtW for document modules, we get a display name by enumerating properties on the COM object, like @MDoerner mentioned - this is a rather expensive operation, but we can't know that a document module's display name was changed unless we check.
At the moment, Rubberduck sees `Workbook` and `Worksheet` modules as document modules with a different set of properties, and deep down in the lower-level tier we know `Sheet1` is a `Worksheet` and `ThisWorkbook` is a `Workbook`, but that information isn't yet making it to the higher-level code, so we don't know that the DisplayName of the `ThisWorkbook` is also the project's file name - the *project's* DisplayName is thus retrieved (and cached) as shown above, in a somewhat clunky host-agnostic way that leverages the fact that the host document's file name gets displayed in the VBE's mainwindow title bar.

**Comment by SmileyFtW** [comment] 2019-09-28 17:52
As always I know y'all know a LOT more about the underbelly of VBA and the host applications... thanks for all you do!

**Comment by MDoerner** [comment] 2019-10-01 11:59
This is a duplicate of #4789.

**Closed by MDoerner** 2019-10-01 11:59 UTC
Labels: bug, duplicate, edge-case
