### ISSUE TITLE
Annotation API

### ISSUE THREAD

**Issue by autoboosh** [rubberduck-vba/Rubberduck#1116] opened 2016-02-19 01:57 UTC
Depending on whether https://github.com/rubberduck-vba/Rubberduck/pull/1114 gets merged /  actually works, Rubberduck may soon have comments in the parse tree itself. This means that adding annotations to the parse tree should become easier/possible as well.

Perhaps we could build some sort of annotations API, just like the one Java has?

E.g. a class like:

```
public class IAnnotation
{
	public AnnotationType AnnotationType { get; set; }
	public DeclarationType DeclarationType { get; set; }
	public Context Context { get; set; }
	public ParserRuleContext Target { get; set; }
}
```

Each annotation would have its own subclass with its own parameters. E.g. the IgnoreInspection annotation could have a list of ignored inspections.

What declaration types are there currently, i.e. what can annotations be applied to? Modules and methods so far it seems?

The annotations could be made available as one big list through the parse state or through their "target contexts", e.g. the Declaration class.

Also, what's the official syntax of the annotations? It looks like currently something like this is in use:

`'@AnnotationName @Param1 @Param2`

Perhaps we could use a comma instead of a space after each param to align it with normal VBA syntax?

**Comment by retailcoder** [comment] 2016-02-19 02:26
> *What declaration types are there currently, i.e. what can annotations be applied to? Modules and methods so far it seems?*

And variables. Any `Declaration` has its list of `Annotations`, so *technically* even a project could be annotated... The current code determines a declaration has annotations by looking at the code line *immediately above* (that's one problem), and seeing whether there's a comment that *begins with* a `@` token (that's *another* problem).

Hence, this annotation isn't valid:

    '@Ignore ProcedureNotUsed

    Sub DoSomething()
    End Sub

And this one isn't picked up either:

    Dim i As long '@Ignore UseMeaningfulNames

---

Having the annotations as part of the parse tree would allow us to formalize the syntax. Right now it's pretty much free-for-all, but generally speaking the syntax would go something like this:

     annotation : '\'@' IDENTIFIER WS arg

I'd like to formaize it into something like this:

    annotation : '\'@' IDENTIFIER WS? argList?

Which means `@Ignore` annotations would need to be parameterized like this:

    '@Ignore(VariableNotUsed, VariableNotAssigned)

...actually `argList` wouldn't fit the bill here, we'd need our own new parser rule for it:

>     argList : LPAREN (WS? arg (WS? ',' WS? arg)*)? WS? RPAREN;

>     arg : (OPTIONAL WS)? ((BYVAL | BYREF) WS)? (PARAMARRAY WS)? ambiguousIdentifier (WS? LPAREN WS? RPAREN)? (WS? asTypeClause)? (WS? argDefaultValue)?;

But something like it. Like...

    annotationArgList : LPAREN (WS? annotationArg (WS? ',' WS? annotationArg)*)? WS? RPAREN;

    annotationArg : (IDENTIFIER | LITERAL)

Which would make these legal:

    '@Ignore (ProcedureNotUsed)
    '@Ignore(ProcedureNotUsed)
    '@Ignore (ProcedureNotUsed, VariableNotUsed)

It would be nice to be able to drop the parens, but it gets complicated to force LPAREN and RPAREN to balance when either is optional... unless we double up the whole definition?

    annotationArgList : (LPAREN (WS? annotationArg (WS? ',' WS? annotationArg)*)? WS? RPAREN)
         | (WS? annotationArg (WS? ',' WS? annotationArg)*)?)
    ;

Either way, introducing these rules into the grammar is a milestone that will require a new version number on the grammar file in the top section - it's becoming *Rubberduck's* grammar at that point.

**Comment by retailcoder** [comment] 2016-02-19 02:28
Forgot to clarify... for this to work:

    '@Ignore ProcedureNotUsed
    
    Sub DoSomething()
    End Sub

We'll need to use the VBIDE API's `ProcOfLine` method to determine if the startline of `AnnotationContext` is in the `DoSomething` procedure - procedures begin with the `Sub` keyword as far as grammar is concerned, but the VBE doesn't see it that way.

**Comment by autoboosh** [comment] 2016-02-19 08:49
If you treat `'@Ignore ProcedureNotUsed` as belonging to the procedure that might come somewhere below it, wouldn't that break module level annotations? How would you differentiate between the two?

What do you think about only allowing annotations to sit directly before the element it annotates? If there's no surrounding element, it would be a module level annotation. Example:

```

'@Folder MyFolder

'@Ignore ProcedureNotUsed
Sub Do Something()

'@Ignore NothingHere

End Sub
```

`@Folder` would be treated as a module level declaration ("officially", by allowing annotations to be there via grammar). `@Ignore` however would be treated as a method level annotation.

`'@Ignore NothingHere` could either be ignored or be treated as an error.

What do you think?

**Comment by retailcoder** [comment] 2016-02-19 20:49
@autoboosh the VBIDE API treats any comment above a procedure as part of that procedure's "body", so we can just call `ProcOfLine` to get the name (and `ProcKind`) of the member it belongs to (the horizontal lines denote where a member starts):

![image](https://cloud.githubusercontent.com/assets/5751684/13188321/ca364b90-d71e-11e5-9913-2c8766185b97.png)

Now, there *is* a[n edge] case that doesn't work *exactly* as intended:

![image](https://cloud.githubusercontent.com/assets/5751684/13188333/e8af3514-d71e-11e5-940f-e1fe45bf2d39.png)

...but if module-level annotations are the only thing in the declarations section, they need to be on line 1 for the VBE itself to understand it as part of the *declarations* section:

![image](https://cloud.githubusercontent.com/assets/5751684/13188352/07aa800e-d71f-11e5-834a-066e8fdafe98.png)

Point is, module-level annotations need to be in the declarations section. If that's clear for the users, then there's no need to go overboard with funky rules and syntaxes: we can know that an annotation is module-level if it's part of the `moduleDeclarations` node.

hmm.. perhaps a module-level `@Ignore` annotation could mean "ignore this inspection everywhere in the module"?

I think "illegal" or otherwise no-op annotations should at least pop an inspection result; breaking the parse tree / throwing an error over them would be overkill IMO.

**Comment by autoboosh** [comment] 2016-02-19 22:12
Here's a rough first version. Saw your last comment too late that's why it's implemented using the grammar only.

It works like this:

1. Grammar specifies where annotations may appear (right in front declarations, sub/function/properties, before and next to variable statements)
2. AnnotationListener gathers all annotations and creates IAnnotation instances using IAnnotationFactory
3. Annotations are stored on declarations for later use

Important notes:

- Comments starting with an @-sign are not allowed anymore, they are all treated as annotations
- Module level annotations are held apart from other annotations by requiring there to be an empty line after the last annotation
- Annotations in general must be stacked on top of eachother without any empty lines between them
- No validation is done to ensure that e.g. TargetContext of a variable statement does not get annotated with e.g. TestMethod annotation
- If something is wrong with the annotation, such as a missing argument, the annotation is not created / simply ignored (which can then be found using not yet implemented inspections)

What do you think of it?

**Comment by retailcoder** [comment] 2016-02-19 22:58
Hmm.. might be too strict. I'd rather maintain the possible annotations with code than by rebuilding the parser everytime a new annotation is needed.. no?

**Comment by autoboosh** [comment] 2016-02-20 12:29
OK :)

I'll change the code and post the updates.

**Comment by autoboosh** [comment] 2016-02-20 15:08
Updated to use VBE API for finding declaration type. Not sure if it's correct though: https://github.com/autoboosh/Rubberduck/commit/e2cd851c41650f13a001d48687ca201a9bac96db. Annotations can now be anywhere where comments can be without throwing a parser error.

It uses `ProcStartLine` instead of `ProcOfLine` since at the point of instantiation it already knows what procedure it is.

Module level annotations are now found by scanning the number of lines given by `CountOfDeclarationLines` starting from line 1.

Method level annotations are found by scanning the region between `ProcStartLine` and `(Procedure|Function|Property).Context.Start.Line`.

Variable annotations are found by retrieving all annotations defined right before the statement, i.e. without any empty line or other statement in between. "Same level" annotations are supported too.

Example:

```
'@Ignore Inspection1 '@Ignore Inspection2
'@Folder TestFolder

'@TestMethod
Public Sub Test()
    '@Ignore VariableNotUsed1
    Dim a As Integer '@Ignore VariableNotUsed2 '@Ignore VariableNotUsed3
End Sub
```

Multiple annotations can be defined on the same line.

In this example, there would be 3 module level annotations (2 Ignore, 1 Folder). 1 method level annotation (TestMethod) and 3 variable annotations.

Thoughts? :)

**Comment by retailcoder** [comment] 2016-02-20 15:15
Pure awesomeness!! The only thing is, I wonder if we shouldn't drop the apostrophe as part of the `@Marker`. What do you think? Would it make anything more frail or anything?

I hate that this would then be legal, but is it reasonable?

    ' some comment @SomeAnnotation
    Dim foo

**Comment by autoboosh** [comment] 2016-02-20 15:30
That should be possible, yes.

I'm not sure whether it's worth it though. I also don't like the comment marker being a part of the annotation marker but at least this way it's clearly separated. There are comments and then there are annotations. Users can still add comments on a separate line before the annotations. I'd leave it like this tbh and only add it if some user really really wants it :)

**Comment by autoboosh** [comment] 2016-02-20 22:32
Just discovered the Attribute and Member classes used for the TestExplorer. Apparently there's some annotation parsing in there as well.

What exactly is the idea with these? Should annotations be named annotations or attributes? Can they simply be replaced by the new annotation facility or is there something one should watch out for?

**Comment by retailcoder** [comment] 2016-02-20 23:55
That unit test discovery code pretty much predates the Rubberduck project - it would be nice to be able to rewrite this to use the new API for 2.0

**Comment by autoboosh** [comment] 2016-02-21 16:00
It's rewritten now. Can you take a look please? Here's the commit: https://github.com/autoboosh/Rubberduck/commit/f7fb474513e5f7a5560940f1276db91457c99022.

It looks like a lot but it's basically nothing more than removing the MemberAttributes and replacing them with the annotations + introducing a TestModule class to make it easier to group the tests, seemed like something like that was missing.

The "add a new test method" functionality doesn't create a testmethod by itself anymore now. It merely adds the test method text to the code pane. Testmethods are named by date + hours and seconds now.

Looks like the test explorer might need some more work but at least running tests should work as before.

I'd also like to hear your thoughts on the design of the annotations in general. E.g. is there a better way of instantiating the annotation classes? It seems like the annotation factory might blow up in size with time.

**Comment by retailcoder** [comment] 2016-02-21 16:32
@autoboosh amazing! I'll take a look as soon as I have a chance! :smiley:

**Comment by autoboosh** [comment] 2016-03-06 12:38
It looks like quite a few changes are coming to the declaration / resolving part which also relies on these annotations. Should we wait until those changes are merged into next to prevent conflicts?

**Comment by retailcoder** [comment] 2016-03-06 16:01
Sounds like a good idea. I'm not sure I'll be able to merge my changes this weekend though... there's a number of *cough* undesirable side-effects *cough* that come with suddenly working with 37K declarations (vs. 2K)

**Comment by autoboosh** [comment] 2016-04-20 18:52
The annotations are in the next branch now, just not used everywhere yet.

**Comment by retailcoder** [comment] 2016-04-29 15:59
closing for now - let's make separate issues for things that need to be changed to leverage this.

**Closed by retailcoder** 2016-04-29 15:59 UTC
Labels: code-parsing
