### ISSUE TITLE
all sub menus for refactoring and indentation are greyed out

### ISSUE THREAD

**Issue by mbrillante** [rubberduck-vba/Rubberduck#5331] opened 2019-12-23 14:46 UTC
**Rubberduck version information**
The info below can be copy-paste-completed from the first lines of Rubberduck's log or the About box:

    Rubberduck version [2.5.0.5244]
    Operating System: [Windows 7 Service pack 1 , X64]
    Host Product: [Office X86]
    Host Version: [16.0.11328.20368]
    Host Executable: [Excel]

**Description**
EVen after refreshing the code and the initialization status bar set to ready, all the refactoring and indendation sub menus are greyed out
![Screenshot1](https://user-images.githubusercontent.com/13575139/71363964-af9d5c80-2592-11ea-8080-03cb458afd4d.png)

**To Reproduce**
1. Go to 'VBA code'
2. Click on 'refresh on status bar'
3. open rubberduck/indent  menu
4. See sub menus greyed out

**Expected behavior**
Go to 'VBA code'
2. Click on 'refresh on status bar'
3. open rubberduck/indent  menu
4. See sub menus should be available to use
[RubberduckLog.txt](https://github.com/rubberduck-vba/Rubberduck/files/3995311/RubberduckLog.txt)

**Screenshots**

**Logfile**
Rubberduck generates extensive logging in TRACE-Level. If no log was created at `%APPDATA%\Rubberduck\Logs`, check your settings. Include this log for bug reports about the behavior of Rubberduck.

**Additional context**

**Comment by retailcoder** [comment] 2019-12-23 14:49
Are the indenter commands also disabled in the code pane context menu?

**Comment by mbrillante** [comment] 2019-12-23 14:56
yes I am afraid

![Screenshot2](https://user-images.githubusercontent.com/13575139/71364511-5df5d180-2594-11ea-83af-124a29260eb7.png)

**Comment by retailcoder** [comment] 2019-12-23 15:04
Ok, just looked at the logs - looks like a COM registration issue. This could be caused by a broken Office install, for example if you are running side-by-side different versions of Office that weren't installed in chronological order (e.g. installed Office 2016, then Access 2013)

**Comment by retailcoder** [comment] 2019-12-23 15:11
Linking #4955 - are other VBIDE add-ins loaded?

**Comment by mbrillante** [comment] 2019-12-23 15:13
Thanks for the very quick response, then there is very little that I can do as my organization does not allow me to fix this. In any case rubberduck is still very helpful to me

**Comment by mbrillante** [comment] 2019-12-23 15:14
> are other VBIDE add-ins loaded?

No

**Comment by retailcoder** [comment] 2019-12-23 15:16
Sorry to hear... on the other hand since side-by-side installs are only officially supported when installed in chronological order, you may have a solid case to get your IT department to repair Office: Rubberduck is being a coalmine canary here - it's very likely other things can break.

**Comment by bclothier** [comment] 2019-12-23 15:18
Just to confirm - did you try reinstalling Rubberduck? You should be able to do this using per-user install.

**Comment by mbrillante** [comment] 2019-12-23 15:19
Ys I did re-install it per user

**Comment by mbrillante** [comment] 2019-12-23 15:21
> Ok, just looked at the logs - looks like a COM registration issue. This could be caused by a broken Office install, for example if you are running side-by-side different versions of Office that weren't installed in chronological order (e.g. installed Office 2016, then Access 2013)

Theoretically I should not be allowed to install any software without their permission but I need to do my job properly :-)

**Comment by bclothier** [comment] 2019-12-23 15:22
Exactly why we support per-user install. ;-)

**Comment by mbrillante** [comment] 2019-12-23 15:22
looking at the installed programs, I have Office 365 before Project and Visio 2016

**Comment by retailcoder** [comment] 2019-12-23 15:31
Unfortunately there isn't much we can do on our end to fix this :(

Since the problem is already reported (linked issue), I'll be closing this one as a duplicate.

Good luck!

**Closed by retailcoder** 2019-12-23 15:31 UTC
Labels: duplicate, support
