### ISSUE TITLE
Member 'visible' was not found on the compile-time interface for type 'Label'

### ISSUE THREAD

**Issue by SystemsModelling** [rubberduck-vba/Rubberduck#3911] opened 2018-04-09 15:36 UTC
lblResult.Visible = true

**Comment by retailcoder** [comment] 2018-04-09 15:45
This is a known, long-standing resolver issue; MSForms controls have a weird type hierarchy and we're only seeing the declared type, IIRC `MSForms.Label` - the `Visible` property being a member of `MSForms.Control`, this issue will resolve itself when we figure out how to correctly annotate the MSForm types' type hierarchy.

**Comment by bclothier** [comment] 2018-04-09 15:47
Ref: [TypeLib API Integration](https://github.com/rubberduck-vba/Rubberduck/projects/15)

**Comment by comintern** [comment] 2018-10-15 00:49
Closing this as a duplicate of #2592. This specific example will no longer be reported after the incoming fix for #3532.

**Closed by comintern** 2018-10-15 00:49 UTC
Labels: bug, resolver
