### ISSUE TITLE
Sync exported code with folder annotations

### ISSUE THREAD

**Issue by Greedquest** [rubberduck-vba/Rubberduck#5284] opened 2019-11-13 07:38 UTC
**Justification**
When using the "export active project" function for source control, all files are dumped in a single folder - this makes navigation in Windows explorer or on GitHub more difficult. It would be good to specify a folder structure when exporting the project, similar to how RD is structured in GitHub.

**Description**
I think the best option would be to use existing folder annotations to dictate export directory. Folder paths would be relative to a specified root directory or perhaps just the active host document path

e.g for Excel, a code module with
```vb
'@Folder(Core.duckCodez)
```
... would be exported to
```none
{Workbook.Path}/Core/duckCodez/module.bas
```
Or use a folder selection dialogue to set the root path like we currently have.

**Additional context**
Worth noting that this could be breaking in filesystems that don't care about capitalisation/are more strict than RD is with folder paths (not sure if this is a problem in Windows, don't have my computer to hand)

**Comment by bclothier** [comment] 2019-11-13 12:02
Duplicate of #4646

**Closed by bclothier** 2019-11-13 12:02 UTC
Labels: enhancement
