### ISSUE TITLE
ninject creates two view instances in V 1.4.3

### ISSUE THREAD

**Issue by alanturing88** [rubberduck-vba/Rubberduck#2393] opened 2016-12-01 08:23 UTC
Hi,

I found this tool a few weeks ago and tried to make it run on my machine.

After testing the 2.x Versions I decided to use the stable Version 1.4.3. 

But in some views I could not do anything (e.g. nothing happend if I clicked on "Update" button in "Settings" view from source control) 

I found nothing about this issue on this site so i decided to debug myself.

Now I found something that I don't understand: Ninject creates two instances of some views for constructor injection... 

I changed the code in SourceControlBindings
from 
`Bind<ISettingsView>().To<SettingsControl>();`
to
`Bind<ISettingsView>().To<SettingsControl>().InSingletonScope();`

...after that code injection worked correctly (for my understanding)

The fact that this issue is not listed in the issue tracker makes me believe that this is not an error happening on any other machines. Am I missing something or is this a real issue?

thanks

**Comment by retailcoder** [comment] 2016-12-01 16:05
Hi @alanturing88, can you share a link to the commit/tree you're working with? Or are you working off [this tree (the 1.4.3 tag)](https://github.com/rubberduck-vba/Rubberduck/tree/5116cfc18903fba578e27cd84c3a99e97cec92dd)? Rubberduck has changed **A LOT** since v1.4.3 (3,642 commits to [next] since that release - I can't even begin to tell you how many bugs were found and fixed since then), in major breaking ways.

In fact, the very reason for the major version to turn to 2.0 was specifically because of all the breaking architectural changes that were required to invert dependencies and implement proper IoC/DI and decouple all the components to enable decent testability (we currently have over 1500 green tests and still not half the coverage we'd like to have); v1.4.3 did not use Ninject, or actually, only did half-assed DI that only affected the source control stuff (and boy, that was wrong!) - basically that "stable" version was a bloody tangled patchwork mess that I wouldn't touch with a ten-foot pole; may I ask what made you work off that version rather than the *much* more robust 2.x architecture?

Looking at [SourceControlBindings.cs](https://github.com/rubberduck-vba/Rubberduck/blob/5116cfc18903fba578e27cd84c3a99e97cec92dd/RetailCoder.VBE/UI/SourceControl/SourceControlBindings.cs) as it was, I'm seeing other problems: everything is implicitly binded in transient scope, which means the kernel won't call `Dispose` on any `IDisposable` dependencies - which is definitely a major problem. If singleton scope fixes it, roll with it - but in any case, the *composition root* should be responsible for building the entire application's dependency graph, *once*, as close as possible to the entry point. In 2.x that happens in the `_Extension` class, at start-up, and there is only ever one single kernel, that only ever lives in the class it's created in.

The reason there is no issue for it, is probably because after the 1.4.3 release, I proceeded with the major refactorings that lead to the 2.x architecture, and the entire `SourceControlBindings` file was completely removed - I cannot tell you why two instances would be created, but I can tell you that this is definitely not the only thing that's utterly and completely broken with the 1.x architecture, and hundreds if not thousands of problems found in 1.x are either moot, irrelevant, or fixed in 2.x - and I'm not even talking about parser/resolver issues.

I would gladly help you work out any bugs in the current / [next] build though - at this point the only thing that's preventing a "green" / "stable" 2.0 release is the teardown: there's something about `RubberduckHooks` and the `RubberduckCommandBar` (don't look for them in 1.x!) that isn't done right, that's crashing on dispose and bringing down the host process with it. We're closing in on the root cause and getting closer every day - feel free to fork the repository to keep up with all the changes being made.

**Closed by retailcoder** 2016-12-01 16:05 UTC
Labels: bug

**Comment by alanturing88** [comment] 2016-12-02 06:13
Hi @retailcoder,

thank you for your informative answer. I decided to use 1.4.3 because I tought it was latest stable release for 1.x. I used the source code from the [latest release](https://github.com/rubberduck-vba/Rubberduck/releases/tag/v1.4.3). 

Now I will try and fork Version 2.x.  

Thank you for your work on this tool! I am really excided from source control in VBE with Git. Great!

regards
