### ISSUE TITLE
Extract Method is ignorant of indentation 

### ISSUE THREAD

**Issue by ThunderFrame** [rubberduck-vba/Rubberduck#2285] opened 2016-10-05 08:17 UTC
The indentation of the extracted lines is preserved, and the indentation of the call to the new method is seemingly always 0 spaces.

Also note the error in the new method line placement - see comment in code below...

**Before:**

``` vb
Sub foo()

  Dim x As String
  If True Then
    If True Then
      If True Then
        x = "foo"
      End If
    End If
  End If

End Sub
```

**After:**

``` vb
Sub foo()

  If True Then
    If True Then
      If True Then
      End If
NewMethod 'Note this is also on the wrong line - it should be 1 line higher up
    End If
  End If

End Sub
Private Sub NewMethod()
  Dim x As String
        x = "foo"
End Sub
```

**Comment by retailcoder** [comment] 2016-10-05 13:30
This is by design, sort of - the refactoring was written before the indenter was finished - it's not a feature of the *extract method* refactoring to know how to indent code.

Changing from [bug] to [enhancement], since all that's needed is to call into the indenter interface when generating the extracted method.

**Comment by bclothier** [comment] 2017-11-08 00:53
@Vogel612, please assign to me.

**Closed** 2023-01-07 23:37 UTC
Labels: enhancement, feature-refactorings, refactoring-extract-method, work-item
