### ISSUE TITLE
Parse error using build .2827

### ISSUE THREAD

**Issue by daFreeMan** [rubberduck-vba/Rubberduck#3753] opened 2018-02-05 19:03 UTC
Win7 64-bit, Office 2010 32-bit, RD .2827

I have clean compiling code, yet build .2827 is throwing a parse error:

```
2018-02-05 13:43:43.4370;ERROR-2.1.2.2827;Rubberduck.Parsing.VBA.ParseCoordinator;Unexpected exception thrown in parsing run. (thread 38).;System.Runtime.InteropServices.COMException (0x80004005): The expression you entered refers to an object that is closed or doesn't exist.
```

Full log attached.
[RubberduckLog.txt](https://github.com/rubberduck-vba/Rubberduck/files/1696366/RubberduckLog.txt)

Based on some additional testing:
* I get a clean parse when running .2825
* I get the error with NO forms open
* I get a clean parse with ALL forms open

**Comment by Vogel612** [comment] 2018-02-05 22:14
IIUC this is going to be related to the changes in how Rubberduck accesses the COM Api exposed by the VBE. Recently this has changed very heavily...

**Comment by bclothier** [comment] 2018-02-12 22:04
I found what I believe is a variant. Trying opening all forms in design as @daFreeMan originally reported but that did NOT fix my parse error.

In my log, I have this:

```2018-02-12 16:02:53.3594;ERROR-2.1.6617.23383;Rubberduck.Parsing.VBA.ParseCoordinator;Unexpected exception thrown in parsing run. (thread 17).;System.Runtime.InteropServices.COMException (0x80004005): Error HRESULT E_FAIL has been returned from a call to a COM component.
   at Microsoft.Vbe.Interop.VBComponentClass.get_Type()
   at Rubberduck.VBEditor.SafeComWrappers.VBA.VBComponent.get_Type() in C:\GitHub\Rubberduck\Rubberduck\Rubberduck.VBEEditor\SafeComWrappers\VBA\VBComponent.cs:line 16
   at Rubberduck.Navigation.CodeExplorer.CompareByType.Compare(CodeExplorerItemViewModel x, CodeExplorerItemViewModel y) in C:\GitHub\Rubberduck\Rubberduck\RetailCoder.VBE\Navigation\CodeExplorer\CodeExplorerItemViewModel.cs:line 96
   at System.Linq.EnumerableSorter`2.CompareKeys(Int32 index1, Int32 index2)
   at System.Linq.EnumerableSorter`1.QuickSort(Int32[] map, Int32 left, Int32 right)
   at System.Linq.EnumerableSorter`1.Sort(TElement[] elements, Int32 count)
   at System.Linq.OrderedEnumerable`1.<GetEnumerator>d__1.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Rubberduck.Navigation.CodeExplorer.CodeExplorerItemViewModel.ReorderItems(Boolean sortByName, Boolean groupByType) in C:\GitHub\Rubberduck\Rubberduck\RetailCoder.VBE\Navigation\CodeExplorer\CodeExplorerItemViewModel.cs:line 246
   at Rubberduck.Navigation.CodeExplorer.CodeExplorerViewModel.ReorderChildNodes(IEnumerable`1 nodes) in C:\GitHub\Rubberduck\Rubberduck\RetailCoder.VBE\Navigation\CodeExplorer\CodeExplorerViewModel.cs:line 449
   at Rubberduck.Navigation.CodeExplorer.CodeExplorerViewModel.ReorderChildNodes(IEnumerable`1 nodes) in C:\GitHub\Rubberduck\Rubberduck\RetailCoder.VBE\Navigation\CodeExplorer\CodeExplorerViewModel.cs:line 450
   at Rubberduck.Navigation.CodeExplorer.CodeExplorerViewModel.set_Projects(ObservableCollection`1 value) in C:\GitHub\Rubberduck\Rubberduck\RetailCoder.VBE\Navigation\CodeExplorer\CodeExplorerViewModel.cs:line 290
   at Rubberduck.Navigation.CodeExplorer.CodeExplorerViewModel.HandleStateChanged(Object sender, ParserStateEventArgs e) in C:\GitHub\Rubberduck\Rubberduck\RetailCoder.VBE\Navigation\CodeExplorer\CodeExplorerViewModel.cs:line 332
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at Rubberduck.Parsing.VBA.RubberduckParserState.OnStateChanged(Object requestor, ParserState state) in C:\GitHub\Rubberduck\Rubberduck\Rubberduck.Parsing\VBA\RubberduckParserState.cs:line 331
   at Rubberduck.Parsing.VBA.RubberduckParserState.set_Status(ParserState value) in C:\GitHub\Rubberduck\Rubberduck\Rubberduck.Parsing\VBA\RubberduckParserState.cs:line 546
   at Rubberduck.Parsing.VBA.RubberduckParserState.SetStatusAndFireStateChanged(Object requestor, ParserState status) in C:\GitHub\Rubberduck\Rubberduck\Rubberduck.Parsing\VBA\RubberduckParserState.cs:line 559
   at Rubberduck.Parsing.VBA.ParseCoordinator.ExecuteCommonParseActivities(IReadOnlyCollection`1 toParse, IReadOnlyCollection`1 toReresolveReferencesInput, CancellationToken token) in C:\GitHub\Rubberduck\Rubberduck\Rubberduck.Parsing\VBA\ParseCoordinator.cs:line 242
   at Rubberduck.Parsing.VBA.ParseCoordinator.ParseAllInternal(Object requestor, CancellationToken token) in C:\GitHub\Rubberduck\Rubberduck\Rubberduck.Parsing\VBA\ParseCoordinator.cs:line 377
   at Rubberduck.Parsing.VBA.ParseCoordinator.ParseAll(Object requestor, CancellationToken token) in C:\GitHub\Rubberduck\Rubberduck\Rubberduck.Parsing\VBA\ParseCoordinator.cs:line 313
2018-02-12 16:02:53.3594;INFO-2.1.6617.23383;Rubberduck.Parsing.VBA.RubberduckParserState;RubberduckParserState (37) is invoking StateChanged (Error);
2018-02-12 16:02:53.4694;DEBUG-2.1.6617.23383;Rubberduck.Parsing.VBA.ParseCoordinator;Parsing run finished after 4.8448421s. (thread 17).;
2018-02-12 16:02:54.4415;DEBUG-2.1.6617.23383;Rubberduck.UI.Command.MenuItems.CommandBars.AppCommandBarBase;(53291640) Executing click handler for commandbar item '', hash code 9464271;
```

**Comment by MDoerner** [comment] 2018-02-16 14:15
Looking at the log again, I guess the actual problem is ot in what the PR above tries to fix, but in the code trying to determin the supertypes of document modules, which actually does not work anyway. (Reminder to self, forms in Access are documents not user forms.)

**Comment by MDoerner** [comment] 2018-02-16 15:10
The only difference in the supertype code is that the `ProjectsRepository` gets used. Somehow, the `VBComponent`s seem to only really attach to their properties if the `CodeModule` gets accessed right away or it is being accessed by the VBE itself (open code pane).

**Comment by bclothier** [comment] 2018-02-16 15:59
Regarding the issue with resolving the supertype of the document modules -- just a reminder that the capability is now there but needs to be implemented. There are a number of issues which touch this aspect, all grouped in this [TypeLib API project](https://github.com/rubberduck-vba/Rubberduck/projects/15), so this part likely needs to be changed anyway.

**Comment by bclothier** [comment] 2019-08-12 22:44
Cannot reproduce; most likely fixed via linked issues but this issue got missed. Closing.

**Closed by bclothier** 2019-08-12 22:44 UTC
Labels: bug, regression
