### ISSUE TITLE
Comma/Semi-Colon at end of Debug.Print statements causes parser error

### ISSUE THREAD

**Issue by ThunderFrame** [rubberduck-vba/Rubberduck#1790] opened 2016-06-11 04:12 UTC
```
Sub Foo()
  
  Debug.Print 1;
  
End Sub
```

```
Sub Foo()
  
  Debug.Print 1,
  
End Sub

**Comment by ThunderFrame** [comment] 2016-06-11 04:13
I'd expect the semi-colon case to be more common than the comma case.

**Comment by ThunderFrame** [comment] 2016-06-11 09:41
Actually, a semi-colon anywhere on the line is a parser error.

**Comment by autoboosh** [comment] 2016-06-11 10:17
It looks like Debug.Print takes an output list as argument instead of "normal" arguments? As @retailcoder said, it's just like the print statement and others: https://github.com/rubberduck-vba/Rubberduck/blob/next/Rubberduck.Parsing/Grammar/VBAParser.g4#L218.

I tried to find the signature of Debug.Print online but couldn't find anything. But I guess we could special case Debug.Print in the grammar by making e.g. a debugPrintStmt. We'd have to consider this in the resolver too then I guess? Otherwise we wouldn't add any references.

**Comment by BobTB** [comment] 2016-06-11 14:47
This is a duplicate of #1766 first three examples.

**Comment by retailcoder** [comment] 2016-06-11 15:58
@autoboosh IIRC it's also applicable when writing/printing to a file

**Comment by autoboosh** [comment] 2016-06-11 16:24
That should be covered already though, right? By the printStmt and writeStmt:

**Comment by retailcoder** [comment] 2016-06-11 16:29
Does `outputList` allow for semicolons?

**Comment by autoboosh** [comment] 2016-06-11 16:51
Yeah, here's the description: (5.4.5.8.1 Output Lists)[https://msdn.microsoft.com/en-us/library/ee199475.aspx]. So you can write something like this:

```
Debug.Print "Table"; Tab; "Attribute"
Debug.Print "Table1"; Tab; "Attribute1"
```

**Closed** 2016-06-11 23:53 UTC
Labels: bug, code-parsing, critical
