### ISSUE TITLE
Rubberduck Add-In could not be loaded (Autodesk Inventor 2020, missing log files)

### ISSUE THREAD

**Issue by sirKitKat** [rubberduck-vba/Rubberduck#5539] opened 2020-07-08 07:49 UTC
**Rubberduck version information**
The info below can be copy-paste-completed from the first lines of Rubberduck's log or the About box:

    Rubberduck version 2.5.0.5244
    Operating System: Windows 10 Pro (Microsoft Windows NT 10.0.18363.0 x64)
    Host Product: Autodesk Inventor Professional 2020
    Host Version: Release 2020.3 (Build 373)
    Host Executable: Inventor.exe

**Description**
After installing, the following error comes up when starting (loading) Rubberduck:
Rubberduck's startup sequence threw an unexpected exception. Please check the Rubberduck logs for more information and report an issue if necessary.

The folder `\AppData\Roaming\Rubberduck\Logs\` is empty.

**To Reproduce**
1. Install, Open & Close Autodesk Inventor (there is a trail version for 30 day's)
2. Install Rubberduck
3. Open Inventor
4. Open the VBE (Tools->VBA Editor)
5. The Rubberduck loadingscreen appears

**Expected behavior**
Rubberduck finishing the startup sequence successfully.

**Screenshots**
![image](https://user-images.githubusercontent.com/1853002/86891115-9909bd80-c0fe-11ea-8b94-6d5ecb4c91bc.png)
![image](https://user-images.githubusercontent.com/1853002/86891343-f998fa80-c0fe-11ea-8597-8a921006e29f.png)
![image](https://user-images.githubusercontent.com/1853002/86890605-dc176100-c0fd-11ea-9e01-fd359cc08c7d.png)

**Logfile**
_No logfile was created_

**Additional context**
Rubberduck seems to work fine in Office 365 (including trace log)

**Comment by MDoerner** [comment] 2020-07-08 09:45
Thanks for reporting. We already have an issue for this and we do not really know why this happens. Thanks also for mentioning the trial version. We might use that to investigate.

Duplicate of #5373

**Closed by MDoerner** 2020-07-08 09:45 UTC
Labels: duplicate
