### ISSUE TITLE
'@folder fails if not on the first line of code

### ISSUE THREAD

**Issue by daFreeMan** [rubberduck-vba/Rubberduck#2656] opened 2017-02-07 15:47 UTC
If I have 

    '@folder "OnOpen.SetUp"
    Option Explicit

the `@folder` works perfectly.

If I have 

    Option Explicit
    '@folder "OnOpen.SetUp"

the `@folder` is ignored.

There should probably be an inspection for that. There could possibly also be a warning during the parse that the `@folder` command was found but ignored.

![rd folder failure](https://cloud.githubusercontent.com/assets/11889733/22698504/bcc5149e-ed22-11e6-8f95-541bf3f7c2b5.PNG)

**Comment by comintern** [comment] 2017-02-07 18:13
Currently annotating the module is being handled here...

        private IEnumerable<IAnnotation> FindAnnotations()
        {
            if (_annotations == null)
            {
                return null;
            }
            var lastDeclarationsSectionLine = _qualifiedName.Component.CodeModule.CountOfDeclarationLines;
            var annotations = _annotations.Where(annotation => annotation.QualifiedSelection.QualifiedName.Equals(_qualifiedName)
                && annotation.QualifiedSelection.Selection.EndLine <= lastDeclarationsSectionLine);
            return annotations.ToList();
        }

...which is explicitly requiring the folder annotation to be above all of the declaration lines (in the example code that would be `Option Explicit`).  Not sure if this is intentional or not, but it would be pretty easy to modify the rule to allow it anywhere above the first procedure line or anywhere in the module.

Thoughts?

**Comment by retailcoder** [comment] 2017-02-07 18:28
@comintern go ahead; I'd say a module-level annotation is legal anywhere in that module's *declarations section*.

**Comment by comintern** [comment] 2017-02-07 18:45
OK, officially re-defining what constitutes the declarations section.  The root of the issue is that `CodeModule.CountOfDeclarationLines` doesn't consider comments or whitespace to be "declarations".

This code has 3 declaration lines:
```
Option Explicit
'@folder "OnOpen.SetUp"
Dim foo As Long

Private Sub ObscuredByHandDrawnRedCircle()
    '...
End Sub
```
This code has 1:
```
Option Explicit
'@folder "OnOpen.SetUp"


Private Sub ObscuredByHandDrawnRedCircle()
    '...
End Sub
```

**Comment by retailcoder** [comment] 2017-02-07 18:49
There's going to be an ambiguity between module-level and procedure-level annotations for the first procedure. Consider:

    '@Ignore ProcedureNotUsed

    Public Sub DoSomething()
    End Sub

    Public Sub DoSomethingElse()
    End Sub

Is the `@Ignore` annotation at module level? Or tacked to `DoSomething`? (notice there is *no* declarations section here)

**Comment by comintern** [comment] 2017-02-07 19:11
The annotation finder *should* attach the annotations to both in that case. This may be a good case to moving toward more hierarchical annotations (ref #2532). In the meantime, it should be sufficient to filter the individual annotations by "scope" - i.e., a `'@Folder` annotation can only be added to `*ModuleDeclaration`, `@Ignore` etc. can't.

**Comment by retailcoder** [comment] 2017-02-07 19:12
Almost sounds like .net attributes' `AttributeUsage` attribute.

**Comment by comintern** [comment] 2017-02-08 02:16
Played around with coding this and determined that the documentation for `CodeModule.CountOfDeclarationLines` and `CodeModule.ProcOfLine` are misleading.  The declaration lines are anything that is left over from counting *up* from the first line that returns a non-empty result from `CodeModule.ProcOfLine`.  That function is documented as:

>  **Remarks**
> 
> A line is within a procedure if it's a blank line or comment line preceding the procedure declaration and, if the procedure is the last procedure in a code module, a blank line or lines following the procedure.

In practice, it's *all* of the blank lines or comments preceding the declaration ***except*** lines containing comments immediately following declaration lines.

This works in the current build and adds the folder annotation.
```
Option Explicit
'@Folder "Some.Folder"      <--last declaration line.


Private Sub Proc()
    '...
End Sub
```
This doesn't:
```
Option Explicit      '<--last declaration line.

'@Folder "Some.Folder"    '<--first line of proc.

Private Sub Proc()
    '...
End Sub
```
This also works:
```
Option Explicit

'@folder "OnOpen.SetUp"
Dim Foo As Long
Private Sub ObscuredByHandDrawnRedCircle()
    '...
End Sub
```
Anything above `Option Explicit` obviously works (assuming it compiles...).

**Closed** 2017-02-08 02:59 UTC
Labels: feature-annotations, feature-code-explorer, status-bydesign, support

**Comment by ThunderFrame** [comment] 2017-02-08 03:03
Actually, the rule is a little more nuanced. As usual, it's line continuations that facilitate the madness.

```
Option Explicit

'@folder "OnOpen.SetUp"



' Declarations end, at the end of the next physical line _




Sub test()

End Sub
```

**Comment by daFreeMan** [comment] 2017-02-08 12:44
@comintern might want to document that somewhere. Other than in the issue report, that is. :)

**Comment by PeterMTaylor** [comment] 2017-02-08 19:43
Suggesting the Wiki @comintern  :)
