### ISSUE TITLE
Has the Code Inspection window has lost its "inspection description bar"?

### ISSUE THREAD

**Issue by daFreeMan** [rubberduck-vba/Rubberduck#5270] opened 2019-11-07 15:38 UTC
**Rubberduck version information**
```
Version 2.4.1.5182
OS: Microsoft Windows NT 10.0.17134.0, x64
Host Product: Microsoft Office 2016 x64
Host Version: 16.0.4912.1000
Host Executable: EXCEL.EXE
```

**Description**
The info bar describing the inspection and offering the full list of quick fixes has disappeared! Oh, wait, it's there, it's just... hiding.

**To Reproduce**
1. Open the Code Inspections tool window
2. Expand a section
3. Click an inspection
1. Grab the scroll thumb and scroll all the way to the bottom of the window.
1. Oh, there you are! Don't be shy, come out an play

**Expected behavior**
This is definitely a regression. The description bar should always be visible. The vertical scroll bar should only be on the "inspections" pane in the TW, not for the entire window.

**Screenshots**
Hey, where'd it go?
![2019-11-07 10_30_24-Window](https://user-images.githubusercontent.com/11889733/68403154-7deb4600-014a-11ea-85ea-b318d51efaf9.png)

There you are!
![2019-11-07 10_31_20-Window](https://user-images.githubusercontent.com/11889733/68403172-86438100-014a-11ea-8a49-81e8fb6fe296.png)

**Logfile**
[RubberduckLog.txt](https://github.com/rubberduck-vba/Rubberduck/files/3820377/RubberduckLog.txt)

**Additional context**
Come out, come out, wherever you are!

**Comment by retailcoder** [comment] 2019-11-07 15:39
Duplicate of #5265

**Closed by retailcoder** 2019-11-07 15:39 UTC
Labels: bug, duplicate
