### ISSUE TITLE
Control declarations aren't cleared from the cache on reparse.

### ISSUE THREAD

**Issue by comintern** [rubberduck-vba/Rubberduck#2603] opened 2017-01-31 15:47 UTC
Noticed this on #2602 (same code):

In a  `UserForm`  with  `TextBox1` :
```
Private Sub TextBox1_Exit(ByVal Cancel As MSForms.ReturnBoolean)
    If TextBox1.Text = vbNullString Then
        MsgBox "Value required"
        Cancel = True
    End If
End Sub
```
The first set of results is "normal" (given the false inspection hit):
![untitled](https://cloud.githubusercontent.com/assets/8944005/22471995/d93b653a-e799-11e6-85d7-99bbfe3144a6.png)

Hitting the reparse button give this:

![untitled2](https://cloud.githubusercontent.com/assets/8944005/22472051/0c88d4f4-e79a-11e6-8442-5083ccf1c300.png)
 Hit it again...
![untitled3](https://cloud.githubusercontent.com/assets/8944005/22472117/3d02bdde-e79a-11e6-8771-c0366b55733d.png)

...etc.

**Comment by retailcoder** [comment] 2017-02-01 01:56
Odd. `RubberduckParserState.AddDeclaration` is *supposed* to handle this.

````csharp
        /// <summary>
        /// Adds the specified <see cref="Declaration"/> to the collection (replaces existing).
        /// </summary>
        public void AddDeclaration(Declaration declaration)
        {
            var key = declaration.QualifiedName.QualifiedModuleName;
            var declarations = _moduleStates.GetOrAdd(key, new ModuleState(new ConcurrentDictionary<Declaration, byte>())).Declarations;

            if (declarations.ContainsKey(declaration))
            {
                byte _;
                while (!declarations.TryRemove(declaration, out _))
                {
                    Logger.Warn("Could not remove existing declaration for '{0}' ({1}). Retrying.", declaration.IdentifierName, declaration.DeclarationType);
                }
            }
            while (!declarations.TryAdd(declaration, 0) && !declarations.ContainsKey(declaration))
            {
                Logger.Warn("Could not add declaration '{0}' ({1}). Retrying.", declaration.IdentifierName, declaration.DeclarationType);
            }
        }
````

**Comment by retailcoder** [comment] 2017-02-01 02:10
Bug is repro'd only when there's no reparse between inspection runs. This points to a bug in the `DeclarationFinder` cache of ...parameter declarations?

**Comment by retailcoder** [comment] 2017-02-01 02:23
Wrong lead. The parameter declaration's `References` collection has 3 dupes after the 3rd inspection re-run. This has to be a resolver bug.

**Comment by retailcoder** [comment] 2017-02-01 04:36
Ok, this is much trickier than I originally thought.

**Comment by comintern** [comment] 2017-02-02 01:08
Just checked the logs for this. When the inspection results are refreshed from the Code Inspections window, the inspections themselves run _twice_...

```
2017-02-01 19:05:38.8303;DEBUG-2.0.12.31400;Rubberduck.UI.Command.MenuItems.CommandBars.AppCommandBarBase;(642126) Executing click handler for commandbar item 'Ready', hash code 50254750;
2017-02-01 19:05:39.0546;DEBUG-2.0.12.31400;Rubberduck.App;App handles StateChanged (Ready), evaluating menu states...;
2017-02-01 19:05:39.0788;TRACE-2.0.12.31400;Rubberduck.Root.TimedCallLoggerInterceptor;Intercepted invocation of 'ApplicationWorksheetFunctionInspection.GetInspectionResults' ran for 23ms;
2017-02-01 19:05:39.0894;TRACE-2.0.12.31400;Rubberduck.Root.EnumerableCounterInterceptor`1;Intercepted invocation of 'ApplicationWorksheetFunctionInspection.GetInspectionResults' returned 0 objects.;
[snip]
2017-02-01 19:05:40.3269;TRACE-2.0.12.31400;Rubberduck.UI.Inspections.InspectionResultsViewModel+<RefreshInspections>d__35;Inspections loaded in 1296ms;
2017-02-01 19:05:40.4439;DEBUG-2.0.12.31400;Rubberduck.App;App handles StateChanged (ResolvedDeclarations), evaluating menu states...;
2017-02-01 19:05:40.5396;DEBUG-2.0.12.31400;Rubberduck.Parsing.VBA.RubberduckParserState;Module 'UserForm1' state is changing to 'ResolvingReferences' (thread 14);
2017-02-01 19:05:40.5396;DEBUG-2.0.12.31400;Rubberduck.App;App handles StateChanged (ResolvingReferences), evaluating menu states...;
2017-02-01 19:05:40.6402;DEBUG-2.0.12.31400;Rubberduck.Parsing.VBA.RubberduckParserState;Module 'ThisWorkbook' state is changing to 'ResolvingReferences' (thread 14);
2017-02-01 19:05:40.6518;DEBUG-2.0.12.31400;Rubberduck.Parsing.VBA.RubberduckParserState;Module 'Sheet1' state is changing to 'ResolvingReferences' (thread 14);
2017-02-01 19:05:40.9718;WARN-2.0.12.31400;Rubberduck.Parsing.Symbols.TypeAnnotationPass;Failed to resolve type VBE;
2017-02-01 19:05:41.1767;WARN-2.0.12.31400;Rubberduck.Parsing.Symbols.TypeAnnotationPass;Failed to resolve type VBProject;
2017-02-01 19:05:41.2135;WARN-2.0.12.31400;Rubberduck.Parsing.Symbols.TypeAnnotationPass;Failed to resolve type VBProject;
2017-02-01 19:05:41.3972;WARN-2.0.12.31400;Rubberduck.Parsing.Symbols.TypeAnnotationPass;Failed to resolve type VBE;
2017-02-01 19:05:41.4590;DEBUG-2.0.12.31400;Rubberduck.Parsing.VBA.RubberduckParserState;Module 'UserForm1' state is changing to 'ResolvingReferences' (thread 15);
2017-02-01 19:05:41.4619;DEBUG-2.0.12.31400;Rubberduck.Parsing.VBA.ParseCoordinator;Resolving identifier references in 'VBAProject.UserForm1'... (thread 15);
2017-02-01 19:05:41.4619;TRACE-2.0.12.31400;Rubberduck.Parsing.Symbols.IdentifierReferenceResolver;Setting current scope: TextBox1_Exit (Procedure) in thread 15;
2017-02-01 19:05:41.4619;TRACE-2.0.12.31400;Rubberduck.Parsing.Symbols.IdentifierReferenceResolver;Current scope is now TextBox1_Exit in thread 15;
2017-02-01 19:05:41.4619;DEBUG-2.0.12.31400;Rubberduck.Parsing.VBA.ParseCoordinator;Binding resolution done for component 'UserForm1' in 2ms (thread 15);
2017-02-01 19:05:41.4619;DEBUG-2.0.12.31400;Rubberduck.Parsing.VBA.RubberduckParserState;Module 'UserForm1' state is changing to 'Ready' (thread 15);
2017-02-01 19:05:41.4871;DEBUG-2.0.12.31400;Rubberduck.Parsing.VBA.RubberduckParserState;Module 'ThisWorkbook' state is changing to 'ResolvingReferences' (thread 15);
2017-02-01 19:05:41.4871;DEBUG-2.0.12.31400;Rubberduck.Parsing.VBA.ParseCoordinator;Resolving identifier references in 'VBAProject.ThisWorkbook'... (thread 15);
2017-02-01 19:05:41.4871;DEBUG-2.0.12.31400;Rubberduck.Parsing.VBA.ParseCoordinator;Binding resolution done for component 'ThisWorkbook' in 0ms (thread 15);
2017-02-01 19:05:41.4996;DEBUG-2.0.12.31400;Rubberduck.Parsing.VBA.RubberduckParserState;Module 'ThisWorkbook' state is changing to 'Ready' (thread 15);
2017-02-01 19:05:41.5103;DEBUG-2.0.12.31400;Rubberduck.Parsing.VBA.RubberduckParserState;Module 'Sheet1' state is changing to 'ResolvingReferences' (thread 15);
2017-02-01 19:05:41.5103;DEBUG-2.0.12.31400;Rubberduck.Parsing.VBA.ParseCoordinator;Resolving identifier references in 'VBAProject.Sheet1'... (thread 15);
2017-02-01 19:05:41.5103;DEBUG-2.0.12.31400;Rubberduck.Parsing.VBA.ParseCoordinator;Binding resolution done for component 'Sheet1' in 0ms (thread 15);
2017-02-01 19:05:41.5257;DEBUG-2.0.12.31400;Rubberduck.Parsing.VBA.RubberduckParserState;Module 'Sheet1' state is changing to 'Ready' (thread 15);
2017-02-01 19:05:41.5393;DEBUG-2.0.12.31400;Rubberduck.App;App handles StateChanged (Ready), evaluating menu states...;
2017-02-01 19:05:41.7877;TRACE-2.0.12.31400;Rubberduck.Root.TimedCallLoggerInterceptor;Intercepted invocation of 'VariableTypeNotDeclaredInspection.GetInspectionResults' ran for 7ms;
2017-02-01 19:05:41.7877;TRACE-2.0.12.31400;Rubberduck.Root.EnumerableCounterInterceptor`1;Intercepted invocation of 'VariableTypeNotDeclaredInspection.GetInspectionResults' returned 0 objects.;
[snip]
2017-02-01 19:05:42.2924;TRACE-2.0.12.31400;Rubberduck.UI.Inspections.InspectionResultsViewModel+<RefreshInspections>d__35;Inspections loaded in 770ms;
```

**Comment by MDoerner** [comment] 2017-02-02 12:53
The problem here is that a state changed event (ready) is fired after the button click. Atm, the method starting the inspections registers to that event. Accordingly, it starts the inspections right after the button click, although a reparse is imminent. 

To solve this, we should probably follow @retailcoders suggestions to relocate the inspection start into the `ParseCoordinator`. This would also allow to cancel inspections or at least the processing of their results.

**Comment by retailcoder** [comment] 2017-03-02 17:01
Since inspections aren't moving to `Rubberduck.Parsing` assembly/namespace in 2.0.12, I'm deferring this issue for now.

**Comment by MDoerner** [comment] 2017-05-17 22:30
I think the original issue was a problem with the removal, or rather lack of, of references.

Can the original issue still be reproduced?

**Comment by retailcoder** [comment] 2017-05-21 17:41
With the inspections now controlled and cancelled by the the parse coordinator, plus the fixes made to caching mechanisms, I don't see how this would be reproducible now. Considered fixed.

**Closed by retailcoder** 2017-05-21 17:41 UTC
Labels: bug, critical, parse-tree-processing, status-deferred
