### ISSUE TITLE
Code Inspection: Right click fix

### ISSUE THREAD

**Issue by IvenBach** [rubberduck-vba/Rubberduck#2767] opened 2017-03-02 01:20 UTC
You can click Fix and select an option in there. Would it be possible to allow a Rt-Click and have the same options pop up?

**Comment by retailcoder** [comment] 2017-03-02 01:39
Duplicate of #2614.

---

Definitely a must - the only problem is that the way inspections work ATM doesn't quite play well with it... but I'm going to be moving the `IInspection` interface (the whole `Rubberduck.Inspections.Abstract` namespace actually) to the `Rubberduck.Parsing` assembly/namespace, and from there we'll be able to *eventually* start *annotating* things (e.g. parse tree nodes) with inspection results.

Right now inspections run *as a result of* parsing/resolving being completed, on-the-side, yielding pretty much a "list of inspection results"; by moving them to the `Rubberduck.Parsing` assembly we'll be making them a full-fledged part of the parser, and the parse coordinator will have a better grip on them (e.g. cancelling them will be much easier) - and with the results being actually part of the parse trees the context-sensitive toolbar/"status bar" will be able to know when the selection has inspection results attached, which means we'll also be able to have a context menu dedicated to inspections, and therefore we'll be able to select a quickfix in-place, right there in the code pane... and in 3.0 ...nevermind, I'm drifting. But this will enable *awesome* things 😃

**Closed** 2017-03-02 01:42 UTC
Labels: duplicate, enhancement, feature-inspections, feature-request
