### ISSUE TITLE
Object variable 'VariableName' is assigned without the 'Set' keyword

### ISSUE THREAD

**Issue by carlossierra311** [rubberduck-vba/Rubberduck#4359] opened 2018-09-08 23:17 UTC
I am getting the **Object variable 'VariableName' is assigned without the 'Set' keyword** Code Quality Issue being reported incorrectly (imho) for a lot of variable assignments.  

Here is one particular (simplified) example where the issue is being reported for the `Cell.Interior.Color` property:
```
Private Sub AddCellMessage(ByVal Color As CellColor)
    With Cell
        .Interior.Color = Color ' This shouldn't be marked in my opinion! 
    End With
End Sub
```

Here is another example that makes even less sense to me, as the `Cell` variable "assignment" is done as part of the `for each` cycle: 
```
Public Function IsEmptyRange(ByVal CellRange As Range) As Boolean
    IsEmptyRange = True
    Dim Cell As Range
    For Each Cell In CellRange
        If (Not IsEmpty(Cell.Value2)) Then
            IsEmptyRange = False
            this.Logger.Error Message:="Cell is not empty.", Args:=Cell
        End If
    Next
End Function
```

Thanks!

Version 2.2.0.3739
OS: Microsoft Windows NT 10.0.17134.0, x64
Host Product: Microsoft Office 2016 x86
Host Version: 16.0.10730.20088
Host Executable: EXCEL.EXE

**Comment by daFreeMan** [comment] 2018-09-09 13:49
Duplicate of #4318

**Closed** 2018-09-09 14:53 UTC
Labels: bug, duplicate, feature-inspections, inspection-false-positive
