### ISSUE TITLE
Parser Error for Multi-Line Date Array

### ISSUE THREAD

**Issue by pmtutko** [rubberduck-vba/Rubberduck#1917] opened 2016-06-27 15:51 UTC
Running Rubberduck v2.0.3.32032 (Beta 3), I'm getting a parser error

> Module 1  Module L6C54  no viable alternative at input '#1/1/2016#, #2/2/2016#, # _\r\n'

for the following code:

    Option Explicit
    Sub test()
        Dim foo() As Date
        foo = Array(#1/1/2016#, #2/2/2016#, #3/3/2016#)
        foo = Array(#1/1/2016#, #2/2/2016#, #3/3/2016#, # _
                    4/4/2016#, #5/5/2016#)
    End Sub

I picked up this error when scanning an older module I created that had a sub to test a particular set of functions using dates. The Date array without the line break parses without issue. The Date array with the line break is the one generating the problem report.

**Comment by Hosch250** [comment] 2016-06-27 15:53
Looks like our grammar doesn't support whitespace or a line continuation after that character in a date.

**Comment by retailcoder** [comment] 2016-06-27 15:58
@pmtutko VBA allows *that*?? I mean, you're chopping the *date literal* token in two... Thanks for reporting this bug (it *is* a bug if VBA compiles it and our parser chokes on it), but honestly IMO VBA shouldn't be allowing this. What's the rationale for splitting a date literal token on two lines?

Does this parse correctly?

    foo = Array(#1/1/2016#, #2/2/2016#, #3/3/2016#, _
                #4/4/2016#, #5/5/2016#)

@Hosch250 FWIW that's a low-priority edge case issue, unless there's a problem parsing the above.

**Comment by Hosch250** [comment] 2016-06-27 16:01
That isn't even valid VBA--I just tried it.

**Comment by pmtutko** [comment] 2016-06-27 16:01
@Hosch250 your extended line array is what I originally entered into VBA. The VBA editor broke the line after the "#", not me. While I didn't agree with the automatic reformatting, it compiles just fine. The rubberduck parser complains though.

**Comment by Hosch250** [comment] 2016-06-27 16:02
That is so weird.  I just tried typing it, and it complained right out.

**Comment by pmtutko** [comment] 2016-06-27 16:04
I'm personally fine with not fixing this and agree that it's a weird edge case. I commented the line in my test sub to avoid the issue. It's not a syntax I would normally use anyway. Just wanted to make the team aware of it.

**Comment by Hosch250** [comment] 2016-06-27 16:05
OK.  I can't even get the VBE to accept the input, so I guess we probably won't fix it.

**Comment by Hosch250** [comment] 2016-06-28 03:53
We figured out how to reproduce this.  Expect a fix next release.

**Closed** 2016-06-28 20:49 UTC
Labels: bug, vba-grammar
