### ISSUE TITLE
MS Access leaves a ghost process

### ISSUE THREAD

**Issue by daFreeMan** [rubberduck-vba/Rubberduck#3905] opened 2018-04-09 12:01 UTC
Win10, Office 2016 64-bit.

Open Access, open VBE, parse project, close Access. MSACCESS.EXE remains in Task Manager.

[RubberduckLog.txt](https://github.com/rubberduck-vba/Rubberduck/files/1889746/RubberduckLog.txt)

**Comment by Vogel612** [comment] 2018-04-09 12:13
Apart from a few SLL mode failures for parsing, the log looks pretty clean

**Comment by MDoerner** [comment] 2018-04-09 12:26
After having a short look at the log file, I think the problem is that a parse still has been running when RD has been shut down.

**Comment by daFreeMan** [comment] 2018-04-09 12:28
Reproduced the hang. Reran with trace log. Was sure to wait until the parse had completed. Shut down VBE, then exited Access. Last time I just closed Access & let it close down the VBE.
[RubberduckLog.txt](https://github.com/rubberduck-vba/Rubberduck/files/1889847/RubberduckLog.txt)

**Comment by MDoerner** [comment] 2018-04-09 12:34
Hm, the toolwindows seem to not close down, which basicallyeans they never get a `WM_CLOSE` message.

**Comment by daFreeMan** [comment] 2018-04-09 12:35
Knowing is half the battle. That sounds like progress to me!!

**Comment by bclothier** [comment] 2018-04-09 17:11
FYI I cannot replicate this on Access 2016 x32 on Windows 10 but I can on Access 2010 x32 on Windows 7.... and only if I've parsed.

**Comment by daFreeMan** [comment] 2018-04-09 18:15
My old machine was Win7 Office2010 x32 and yes, I had it very consistently on that one, too.

**Comment by Vogel612** [comment] 2018-04-09 20:07
Can confirm clean exit on Access 2016 on Windows 10

**Comment by bclothier** [comment] 2018-04-09 20:09
I'm sure there's a setting at play. Maybe having a window visible at startup? 

Or it may depend on code (e.g. exceptions from inspection => dirty exit), maybe?

**Comment by daFreeMan** [comment] 2018-04-09 20:54
That could be it. I do have a form auto-run and it's usually open when I exit.

**Comment by daFreeMan** [comment] 2018-04-10 13:40
I tested closing out the default form and I'm still getting a zombie. :(

I saw in #3614 that there was a note about closing Access with an RD tool window docked, which I normally do with my CE.

I opened my Access project, undocked the CE then closed the project.
I reopened my project, parsed, then closed the VBE followed by Access itself. 
I'm still getting a zombie.

**Comment by retailcoder** [comment] 2018-04-11 14:29
@daFreeMan that would probably be the CLR eventually coming to the realization that it's time to perform garbage collection of whatever was left behind :+1:

**Comment by daFreeMan** [comment] 2018-04-12 11:38
Due to HIPAA regulations, it's incredibly difficult to get a file off our work network. Also, it's _possible_ that there might be some HIPPA data visible in the dump file. To mitigate the issue and prevent me getting myself fired, I'm going to attempt to reproduce the issue at home and load the dump file from there.

**Comment by MDoerner** [comment] 2018-04-12 21:46
Althouggh I cannot reproduce this ecaxt issue, I get a never ending sequence of access violations on shutdown when running in the debugger. 

After some investigation, I found out that this behaviour started with PR #3857.

**Comment by dermoench42** [comment] 2018-07-09 14:32
Can confirm sometimes an unclean shutdown on current Windows10 / Office 2016 64bit in an VirtualBox.

mostly after using some rubberduck functionality e.g. 'indent' current module.

An MS Access ghost task remains an if restarting some 10 seconds later, Rubberduck won't come up - only the virgin VBE.

After killing the ghost and restarting Access Rubberduck comes up, but displays the 'first start after install' message: "Would You like to see the chanlog..." or similar.

But maybe it is related to the 'refresh' - on my db it took around a minute to finish.

When closing access while rubberduck is refreshing, the cpuload of the ghost task stays hi for this minute and then goes down to zero. But the process doesn't disappear. And again when restarting access rubberduck won't appear.

ervin

Version 2.2.0.3468
OS: Microsoft Windows NT 10.0.17134.0, x64
Host Product: Microsoft Office 2016 x64
Host Version: 16.0.10228.20080
Host Executable: MSACCESS.EXE

**Comment by bclothier** [comment] 2018-07-29 13:53
I can confirm that behavior was present with the stable version. However, in latest prereleases, the behavior does not seem to exhibit anymore. Can anyone else confirm if one download the latest pre-release, that it solves the issue?

**Comment by Inarion** [comment] 2018-07-30 08:53
Unfortunately, I can repro the issue even with the latest prerelease. :(

```
Version 2.2.0.3564
OS: Microsoft Windows NT 6.1.7601 Service Pack 1, x64
Host Product: Microsoft Office 2013 x86
Host Version: 15.0.5023.1000
Host Executable: MSACCESS.EXE
```

What I did, with both approaches being 100% reproducible for me:

----

1. Launch some DB in Access.
2. Open the VBE.
3. Close VBE and Access.

Result: [No ghost process](https://github.com/rubberduck-vba/Rubberduck/files/2240293/RubberduckLog_Issue.3905_ghostWithoutParserLog.txt).

----

1. Launch some DB in Access.
2. Open the VBE.
3. Have RD parse the project.
4. Close VBE and Access.

Result: [Ghost process](https://github.com/rubberduck-vba/Rubberduck/files/2240294/RubberduckLog_Issue.3905_noGhost.txt)\* that when reused will not have RD loaded. (*Reused* in that executing an .accdb file or similar will not spawn a new process but seemingly use the existing one)

----

\* I've removed the details of the parser run - if you think it's essential to review those 3.8k lines as well, I can provide them. (Though I'd prefer to not publicly upload them - it's my current project at work.)

**Comment by Inarion** [comment] 2018-07-30 08:58
> 100% reproducible for me

Huh? This is only true with *one* .accdb. If I try again with a different one,  in both approaches Access can cleanly exit...
[Trace log (without parsing part) of approach 2 with a different .accdb](https://github.com/rubberduck-vba/Rubberduck/files/2240372/RubberduckLog_Issue.3905_ParsingWithoutAGhost.txt)

So maybe the parser log is the crucial part? Please tell me your thoughts.

**Comment by ThunderFrame** [comment] 2018-07-30 11:58
@Inarion - Are you waiting for the Inspections to appear before closing Access?

If you take a copy of the ghosting ACCDB, and remove all modules, forms and reports, then close and reopen Access, then parse the trimmed down database, do you get ghosting on exit? And if you then further remove all non-default references, close Access, reopen and parse?

That is, if you whittle the ghosting ACCDB down to being a blank database, does it still cause problems? If it doesn't, then I guess we need to discover which component/reference is causing the problem, by slowly removing items one at a time until we can produce a MCVE.

**Comment by Inarion** [comment] 2018-07-30 12:01
> Are you waiting for the Inspections to appear before closing Access?

I didn't even open the inspections window - just the initial parse to get RD working. (I clicked the `Pending` button and waited for the parse to finish, then closed Access.)

As for your other questions: I will try to get these tested today. (If my already melting brain allows for it... it's too goddamn hot...)

**Comment by bclothier** [comment] 2018-07-30 12:02
From a skim, I cannot see anything that's significant different between the logs. 

I'm fairly sure that this has to do with a inspection that's causing a leak, which would be why it clean exits for a particular file; it depends on its codebase or something like, So we're getting closer with a MCVE in order to fix it.

@MDoerner  just making - is this a cause for concern? I'm not sure if that's a factor but I doubt it:
```

2018-07-30 10:51:18.0938;WARN-2.2.0.3564;Rubberduck.VBEditor.SafeComWrappers.SafeComWrapper`1;Released COM wrapper of type Rubberduck.VBEditor.SafeComWrappers.Office12.CommandBarControl whose underlying RCW has already been released from outside the SafeComWrapper. New reference count is -1.;
```

**Comment by Inarion** [comment] 2018-07-30 13:12
After some chit-chat and trial and error, the current state of our research suggests that parsing an Access project while any form is open will lead to a ghost process remaining.

MCVE:

1. Create a new .accdb file from within Access.
2. Close the automatically created table without saving. (It should disappear.)
3. Create a new empty form (Create --> Empty form) and save it. (I think saving is crucial here!)
4. Open the VBE and parse. (Note there is no actual code in the current project.)
5. Close Access.

Voilà: Hello, Ghost!

**Comment by comintern** [comment] 2018-07-30 13:31
Linking [chat](https://chat.stackexchange.com/transcript/message/45910223#45910223).

**Comment by bclothier** [comment] 2018-07-30 13:39
No, stopping will not reset the forms opened via the `DoCmd.OpenForm`. Their state, OTOH, will be messed up.

**Comment by ThunderFrame** [comment] 2018-07-30 13:42
Also, IIRC, an Access Form, currently, can only have its controls enumerated if the form is open in design view, but I forget whether Rubberduck even *tries* to enumerate the controls (or do anything differently) if the form is open in design view.

**Comment by bclothier** [comment] 2018-07-30 13:44
Actually, I believe controls can be enumerated in a open form. That's the tricky thing. There is an overlap of what code can run in design state and what code can run in run state; and it's fairly substantial; including enumerating the controls. To ensure you are working with a form in design view and not an open form, requires that you know a bit about Access OM in order to query its design state. I don't believe there is a programmatic equivalent from VBE's OM alone to tell us that.

**Comment by ThunderFrame** [comment] 2018-07-30 13:53
Depending upon the Access version, you can get an idea of the design state by interrogating the serialized VBA/Access forms/Reports and other meta) in the `MSys` tables. The old format is a serialized Compound Binary File Format of IStorages and IStreams, the new format is a table hierarchy of Binary fields (IStreams) and parent fields (IStorages). i.e. Both formats are effectively a hierarchy of IStreams. IIRC, there is sometimes a second hierarchy, when design changes are made. We could potentially interrogate this structure to identify the state of the open forms/reports, but it would take some work to identify what exactly constitutes a changed or in use object.

**Comment by A9G-Data-Droid** [comment] 2018-08-24 16:26
I am not seeing this behavior in v2.2.0.3703-pre. I have a fairly simple project with a few forms and some code that updates tables. I can parse, do some stuff with the duck and close Access. It seems to shutdown gracefully for me.

**Comment by Inarion** [comment] 2018-08-27 09:49
@A9G-Data-Droid Can't confirm. As long as any form is open in form view or layout view while parsing, the ghost is created.
If I close all open forms / switch to design mode before parsing, all is fine.

**Comment by daFreeMan** [comment] 2018-08-27 13:14
Unfortunately, I'm with @Inarion - I too am continuing to get the ghost if I parse the project with a form in `Form View`. If the form is in `Design View`, all is good.

**Comment by dermoench42** [comment] 2018-09-05 19:03
Today I installed Rubberduck v2.2.0.3749-pre
I opened my DB went to the Code Editor, clicked on refresh on the rubberduck explorer window. After some time it displays my db and the modules. Meanwhile I took a look on some modules, found what I wanted to check. Was OK so I closed the vba editor. Closed Access, too. Took a look at the Task Manager and there it was: MS ACCESS running, 628,8MB RAM. For 20 Minutes now.
Reopen the same db works, calling the vba editor...
Rubberduck splash missing, rubberduck missing.
2. Test. Do the same as above, but not killing the task. Try to open another database. Hmm, nothing happens at all, but the lockfile (.laccdb) appears and the MS ACCESS task has some cpu load (25%). Open a 3rd db. It appears immediately and also rubberduck, but in an new task, which remains the same way as ghost.
There is something in Rubberduck which prevents Access from terminating or freeing the Ressources.
ervin

**Comment by A9G-Data-Droid** [comment] 2018-10-01 22:12
I found a thread from GetLatestVersionAsync was still running after I had closed Access. This is only one of the stragglers. After I disabled version check I am still seeing the ghost process occasionally. I believe there might be a WPF thread still running as well because I see the XAML debugger still going after Access is closed.

>Microsoft.VisualStudio.DesignTools.WpfTap.dll!Microsoft.VisualStudio.DesignTools.WpfTap.Networking.AnonymousPipe.WaitForCondition

**Comment by daFreeMan** [comment] 2018-10-02 14:59
Unfortunately, I must again agree with @Inarion. Running build .3835, I launched Access, closed my auto-open form, launched the VBE, turned OFF the version check, closed the VBE and Access, relaunched my project leaving the auto-open form open, parsed, closed Access and have a zombie Access process.

Don't let this dissuade you, @A9G-Data-Droid, keep going! Keep digging! Somebody's got to figure this out and it may as well be you!

**Comment by A9G-Data-Droid** [comment] 2018-10-02 15:11
Sorry if I was unclear. I have identified at least 2 threads that hang after close. One is the version check and one is a WPF object. The WPF thread remains when version check is disabled.

**Comment by bclothier** [comment] 2018-10-24 00:33
Update - I was able to pinpoint the problem down to code explorer, specifically this constructor here:

```
        public CodeExplorerComponentViewModel(CodeExplorerItemViewModel parent, Declaration declaration, IEnumerable<Declaration> declarations, IProjectsProvider projectsProvider)
        {
...
            var qualifiedModuleName = declaration.QualifiedName.QualifiedModuleName;
            try
            {
                switch (qualifiedModuleName.ComponentType)
                {
                    case ComponentType.Document:
                        var component = _projectsProvider.Component(qualifiedModuleName);
                        string parenthesizedName;
                        using (var properties = component.Properties)
                        using (var nameProperty = properties["Name"])
                        {
                            parenthesizedName = nameProperty.Value.ToString() ?? string.Empty;
                        }
...
            }
            catch
            {
                // gotcha! (this means that the property either doesn't exist or we weren't able to get it for some reason)
            }
        }
```

When the form is in design view, there is no problem running the constructor and all is good. However, when it's in form view, an exception is thrown. 

The first exception is:
```
+		$exception	{"Function or interface marked as restricted, or the function uses an Automation type not supported in Visual Basic"}	System.Runtime.InteropServices.COMException
```

thrown on the line `using (var properties = component.Properties)`.

The second exception for the same QMN called again later is:
```
+		$exception	{"Object doesn't support this property or method"}	System.NotSupportedException
```

thrown on the line `using (var nameProperty = properties["Name"])`

I have verified that if we skip the section entirely, Rubberduck is able to parse even when the form is open in form view and will not leave a ghost process. Obviously the exceptions are causing it to leak a COM object and thus we end up with a ghost process.

**Closed** 2018-11-06 04:57 UTC
Labels: bug, critical
