### ISSUE TITLE
Parsing error - "On Error Goto 0"

### ISSUE THREAD

**Issue by dornech** [rubberduck-vba/Rubberduck#5076] opened 2019-08-01 10:24 UTC
**Rubberduck version information**
The info below can be copy-paste-completed from the first lines of Rubberduck's log or the About box:

	Rubberduck version 2.4.1.4627 loading:
	Operating System: Microsoft Windows NT 10.0.16299.0 x64
	Host Product: Microsoft Office 2016 x86
	Host Version: 16.0.4873.1000
	Host Executable: EXCEL.EXE;

**Description**
I get parse errors on function modules containing an error handling.
Parsing error occurs on first column of any line containing an "On Error Goto 0"

Error :
2019-08-01 12:02:35.7911;ERROR-2.4.1.4627;Rubberduck.Parsing.VBA.Parsing.ModuleParser;Syntax error; offending token 'End Function' at line 583, column 1 in the CodePaneCode

**Comment by daFreeMan** [comment] 2019-08-01 13:23
Thanks for reporting. Can you include the full log (you should be able to upload it to your OP or a new comment) and also include an MCVE or the actual code that causes the error?

**Comment by retailcoder** [comment] 2019-08-01 14:14
Please confirm that the code compiles (`End Function` being the offending token is weird), and include a small VBA code snippet that reproduces the problem (whether your actual code or not) - as it stands we have very little to chew on, and no indication of what the problem could be.

I'll take a guess though (can't test it at this moment) - could you happen to terminate `On Error` statements with an instructions separator token?

    On Error GoTo 0:

If so, try removing the colon character, it's redundant anyway.

**Comment by dornech** [comment] 2019-08-01 16:47
Thanks for your repsonses.
"On Error Goto 0:" does not fix the problem :-(

Function causing the problem is as follows:

Function IsInCollection(ByRef objCollection As Object, ByRef s_Element As String) As Boolean
   On Error Resume Next
   If IsEmpty(objCollection(s_Element)) Then: 'DoNothing
   IsInCollection = (Err.Number = 0)
   On Error GoTo 0
End Function

Pretty straight forward, eh? It does compile in VBA. If I delete it, no problem with the module. 
However, I am not sure if the On Error is the problem - I thought so due to the fact, that I receive another parsing error in a function having an "On Error Goto 0" before the "End Function"

Playing around I found out, that the parse error disappears if I delete the following line:
   **If IsEmpty(objCollection(s_Element)) Then: 'DoNothing**
This seems to be the reason for the second parsing error as well as this is a similar command:
**If IsEmpty(objWB.Worksheets(s_Worksheet)) Then:**

When Replacing "Then:" by a CRLF and "End If", it works. 
So, while "Then:" is allowed VBA syntax, this seems to cause problems for the Rubberduck parsing.

Sorry for the first misleading analysis.

**Comment by bclothier** [comment] 2019-08-01 17:05
The thing about the `Then:` is [an known issue](https://github.com/rubberduck-vba/Rubberduck/issues/1457). 

I should note that the code is somehow misleading. You have a comment `'Do Nothing` but in fact it doesn't do nothing - it just blows through and execute the next lines anyway. If you intended to stop there, you should have a `Then Exit Sub` at least.<sup>1</sup> Because of the `On Error Resume Next`, it makes no difference, so that line actually contributes little besides short-circuiting. 

But the real crux is the use of single-line `If` statement. From a grammarical standpoint, the single-line `If` statement and a block `If` statement behave very different and because of that, easily contributes to a fair amount of bugs or strange behaviors. For that reason, we'd encourage to be consistent and always use block `If` and avoid using any instruction separators.

Since the linked issue already covers the issue, I'll close this issue. Thanks for reporting and please keep sending us feedback, good or bad on the product! :)

**Closed** 2019-08-01 18:09 UTC
Labels: bug
