### ISSUE TITLE
 Object variable ... is assigned without the 'Set' keyword 

### ISSUE THREAD

**Issue by SystemsModelling** [rubberduck-vba/Rubberduck#2620] opened 2017-02-03 12:04 UTC
Any variable that is defined with a predefined Excel type gets caught this way.

 Object variable 'AskOKtoSendTODB' is assigned without the 'Set' keyword 
'Function AskOKtoSendTODB(...) As VbMsgBoxResult

 Object variable 'CalculationMode' is assigned without the 'Set' keyword 
Public CalculationMode As XlCalculation
 Me.CalculationMode = Application.Calculation '<--- 

 Object variable 'Cancel' is assigned without the 'Set' keyword 
Private Sub txtQuestion_Exit(ByVal Cancel As MSForms.ReturnBoolean)
Cancel = True

 Object variable 'dictRespondent' is assigned without the 'Set' keyword 
It's indexed. 
Set dictRespondent = CreateObject("Scripting.Dictionary")
dictRespondent("respondent_id") = …etc

**Comment by ThunderFrame** [comment] 2017-02-03 12:38
Hi @SystemsModelling , can you expand on the dictionary example? What are you assigning? An object or a simple value?

I get a repro with a late-bound dictionary `Object`, but not with an early-bound `Dictionary`.

The preferred way of adding to a Dictionary is with the `Add` method (preferably using the `Exists` method *beforehand*), but MS decided that the default `Item` *getter*, should actually return the item if it exists, or add the item and then return it if it doesn't. Which is just plain bonkers.

```vb
Sub test()

  Dim dic As Scripting.Dictionary
  Set dic = New Dictionary
  
  Debug.Print dic.Count 'Prints 0
  
  'This implicitly adds "Foo" to the dictionary
  'even though I'm READING a property!!!
  Debug.Print dic("Foo")
    
  Debug.Print dic.Count 'Prints 1

End Sub
```

**Comment by retailcoder** [comment] 2017-02-03 13:21
The `Cancel` parameter is a reference type with a default member. That's a legit false positive, fixed and merged IIRC (just not yet released).

Enum resolution is also fixed and merged.

Late-bound objects are a problem for now; all we know about them is that they're objects; I agree that we should pick up the subscript and not resolve the dictionary as the assignment target. Soon we'll be able to resolve `CreateObject` types though.

**Comment by comintern** [comment] 2017-02-03 13:27
@retailcoder  The enum resolution is fixed, but the inspection is picking them up as requiring `Set`. Repro'd with:

```
Function foo() As VbMsgBoxResult
    foo = vbOK
End Function
```

**Comment by comintern** [comment] 2017-02-03 15:35
Regarding this part:

>  Object variable 'Cancel' is assigned without the 'Set' keyword
>  Private Sub txtQuestion_Exit(ByVal Cancel As MSForms.ReturnBoolean)
>  Cancel = True

The result above is a duplicate of #2602. `MSForms.ReturnBoolean` actually **_is_** an object.  The code `Cancel = True` is being resolved by VBA as `Cancel.Value = True`.  It's an implicit default member call triggered by attempting to assign a literal to a reference type.  This code would trigger its own inspection if\when there is an implementation for #2504 that includes the LHS of the expression.

**Comment by SystemsModelling** [comment] 2017-02-03 15:58
"Hi @SystemsModelling , can you expand on the dictionary example? What are you assigning? An object or a simple value?"

Set dictRespondent = CreateObject("Scripting.Dictionary")
               'rely on ability of dictionary to create key if new
dictRespondent("respondent_id") = Cells(lRow, 1).Value
dictRespondent(SMAPI_COLLECTOR_ID) = Cells(lRow, 2).Value
dictRespondent("ip_address") = Cells(lRow, 3).Value
..etc....

Patrick

**Comment by comintern** [comment] 2017-02-03 16:37
If `dictRespondent` is declared as `Object`, RD (currently) isn't making the assumption that it has either a default member or that the default member is indexed.  This expression...

    dictRespondent("respondent_id")

...turns into this code after all of the implicit references are resolved:

   dictRespondent.Item("respondent_id")

In the long term we'd like to have RD perform its own binding for `CreateObject("Scripting.Dictionary")` so that it would *know*, that `dictRespondent` is a `Scripting.Dictionary` and be able to resolve the call.  ATM, it isn't possible to determine this for late bound types.

**Comment by retailcoder** [comment] 2017-02-03 16:41
@comintern in the meantime we can probably tweak the resolver so that when it determines that an object is the target of an assignment, it verifies if there's a `LPAREN` token immediately after the identifier reference; in which case we could be creating the identifier reference, without setting its `IsAssignmentTarget` flag. Thoughts?

**Comment by comintern** [comment] 2017-02-03 16:52
@retailcoder That sounds like it would work just fine.

**Comment by retailcoder** [comment] 2017-03-02 15:49
@comintern wow, it's actually *much* simpler than that!

````csharp
if (isAssignmentTarget && expression.Context.Parent is VBAParser.IndexExprContext)
{
    // 'SomeDictionary' is not the assignment target in 'SomeDictionary("key") = 42'
    isAssignmentTarget = false;
}
````

**Closed** 2017-03-02 16:05 UTC
Labels: bug, feature-inspections
