### ISSUE TITLE
Evaluate (and perform) csproj format update

### ISSUE THREAD

**Issue by Vogel612** [rubberduck-vba/Rubberduck#3944] opened 2018-04-18 21:13 UTC
The csproj files are a regular source of pain for pull-requests dealing with moving stuff around and just general development.  
MS did add a new csproj format that can use globbing and other cool (read: basic) features that are useful for remotely human readable project control.

The following guide can help migrate an old configuration to a new one: https://www.natemcmaster.com/blog/2017/03/09/vs2015-to-vs2017-upgrade/

**Comment by rubberduck203** [comment] 2018-04-18 21:39
Just a word of caution, this change will break compatibility with VS2013 & VS2015. 

If we do this, all contributors need to be using the latest version of Visual Studio.

**Comment by Vogel612** [comment] 2018-04-18 21:41
we require VS 2017 anyways for some thing or other. since quite a while as well.

**Comment by MDoerner** [comment] 2018-04-18 21:41
I think we are forced to use VS2017 for some time already because we are using C#7.1 and VS does not ship with a compiler for it prior to VS2017.

**Comment by Vogel612** [comment] 2018-04-18 21:43
note that for pur wpf stuff. https://github.com/dotnet/sdk/issues/491 might be relevant

**Comment by rubberduck203** [comment] 2018-04-18 23:11
Ok. Cool. I know I’m out of the loop. Just wanted to make sure we didn’t break any contributors. It’s because of y’all I don’t have to worry about the project after all.

**Comment by mungojam** [comment] 2018-07-25 14:15
You can give [this converter](https://github.com/hvanbakel/CsprojToVs2017) a go if you like. It's just had WPF support added. [This nearly merged pull request](https://github.com/hvanbakel/CsprojToVs2017/pull/136) should lead to a really neat project file afterwards, though it's pretty easy to manually tidy up anyway.

**Comment by hvanbakel** [comment] 2018-07-26 03:18
That PR is now merged. Updating the readme now on how to use as a net core global tool 😄

**Comment by Vogel612** [comment] 2018-09-17 00:56
I've been battling MSBuild for a few hours now to migrate at least some of the satellite assemblies to the new csproj format. Rubberduck.Deployment has been a bit ... resistant, though. 

I'm not sure what to make of the following error that shows when trying to run tlbexp on Rubberduck.dll for the 64-bit tlb:

> 3>Running tlbexp.exe
> 3>cmd = C:\Program Files (x86)\Microsoft SDKs\Windows\v10.0A\bin\NETFX 4.6.1 Tools\tlbexp.exe
> 3>Microsoft (R) .NET Framework Assembly to Type Library Converter 4.6.1055.0
> 3>Copyright (C) Microsoft Corporation.  All rights reserved.
> 3>
> 3>Assembly exported to 'F:\[..]\Rubberduck\Rubberduck.Deployment\bin\Debug\net46\Rubberduck.x32.tlb'
> 3>Generated 32-bit TLB
> 3>Microsoft (R) .NET Framework Assembly to Type Library Converter 4.6.1055.0
> 3>Copyright (C) Microsoft Corporation.  All rights reserved.
> 3>
> 3>F:\[..]\Rubberduck\Rubberduck.Deployment\BuildRegistryScript.ps1 :
> 3>TlbExp : warning TX00131175: When cross-compiling, all type library references should be
> 3>included on the command line to ensure the correct bit-specific type libraries are loaded.
> 3>In Zeile:1 Zeichen:1
> 3>+ & 'F:\[..]\Rubberduck\Rubberduck.Deployment\ ...
> 3>+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> 3>    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
> 3>    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,BuildRegistryScript.ps1
> 3>
> 3>F:\[..]\Rubberduck\Rubberduck.Deployment\Rubberduck.Deployment.csproj(78,5): error MSB3073: The command "%SystemRoot%\System32\WindowsPowerShell\v1.0\powershell.exe -ExecutionPolicy Bypass -command "& 'F:\[..]\Rubberduck\Rubberduck.Deployment\BuildRegistryScript.ps1' -config 'Debug' -builderAssemblyPath 'F:\[..]\Rubberduck\Rubberduck.Deployment\bin\Debug\net46\Rubberduck.Deployment.dll' -netToolsDir 'C:\Program Files (x86)\Microsoft SDKs\Windows\v10.0A\bin\NETFX 4.6.1 Tools\' -wixToolsDir 'F:\[..]\Rubberduck\Rubberduck.Deployment\\WixToolset\' -sourceDir 'F:\[..]\Rubberduck\Rubberduck.Deployment\bin\Debug\net46\' -targetDir 'F:\[..]\Rubberduck\Rubberduck.Deployment\bin\Debug\net46\' -projectDir 'F:\[..]\Rubberduck\Rubberduck.Deployment\' -includeDir 'F:\[..]\Rubberduck\Rubberduck.Deployment\InnoSetup\Includes\' -filesToExtract 'Rubberduck.dll|Rubberduck.API.dll'"" exited with code 1.
> 3>Done building project "Rubberduck.Deployment.csproj" -- FAILED.

Any help is appreciated

**Comment by bclothier** [comment] 2018-09-17 06:01
I feel like there's missing data in there. For one thing, it's not all that clear whether it's actually erroring with the TLB generation. It might be actually failing on the [heat.exe at line 223](https://github.com/rubberduck-vba/Rubberduck/blob/next/Rubberduck.Deployment/BuildRegistryScript.ps1#L223).

Note that the error before the separator is cut off:
```
3>+ & 'F:[..]\Rubberduck\Rubberduck.Deployment\ ...
```
 and that isn't the path to the SDK where the tlbexp.exe would be defined. However, `heat.exe` would be a package within the Rubberduck project's `packages` folder. 

I would uncomment the [lines  161-175](https://github.com/rubberduck-vba/Rubberduck/blob/next/Rubberduck.Deployment/BuildRegistryScript.ps1#L161L175) and verify that all the variables are sane and perhaps test with manual execution of the tools in the script to see if the error can be reproduced.

**Closed** 2018-10-18 01:40 UTC
Labels: difficulty-02-ducky, discussion, technical-debt, up-for-grabs
